### ISSUE TITLE
Docker: The `queue.put()` got stuck when run `extract` with `-f` filter provided

### ISSUE THREAD

**Issue by VicGrygorchyk** [deepfakes/faceswap#1000]
Running a command inside the docker container:
```
faceswap.py extract -L INFO -D=s3fd -A=fan -nm=clahe -i=/srv/trump -o=/srv/trump_out -f /srv/trump_example/*

```
OUTPUT:
```
Setting Faceswap backend to NVIDIA
03/28/2020 10:48:53 INFO     Log level set to: INFO
03/28/2020 10:48:54 INFO     Output Directory: /srv/trump_out
03/28/2020 10:48:55 INFO     Extracting and aligning face for Face Filter...
03/28/2020 10:48:55 INFO     Filter: ['/srv/trump_example/11_0.jpeg', '/srv/trump_example/1_0.jpeg', '/srv/trump_example/21_0.jpg'']
03/28/2020 10:48:55 INFO     Loading Detect from Cv2_Dnn plugin...
03/28/2020 10:48:55 INFO     Loading Align from Cv2_Dnn plugin..
```
Full log and debug info (`python -c "from lib.sysinfo import SysInfo ; print(SysInfo().full_info())`) here:
[logs (1).txt](https://github.com/deepfakes/faceswap/files/4399107/logs.1.txt)

Tried on two different platfoms: Laptop Ubuntu 18.04 Geforce GTX 965m and GCP instance with Nvidia T4.

Both times I tried inside Docker image.

______________________

**Comment by VicGrygorchyk** [comment]
After debugging:
 I run script with `-f` filter provided.
From my debugging I ended up seeing the problem in `def queue_images()` method of `faceswap/lib/face_filter.py`. It tries to execute `in_queue.put(feed_dict)` and waits for free slot.
If we add timeout to put() it crashes with:
```
INFO     Sending EOF to filter queue
ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/srv/lib/cli.py", line 127, in execute_script
    process = script(arguments)
  File "/srv/scripts/extract.py", line 51, in __init__
    self._post_process = PostProcess(arguments)
  File "/srv/scripts/fsmedia.py", line 349, in __init__
    self._actions = self._set_actions()
  File "/srv/scripts/fsmedia.py", line 368, in _set_actions
    task = globals()[action](*args, **kwargs)
  File "/srv/scripts/fsmedia.py", line 533, in __init__
    self._filter = self._load_face_filter(**kwargs)
  File "/srv/scripts/fsmedia.py", line 576, in _load_face_filter
    ref_threshold)
  File "/srv/lib/face_filter.py", line 46, in __init__
    self.align_faces("cv2-dnn", "cv2-dnn", "none", multiprocess)
  File "/srv/lib/face_filter.py", line 78, in align_faces
    self.run_extractor(extractor)
  File "/srv/lib/face_filter.py", line 89, in run_extractor
    self.queue_images(extractor)
  File "/srv/lib/face_filter.py", line 125, in queue_images
    in_queue.put("EOF", timeout=1)
  File "/usr/lib/python3.6/queue.py", line 141, in put
    raise Full
queue.Full

````
Is it any reason you limited to 1 a Queue size in `plugins/extract/pipeline.py::Extractor` ?
I mean, I read a comment, but I wonder if the scripts puts at least one filter and EOF into 1-sized Queue, is it right?
________________________
Well, I changed self.queue_size = 0 and checked out to `18660da1c92994615e88a032242c552295dc96e3` commit, as next commit, where `ExtractMedia ` has been added - failed for me, I got no instance of `ExtractMedia`, but a `dict`.

**Comment by torzdf** [comment]
Filter is unlikely to be looked at as the way it works will change in the future.

You are entering commands incorrectly. Don't put an equals sign between the flag and the option.

**Comment by VicGrygorchyk** [comment]
Well, I don't want sound irritating, but `=` and ` ` are the same for command line params.
BTW, is it correct?
```
python3 faceswap.py extract -L INFO -D cv2-dnn -A fan -i /srv/face/in -o /srv/face/out -f /srv/filter/test.jpg /srv/filter/test1.jpg 
```
 the result is the same, it's stuck.
I don't see any reason it should be closed.

**Comment by torzdf** [comment]
Filter is poor and not recommended. It will be improved and fixed.

Much better to extract all faces, then sort after, More info here:
https://forum.faceswap.dev/viewtopic.php?f=5&t=27#sort

As to your second point, your output would suggest that they are not the same, but I haven't checked:

faceswap.py extract -L INFO **-D=s3fd -A=fan**

```
03/28/2020 10:48:55 INFO     Loading Detect from Cv2_Dnn plugin...
03/28/2020 10:48:55 INFO     Loading Align from Cv2_Dnn plugin..
```

**Comment by VicGrygorchyk** [comment]
Thank you for your support!
