### ISSUE TITLE
Convert Images has no face 

### ISSUE THREAD

**Issue by Tian14267** [deepfakes/faceswap#1002]
Hello. Author, I get a problem when I convert my images. The output of my convert image has no face ,can you help me ?
The output pic just like this:

![0](https://user-images.githubusercontent.com/27938135/77992017-cdc7e500-7357-11ea-877b-c46c3df88b20.png)

The order I input is:
`python faceswap.py convert -i=./data/src  -o=./data/convert_out  -m=models`
and the models folder is like this:
![1](https://user-images.githubusercontent.com/27938135/77992515-c94ffc00-7358-11ea-9d9b-79be934a6f31.png)

Do I use the wrong input order ?

**Comment by Tian14267** [comment]
@luiscosio @wiso @procule @Ganonmaster

**Comment by wiso** [comment]
Hello @Tian14267 , I am not an "author"

By the way it seems that you just need to train more or to provide more input images.

**Comment by Tian14267** [comment]
sorry, but Thank you for your suggestion. I will try more training epoch ,and more Input pic.
@wiso

**Comment by torzdf** [comment]
Yep. Not enough training.

You should see our guides here: https://forum.faceswap.dev/app.php/tag/Guide
