### ISSUE TITLE
error converting video

### ISSUE THREAD

**Issue by kira228822** [deepfakes/faceswap#1009]
(faceswap) root@kali:/home/k/faceswap# python faceswap.py convert -i /home/k/faceswap/src/Fake.mp4 -o /home/k/faceswap/converted/ -m /home/k/faceswap/fake_n_model2 -otf
Setting Faceswap backend to CPU
04/11/2020 13:14:28 INFO     Log level set to: INFO
Using TensorFlow backend.
04/11/2020 13:14:29 INFO     Input Video: /home/k/faceswap/src/Fake.mp4
04/11/2020 13:14:30 INFO     Loading Writer from Opencv plugin...                                          
04/11/2020 13:14:30 WARNING  On-The-Fly conversion selected. This will use the inferior cv2-dnn for extraction and will produce poor results.
04/11/2020 13:14:30 WARNING  It is recommended to generate an alignments file for your destination video with Extract first for superior results.
04/11/2020 13:14:30 WARNING  There was an error reading from the Nvidia Machine Learning Library. Either you do not have an Nvidia GPU (in which case this warning can be ignored) or the most likely cause is incorrectly installed drivers. If this is the case, Please remove and reinstall your Nvidia drivers before reporting.Original Error: Driver Not Loaded
04/11/2020 13:14:30 WARNING  No GPU detected. Switching to CPU mode
04/11/2020 13:14:30 INFO     Loading Detect from Cv2_Dnn plugin...
04/11/2020 13:14:30 INFO     Loading Align from Cv2_Dnn plugin...
04/11/2020 13:14:30 INFO     Initializing cv2-DNN Detector (Detect)...
04/11/2020 13:14:30 INFO     Initialized cv2-DNN Detector (Detect) with batchsize of 1
04/11/2020 13:14:30 INFO     Initializing cv2-DNN Aligner (Align)...
04/11/2020 13:14:30 INFO     Initialized cv2-DNN Aligner (Align) with batchsize of 1
04/11/2020 13:14:30 WARNING  There was an error reading from the Nvidia Machine Learning Library. Either you do not have an Nvidia GPU (in which case this warning can be ignored) or the most likely cause is incorrectly installed drivers. If this is the case, Please remove and reinstall your Nvidia drivers before reporting.Original Error: Driver Not Loaded
04/11/2020 13:14:30 WARNING  No GPU detected. Switching to CPU mode                                        
04/11/2020 13:14:30 INFO     Loading Model from Original plugin...                                         
04/11/2020 13:14:30 INFO     Using configuration saved in state file                                       
04/11/2020 13:14:34 INFO     Loaded model from disk: '/home/k/faceswap/fake_daud_model2'                   
04/11/2020 13:14:35 ERROR    You have selected the Mask Type `extended` but at least one face does not have this mask stored in the Alignments File.
04/11/2020 13:14:35 ERROR    You should generate the required masks with the Mask Tool or set the Mask Type option to an existing Mask Type.
04/11/2020 13:14:35 ERROR    A summary of existing masks is as follows:                                    
04/11/2020 13:14:35 WARNING  There was an error reading from the Nvidia Machine Learning Library. Either you do not have an Nvidia GPU (in which case this warning can be ignored) or the most likely cause is incorrectly installed drivers. If this is the case, Please remove and reinstall your Nvidia drivers before reporting.Original Error: Driver Not Loaded
04/11/2020 13:14:35 ERROR    Total faces: 0, Masks: {}                                                     
04/11/2020 13:14:35 WARNING  No GPU detected. Switching to CPU mode                                        
Converting:   0%|                                                                  | 0/735 [00:05<?, ?it/s]/bin/sh: 1: ldconfig: not found
/bin/sh: 1: ldconfig: not found
/bin/sh: 1: ldconfig: not found
OMP: Warning #190: Forking a process while a parallel region is active is potentially unsafe.
04/11/2020 13:14:41 INFO     To get more information on this error see the crash report written to '/home/k/faceswap/crash_report.2020.04.11.131441128171.log'
Converting:   0%|
please help solve the problem

**Comment by torzdf** [comment]
> 04/11/2020 13:14:35 ERROR You have selected the Mask Type extended but at least one face does not have this mask stored in the Alignments File.
04/11/2020 13:14:35 ERROR You should generate the required masks with the Mask Tool or set the Mask Type option to an existing Mask Type.
