### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by bildde4chan** [deepfakes/faceswap#101]
virtualenv '/home/test/Desktop/faceswap-master'
python3.5 '/home/test/Desktop/faceswap-master/faceswap.py' -h

test@ubuntu:~$ virtualenv '/home/test/Desktop/faceswap-master'
New python executable in /home/test/Desktop/faceswap-master/bin/python
Installing setuptools, pip, wheel...done.
test@ubuntu:~$ python3.5 '/home/test/Desktop/faceswap-master/faceswap.py' -h
Traceback (most recent call last):
  File "/home/test/Desktop/faceswap-master/faceswap.py", line 8, in <module>
    from lib.utils import FullHelpArgumentParser
  File "/home/test/Desktop/faceswap-master/lib/utils.py", line 5, in <module>
    from scandir import scandir
ImportError: No module named 'scandir'
test@ubuntu:~$

**Comment by Clorr** [comment]
Hello, the error is on the last line: "No module named scandir". Did you install the requirements? They are located in `requirements.txt` or `requirements-gpu.txt` and you can install them with `pip3 install -r requirements.txt`. Also don't forget to install CUDA and CuDNN
