### ISSUE TITLE
Check failed: vec.size() == NDIMS 

### ISSUE THREAD

**Issue by chunxingque** [deepfakes/faceswap#1017]
5/03/2020 20:04:39 INFO     No existing state file found. Generating.
05/03/2020 20:04:42 INFO     Creating new 'original' model in folder: 'E:\AiLearning\project\model'
05/03/2020 20:04:42 INFO     Loading Trainer from Original plugin...
05/03/2020 20:04:42 INFO     Enabled TensorBoard Logging
2020-05-03 20:05:01.916652: F .\tensorflow/core/util/bcast.h:111] Check failed: vec.size() == NDIMS (1 vs. 2)
Process exited.

why?
help me

**Comment by torzdf** [comment]
There is not enough information here to diagnose, so closing.
