### ISSUE TITLE
Windows installer broken

### ISSUE THREAD

**Issue by BlueONn** [deepfakes/faceswap#1022]
**Crash reports MUST be included when reporting bugs.**
(check) CPU Supports SSE4 Instructions
(check) Completed check for installed applications
(check) Setting up for: cpu

Downloading Miniconda3...
Installing Miniconda3. This will take a few minutes...
Miniconda3 installed.
Initializing Conda...
Creating Conda Virtual Environment...
Error Creating Conda Virtual Environment
Install Aborted

**Describe the bug**
Installer is broken

**To Reproduce**
1. Download installer (Windows) from github
2. Click "Install"
3. See error

**Expected behavior**
Just install

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Python Version 3.8.3rc1
 - Conda Version I first time hear about it , i never instaled it.
 - Commit ID What ?
 - 
**Additional context**
_--===+ Hardware +===--_
Intel Pentium (R) n3530
Intel HD Graphics (Bay Trail)
4GB (SODIMM) [DDR3]
HDD 500GB
UEFI

**Crash Report**
Faceswap is not installing , so they have no directory for storing crash report

**Comment by torzdf** [comment]
This is likely to be an issue/conflict with your system, as in 99% of cases the installer works fine.

That said, Intel HD Graphics won't be good enough to run Faceswap, so this probably isn't worth diagnosing.
