### ISSUE TITLE
Is there a technical explanation of the model itself?

### ISSUE THREAD

**Issue by danielegrattarola** [deepfakes/faceswap#103]
Not really an issue, I know, but is there any technical explanation of the model architecture? The one in the readme about neural networks is pretty entry-level.

Thanks

**Comment by Clorr** [comment]
Question was also asked in #73 about which paper this is based on. You will also find some info on reddit, but there is not much about this around. All I can tell you is that it is an [autoencoder](https://en.wikipedia.org/wiki/Autoencoder)
