### ISSUE TITLE
RuntimeError: The Session graph is empty. Add operations to the graph before calling run()

### ISSUE THREAD

**Issue by RedJupid** [deepfakes/faceswap#1030]
**Desktop (please complete the following information):**
 - OS: [Win10]
 - Python Version [3.6]
 - Conda Version [e.g. 4.5.12]
 - Commit ID [e.g. e83819f]
 - 
**Additional context**
when i train a model on the faces extracted from the photos/videos

**Crash Report**
06/12/2020 12:16:24 MainProcess     _training_0     _base           _tensorboard_kwargs       DEBUG    {'histogram_freq': 0, 'batch_size': 64, 'write_graph': True, 'write_grads': True, 'update_freq': 'batch'}
06/12/2020 12:16:24 MainProcess     _training_0     _base           _set_tensorboard          INFO     Enabled TensorBoard Logging
06/12/2020 12:16:24 MainProcess     _training_0     _base           _use_mask                 DEBUG    False
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initializing Samples: model: '<plugins.train.model.original.Model object at 0x000001D7132C0BE0>', use_mask: False, coverage_ratio: 0.6875)
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initialized Samples
06/12/2020 12:16:24 MainProcess     _training_0     _base           _use_mask                 DEBUG    False
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initializing Timelapse: model: <plugins.train.model.original.Model object at 0x000001D7132C0BE0>, use_mask: False, coverage_ratio: 0.6875, image_count: 14, batchers: '{'a': <plugins.train.trainer._base.Batcher object at 0x000001D87054E8D0>, 'b': <plugins.train.trainer._base.Batcher object at 0x000001D870571860>}')
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initializing Samples: model: '<plugins.train.model.original.Model object at 0x000001D7132C0BE0>', use_mask: False, coverage_ratio: 0.6875)
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initialized Samples
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initialized Timelapse
06/12/2020 12:16:24 MainProcess     _training_0     _base           __init__                  DEBUG    Initialized Trainer
06/12/2020 12:16:24 MainProcess     _training_0     train           _load_trainer             DEBUG    Loaded Trainer
06/12/2020 12:16:24 MainProcess     _training_0     train           _run_training_cycle       DEBUG    Running Training Cycle
06/12/2020 12:16:24 MainProcess     _run_0          training_data   initialize                DEBUG    Initializing constants. training_size: 256
06/12/2020 12:16:24 MainProcess     _run_0          training_data   initialize                DEBUG    Initialized constants: {'clahe_base_contrast': 2, 'tgt_slices': slice(40, 216, None), 'warp_mapx': '[[[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n ...\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]]', 'warp_mapy': '[[[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n ...\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]]', 'warp_pad': 80, 'warp_slices': slice(8, -8, None), 'warp_lm_edge_anchors': '[[[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n ...\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]]', 'warp_lm_grids': '[[[  0.   0.   0. ...   0.   0.   0.]\n  [  1.   1.   1. ...   1.   1.   1.]\n  [  2.   2.   2. ...   2.   2.   2.]\n  ...\n  [253. 253. 253. ... 253. 253. 253.]\n  [254. 254. 254. ... 254. 254. 254.]\n  [255. 255. 255. ... 255. 255. 255.]]\n\n [[  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]\n  ...\n  [  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]]]'}
06/12/2020 12:16:24 MainProcess     _run_0          training_data   initialize                DEBUG    Initializing constants. training_size: 256
06/12/2020 12:16:24 MainProcess     _run_0          training_data   initialize                DEBUG    Initialized constants: {'clahe_base_contrast': 2, 'tgt_slices': slice(40, 216, None), 'warp_mapx': '[[[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n ...\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]\n\n [[ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]\n  [ 40.  84. 128. 172. 216.]]]', 'warp_mapy': '[[[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n ...\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]\n\n [[ 40.  40.  40.  40.  40.]\n  [ 84.  84.  84.  84.  84.]\n  [128. 128. 128. 128. 128.]\n  [172. 172. 172. 172. 172.]\n  [216. 216. 216. 216. 216.]]]', 'warp_pad': 80, 'warp_slices': slice(8, -8, None), 'warp_lm_edge_anchors': '[[[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n ...\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]\n\n [[  0   0]\n  [  0 255]\n  [255 255]\n  ...\n  [127 255]\n  [255 127]\n  [  0 127]]]', 'warp_lm_grids': '[[[  0.   0.   0. ...   0.   0.   0.]\n  [  1.   1.   1. ...   1.   1.   1.]\n  [  2.   2.   2. ...   2.   2.   2.]\n  ...\n  [253. 253. 253. ... 253. 253. 253.]\n  [254. 254. 254. ... 254. 254. 254.]\n  [255. 255. 255. ... 255. 255. 255.]]\n\n [[  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]\n  ...\n  [  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]\n  [  0.   1.   2. ... 253. 254. 255.]]]'}
06/12/2020 12:16:24 MainProcess     _training_0     deprecation     new_func                  DEBUG    From C:\Users\xd\Anaconda3\envs\pytorch2\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
06/12/2020 12:16:57 MainProcess     _training_0     _base           generate_preview          DEBUG    Generating preview
06/12/2020 12:16:57 MainProcess     _training_0     _base           largest_face_index        DEBUG    0
06/12/2020 12:16:57 MainProcess     _training_0     _base           compile_sample            DEBUG    Compiling samples: (side: 'a', samples: 14)
06/12/2020 12:17:01 MainProcess     _training_0     _base           generate_preview          DEBUG    Generating preview
06/12/2020 12:17:01 MainProcess     _training_0     _base           largest_face_index        DEBUG    0
06/12/2020 12:17:01 MainProcess     _training_0     _base           compile_sample            DEBUG    Compiling samples: (side: 'b', samples: 14)
06/12/2020 12:17:01 MainProcess     _training_0     _base           show_sample               DEBUG    Showing sample
06/12/2020 12:17:01 MainProcess     _training_0     _base           _get_predictions          DEBUG    Getting Predictions
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_predictions          DEBUG    Returning predictions: {'a_a': (14, 64, 64, 3), 'b_a': (14, 64, 64, 3), 'a_b': (14, 64, 64, 3), 'b_b': (14, 64, 64, 3)}
06/12/2020 12:17:02 MainProcess     _training_0     _base           _to_full_frame            DEBUG    side: 'a', number of sample arrays: 3, prediction.shapes: [(14, 64, 64, 3), (14, 64, 64, 3)])
06/12/2020 12:17:02 MainProcess     _training_0     _base           _frame_overlay            DEBUG    full_size: 256, target_size: 176, color: (0, 0, 255)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _frame_overlay            DEBUG    Overlayed background. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'a', sample.shape: (14, 64, 64, 3), target_size: 176, scale: 2.75)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'a' shape: (14, 176, 176, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'a', sample.shape: (14, 64, 64, 3), target_size: 176, scale: 2.75)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'a' shape: (14, 176, 176, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'a', sample.shape: (14, 64, 64, 3), target_size: 176, scale: 2.75)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'a' shape: (14, 176, 176, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _overlay_foreground       DEBUG    Overlayed foreground. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _overlay_foreground       DEBUG    Overlayed foreground. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _overlay_foreground       DEBUG    Overlayed foreground. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'a', sample.shape: (14, 256, 256, 3), target_size: 128, scale: 0.5)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'a' shape: (14, 128, 128, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'a', sample.shape: (14, 256, 256, 3), target_size: 128, scale: 0.5)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'a' shape: (14, 128, 128, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'a', sample.shape: (14, 256, 256, 3), target_size: 128, scale: 0.5)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'a' shape: (14, 128, 128, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    side: 'a', width: 128
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    height: 32, total_width: 384
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    texts: ['Original (A)', 'Original > Original', 'Original > Swap'], text_sizes: [(72, 9), (116, 9), (102, 9)], text_x: [28, 134, 269], text_y: 20
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    header_box.shape: (32, 384, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _to_full_frame            DEBUG    side: 'b', number of sample arrays: 3, prediction.shapes: [(14, 64, 64, 3), (14, 64, 64, 3)])
06/12/2020 12:17:02 MainProcess     _training_0     _base           _frame_overlay            DEBUG    full_size: 256, target_size: 176, color: (0, 0, 255)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _frame_overlay            DEBUG    Overlayed background. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'b', sample.shape: (14, 64, 64, 3), target_size: 176, scale: 2.75)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'b' shape: (14, 176, 176, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'b', sample.shape: (14, 64, 64, 3), target_size: 176, scale: 2.75)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'b' shape: (14, 176, 176, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'b', sample.shape: (14, 64, 64, 3), target_size: 176, scale: 2.75)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'b' shape: (14, 176, 176, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _overlay_foreground       DEBUG    Overlayed foreground. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _overlay_foreground       DEBUG    Overlayed foreground. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _overlay_foreground       DEBUG    Overlayed foreground. Shape: (14, 256, 256, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'b', sample.shape: (14, 256, 256, 3), target_size: 128, scale: 0.5)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'b' shape: (14, 128, 128, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'b', sample.shape: (14, 256, 256, 3), target_size: 128, scale: 0.5)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'b' shape: (14, 128, 128, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resizing sample: (side: 'b', sample.shape: (14, 256, 256, 3), target_size: 128, scale: 0.5)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _resize_sample            DEBUG    Resized sample: (side: 'b' shape: (14, 128, 128, 3))
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    side: 'b', width: 128
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    height: 32, total_width: 384
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    texts: ['Swap (B)', 'Swap > Swap', 'Swap > Original'], text_sizes: [(59, 9), (87, 9), (102, 9)], text_x: [34, 148, 269], text_y: 20
06/12/2020 12:17:02 MainProcess     _training_0     _base           _get_headers              DEBUG    header_box.shape: (32, 384, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _duplicate_headers        DEBUG    side: a header.shape: (32, 384, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _duplicate_headers        DEBUG    side: b header.shape: (32, 384, 3)
06/12/2020 12:17:02 MainProcess     _training_0     _base           _stack_images             DEBUG    Stack images
06/12/2020 12:17:02 MainProcess     _training_0     _base           get_transpose_axes        DEBUG    Even number of images to stack
06/12/2020 12:17:02 MainProcess     _training_0     _base           _stack_images             DEBUG    Stacked images
06/12/2020 12:17:02 MainProcess     _training_0     _base           show_sample               DEBUG    Compiled sample
06/12/2020 12:17:02 MainProcess     _training_0     _base           save_models               DEBUG    Backing up and saving models
06/12/2020 12:17:02 MainProcess     _training_0     _base           get_save_averages         DEBUG    Getting save averages
06/12/2020 12:17:02 MainProcess     _training_0     _base           get_save_averages         DEBUG    Average losses since last save: {'a': 0.23478934168815613, 'b': 0.1909620612859726}
06/12/2020 12:17:02 MainProcess     _training_0     _base           check_loss_drop           DEBUG    Loss for 'a' has not dropped
06/12/2020 12:17:02 MainProcess     _training_0     _base           should_backup             DEBUG    Lowest historical save iteration loss average: {'a': 0.2322780340909958, 'b': 0.19263961911201477}
06/12/2020 12:17:02 MainProcess     _training_0     _base           should_backup             DEBUG    Backing up: False
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 _base           save                      DEBUG    Saving model: 'C:\Users\xd\PycharmProjects\faceswap\model\zgj_ym\original_decoder_A.h5'
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_1 _base           save                      DEBUG    Saving model: 'C:\Users\xd\PycharmProjects\faceswap\model\zgj_ym\original_decoder_B.h5'
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_2 _base           save                      DEBUG    Saving model: 'C:\Users\xd\PycharmProjects\faceswap\model\zgj_ym\original_encoder.h5'
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 _base           save                      DEBUG    Saving State
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 serializer      save                      DEBUG    filename: C:\Users\xd\PycharmProjects\faceswap\model\zgj_ym\original_state.json, data type: <class 'dict'>
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 serializer      _check_extension          DEBUG    Original filename: 'C:\Users\xd\PycharmProjects\faceswap\model\zgj_ym\original_state.json', final filename: 'C:\Users\xd\PycharmProjects\faceswap\model\zgj_ym\original_state.json'
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 serializer      marshal                   DEBUG    data type: <class 'dict'>
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 serializer      marshal                   DEBUG    returned data type: <class 'bytes'>
06/12/2020 12:17:02 MainProcess     ThreadPoolExecutor-16_0 _base           save                      DEBUG    Saved State
06/12/2020 12:17:02 MainProcess     _training_0     multithreading  run                       DEBUG    Error in thread (_training_0): The Session graph is empty.  Add operations to the graph before calling run().
06/12/2020 12:17:03 MainProcess     MainThread      train           _monitor                  DEBUG    Thread error detected
06/12/2020 12:17:03 MainProcess     MainThread      train           _monitor                  DEBUG    Closed Monitor
06/12/2020 12:17:03 MainProcess     MainThread      train           _end_thread               DEBUG    Ending Training thread
06/12/2020 12:17:03 MainProcess     MainThread      train           _end_thread               CRITICAL Error caught! Exiting...
06/12/2020 12:17:03 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: '_training'
06/12/2020 12:17:03 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: '_training_0'
06/12/2020 12:17:03 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: '_training_0'
Traceback (most recent call last):
  File "C:\Users\xd\PycharmProjects\faceswap\lib\cli\launcher.py", line 155, in execute_script
    process.process()
  File "C:\Users\xd\PycharmProjects\faceswap\scripts\train.py", line 162, in process
    self._end_thread(thread, err)
  File "C:\Users\xd\PycharmProjects\faceswap\scripts\train.py", line 202, in _end_thread
    thread.join()
  File "C:\Users\xd\PycharmProjects\faceswap\lib\multithreading.py", line 121, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\Users\xd\PycharmProjects\faceswap\lib\multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xd\PycharmProjects\faceswap\scripts\train.py", line 227, in _training
    raise err
  File "C:\Users\xd\PycharmProjects\faceswap\scripts\train.py", line 217, in _training
    self._run_training_cycle(model, trainer)
  File "C:\Users\xd\PycharmProjects\faceswap\scripts\train.py", line 316, in _run_training_cycle
    model.save_models()
  File "C:\Users\xd\PycharmProjects\faceswap\plugins\train\model\_base.py", line 477, in save_models
    _ = [thread.result() for thread in save_threads]
  File "C:\Users\xd\PycharmProjects\faceswap\plugins\train\model\_base.py", line 477, in <listcomp>
    _ = [thread.result() for thread in save_threads]
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\concurrent\futures\_base.py", line 425, in result
    return self.__get_result()
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\concurrent\futures\_base.py", line 384, in __get_result
    raise self._exception
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\concurrent\futures\thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\xd\PycharmProjects\faceswap\plugins\train\model\_base.py", line 856, in save
    self.weights = self.network.get_weights()
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\site-packages\keras\engine\network.py", line 504, in get_weights
    return K.batch_get_value(weights)
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\site-packages\keras\backend\tensorflow_backend.py", line 2939, in batch_get_value
    return tf_keras_backend.batch_get_value(ops)
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\site-packages\tensorflow\python\keras\backend.py", line 2819, in batch_get_value
    return get_session().run(tensors)
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Users\xd\Anaconda3\envs\pytorch2\lib\site-packages\tensorflow\python\client\session.py", line 1077, in _run
    raise RuntimeError('The Session graph is empty.  Add operations to the '
RuntimeError: The Session graph is empty.  Add operations to the graph before calling run().

**Comment by torzdf** [comment]
This looks like a local install issue. I recommend setting up a new virtual environment and trying again.

If this doesn't work, please look for usage support on  our [Discord server](https://discord.gg/FC54sYg) or [Forum](https://faceswap.dev/forum)
