### ISSUE TITLE
The distinction between neck parts is obvious

### ISSUE THREAD

**Issue by stone100010** [deepfakes/faceswap#1031]
I'm trying to replace the head, and the effect of head replacement is OK. There is a small problem. I didn't mark the necks of both sides when I marked the data, so that the neck parts were clearly distinguished after replacement. Can we complete the fusion by blurring the neck area?

**Comment by bryanlyon** [comment]
Please only use issues for actual code bugs.  For questions on using the application please post on https://forum.faceswap.dev/ .  However, we do have blur options, you can test the various settings to find a good match for your video in the preview tool.
