### ISSUE TITLE
Rebuilding TensorFlow backend

### ISSUE THREAD

**Issue by VadVergasov** [deepfakes/faceswap#1036]
When using the FaceSwap there is an info message:
`I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2`

Is there a way to rebuild the TensorFlow binary in the FaceSwap environment to add AVX and AVX 2 instructions?
OS: Windows 10 x64.
Using the Conda as environment manager.

**Comment by torzdf** [comment]
Yes. although I believe that the Conda version is compiled with AVX (should be pulled in by the installer)

**Comment by VadVergasov** [comment]
Removing tensorflow from environment and installing tensorflow==1.15.0 and tesnorflow-gpu==1.15.0 added AVX instructions.
