### ISSUE TITLE
"Failed to get convolution algorithm" while Trainning

### ISSUE THREAD

**Issue by paulosalgado** [deepfakes/faceswap#1039]
Just installed Faceswap on my computer using the script provided and, when tried the Training function, got this error: 

[crash_report.2020.07.28.003102128162.log](https://github.com/deepfakes/faceswap/files/4985835/crash_report.2020.07.28.003102128162.log)

I don't have CUDA nor CUDNN installed.

Can you guys help?

Thanks in advance.

**Comment by torzdf** [comment]
Enable the "allow growth" option.

**Comment by paulosalgado** [comment]
Is this option on the GUI? If so, it's already selected.

![Screenshot_2020-07-28_18-26-49](https://user-images.githubusercontent.com/1883285/88724038-348bbe00-d100-11ea-9ab3-77c649e26b95.png)

**Comment by paulosalgado** [comment]
Can anyone help?
