### ISSUE TITLE
Extract via GPU

### ISSUE THREAD

**Issue by shadowfolder** [deepfakes/faceswap#104]
It seems extract processing via CPU. How to turn it to run via GPU?
My command is python faceswap.py extract -i ~/faceswap/photo/trump -o ~/faceswap/data/trump
All cuda's modes is installed.

**Comment by flip1995** [comment]
Extracting with multiple threads is already on the way. #62

**Comment by Clorr** [comment]
Multi-threading and GPU processing are 2 separate thing. The code here does not use GPU at all, it is only the library used that are made to use it or not. If you want to have GPU for extract you can look for a `dlib` compiled with CUDA support.

In #62, there is a proposal for multi threading, which will increase throughput by using all CPU cores, but not use GPU

**Comment by Clorr** [comment]
Now done in #109
