### ISSUE TITLE
How to output video?

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [deepfakes/faceswap#1042]
When I select a video and use convert, only a lot of images appear in the output folder. So I was confused as to whether the program included the ability to output Faceswap video directly. Or what tools do I need to convert frames into video?

**Comment by torzdf** [comment]
Use the "FFMEG" plugin in the writer settings.

Please direct further general usage question to the [FaceSwap Discord server](https://discord.gg/FC54sYg) or the [FaceSwap Forum](https://faceswap.dev/forum)
