### ISSUE TITLE
Hello,I wonder that when build its environment,will my detectron2 and tensorflow get destoryed?I have download CUDA10.0,so should I choose yes when being asked "enable CUDA"?

### ISSUE THREAD

**Issue by Blackpinkup** [deepfakes/faceswap#1043]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by torzdf** [comment]
Please direct usage questions to the [FaceSwap Discord server](https://discord.gg/FC54sYg) or the [FaceSwap Forum](https://faceswap.dev/forum)
