### ISSUE TITLE
how i manual the option if there resource only one side of face?

### ISSUE THREAD

**Issue by ACG-MM** [deepfakes/faceswap#1044]
i try to train this resource with default setting in faceswap graphical client. it never get final result. should i change the trainer or some ting? i ve tried to google so excuse me.
![Capture](https://user-images.githubusercontent.com/63167197/89531689-39005700-d823-11ea-8a86-b8d09002e6ef.PNG)

**Comment by ACG-MM** [comment]
hello ;[

**Comment by torzdf** [comment]
The github is for bugs and issues. You are best off getting tips about this kind of thing from our Discord Server:

https://discord.gg/FC54sYg
