### ISSUE TITLE
"Failed to get convolution algorithm" while Trainning

### ISSUE THREAD

**Issue by paulosalgado** [deepfakes/faceswap#1046]
Just installed Faceswap on my computer using the script provided and, when tried the Training function, got this error: 

[crash_report.2020.07.28.003102128162.log](https://github.com/deepfakes/faceswap/files/4985835/crash_report.2020.07.28.003102128162.log)

Allow Growth option is enable in the GUI: 
![Untitled](https://user-images.githubusercontent.com/1883285/88724238-87657580-d100-11ea-9fa8-fa88b9195277.png)

I don't have CUDA nor CUDNN installed.

Can you guys help?

Thanks in advance.

PS: originally posted this [issue](https://github.com/deepfakes/faceswap/issues/1039), however, was closed without resolution.

**Comment by torzdf** [comment]
This is basically an out of memory issue. You might be able to train with a super low batchsize, but most likely that card will not be able to handle Faceswap.
