### ISSUE TITLE
Allow change the font color of the prompt window

### ISSUE THREAD

**Issue by poly000** [deepfakes/faceswap#1047]
**Describe the solution you'd like**
Allow change the font color of the prompt window (mouse hover on a option to callout), it's hard to see the contents on linux.

**Additional context**
![图片](https://user-images.githubusercontent.com/34085039/90350481-e8cd9400-e06f-11ea-827d-ba95fca940fb.png)

**Comment by GoldExplosion** [comment]
i would like to take this issue, seems like a good first issue. but sure how to proceed?

**Comment by torzdf** [comment]
@GoldExplosion Sure. Go for it....

You'll need to add a config option to https://github.com/deepfakes/faceswap/blob/master/lib/gui/_config.py and reference it in https://github.com/deepfakes/faceswap/blob/725d8649752057cfcf7ba485772007c1805406a8/lib/gui/custom_widgets.py#L532

**Comment by GoldExplosion** [comment]
thank you

**Comment by GoldExplosion** [comment]
@poly000, the solution is to change the colour of the main menu bar, am i right to assume that?

**Comment by torzdf** [comment]
Closing due to #1053
