### ISSUE TITLE
Allow direct call in python

### ISSUE THREAD

**Issue by consciousgaze** [deepfakes/faceswap#1048]
**Is your feature request related to a problem? Please describe.**
Now the conversion is always through faceswap.py or GUI. But sometimes I want to directly write python to do training/extracting/converting. But I found it is not easy to construct a proper argparse.Namesapce  object to pass to the convert.Convert class. Is it possible to provide a direct python interface to extract, train and convert?

**Describe the solution you'd like**
Provide a Convert function/class that direclty accepts the parameters, not through argparse.

**Describe alternatives you've considered**
My current issue is that I can only use the 1080 on my computer not the 2060. My search shows me that I have to set the tf.config to allow growth (https://github.com/tensorflow/tensorflow/issues/24828#issuecomment-464957482). This setting exists in extract but not in convert. May be add the setting into convert to?

**Comment by torzdf** [comment]
Sure, it's possible, but it's unlikely to be something we implement, as argparse is the main entry point for the faceswap software and passing the namespace through the various processes is a lot easier in terms of code maintenance.

That said, you can just create your own "dummy" namespace.

https://stackoverflow.com/questions/28345780/how-do-i-create-a-python-namespace-argparse-parse-args-value
