### ISSUE TITLE
Add extractor feature to label image with face pose?

### ISSUE THREAD

**Issue by consciousgaze** [deepfakes/faceswap#1051]
Though there may exist lots of face frames in a video, it is very like that most of the frames are similar to each other. 
E.g in one period of time, a person may just stand there and talking. In such cases, i believe 90% of the face images are useless in training since they are similar to each other. Only some of them with meaningful changes (face direction, facial expression etc.) are useful. Thus I am curious whether to label a face image with such information (or put similar ones into one folder).

I think a good solution to start can be face-pose labeling. If we imaging an arrow starting from the center of the head and pointing to the nose tip, the face-pose can be accurately described by the angle of the formed arrow. If we let the arrow length to be unit, the face-pose can be expressed with a 3d vector (i.e. three numbers) on the unit sphere. 

If we provide a number of classes, say n, we can have n vectors that uniformly distributed on the unit sphere and face images can be categorized into these n classes.

--- P.S. --
* There are other categorization ways such as using cross-correlation between two images as the distance function between two images and use it for categorization. But I believe it may be pretty computational expensive since this is an O(n^2) algorithm.
* I believe this request is different from #123 since that issue majorly concerns face set similarity between two sources.
* I am willing to do this contribution myself too (with limited commitment), but I may need some guide/discussion on where to put this feature and what coding guidelines I need to follow.

**Comment by torzdf** [comment]
I would very much welcome a PR on this, to investigate it's usefulness, but it is unlikely I would develop anything like it.

I would guess this would be best as a tool, perhaps part of the sort tool (which really needs a rework anyway),
