### ISSUE TITLE
AttributeError: 'module' object has no attribute 'abc'

### ISSUE THREAD

**Issue by ChocolateJin** [deepfakes/faceswap#1056]
Question is as on the title. Don't know how to deal with it. Plz help me!!!
The concrete information(Maybe is a noob question since I am using python the first time.):

E:\gitfile\faceswap>py -2 faceswap.py
Setting Faceswap backend to NVIDIA
Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    from lib.cli import args
  File "E:\gitfile\faceswap\lib\cli\args.py", line 11, in <module>
    from lib.utils import get_backend
  File "E:\gitfile\faceswap\lib\utils.py", line 589, in <module>
    class KerasFinder(importlib.abc.MetaPathFinder):
AttributeError: 'module' object has no attribute 'abc'

**Comment by bryanlyon** [comment]
Issues are for code bugs not for technical support. You can go to the forums or discord for support. I suggest starting here https://forum.faceswap.dev/app.php/faqpage?sid=0cf9364decab1e655b7a44b4a450a885#f1r1
