### ISSUE TITLE
How to use GPU to train model?

### ISSUE THREAD

**Issue by ooobsidian** [deepfakes/faceswap#1057]
## Expected behavior
I use `python faceswap.py train -A /data/data/face_data/fss_extract -ala /data/data/face_data/fss/alignments.fsa -B /data/data/face_data/pdd_extract -alb /data/data/face_data/pdd/alignments.fsa -m model -bs 16` to train model.
And I want GPU has high utilization, but it not.

## Actual behavior

But CPU has a high utilization rate.

**Comment by test1230-lab** [comment]
How did you determine the gpu utilization %￼

**Comment by ooobsidian** [comment]
`nvidia-smi`

**Comment by bryanlyon** [comment]
Issues are for code bugs not for technical support.  You can go to the forums or discord for support.  I suggest starting here https://forum.faceswap.dev/app.php/faqpage?sid=0cf9364decab1e655b7a44b4a450a885#f1r1
