### ISSUE TITLE
Can't find faceswap-model you called in readme.md

### ISSUE THREAD

**Issue by StevenJokes** [deepfakes/faceswap#1058]
![image](https://user-images.githubusercontent.com/25657787/91722882-7d3a0980-ebcd-11ea-87c0-f55c6ab68553.png)

https://github.com/deepfakes-models/faceswap-models/releases
Is it?
Where can  discuss/suggest/commit?

**Comment by bryanlyon** [comment]
We mainly do discussions at the forum or discord.  https://forum.faceswap.org
