### ISSUE TITLE
crash when launching faceswap gui on windows

### ISSUE THREAD

**Issue by walkingmu** [deepfakes/faceswap#1059]
**Describe the bug**
When launching gui using command "python faceswap.py gui", the gui pops up and then goes away by itself almost immediately.

**To Reproduce**
run python faceswap.py gui command

**Expected behavior**
GUI shows up normally.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Python Version [e.g. 3.5, 3.6] 3.8
 - Conda Version [e.g. 4.5.12] 4.8.4
 - Commit ID [e.g. e83819f]  e6d62b8
 - 
**Additional context**

**Crash Report**
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: extract)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'options_panel_width')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 30)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'console_panel_height')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 20)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'icon_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 14)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: default)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 9)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'autosave_last_session')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: prompt)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'timeout')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 120)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'auto_load_model_stats')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: True)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'fullscreen')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'tab')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: extract)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'options_panel_width')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 30)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'console_panel_height')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 20)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'icon_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 14)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: default)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 9)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'autosave_last_session')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: prompt)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'timeout')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 120)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'auto_load_model_stats')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: True)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'fullscreen')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'tab')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: extract)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'options_panel_width')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 30)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'console_panel_height')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 20)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'icon_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 14)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: default)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 9)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'autosave_last_session')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: prompt)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'timeout')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 120)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'auto_load_model_stats')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: True)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'fullscreen')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: False)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'tab')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: extract)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'options_panel_width')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 30)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'console_panel_height')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 20)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'icon_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 14)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: default)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'font_size')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 9)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'autosave_last_session')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'str'>, value: prompt)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'timeout')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'int'>, value: 120)
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Getting config item: (section: 'global', option: 'auto_load_model_stats')
09/04/2020 11:35:18 MainProcess     MainThread      config          get                       DEBUG    Returning item: (type: <class 'bool'>, value: True)
09/04/2020 11:35:18 MainProcess     MainThread      utils           set_geometry              DEBUG    Geometry: 1602x854
09/04/2020 11:35:18 MainProcess     MainThread      wrapper         __init__                  DEBUG    Initializing ProcessWrapper
09/04/2020 11:35:18 MainProcess     MainThread      wrapper         set_callbacks             DEBUG    Setting tk variable traces
09/04/2020 11:35:18 MainProcess     MainThread      wrapper         __init__                  DEBUG    Initializing FaceswapControl
09/04/2020 11:35:18 MainProcess     MainThread      wrapper         __init__                  DEBUG    Initialized FaceswapControl
09/04/2020 11:35:18 MainProcess     MainThread      wrapper         __init__                  DEBUG    Initialized ProcessWrapper
09/04/2020 11:35:18 MainProcess     MainThread      utils           delete_preview            DEBUG    Deleting previews
09/04/2020 11:35:18 MainProcess     MainThread      utils           _clear_image_cache        DEBUG    Clearing image cache
09/04/2020 11:35:18 MainProcess     MainThread      utils           __init__                  DEBUG    Initializing: PreviewTrigger
09/04/2020 11:35:18 MainProcess     MainThread      utils           __init__                  DEBUG    Initialized: PreviewTrigger (trigger_file: E:\Code\python\deepfakes_new\lib\gui\.cache\.preview_trigger)
09/04/2020 11:35:18 MainProcess     MainThread      gui             build_gui                 DEBUG    Building GUI
09/04/2020 11:35:18 MainProcess     MainThread      menu            __init__                  DEBUG    Initializing MainMenuBar
09/04/2020 11:35:18 MainProcess     MainThread      menu            __init__                  DEBUG    Initializing FileMenu
09/04/2020 11:35:18 MainProcess     MainThread      menu            build                     DEBUG    Building File menu
09/04/2020 11:35:18 MainProcess     MainThread      menu            build                     DEBUG    Built File menu
09/04/2020 11:35:18 MainProcess     MainThread      menu            __init__                  DEBUG    Initialized FileMenu
09/04/2020 11:35:18 MainProcess     MainThread      menu            __init__                  DEBUG    Initializing SettingsMenu
09/04/2020 11:35:18 MainProcess     MainThread      menu            scan_for_plugin_configs   DEBUG    Scanning path: 'e:\Code\python\deepfakes_new\plugins'
09/04/2020 11:35:18 MainProcess     MainThread      config          __init__                  DEBUG    Initializing: Config
09/04/2020 11:35:18 MainProcess     MainThread      config          get_config_file           DEBUG    Config File location: 'e:\Code\python\deepfakes_new\config\convert.ini'
09/04/2020 11:35:18 MainProcess     MainThread      _config         set_defaults              DEBUG    Setting defaults
09/04/2020 11:35:18 MainProcess     MainThread      _config         load_module               DEBUG    Adding defaults: (filename: color_transfer_defaults.py, module_path: Code.python.deepfakes_new.plugins.convert.color, plugin_type: color
09/04/2020 11:35:18 MainProcess     MainThread      _config         load_module               DEBUG    Importing defaults module: Code.python.deepfakes_new.plugins.convert.color.color_transfer_defaults
Traceback (most recent call last):
  File "e:\Code\python\deepfakes_new\lib\cli\launcher.py", line 155, in execute_script
    process = script(arguments)
  File "e:\Code\python\deepfakes_new\scripts\gui.py", line 193, in __init__
    self.root = FaceswapGui(arguments.debug)
  File "e:\Code\python\deepfakes_new\scripts\gui.py", line 35, in __init__
    self.build_gui()
  File "e:\Code\python\deepfakes_new\scripts\gui.py", line 66, in build_gui
    self.configure(menu=MainMenuBar(self))
  File "e:\Code\python\deepfakes_new\lib\gui\menu.py", line 44, in __init__
    self.settings_menu = SettingsMenu(self)
  File "e:\Code\python\deepfakes_new\lib\gui\menu.py", line 59, in __init__
    self.configs = self.scan_for_plugin_configs()
  File "e:\Code\python\deepfakes_new\lib\gui\menu.py", line 73, in scan_for_plugin_configs
    config = self.load_config(plugin_type)
  File "e:\Code\python\deepfakes_new\lib\gui\menu.py", line 90, in load_config
    config = module.Config(None)
  File "e:\Code\python\deepfakes_new\lib\config.py", line 27, in __init__
    self.set_defaults()
  File "e:\Code\python\deepfakes_new\plugins\convert\_config.py", line 31, in set_defaults
    self.load_module(filename, import_path, plugin_type)
  File "e:\Code\python\deepfakes_new\plugins\convert\_config.py", line 40, in load_module
    mod = import_module("{}.{}".format(module_path, module))
  File "C:\Users\abcdef\Anaconda3\envs\deepfakes\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Code'

============ System Information ============
encoding:            cp1252
git_branch:          master
git_commits:         e6d62b8 Bugfixes:   - dfl_h128 Legacy Weights update   - lib.faces_detect - Logging fix. 35b6cd1 Merge branch 'staging'. 074f305 Update losses unit tests. 1e86299 Update INSTALL.md. 24c45f9 Update INSTALL.md
gpu_cuda:            10.1
gpu_cudnn:           No global version found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: GeForce RTX 2070
gpu_devices_active:  GPU_0
gpu_driver:          452.06
gpu_vram:            GPU_0: 8192MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.19041-SP0
os_release:          10
py_command:          faceswap.py gui
py_conda_version:    conda 4.8.4
py_implementation:   CPython
py_version:          3.8.5
py_virtual_env:      True
sys_cores:           12
sys_processor:       Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
sys_ram:             Total: 65379MB, Available: 58612MB, Used: 6766MB, Free: 58612MB

=============== Pip Packages ===============
absl-py==0.10.0
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
fastcluster==1.1.26
ffmpy==0.2.3
gast==0.3.3
google-auth==1.21.1
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
h5py==2.10.0
idna==2.10
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work
imageio-ffmpeg @ file:///home/conda/feedstock_root/build_artifacts/imageio-ffmpeg_1589202782679/work
joblib @ file:///tmp/build/80754af9/joblib_1594236160679/work
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib @ file:///C:/ci/matplotlib-base_1592837548929/work
mkl-fft==1.1.0
mkl-random==1.1.1
mkl-service==2.3.0
numpy @ file:///C:/ci/numpy_and_numpy_base_1596215850360/work
nvidia-ml-py3 @ git+https://github.com/deepfakes/nvidia-ml-py3.git@6fc29ac84b32bad877f078cb4a777c1548a00bf6
oauthlib==3.1.0
olefile==0.46
opencv-python==4.4.0.42
opt-einsum==3.3.0
pathlib==1.0.1
Pillow @ file:///C:/ci/pillow_1594298230227/work
protobuf==3.13.0
psutil @ file:///C:/ci/psutil_1598370330503/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
pywin32==227
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn @ file:///C:/ci/scikit-learn_1598377018496/work
scipy==1.4.1
sip==4.19.13
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow-gpu==2.2.0
tensorflow-gpu-estimator==2.2.0
termcolor==1.1.0
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tornado==6.0.4
tqdm @ file:///tmp/build/80754af9/tqdm_1596810128862/work
urllib3==1.25.10
Werkzeug==1.0.1
wincertstore==0.2
wrapt==1.12.1

============== Conda Packages ==============
# packages in environment at C:\Users\abcdef\Anaconda3\envs\deepfakes:
#
# Name                    Version                   Build  Channel
absl-py                   0.10.0                   pypi_0    pypi
astunparse                1.6.3                    pypi_0    pypi
blas                      1.0                         mkl  
ca-certificates           2020.7.22                     0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20                py38_0  
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.1.243             h74a9793_0  
cudnn                     7.6.5                cuda10.1_0  
cycler                    0.10.0                   py38_0  
fastcluster               1.1.26           py38hbe40bda_1    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
ffmpy                     0.2.3                    pypi_0    pypi
freetype                  2.10.2               hd328e21_0  
gast                      0.3.3                    pypi_0    pypi
google-auth               1.21.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.31.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha925a31_3  
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                      py_0  
imageio-ffmpeg            0.4.2                      py_0    conda-forge
intel-openmp              2020.2                      254  
joblib                    0.16.0                     py_0  
jpeg                      9b                   hb83a4c4_2  
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.2.0            py38h74a9793_0  
libpng                    1.6.37               h2a8f88b_0  
libtiff                   4.1.0                h56a325e_1  
lz4-c                     1.9.2                h62dcd97_1  
markdown                  3.2.2                    pypi_0    pypi
matplotlib                3.2.2                         0  
matplotlib-base           3.2.2            py38h64f37c6_0  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38hb782905_0  
mkl_fft                   1.1.0            py38h45dec08_0  
mkl_random                1.1.1            py38h47e9c7a_0  
numpy                     1.19.1           py38h5510c5b_0  
numpy-base                1.19.1           py38ha3acd2a_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
olefile                   0.46                       py_0  
opencv-python             4.4.0.42                 pypi_0    pypi
openssl                   1.1.1g               he774522_1  
opt-einsum                3.3.0                    pypi_0    pypi
pathlib                   1.0.1                      py_1  
pillow                    7.2.0            py38hcc1f983_0  
pip                       20.2.2                   py38_0    anaconda
protobuf                  3.13.0                   pypi_0    pypi
psutil                    5.7.2            py38he774522_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38ha925a31_4  
python                    3.8.5                he1778fa_0    anaconda
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pywin32                   227              py38he774522_1  
qt                        5.9.7            vc14h73c81de_0  
requests                  2.24.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.23.2           py38h47e9c7a_0  
scipy                     1.4.1                    pypi_0    pypi
setuptools                49.6.0                   py38_0    anaconda
sip                       4.19.13          py38ha925a31_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h2a8f88b_0    anaconda
tensorboard               2.2.2                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow-gpu            2.2.0                    pypi_0    pypi
tensorflow-gpu-estimator  2.2.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               he774522_0  
tornado                   6.0.4            py38he774522_1  
tqdm                      4.48.2                     py_0  
urllib3                   1.25.10                  pypi_0    pypi
vc                        14.1                 h0510ff6_4    anaconda
vs2015_runtime            14.16.27012          hf0eaf9b_3    anaconda
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0    anaconda
wincertstore              0.2                      py38_0    anaconda
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0  
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]  anaconda
zstd                      1.4.5                h04227a9_0  

================= Configs ==================
--------- .faceswap ---------
backend:                  nvidia

--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[color.match_hist]
threshold:                99.0

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[mask.mask_blend]
type:                     normalized
kernel_size:              3
passes:                   4
threshold:                4
erosion:                  0.0

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto
skip_mux:                 False

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

--------- extract.ini ---------

[global]
allow_growth:             False

[align.fan]
batch-size:               12

[detect.cv2_dnn]
confidence:               50

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.s3fd]
confidence:               70
batch-size:               4

[mask.unet_dfl]
batch-size:               8

[mask.vgg_clear]
batch-size:               6

[mask.vgg_obstructed]
batch-size:               2

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
icon_size:                14
font:                     default
font_size:                9
autosave_last_session:    prompt
timeout:                  120
auto_load_model_stats:    True

--------- train.ini ---------

[global]
coverage:                 68.75
icnr_init:                False
conv_aware_init:          False
optimizer:                adam
learning_rate:            5e-05
reflect_padding:          False
allow_growth:             False
mixed_precision:          False
convert_batchsize:        16

[global.loss]
loss_function:            ssim
mask_loss_function:       mse
l2_reg_term:              100
eye_multiplier:           12
mouth_multiplier:         8
penalized_mask_loss:      True
mask_type:                extended
mask_blur_kernel:         3
mask_threshold:           4
learn_mask:               False

[model.dfl_h128]
lowmem:                   False

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.dlight]
features:                 best
details:                  good
output_size:              256

[model.original]
lowmem:                   False

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.villain]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4

**Comment by bryanlyon** [comment]
Issues are for code bugs not for technical support. You can go to the forums or discord for support. I suggest starting here https://forum.faceswap.dev/app.php/faqpage?sid=0cf9364decab1e655b7a44b4a450a885#f1r1
