### ISSUE TITLE
Frame advance in manual corrections

### ISSUE THREAD

**Issue by dpedrelli** [deepfakes/faceswap#1061]
This isn't so much of a problem, but it would make the program easier and more intuitive to use.

In the manual corrections mode, there are buttons to go to previous and next frames.  The preview section display images based on the alignments file.  As it is, if I am on frame 4116 and I click Next, it goes to 4117.  However, my next available frame is 4128.  I think it would be easier to use and less confusing to new users if Next/Previous navigated by the frames that are displayed.

**Comment by torzdf** [comment]
You can do this by changing the filter mode to "Has faces"
