### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by fuorissimo** [deepfakes/faceswap#1065]
Hello, i have write here a list of bugs:

https://twitter.com/FuorissimoX/status/1307832275053293569?s=20

**Comment by bryanlyon** [comment]
These are not a bugs and are mostly normal.  You have a very small amount of vram and it sounds like 3 is the largest batch size you can support.  The FSA is created with the original video unless you specify differently.  This is as designed.  PlaidML is converting Cuda Ops to OpenCL and some warning messages are normal.  As long as it's training that's fine.

On the forum: Check your spam/junk folder.  I guarantee it sends an email every time.  You can also join our Discord if you have any questions.

**Comment by fuorissimo** [comment]
I have 4Gb of vram. It's not small. System tell that size batch = 8 is normal for 2 gb. So i expect that work with 16 value, not with 3
![Screenshot (349)](https://user-images.githubusercontent.com/35644089/93734214-9f291980-fbd8-11ea-86f5-9716fd6662f2.png)

![Screenshot (350)](https://user-images.githubusercontent.com/35644089/93734247-c41d8c80-fbd8-11ea-9af5-681c1115312c.png)

**Comment by torzdf** [comment]
I don't know who added that help text (well, I do), but it's a guide at best.

S3FD takes close to 4GB just for the model itself. It's possible that means 2GB + the model size.

Ultimately, @bryanlyon is correct. These are not bugs. Reduce your batch size.
