### ISSUE TITLE
meet error when extrarct image

### ISSUE THREAD

**Issue by MCredbear** [deepfakes/faceswap#1066]
My system is Ubuntu 20.04, nvidia driver version is 450,CUDA version is 11,I think my CUDA is working well because I can run Hashcat with CUDA.
Here is my log:
[crash_report.2020.09.23.011725109505.log](https://github.com/deepfakes/faceswap/files/5263038/crash_report.2020.09.23.011725109505.log)

**Comment by torzdf** [comment]
For some reason you don't have psutil installed, so I can't see the whole log.

However this looks like the same issue: #1071
