### ISSUE TITLE
Windows VS Linux performance benchmark

### ISSUE THREAD

**Issue by shawnngtq** [deepfakes/faceswap#1068]
**Is your feature request related to a problem? Please describe.**
I was wondering if anyone has conduct a performance benchmark between Windows 10 and Linux OS using the same hardware and dataset?

**Describe the solution you'd like**
A simple table showing the time taken for each steps (extract, train, convert, gui) by 2 OS. With a few simple lines of comments if they are important and not addressable by merely time taken.

**Describe alternatives you've considered**
NIL.

**Additional context**
NIL.

**Comment by torzdf** [comment]
I doubt anything like this will be implemented... I simply do not have the time, although anyone else is welcome to post benchmark stats.

Probably the best place for this discussion is on our discord (https://discord.gg/FC54sYg) or our forum (https://forum.faceswap.dev/index.php) though.

**Comment by shawnngtq** [comment]
@torzdf thanks for the fast response, so would you recommend using Linux / Windows then?

**Comment by torzdf** [comment]
Linux
