### ISSUE TITLE
Default MaxPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by LiZhi1919** [deepfakes/faceswap#1071]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
tensorflow.python.framework.errors_impl.InvalidArgumentError:  Default MaxPoolingOp only supports NHWC on device type CPU
when I run the extract process, this happened,

**To Reproduce**
python faceswap.py extract -i ./src/shinzo_abe.mp4 -o ./shinzo_abe

**Expected behavior**
it should run 

**Screenshots**
![image](https://user-images.githubusercontent.com/64736134/94329379-1dc4f300-ffed-11ea-9f39-7bef953eb804.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - Python Version [3.8]
 - Conda Version [4.8.5]
- Tensorflow-GPU [2.2.0]

**Crash Report**
The crash report generated in the root of your Faceswap folder
[crash_report.2020.09.26.113402559506.log](https://github.com/deepfakes/faceswap/files/5286135/crash_report.2020.09.26.113402559506.log)

**Comment by torzdf** [comment]
Remove the system installed Cuda and cuDNN and reinstall Faceswap.

Unless you have a custom Tensorflow, you are running the wrong version of Cuda. Coupled with this, for some reason you do not have any Cuda Toolkit installed in your Conda environment.
