### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by ikeacat** [deepfakes/faceswap#1072]
**Describe the bug**
A critical error appears when training (using the IAE model) right after updating to the latest version.. It throws the error described in the title.

**To Reproduce**
1: Press train.
2: Wait for error.

**Expected behavior**
I expected it to start training the model like it did before I updated.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8.1
 - Conda Version 4.8.3

**Crash Report**
https://pastebin.com/UhT6XBd3

**Comment by torzdf** [comment]
Please update to latest code and try again.

I have just tried this model with your settings, and it trains fine.
