### ISSUE TITLE
Not satisfying results 

### ISSUE THREAD

**Issue by ayush9198gupta** [deepfakes/faceswap#1075]
Hi,

I have used this model and complete all the instructions at every end but after convert i am getting blurry faces in the output. I have trained my images over 20 Lakhs iterations but still not satisfying result.also I have used sharpen method but it not worked for my case.

can you help me

**Comment by torzdf** [comment]
A better place for these kinds of messages is in our Discord (https://discord.gg/FC54sYg) or at our forum (https://faceswap.dev/forum), where you are welcome to join.
