### ISSUE TITLE
Crash at start of extraction process

### ISSUE THREAD

**Issue by dosier** [deepfakes/faceswap#1080]
> Setting Faceswap backend to AMD
> 10/17/2020 09:27:05 INFO     Log level set to: INFO
> 10/17/2020 09:27:05 INFO     Setting up for PlaidML
> 10/17/2020 09:27:05 INFO     Using GPU(s): ['AMD - AMD Radeon RX 580 Compute Engine (experimental)']
> 10/17/2020 09:27:05 INFO     Successfully set up for PlaidML
> 10/17/2020 09:27:07 INFO     Output Directory: /Users/stanbend/Documents/DeepFake/PAUL
> 10/17/2020 09:27:09 ERROR    Got Exception on main handler:
> Traceback (most recent call last):
> File "/Users/stanbend/PycharmProjects/faceswap/lib/cli/launcher.py", line 181, in execute_script
> process = script(arguments)
> File "/Users/stanbend/PycharmProjects/faceswap/scripts/extract.py", line 44, in __init__
> self._images = ImagesLoader(self._args.input_dir, fast_count=True)
> File "/Users/stanbend/PycharmProjects/faceswap/lib/image.py", line 756, in __init__
> self._get_count_and_filelist(fast_count, count)
> File "/Users/stanbend/PycharmProjects/faceswap/lib/image.py", line 860, in _get_count_and_filelist
> self._count = int(count_frames(self.location,
> File "/Users/stanbend/PycharmProjects/faceswap/lib/image.py", line 593, in count_frames
> duration = int(convert_to_secs(*output[idx:].split(",", 1)[0].strip().split(":")))
> File "/Users/stanbend/PycharmProjects/faceswap/lib/utils.py", line 217, in convert_to_secs
> retval = float(args[0])
> ValueError: could not convert string to float: 'N/A'

**Describe the bug**
Not sure what the bug is, but it occurs when trying to extract faces out of a mp4/mpv video, before any processing has been done.

**To Reproduce**
1. Go to 'Extract'
2. Click on 'select a video...'
3. Select a mpv/mp4 video
4. Press "Extract"

**Expected behavior**
For the program to extract faces out of a video.

**Desktop (please complete the following information):**
 - OS: macOS Catalina (10.15.7)
 - Python Version [3.8]

**Additional context**
Using GUI

**Crash Report**
[crash_report.2020.10.17.092146109414.log](https://github.com/deepfakes/faceswap/files/5395130/crash_report.2020.10.17.092146109414.log)

**Comment by torzdf** [comment]
This is a problem with your video file. Try converting it to mp4. Ultimately the header of your video file has not stored the duration correctly.
