### ISSUE TITLE
mtcnn extractor warning messages

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#1082]
I tried to change from s3fd to mtccn, to see how the detection went, and then it spewed a lot of messages like this:

10/25/2020 12:40:39 WARNING  5 out of the last 5 calls to <function Model.make_predict_function.<locals>.predict_function at 0x000002AC515C1158> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.

Code pulled from the repo here.

No crash, but the result is slow and the detection is not very good. 

Command line:

python.exe faceswap.py extract -i D:/Fakes/%1 -o D:/Fakes/%1/aligned -al D:/Fakes/%1/aligned.fsa -D s3fd -A fan -M unet-dfl -nm clahe -r on -min 0 -l 0.4 -een 1 -sz 256 -si 0 -L INFO

pip freeze

absl-py==0.10.0
astunparse==1.6.3
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
fastcluster==1.1.26
ffmpy==0.2.3
gast==0.3.3
google-auth==1.21.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.31.0
h5py==2.10.0
idna==2.10
imageio==2.9.0
imageio-ffmpeg==0.4.2
importlib-metadata==1.7.0
joblib==0.16.0
Keras-Preprocessing==1.1.2
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.2.2
numpy==1.18.5
nvidia-ml-py3==7.352.1
oauthlib==3.1.0
opencv-python==4.4.0.42
opt-einsum==3.3.0
pathlib==1.0.1
Pillow==7.2.0
protobuf==3.13.0
psutil==5.7.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==2.4.7
python-dateutil==2.8.1
pywin32==228
requests==2.24.0
requests-oauthlib==1.3.0
rsa==4.6
scikit-learn==0.23.2
scipy==1.4.1
six==1.15.0
tensorboard==2.2.2
tensorboard-plugin-wit==1.7.0
tensorflow-gpu==2.2.0
tensorflow-gpu-estimator==2.2.0
termcolor==1.1.0
threadpoolctl==2.1.0
tqdm==4.48.2
urllib3==1.25.10
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0

**Comment by torzdf** [comment]
Does this issue still persist? I haven't been able to replicate on latest code.

**Comment by Kirin-kun** [comment]
I didn't test recently, as S3FD is doing the job.

I will eventually test again. Stay tuned.

**Comment by torzdf** [comment]
Hugely appreciated. No rush (as it is a secondary detector).

**Comment by torzdf** [comment]
closing issue as stale
