### ISSUE TITLE
RTX 3000 support

### ISSUE THREAD

**Issue by dmiszkiewicz** [deepfakes/faceswap#1083]
Tensorflow-gpu 2.4.0rc0 has support for CUDA11 and cuDNN 8.0.2, so RTX 3000 is working correctly. I will try to create pull request with initial changes to support Tensorflow-gpu 2.4.0rc0 this week. It seems that stuff like extracting and training is working.

**Comment by torzdf** [comment]
Thanks for this.... I won't implement until Tensorflow 2.4 releases in case of API changes....

Ideally I'd wait for Conda to update too, but I know people are sitting on their 3xxx cards wanting to get going.

**Comment by neoblizz** [comment]
@torzdf maybe I can help with this, can you point me to the right set of files to look at?

**Comment by PeterTemps** [comment]
Looking forward to RTX 3000 support.

**Comment by dmiszkiewicz** [comment]
Hi, I created https://github.com/deepfakes/faceswap/pull/1086 which include update TensorFlow to 2.4.0rc1. I tested it with 3080 and basic stuff is working, there is a problem with few things like learning graph and analysis table.

**Comment by torzdf** [comment]
This has been merged into Master.

Whilst Faceswap will now run on the Tensorflow 2.4 api, it will not install it by default (We still need to wait for Conda to update for this).

I have some instructions here: 
https://forum.faceswap.dev/viewtopic.php?f=4&t=1226

However, you are on your own, and we won't directly support this until we can pull Cuda 11 in from Conda.
