### ISSUE TITLE
Being informed on manual preview refresh

### ISSUE THREAD

**Issue by WreckedMessiah** [deepfakes/faceswap#1085]
On slower hardware and with demanding model configurations it can take several minutes until a manual preview refresh actually completes.

For that reason I suggest that another message "Refresh preview done" will be added, so that the user can focus on other things in the meantime and still reliably tell whether the refresh has completed or not.

**Comment by torzdf** [comment]
I *believe* this has been implemented, so closing. Please let me know if it's not working for you.
