### ISSUE TITLE
Crash during Extraction

### ISSUE THREAD

**Issue by achuet** [deepfakes/faceswap#1089]
Hi , Got this error in Windows 10 during Extract process.

Traceback (most recent call last):
  File "C:\Users\ats\faceswap\lib\cli\launcher.py", line 182, in execute_script
    process.process()
  File "C:\Users\ats\faceswap\scripts\extract.py", line 118, in process
    self._run_extraction()
  File "C:\Users\ats\faceswap\scripts\extract.py", line 219, in _run_extraction
    self._output_faces(saver, extract_media)
  File "C:\Users\ats\faceswap\scripts\extract.py", line 285, in _output_faces
    face.hash, image = encode_image_with_hash(face.aligned_face, extension)
  File "C:\Users\ats\faceswap\lib\image.py", line 427, in encode_image_with_hash
    encoded_image = cv2.imencode(extension, image)[1]
cv2.error: OpenCV(4.4.0) C:\Users\appveyor\AppData\Local\Temp\1\pip-req-build-h4wtvo23\opencv\modules\imgcodecs\src\loadsave.cpp:926: error: (-2:Unspecified error) could not find encoder for the specified extension in function 'cv::imencode'

**Comment by PickelR1ck** [comment]
restart the installer and if that doesn't work delete and download the installer again (turning off ur antivirus might help)

**Comment by torzdf** [comment]
Provide crash report.

**Comment by passjwhub** [comment]
I have the same crash issues at the last version on master branch.
I am tring to extract face a 60 min vedio, but when the process most done, the crash happend.
something like this:
    return Invocation(self._ctx, self)
  File "..\lib\site-packages\plaidml\__init__.py", line 1484, in __init__
    self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
OSError: exception: access violation writing 0x0000000000000010


@torzdf 
the total log as annx. thanks. please give me some advise.
[crash_report.2020.11.22.222458711067.log](https://github.com/deepfakes/faceswap/files/5579663/crash_report.2020.11.22.222458711067.log)

**Comment by torzdf** [comment]
> self._as_parameter_ = _lib().plaidml_schedule_invocation(ctx, invoker)
> OSError: exception: access violation writing 0x0000000000000010
> 

This is a GPU memory error. You can try lowering the batch (Settings > Extract Settings), find all the plugins and lower to 1.

However, I believe you are using an integrated GPU, so you may never get this to work.

**Comment by passjwhub** [comment]
> so you may never get this to work.

what you mean ， could you like to give some detail, why i may never get this to work.  It is AMD vega 8, can be work? :)
