### ISSUE TITLE
Document memory usage requirements

### ISSUE THREAD

**Issue by akostadinov** [deepfakes/faceswap#1091]
**Is your feature request related to a problem? Please describe.**
I'm trying to understand what box to get so I can start experimenting with faceswap. So I see a good offer for a 16GB RAM machine (I already have a GPU with 16GB integrated memory) but I don't know if this will allow me to work with descent size videos. e.g. will it let me process 720p videos? 

**Describe the solution you'd like**
Update documentation with some clue of what user to expect as memory requirement. This is related to #5

Thank you.

**Comment by torzdf** [comment]
You're best off looking at this thread for GPU stuff as it gets updated fairly regularly.
https://forum.faceswap.dev/viewtopic.php?f=16&t=10

For RAM, I deliberately dev on a machine limited to 8GB RAM so anything over and above this will be fine.
