### ISSUE TITLE
train_function failed

### ISSUE THREAD

**Issue by chrisgame1002** [deepfakes/faceswap#1097]
Faceswap Linux gui v2.0.0 
when i traning ,i got

Function call stack:
train_function

12/10/2020 12:59:11 CRITICAL An unexpected crash has occurred. Crash report written to '/home/bill/faceswap/crash_report.2020.12.10.125910185970.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

This is my log [crash_report.2020.12.10.125732205001.log](https://github.com/deepfakes/faceswap/files/5670360/crash_report.2020.12.10.125732205001.log)

**Comment by torzdf** [comment]
Uninstall the globally installed Cuda. It is conflicting.
