### ISSUE TITLE
Which algorithm is using ？

### ISSUE THREAD

**Issue by superxi** [deepfakes/faceswap#1098]
Hi：
   Thanks for you awsome work，I'm wondering which algorithm is currently used by the latest version. Is there any related literature or paper for reference?

**Comment by lhprojects** [comment]
I guess if you go through the guide of Extraction, Training and Convert at https://faceswap.dev/. You will have an overview of the whole process procedure and the underlying algorithm.

**Comment by torzdf** [comment]
Yep, it's mostly covered there. Either way, the best place for this kind of discussion is our [forum](https://faceswap.dev/forum) or [Discord](https://discord.gg/FC54sYg)
