### ISSUE TITLE
Program failed to detect GPU.

### ISSUE THREAD

**Issue by GTK-ARJUN** [deepfakes/faceswap#1101]
**Describe the bug**
The program is unable to detect rtx 2070 super

**Desktop (please complete the following information):**
 - OS: windows 10
 - Python Version 3.7.9
 - Conda Version 4.9.2
 - 
**Additional context**
An unhandled exception occured loading pynvml. Original error: Uninitialized
No GPU detected. Switching to CPU mode
12/21/2020 17:34:13 INFO     Log level set to: INFO
12/21/2020 17:34:28 INFO     Updating config at: 'H:\Program Files\faceswap\config\gui.ini'

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by torzdf** [comment]
https://forum.faceswap.dev/viewtopic.php?f=4&t=1191

**Comment by VadVergasov** [comment]
461.09 solves this issue.

**Comment by ESikich** [comment]
> 461.09 solves this issue.

Not the case for GeForce 1050 Ti.

**Comment by torzdf** [comment]
You can downgrade your driver to a pre-460 version. Ultimately this issue is an Nvidia driver issue. They have an open ticket for it, and it will eventually be resolved upstream.

**Comment by ESikich** [comment]
> You can downgrade your driver to a pre-460 version. Ultimately this issue is an Nvidia driver issue. They have an open ticket for it, and it will eventually be resolved upstream.

I completely uninstalled drivers and installed 457.51 but the issue still persists.
I understand this is an NVidia issue, but I think this is worth an update to your Readme.

**Comment by VadVergasov** [comment]
> > 461.09 solves this issue.
> 
> Not the case for GeForce 1050 Ti.

You've tried to reinstall faceswap?

**Comment by ESikich** [comment]
Yes, no luck.

**Comment by torzdf** [comment]
If the issue persists on 457.51 then there is an issue in your setup somewhere.

This error: `An unhandled exception occured loading pynvml. Original error: Uninitialized` is **specific** to the 460 drivers. You may need to [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) your drivers.
