### ISSUE TITLE
Docker install has outdated python 3.6

### ISSUE THREAD

**Issue by greylurk** [deepfakes/faceswap#1104]
## Expected behavior

Adapting the Docker GPU instructions, I was attempting to run the CPU-based faceswap.py in a Docker CPU file using the provided Dockerfile.cpu:

## Actual behavior

The faceswap.py execution failed stating that it required python 3.7, which is not provided by the tensorflow docker image.

## Steps to reproduce

```
$ docker build -t deepfakes-cpu -f Dockerfile.cpu .
$ docker run --rm -it -p 8888:8888 --hostname faceswap-cpu --name faceswap-cpu -v $PWD:/srv deepfakes-cpu

root@faceswap-cpu:/srv# python faceswap.py -h
Setting Faceswap backend to CPU
There was an error reading from the Nvidia Machine Learning Library. Either you do not have an Nvidia GPU (in which case this warning can be ignored) or the most likely cause is incorrectly installed drivers. If this is the case, Please remove and reinstall your Nvidia drivers before reporting.Original Error: NVML Shared Library Not Found
No GPU detected. Switching to CPU mode
Traceback (most recent call last):
  File "faceswap.py", line 11, in <module>
    raise Exception("This program requires at least python3.7")
Exception: This program requires at least python3.7
```

## Other relevant information
- **Operating system and version:** macOS
- **Python version:** 3.6.4
- **Faceswap version:** 5a79a6f5e9f859bbd80d5f403052df82e1c25f1c
- **Faceswap method:** CPU

**Comment by torzdf** [comment]
None of the current Devs use Docker, however a user has kindly raised a PR which hopefully addresses this which is now in the main code.
