### ISSUE TITLE
Cannot train when using AMD GPU

### ISSUE THREAD

**Issue by HHK01** [deepfakes/faceswap#1105]
1. Try to train a model using AMD 
2. Crashs

Should train

**Desktop (please complete the following information):**
 - Wndows 10
 - Python Version : Same as latest installation
 - Conda Version : Same as latest installation 
 - Commit ID : 5a79a6f5e9f859bbd80d5f403052df82e1c25f1c

**Crash Report**
[crash_report.2020.12.27.200432511437.log]
(https://github.com/deepfakes/faceswap/files/5745121/crash_report.2020.12.27.200432511437.log)

**Comment by HilalHk** [comment]
same issue as https://forum.faceswap.dev/viewtopic.php?t=1210

**Comment by emiliodallatorre** [comment]
I have the same problem on my MacBook Pro, currently trying to find a workaround not involving using my CPU as a toaster...

**Comment by emiliodallatorre** [comment]
Did you tried the branch with Tensorflow 2.4? @HilalHk

**Comment by emiliodallatorre** [comment]
> Did you tried the branch with Tensorflow 2.4? @HilalHk 

No luck, I tried.

**Comment by HilalHk** [comment]
try it with faceswap v1 https://newreleases.io/project/github/deepfakes/faceswap/release/v1.0.0

**Comment by emiliodallatorre** [comment]
> try it with faceswap v1 https://newreleases.io/project/github/deepfakes/faceswap/release/v1.0.0

It's not so easy, on a Mac...

**Comment by torzdf** [comment]
Ok, this should be fixed in the latest version.

It seems that AMD backend is no longer compatible with Tensorboard logging above Tensorflow version 2.2.

As this is a dependency regression, it is best that you delete your Faceswap folder + re-run the installer. This should get things working again.

**Comment by emiliodallatorre** [comment]
> Ok, this should be fixed in the latest version.
> 
> It seems that AMD backend is no longer compatible with Tensorboard logging above Tensorflow version 2.2.
> 
> As this is a dependency regression, it is best that you delete your Faceswap folder + re-run the installer. This should get things working again.

I can confirm that, after I removed `tensorflow` from my Conda environment and installed `tensorflow-2.2.0` all is working correctly. Many thanks for the great work @torzdf!
