### ISSUE TITLE
Which file to edit Tkinter tooltips?

### ISSUE THREAD

**Issue by CaptainStabs** [deepfakes/faceswap#1106]
Didn't really fit into either category.
Noticed a few typos (I'm one of those people) and couldn't figure out where the GUI text and tooltips are located.

**Comment by torzdf** [comment]
I welcome cleaning up of the grammar/spelling as  long as it is done in a single PR and not 1 word changes here and there in separate PRs....

The main cli arguments are here:
https://github.com/deepfakes/faceswap/blob/master/lib/cli/args.py

The config items can be found in the plugins folder (search for files called `_config.py`) for each  plugin type, and some plugins also have their own config items (`<plugin_name>_defaults.py`)
