### ISSUE TITLE
question about the correspondence of pair frames from source and target videos

### ISSUE THREAD

**Issue by eternitjl** [deepfakes/faceswap#1113]
Hi, thanks for your great work!
For the Deefakes method in your work，I have a question about the correspondence of pair frames from source and target videos respectively when performing video2video face swaping.

For example, suppose the source video is 10 second length, and the target video is 15 second length. Thus, the number of frames for source and target is different. In this way, to generate the swapped video, how to choose the corresponding pair frames from source and target videos respectively? Specifically, if I want to generate i-th frame of swapped video, which frame should I choose from source and target video, respectively?

Thanks!

**Comment by torzdf** [comment]
The best place for this kind of discussion is our [forum](https://faceswap.dev/forum) or [Discord](https://discord.gg/FC54sYg)
