### ISSUE TITLE
Crash Resport

### ISSUE THREAD

**Issue by OmarMashaal** [deepfakes/faceswap#1115]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

**To Reproduce**
1. Go to Train
2. Click on Train button
3. Scroll down to logs section

File "C:\Users\Omar\faceswap\lib\align\aligned_face.py", line 380, in _convert_centering
out[slices["out"][0], slices["out"][1], :] = image[slices["in"][0], slices["in"][1], :]
ValueError: could not broadcast input array from shape (210,171,3) into shape (210,0,3)

**Expected behavior**
No exception

**Screenshots**
![image](https://user-images.githubusercontent.com/77130981/103959209-37a4d300-51a3-11eb-9237-85f026193e9e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8.5
 - Conda Version 4.9.2

 - 
**Additional context**

**Crash Report**
[crash_report.2021.01.08.111420686448.log](https://github.com/deepfakes/faceswap/files/5784523/crash_report.2021.01.08.111420686448.log)

**Comment by torzdf** [comment]
If there is anyway you can provide your training images + alignment files, I can look into this.

**Comment by isokosan** [comment]
I'm also running into the same issue.
 
I have a small set of files so I could upload the whole image set with the crash report & alignments:

https://drive.google.com/drive/folders/1LDP1LRuEXRyYDH_4CBPjg5ZsdNJZ_a0D?usp=sharing

The alignments files are for the following faces:
20210109_190633_alignments = faceA
VID_20210109_170015_alignments = faceB

Hope this helps!

**Comment by recziat** [comment]
I am not sure why this problem occurs but I seem to have fixed it in my setup by removing some faces from my Set A: When going through the images, I realized that for some input images, the extraction process generated very zoomed-out images, with most of the image area being just black. I assume that the alignment data for those images included very tiny faces, close to 0 in height or width, which caused the error.

**Comment by torzdf** [comment]
This should be fixed in latest commit. Would appreciate confirmation.

**Comment by isokosan** [comment]
How can I check if the latest commit is included in the latest release?

Just updated from the GUI and ran into the same error.
 
 Thanks.

**Comment by torzdf** [comment]
If you go help > Output System Info, one of the earlier lines will tell you what commit you are on.

If the issue persists, then I will need new test data to recreate the error, as it works with the test data I received.
