### ISSUE TITLE
No GPU detected. Switching to CPU mode

### ISSUE THREAD

**Issue by ESikich** [deepfakes/faceswap#1117]
An unhandled exception occured loading pynvml. Original error: Uninitialized
No GPU detected. Switching to CPU mode

1. Double click FaceSwap icon
2. The Python console displays the error

GPU should be detected

 - OS: Windows 10 1909 18363.1256
 - Python Version: 3.7.9
 - Conda: Version 4.9.2
 - Commit ID: Unsure how to find this, installed with the current Windows Installer
 - NVIDIA GeForce GTX 1050 Ti
 - Driver version 27.21.14.6089
 - NVIDIA CUDA Development & Runtime 10.2

**Fixed by modifying MiniCoda3\envs\faceswap\Lib\site-packages\pynvml.py** 

```
def nvmlInit():
    _LoadNvmlLibrary()
    print(nvmlLib)

    #
    # Initialize the library
    #
    fn = _nvmlGetFunctionPointer("nvmlInit_v2")
    ret = fn()
    _nvmlCheckReturn(ret)

    # Atomically update refcount
    global _nvmlLib_refcount
    libLoadLock.acquire()
    _nvmlLib_refcount += 1
    libLoadLock.release()
    return None
```

Change
`    fn = _nvmlGetFunctionPointer("nvmlInit_v2")`
to
`    fn = _nvmlGetFunctionPointer("nvmlInit")`

Not crashing, no report.

**Comment by torzdf** [comment]
Don't do this.

Use working drivers. The latest Nvidia drivers are meant to have fixed this issue, otherwise roll back to a version prior to 460.

Updating system library files is rarely a good idea.

(see here for reference: https://forum.faceswap.dev/viewtopic.php?f=4&t=1191
