### ISSUE TITLE
Wrong mask position in manual edit tool

### ISSUE THREAD

**Issue by ydanila** [deepfakes/faceswap#1119]
After faces extraction masks in manual edit tool always in wrong place.

Extraction made with default setting with only one change for masker (vgg-obstructed).

To reproduce create new project and extract faces from file.

Previously I already used faceswap and masks positions were correct. But with latest version I have such issue. 

![image](https://user-images.githubusercontent.com/1343212/106023538-f041a080-60d7-11eb-9a02-e589905e1fce.png)

gpu_devices:         GPU_0: Advanced Micro Devices, Inc. - gfx902 (experimental)
gpu_devices_active:  GPU_0
gpu_driver:          ['3075.13 (PAL,HSAIL)']
gpu_vram:            GPU_0: 5972MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_conda_version:    conda 4.8.4
py_implementation:   CPython
py_version:          3.8.5
git_commits:         2208eb3 Bugfix: Edge case extracted face sub-cropping error. da5f693 Add python3.8-tk to Dockerfile.gpu and fixed documentation regarding docker launch (#1118). 15bbc95 Update Dockerfile (#1112). 163b8fe sysinfo/setup - Standardize cuda/cudnn checks. f9a5b72 Bugfix - setup.py. Explicitly install cudatoolkit in Conda

**Comment by torzdf** [comment]
The manual tool takes Frames as a source not Faces.

aka: you're using it wrong.
