### ISSUE TITLE
OpenCV Error with anaconda

### ISSUE THREAD

**Issue by shadowfolder** [deepfakes/faceswap#112]
I'm using with anaconda3, opencv is intalled, but im getting error

python3 faceswap.py train -A /home/tuw/Desktop/trump -B /home/tuw/Desktop/cage -m /home/tuw/Desktop/models -p

Model A Directory: /home/tuw/Desktop/trump
Model B Directory: /home/tuw/Desktop/cage
Training data directory: /home/tuw/Desktop/models
Loading data, this may take a while...
Using live preview
Loading Model from Model_Original plugin...
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvWaitKey, file /tmp/build/80754af9/opencv_1512687413662/work/modules/highgui/src/window.cpp, line 682
Traceback (most recent call last):
  File "faceswap.py", line 24, in <module>
    arguments.func(arguments)
  File "/home/tuw/Desktop/faceswap/scripts/train.py", line 21, in process_arguments
    self.process()
  File "/home/tuw/Desktop/faceswap/scripts/train.py", line 102, in process
    key = cv2.waitKey(1000)
cv2.error: /tmp/build/80754af9/opencv_1512687413662/work/modules/highgui/src/window.cpp:682: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvWaitKey

Using TensorFlow backend.
2018-02-03 16:53:31.531327: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
loaded model weights
Loading Trainer from Model_Original plugin...
Starting. Press "Enter" to stop training and save model

**Comment by facepainter** [comment]
It looks like your version of opencv was built without any gui support and is lacking the waitKey function.

How did you install it? Where from?  Do you have previous/other version of OpenCV installed?

To be sure what is the output of...

```
import cv2
print cv2.__version__
```

Whatever the case - you can DL the latest releases and source from here - https://opencv.org/releases.html

**Comment by shadowfolder** [comment]
OpenCV was installed by anaconda, i've removed anaconda and getting another error:
python3 faceswap.py train -A /home/tuw/Desktop/trump -B /home/tuw/Desktop/cage -m /home/tuw/Desktop/models -p
Traceback (most recent call last):
  File "faceswap.py", line 10, in <module>
    from scripts.extract import ExtractTrainingData
  File "/home/tuw/Desktop/faceswap/scripts/extract.py", line 4, in <module>
    from lib.cli import DirectoryProcessor
  File "/home/tuw/Desktop/faceswap/lib/cli.py", line 7, in <module>
    from lib.FaceFilter import FaceFilter
  File "/home/tuw/Desktop/faceswap/lib/FaceFilter.py", line 3, in <module>
    import face_recognition
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/__init__.py", line 7, in <module>
    from .api import load_image_file, face_locations, batch_face_locations, face_landmarks, face_encodings, compare_faces, face_distance
  File "/usr/local/lib/python3.5/dist-packages/face_recognition/api.py", line 4, in <module>
    import dlib
ImportError: libmkl_rt.so: cannot open shared object file: No such file or directory

I've reinstall face_recognition package but this doesn't helped me :cry:

**Comment by gdunstone** [comment]
try reinstalling dlib with pip3

**Comment by Clorr** [comment]
@shadowfolder please open only one issue when you have trouble with your install, you will get feedback from others anyway
