### ISSUE TITLE
crash preview tool

### ISSUE THREAD

**Issue by nanali12** [deepfakes/faceswap#1121]
Loading...
Setting Faceswap backend to AMD
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.
02/08/2021 09:17:09 INFO     Log level set to: INFO
02/08/2021 09:17:09 INFO     Setting up for PlaidML
02/08/2021 09:17:09 INFO     Using GPU(s): ['Advanced Micro Devices, Inc. - Ellesmere (experimental)', 'Advanced Micro Devices, Inc. - Ellesmere (supported)']
02/08/2021 09:17:09 INFO     Successfully set up for PlaidML
02/08/2021 09:17:12 INFO     Input Video: F:\001\A\A.mp4

02/08/2021 09:17:12 INFO     Reading alignments from: 'F:\001\A\A_alignments.fsa'
02/08/2021 09:17:12 INFO     Loading Model from Original plugin...

Using plaidml.keras.backend backend.
02/08/2021 09:17:12 INFO     Using configuration saved in state file
02/08/2021 09:17:13 INFO     Opening device "opencl_amd_ellesmere.0"
02/08/2021 09:17:14 INFO     Loaded model from disk: 'F:\001\M\original.h5'
02/08/2021 09:17:21 INFO     Loading Mask from Box_Blend plugin...
02/08/2021 09:17:21 INFO     Loading Mask from Mask_Blend plugin...
02/08/2021 09:17:21 INFO     Loading Color from Avg_Color plugin...
02/08/2021 09:17:21 INFO     Loading Scaling from Sharpen plugin...
02/08/2021 09:17:24 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\faceswap\lib\cli\launcher.py", line 182, in execute_script
process.process()
File "C:\faceswap\tools\preview\preview.py", line 104, in process
self._build_ui()
File "C:\faceswap\tools\preview\preview.py", line 131, in _build_ui
container.add(self._image_canvas, height=400 * get_config().scaling_factor)
File "C:\Users\KCH\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 4384, in add
self.tk.call((self._w, 'add', child) + self._options(kw))
_tkinter.TclError: unknown option "-height"
02/08/2021 09:17:24 CRITICAL An unexpected crash has occurred. Crash report written to 'C:\faceswap\crash_report.2021.02.08.091721936414.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
Process exited.

[crash_report.2021.02.08.091721936414.log](https://github.com/deepfakes/faceswap/files/5940546/crash_report.2021.02.08.091721936414.log)

**Comment by torzdf** [comment]
Should be fixed in latest commit. Please update.
