### ISSUE TITLE
I apologize in advance but I have no idea where to ask, so I'm opening a post.

### ISSUE THREAD

**Issue by Stifler82** [deepfakes/faceswap#1124]
**Question:** _Does the "Batch Size" value affect the quality of the "Train"? or just about speed?_

**Another question:** _Can you make a Tutorial (but well done, not like the ones I found on Youtube which are explanatory not enough), where you explain all the FaceSwap functions, but above all where you explain how to set it, and the various Performance / Quality "Builds"?_
_(Yes, I know, it also depends on the PC / Laptop / Mac / etc that you are using), but let's say, something for 3 Types of Setup for Computers, something like: "Poor", "Medium", "High - Gaming type" would be a great thing!_

_Thanks in advance for your reply!_

**Comment by bryanlyon** [comment]
We have lots of support at https://forum.faceswap.dev/ including guides, explanations of processes.

The answer to your batch size question is even answered there, at https://forum.faceswap.dev/viewtopic.php?f=6&t=146#:~:text=Batch%20Size
