### ISSUE TITLE
Training Data Location (for wget usage)

### ISSUE THREAD

**Issue by errata0** [deepfakes/faceswap#114]
The URL in the README to download the training data doesn't work with `wget`

I think we'll want to at least put a blurb in here that the `wget`-able URL is [here](https://cdn-06.anonfile.com/p7w3m0d5be/8db87f1e-1517708290/face-swap.zip)

Want me to PR this or does an existing commiter want to handle it?

**Comment by Clorr** [comment]
Feel free to do the modification and a PR
