### ISSUE TITLE
Can I use this to do body swap rather than face?

### ISSUE THREAD

**Issue by ymzlygw** [deepfakes/faceswap#1142]
I mean to just change body part not face. Or just use image1's human body's texture  to cover  image2's human body.
Could you please tell me how to do this?

**Comment by torzdf** [comment]
Faceswap is entirely built to work on faces. You would need to create a pipeline (detect/align/extract) to work on body parts.

**Comment by ymzlygw** [comment]
> Faceswap is entirely built to work on faces. You would need to create a pipeline (detect/align/extract) to work on body parts.

thanks, is there has been any bodyswap lib or opensource can do it?

**Comment by torzdf** [comment]
Not that I know of, I'm afraid (not to say it doesn't exist... it's just not something I have come across)

**Comment by torzdf** [comment]
If you join our Discord though, someone there may have found something.

**Comment by ymzlygw** [comment]
> If you join our Discord though, someone there may have found something.

ok, Thanks!

**Comment by wusaifei** [comment]
@ymzlygw Isn't changing the body and changing the face equivalent? You can put the face of A torso on top of B torso
