### ISSUE TITLE
when support 3060ti？

### ISSUE THREAD

**Issue by soufunlab** [deepfakes/faceswap#1144]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by torzdf** [comment]
Faceswap will run on TF 2.4, which supports 30xx cards, however it involves you setting up the environment yourself and we will not provide direct support for this kind of install.

Ultimately, we are waiting for Anaconda to update their Cuda/cuDNN to support Cuda 11.x cuDNN 8.x when we can update our auto-install scripts. We have no control over this.

You are best off chasing up Anaconda. In the meantime there are some unofficial instructions here: 
https://forum.faceswap.dev/viewtopic.php?f=4&t=1226
