### ISSUE TITLE
bug on require CPU (Mac Big Sur)

### ISSUE THREAD

**Issue by SiNaPsEr0x** [deepfakes/faceswap#1145]
in the end of pip require....

Collecting pynvx==1.0.0
  Using cached pynvx-1.0.0-cp39-cp39-macosx_10_9_x86_64.whl (119 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow<2.5.0,>=2.2.0
ERROR: No matching distribution found for tensorflow<2.5.0,>=2.2.0

resolve?

**Comment by bryanlyon** [comment]
This is not a bug.  Make sure your installing on the right version of python and inside anaconda and it will work.

**Comment by torzdf** [comment]
I'm re-opening this as it *may* be an issue as Anaconda has stopped updating Tensorflow for Mac (last version 2.0.0)

Ultimately, MacOS is a pain as they refuse to play nice with Nvidia and have now gone ARM. It is going to be increasingly difficult to support Macs going forward. You can thank Apple and their entire disregard for ML for that one.

I will investigate, but you may be stuck with sourcing versions yourself and installing manually.

Ultimately, if you are serious about ML then use a better Operating System.

**Comment by SiNaPsEr0x** [comment]
thanks for help... mi mac is intel fortunely

<img width="584" alt="image" src="https://user-images.githubusercontent.com/5438823/113823220-aed80c00-977e-11eb-9850-b117de3d7c4e.png">

**Comment by torzdf** [comment]
You may run into other issues. Our lowest version is 2.2 as we use features which were introduced then (although I cannot remember what they are)

**Comment by BastianZim** [comment]
If this is still relevant, Tensorflow is now available through conda-forge: https://github.com/conda-forge/tensorflow-feedstock

**Comment by torzdf** [comment]
> 
> 
> If this is still relevant, Tensorflow 2.4.1 is now available through conda-forge on intel and arm macs: https://github.com/conda-forge/tensorflow-feedstock

It is to an extent, insofar as we pull Tensorflow from Anaconda channel rather than Conda-Forge.

Generally I try to avoid using Conda-Forge packages as they sometimes cause issues for some users. Whilst installing from Conda-Forge is definitely a workaround for Mac users to get around this issue, as the installer/setup.py does not pull this version in, then it is technically still a bug.

**Comment by BastianZim** [comment]
> Generally I try to avoid using Conda-Forge packages as they sometimes cause issues for some users.

That indeed is the case sometimes but the Tensorflow port is now primarily being done on conda-forge with the Anaconda team being involved there as well, just as an FYI. Additionally, only conda-forge currently compiles for arm macs.

**Comment by torzdf** [comment]
Closing issue as stale
