### ISSUE TITLE
Not an issue - Commercialisation / buying pretrained models / for hire

### ISSUE THREAD

**Issue by johndpope** [deepfakes/faceswap#1146]
there's an app called impressions.app - they probably use this techology on the backend to run inference as well as training. I want to buy pretrained models - or pay someone to build them. Where can I find ? I need an api.

**Comment by bryanlyon** [comment]
Issues here are just for bugs, not for questions like this.  Please see faceswap.dev if you have any other questions.

**Comment by johndpope** [comment]
<img width="1316" alt="Screen Shot 2021-05-14 at 7 50 44 pm" src="https://user-images.githubusercontent.com/289994/118253817-b1e8b980-b4ed-11eb-9e54-494ae3dc63f2.png">

still waiting on a reply.

**Comment by torzdf** [comment]
For some reason your email wasn't delivered (may have gone to spam, but my folder doesn't go back that far).

I have removed the screengrab for privacy reasons (have taken a copy with contact details), but will take a look when I have a second.

**Comment by johndpope** [comment]
We got budget.
If it’s easier to quote daily rates that would be ok.
We’re on aws.
