### ISSUE TITLE
Is faceswap not compatible with RTX 3090?

### ISSUE THREAD

**Issue by karvn** [deepfakes/faceswap#1150]
**Describe the bug**
The newest version of faceswap can't do any job with my machine.
when I extract train or do aliments job, It stucked and no error message print to console.

**To Reproduce**
1. Open faceswap, and do "Extract" job, faceswap stucked 10+ minutes.
2. When faceswap stuck, the console print some messages:
Loading...
Setting Faceswap backend to NVIDIA
05/04/2021 20:08:13 INFO     Log level set to: INFO
05/04/2021 20:08:14 INFO     Output Directory: C:\fw\Aurora\face
05/04/2021 20:08:14 INFO     Loading Detect from S3Fd plugin...
05/04/2021 20:08:14 INFO     Loading Align from Fan plugin...
05/04/2021 20:08:14 INFO     Loading Mask from Components plugin...
05/04/2021 20:08:14 INFO     Loading Mask from Extended plugin...
05/04/2021 20:08:14 INFO     Starting, this may take a while...
05/04/2021 20:08:14 INFO     Initializing S3FD (Detect)...

**Expected behavior**
Expected faceswap do it's work normally "extract" "train" "convert" "aliments job".

**Desktop (please complete the following information):**
Destop information is attach to attachment, it's a window10 information.
But ubuntu20 has the same problem.

[osinfo.log](https://github.com/deepfakes/faceswap/files/6420976/osinfo.log)

**Comment by torzdf** [comment]
https://forum.faceswap.dev/viewtopic.php?f=4&t=1226
