### ISSUE TITLE
gpu is not used

### ISSUE THREAD

**Issue by zhichao123** [deepfakes/faceswap#1151]
gpu is not used, but in gui,it say:
`Setting Faceswap backend to NVIDIA
05/13/2021 10:52:10 INFO     Log level set to: INFO
05/13/2021 10:52:11 INFO     Model A Directory: 'D:\data\yuhewei\new' (393 images)
05/13/2021 10:52:11 INFO     Model B Directory: 'D:\data\zhangtianai\new' (481 images)
05/13/2021 10:52:11 INFO     Training data directory: D:\data\modle
05/13/2021 10:52:11 INFO     ===================================================
05/13/2021 10:52:11 INFO       Starting
05/13/2021 10:52:11 INFO       Press 'Stop' to save and quit
05/13/2021 10:52:11 INFO     ===================================================
05/13/2021 10:52:12 INFO     Loading data, this may take a while...
05/13/2021 10:52:12 INFO     Loading Model from Original plugin...
05/13/2021 10:52:13 INFO     No existing state file found. Generating.
05/13/2021 10:52:13 INFO     Loading Trainer from Original plugin...

05/13/2021 10:52:28 INFO     [Saved models] - Average loss since last save: face_a: 0.46489, face_b: 0.46390
`
I say it in form,but you say its normal in windows,  the picture of the abnormality has the fnal say, or its a bug?
![QQ截图20210513111452](https://user-images.githubusercontent.com/25994340/118072480-7611ff00-b3dc-11eb-9354-4b0fa307ba5a.jpg)

![QQ截图20210513111329](https://user-images.githubusercontent.com/25994340/118072426-5a0e5d80-b3dc-11eb-9dde-f2310fb431c9.jpg)
![QQ截图20210513111345](https://user-images.githubusercontent.com/25994340/118072431-5b3f8a80-b3dc-11eb-8861-d68b1dce358c.jpg)
![QQ截图20210513111355](https://user-images.githubusercontent.com/25994340/118072433-5bd82100-b3dc-11eb-9b07-8f8276eecdbe.jpg)

**Comment by bryanlyon** [comment]
Issues here are just for bugs.  If you have problems like this you can go to https://forum.faceswap.dev/ particularly start with the FAQ page at https://forum.faceswap.dev/app.php/faqpage especially The Q/A at https://forum.faceswap.dev/app.php/faqpage#f1r1 which solves most problems.
