### ISSUE TITLE
训练过程中抛出异常。自动尝试重新训练

### ISSUE THREAD

**Issue by 943332358** [deepfakes/faceswap#1158]
Sorry, I don't know much English

在 训练 过程中，因为电脑配置差的原因。每隔一段时间程序就会抛出异常。需要手动重新点击 训练  来继续训练。
能否捕获这个常见的异常，然后尝试自动重新训练

**Comment by torzdf** [comment]
`Translated original message:`

> **An exception was thrown during training. Automatically try to retrain**
>During the training process, because of the poor computer configuration. Every once in a while, the program will throw an exception. You need to manually re-click Training to continue training.
Can you catch this common anomaly and try to retrain automatically 



We would need to know the specifics of the error. Either way, this is something we are unlikely to implement as everyone's setup is very different and it is impossible to cover for all eventualities

`Translated response:`
>我们需要知道错误的细节。 无论哪种方式，这是我们不太可能实施的，因为每个人的设置都非常不同，并且不可能涵盖所有可能发生的情况
