### ISSUE TITLE
Legacy face centering is not working correctly

### ISSUE THREAD

**Issue by dmiszkiewicz** [deepfakes/faceswap#1163]
Legacy face centering is not working correctly. I'm uploading a preview image for face and legacy centering to compare. 
![legacy](https://user-images.githubusercontent.com/4159022/122555378-813ef700-d03a-11eb-934b-f37a0759c5a4.jpg)
![face](https://user-images.githubusercontent.com/4159022/122555385-83a15100-d03a-11eb-9374-d84a1014f068.jpg)

**Comment by torzdf** [comment]
I believe that this is just a preview window rendering error rather than a bug with the mask. Will look when I get a chance.

**Comment by torzdf** [comment]
I believe this bug was finally fixed with #1263
