### ISSUE TITLE
Trying to get in touch with you regarding a security issue

### ISSUE THREAD

**Issue by huntr-helper** [deepfakes/faceswap#1168]
Hi there,

I couldn't find a `SECURITY.md` in your repository and so am not sure how to best contact you privately to disclose the security issue.

Can you add a `SECURITY.md` file with your e-mail to your repository, so that I know who to contact? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, please let me know so I can ping you the info.

Thanks! (cc @JamieSlome)

**Comment by Alvinchongry** [comment]
Readme

**Comment by torzdf** [comment]
torzdf at google's email service.

**Comment by Chongruiyuan893** [comment]
- [x] - **_[]()_**![image](https://user-images.githubusercontent.com/83970553/123876932-d0f0bd00-d96e-11eb-9aea-915cbd7bbe74.jpeg)@

**Comment by torzdf** [comment]
@JamieSlone @huntr-helper Why do you think it is reasonable to spam Open Source developers with arbitrary messages demanding the adding of a SECURITY.md file. Do you not think developers give up enough time without having to deal with crap like this?

https://githubmemory.com/@huntr-helper

Consider yourself reported.

**Comment by JamieSlome** [comment]
Hello @torzdf - thanks for the feedback. I apologise if the notification came over as spammy - we will definitely take this into consideration and can re-assure that we are constantly iterating on our outreach.

We do still have a security vulnerability report for you - do you have some preferred e-mail or place I can send this to you?

**Comment by bryanlyon** [comment]
contact at faceswap.dev

**Comment by bryanlyon** [comment]
And further, quit spamming repos like this.  We know you've been told to stop.  We've even told you the last time you spammed us.  Do not do this again.

**Comment by JamieSlome** [comment]
@bryanlyon - apologies that a further issue was opened here. This was not by intention, I will investigate what went wrong here.
