### ISSUE TITLE
Realtime solution?

### ISSUE THREAD

**Issue by fortminors** [deepfakes/faceswap#1172]
**Is your feature request related to a problem? Please describe.**
Is there a way to do a faceswap in realtime? Or do I need to go through the whole training process for every pair of people?

**Describe the solution you'd like**
Realtime face swapping

**Describe alternatives you've considered**

**Additional context**

**Comment by bryanlyon** [comment]
We have no plans to add realtime swapping in Faceswap itself.  It simply isn't a part of our goals.

Please see https://github.com/alew3/faceit_live for a project that used faceswap to do realish time swaps.
