### ISSUE TITLE
How to change the Number of GPU?

### ISSUE THREAD

**Issue by dimuthuanuraj** [deepfakes/faceswap#1174]
I have started with two T4 GPUs, But If I need to specifically say to use only one GPU instead of both, How I can modify the program?

Thank you for taking the time to review this question.

**Comment by dimuthuanuraj** [comment]
I have tried that by changing **_gpu_stat.py_** , which is inside the lib. I modified it as **__EXCLUDE_DEVICES = [0]_**.
(I wanted to exclude 0 GPU) But it did not work, Do I need to modify it anywhere else?

@wangyifan349

**Comment by bryanlyon** [comment]
You don't need to modify any code at all.  FS includes the ability to limit the GPUs in use.

Please see: https://forum.faceswap.dev/viewtopic.php?f=6&t=146#:~:text=not%20just%20training.-,Exclude%20GPUs
