### ISSUE TITLE
IF  faceswap  use  CPU。。。。。

### ISSUE THREAD

**Issue by wangyifan349** [deepfakes/faceswap#1176]
C:\Users\Administrator\faceswap\lib\gui\display_graph.py:179: RuntimeWarning: All-NaN slice encountered
  ymin.append(np.nanmin(item) * 1000)
C:\Users\Administrator\faceswap\lib\gui\display_graph.py:180: RuntimeWarning: All-NaN slice encountered
  ymax.append(np.nanmax(item) * 1000)
C:\Users\Administrator\faceswap\lib\gui\display_graph.py:179: RuntimeWarning: All-NaN slice encountered
  ymin.append(np.nanmin(item) * 1000)
C:\Users\Administrator\faceswap\lib\gui\display_graph.py:180: RuntimeWarning: All-NaN slice encountered
  ymax.append(np.nanmax(item) * 1000)
08/02/2021 18:54:17 WARNING  No data to graph for selected session
C:\Users\Administrator\faceswap\lib\gui\display_graph.py:179: RuntimeWarning: All-NaN slice encountered
  ymin.append(np.nanmin(item) * 1000)
C:\Users\Administrator\faceswap\lib\gui\display_graph.py:180: RuntimeWarning: All-NaN slice encountered
  ymax.append(np.nanmax(item) * 1000)

**Comment by bryanlyon** [comment]
This doesn't give us any of the required information to troubleshoot.

If you're having problems, probably best to post a thorough explanation of your problem in the forums at https://forum.faceswap.dev/
