### ISSUE TITLE
crash trying to load video

### ISSUE THREAD

**Issue by kirill77** [deepfakes/faceswap#1177]
This is on Windows. Repro steps:

- sync this github repo;
- install anaconda 3;
- execute: C:\Users\<username>\anaconda3\Scripts\activate.bat && python "setup.py"
- execute: C:\Users\<username>\anaconda3\Scripts\activate.bat && python "faceswap.py" gui
- set the settings as in attached project;
[TrumpProject.txt](https://github.com/deepfakes/faceswap/files/7026019/TrumpProject.txt)
- click 'Extract';

The video comes from youtube - I saved some Trump interview using VLC media player.

Also - perhaps unrelated - it takes huge time (perhaps an hour) for this thing to start doing anything at all. It sits for a long time on this line:

2021-08-21 10:33:04.194188: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0

and I believe later on on some other step. IMHO your program is not very mature guys

*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*
[crash_report.2021.08.21.105644558905.log](https://github.com/deepfakes/faceswap/files/7026010/crash_report.2021.08.21.105644558905.log)

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python Version [e.g. 3.5, 3.6]
 - Conda Version [e.g. 4.5.12]
 - Commit ID [e.g. e83819f]
 - 
**Additional context**

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by torzdf** [comment]
> Crash reports MUST be included when reporting bugs.

**Comment by torzdf** [comment]
See here: https://forum.faceswap.dev/viewtopic.php?f=4&t=1226
This is a false positive down to your GPU/Cuda combination.
