### ISSUE TITLE
The computer monitor suddenly lost no signal when running extraction with Nvidia GPU on win10

### ISSUE THREAD

**Issue by whonor** [deepfakes/faceswap#1178]
When extraction is running, the monitor suddenly lost no signal. I am sure that my monitor and GPU are good to run other deep learning programs.  
I restart my computer to solve this problem. However, this problem appears again when running faceswap. So I think this is a bug while no logs record this problem.

============ System Information ============
encoding:            cp936
git_branch:          master
git_commits:         7e7640e Bugfix: Convert - Fix predicted mask
gpu_cuda:            11.0
gpu_cudnn:           8.0.2
gpu_devices:         GPU_0: GeForce RTX 2060 SUPER
gpu_devices_active:  GPU_0
gpu_driver:          456.71
gpu_vram:            GPU_0: 8192MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          E:\faceswap/faceswap.py gui
py_conda_version:    conda 4.10.3
py_implementation:   CPython
py_version:          3.8.11
py_virtual_env:      True
sys_cores:           12

**Comment by torzdf** [comment]
It's only a bug if it's reproducible by others. This is not. You are welcome to join our forum or discord to discuss ways that you may be able to mitigate this situation.
