### ISSUE TITLE
Add image padding option

### ISSUE THREAD

**Issue by wiso** [deepfakes/faceswap#1181]
**Is your feature request related to a problem? Please describe.**
I would like to use the extract tool to create a dataset to be used for GAN. In particular I would like the faces to have more background.

**Describe the solution you'd like**
Add a --padding option to the cli. It should not be very difficult since I see that internal classes already support for it, but I am not sure how this can be propagated to the cli.

**Comment by torzdf** [comment]
The extract process has been created specifically for use to train models in Faceswap. Whilst I can see benefit for users to use it for other applications, it is certainly not a priority for our project, and adding customizable padding would actually mean adjusting many parts of our code to know what padding that the user selected, whilst bringing no benefit to our project. Sadly I will not be implementing this, but thanks for your feedback.
