### ISSUE TITLE
GPU instantly maxes out VRAM and crashes on tesla M40s regardless of batch side or trainer

### ISSUE THREAD

**Issue by kwibjo** [deepfakes/faceswap#1183]
**Describe the bug:**
GPU instantly maxes out VRAM and crashes on tesla M40 regardless of batch side or trainer.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS Server
 - Python Version: Python 3.8.11
 - Conda Version: conda 4.10.3 (Miniconda)
 - Commit ID: c7d85f89e69c74e97bf7485b064c07487d31faae

**Additional context:**
I have 2 M40 GPUs. Originally I thought it was an issue with distributed training but after running `python faceswap.py train` without `--distributed`, batch side set to 1 and using the default trainer the program still instantly maxxed out the card's VRAM and crashed.

**Crash Report:**
[crash_report.2021.09.05.021629406000.log](https://github.com/deepfakes/faceswap/files/7110803/crash_report.2021.09.05.021629406000.log)
[crash_report.2021.09.05.021838145257.log](https://github.com/deepfakes/faceswap/files/7110804/crash_report.2021.09.05.021838145257.log)
[crash_report.2021.09.05.021955307400.log](https://github.com/deepfakes/faceswap/files/7110805/crash_report.2021.09.05.021955307400.log)
[crash_report.2021.09.05.022020998171.log](https://github.com/deepfakes/faceswap/files/7110806/crash_report.2021.09.05.022020998171.log)

**Comment by torzdf** [comment]
```numpy==1.21.2```
Not compatible with Tensorflow. Downgrade to a version **below** 1.20.
