### ISSUE TITLE
How can i use this project for swaping faces between two images.

### ISSUE THREAD

**Issue by alan-ai-learner** [deepfakes/faceswap#1190]
I want to paste the face of a person from first image to another image. And the person clothes will be same.

**Comment by bryanlyon** [comment]
Faceswap does not work with individual images.  See the FAQ item at https://forum.faceswap.dev/app.php/faqpage#f0r6

Also note that the issues tab is only for code bugs.  For any information or help on running Faceswap please post in the forum or visit our Discord.
