### ISSUE TITLE
Options for the IAE model

### ISSUE THREAD

**Issue by ccoltman** [deepfakes/faceswap#1192]
**Is your feature request related to a problem? Please describe.**
There are no settings for the IAE model

**Describe the solution you'd like**
Options for the IAE model

**Describe alternatives you've considered**
So far just the global training options.

**Additional context**
The model seems to train very quickly (~160EGs/s), and I'm wondering if there are any options to tune in order to end up with a better model at the expense of some of that speed.

**Comment by torzdf** [comment]
The Phaze-A model will do exactly what you want. It already has an IAE preset, so you can load that and tweak from there:

https://forum.faceswap.dev/viewtopic.php?p=5367#p5367
