### ISSUE TITLE
Confusion about loss functions.

### ISSUE THREAD

**Issue by 102300440** [deepfakes/faceswap#1194]
I have some confusion about the  `_set_loss_functions`  in  `plugins/train/model/_base.py`.  The line 1282 of  `plugins/train/model/_base.py` shows that `self._add_l2_regularization_term(loss_func, mask_channel)`. However, in my view, it constrains the l2 loss on the eye and mouth mask channels, which is similar to line 1274 on the face mask. Hence I think it should be corrected to `self._add_l2_regularization_term(loss_func, mask_channels[mask_channel])` . So, is there a mistake here, or just did I misunderstand it?

**Comment by torzdf** [comment]
It's been a *long* time since I wrote that code, but on the face of it, I think you may be correct. I will need to do some testing to make sure though. Thanks for the heads up.

**Comment by torzdf** [comment]
fixed in commit https://github.com/deepfakes/faceswap/commit/3852b2b2d1e19cd2f0d72d111e9d6733bbf5ae26
