### ISSUE TITLE
add the function of selecting multiple faces in the UI of manual

### ISSUE THREAD

**Issue by leeso2021** [deepfakes/faceswap#1198]
the gui is wonderful, but i cant choose multiple faces that i want to delete, 
i have to delete them one by one..
so , is it possbile to add the function so we can quickly choose lots of faces that we want to delete

**Comment by bryanlyon** [comment]
The issues page is for code bugs.  For anything else such as this request, please visit our forums at http://forum.faceswap.dev/

That said, you can delete them en-mass using your file manager.  The manual tool is meant for minor tweaks, batch solutions are done better in other ways.  See the Guides in the forum for advice on the best way to do things.
