### ISSUE TITLE
installer does not work with fresh python 3.9.x

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [deepfakes/faceswap#1201]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

installer does not work with fresh python 3.9.x

**To Reproduce**
1) install presh python
2) start ./faceswap_setup_x64.sh
3) answer questions 
4) See result

**Expected behavior**
installation must pass 

**Screenshots**

```
INFO    Setting up Faceswap...
INFO    Running without root/admin privileges
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Linux 5.10.84-1-MANJARO
INFO    Installed Python: 3.9.9 64bit
ERROR   Please run this script with Python version 3.7 or 3.8 64bit and try again.
INFO    Faceswap installation is complete!
INFO    You can launch Faceswap from the icon on your desktop
```

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version 3.9.9
 - Conda Version : even not reached
 - Commit ID : latest release
 - 
**Additional context**

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by torzdf** [comment]
This isn't a bug. It explicitly says in the report you pasted:
```
ERROR   Please run this script with Python version 3.7 or 3.8 64bit and try again.
```

FS has not been tested in higher versions of Python.
