### ISSUE TITLE
After I install XQuartz, it can't detected screen on Mac Big Sur yet.

### ISSUE THREAD

**Issue by YoTro** [deepfakes/faceswap#1205]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

## Describe the bug
Firstly, I run `python faceswap.py gui` on Mac but it shows 

> _**No display detected. GUI mode has been disabled.**_ 
> _**macOS users need to install XQuartz.**_ 

Then I installed XQuartz-2.7.7.dmg, it still shown it couldn't detected the screen
## Desktop (please complete the following information):
 - OS: MacBook Pro Big Sur 11.1 
 - Python Version: 3.7
 - Conda Version: 4.10.1
 - Commit ID: 183aee3

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by torzdf** [comment]
I'm closing this issue as stale, and because this is more of an Apple/XQuartz issue than a Faceswap issue.
