### ISSUE TITLE
Convert invokes FFmpeg with redundant & conflicting arguments

### ISSUE THREAD

**Issue by HG4554** [deepfakes/faceswap#1206]
**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
FaceSwap convert invokes FFmpeg on the writer side with 2 sets of conflicting output codec options. The first set is generated by write_frames in imageio-ffmpeg, the second by output_params in convert's ffmpeg module. 

/mnt/data/homedir/miniconda3/envs/faceswap/bin/ffmpeg -y -f rawvideo -vcodec rawvideo -s 3840x2160 -pix_fmt rgb24 -r 29.97 -i - -an **-vcodec libx264 -pix_fmt yuv420p -crf 25** -v error -vf scale=3840:2160 **-c:v libx264 -crf 23 -preset medium** /mnt/data/workspace/18/output.mp4

https://github.com/deepfakes/faceswap/blob/183aee37e93708c0ae73845face5b4469319ebd3/plugins/convert/writer/ffmpeg.py#L95

**To Reproduce**
1. Run a convert
2. Inspect ffmpeg arguments with `ps aux | grep ffmpeg`

**Expected behavior**
FFmpeg invocation should not have redundant/conflicting arguments. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: CentOS 8
 - Python Version 3.6.8
 - Conda Version [e.g. 4.5.12]
 - Commit ID 09c7d8aca3c608d1afad941ea78e9fd9b64d9219

**Comment by torzdf** [comment]
Good catch. This bug has been fixed. Thanks.
