### ISSUE TITLE
[Question] Which part of code to implement 'Configure Settings' GUI?

### ISSUE THREAD

**Issue by water5** [deepfakes/faceswap#1208]
Which part of code to implement 'Configure Settings' GUI?

![a](https://user-images.githubusercontent.com/32773605/152643917-b26f4b16-71e0-4f9a-8209-93206355f1b6.jpg)

**Comment by torzdf** [comment]
Can you be a bit more specific about what you're trying to achieve?

**Comment by water5** [comment]
I want to understanding the parameter how to pass from GUI.

**Comment by bryanlyon** [comment]
You're still being very unclear, but here is my best guess as to your question: You want to add a new config option and have it show up in the GUI.

The GUI is generated from config and CLI.  There is no need to specifically modify the GUI to add new functionality.  If you add it to the config or CLI it gets automatically added to the GUI.  Here is a link to what generates the options displayed in your screenshot: https://github.com/deepfakes/faceswap/blob/c900036a4ecbb77ee4ef7e0fa12abe77d117a5b0/plugins/extract/align/fan_defaults.py

If this isn't your question, please describe exactly what you're trying to accomplish and maybe we can understand your needs.

**Comment by water5** [comment]
If I want to modify parameter value range, or add some customized parameter to 'Configure Settings' GUI, where is the code is? (specific `tkinter` code (I guess, or `wxpython` or other GUI?))
