### ISSUE TITLE
The last step when installing faceswap---The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by lahongsang** [deepfakes/faceswap#1217]
The last step when installing faceswap:
a little bug come out as blowing:
```
INFO    All python3 dependencies are met.
        You are good to go.
        
        Enter:  'python faceswap.py -h' to see the options
                'python faceswap.py gui' to launch the GUI
The syntax of the command is incorrect.
Error Setting up Faceswap
Install Aborted
```

**Comment by yaamas** [comment]
@lahongsang what is the command you are running ?

**Comment by lahongsang** [comment]
NO command，the issue occurs when I installing the faceswap in window-64 platform.


it confused me.



---Original---
From: "Yahyaa ***@***.***&gt;
Date: Mon, May 9, 2022 03:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [deepfakes/faceswap] The last step when installing faceswap---Thesyntax of the command is incorrect. (Issue #1217)




 
@lahongsang what is the command you are running ?

**Comment by torzdf** [comment]
Which OS? How were you installing Faceswap (installer/setup.py etc.)

**Comment by lahongsang** [comment]
"""
Windows 10 Pro, 64-bit
DirectX  12
GPU NVIDIA GeForce GTX 1050 Ti
NVIDA 512.59
DCH
CUDA 768
8.17.15.1259		NVIDIA User Experience Driver Component
NVIDIA CUDA 11.6.134 driver
"""
This is my computer information, I had solved the issue by manual installation.
The issue occures in ../lib/gpu_stats.py (Line273 and Line 298).
I delete the parameter .decode("utf-8")

**Comment by torzdf** [comment]
Ok, not sure why that would happen... I did a test install under Windows and did not hit this issue. There was a problem with a version of nvidia-ml-py which caused the above issue, but that version was pulled:
https://pypi.org/project/nvidia-ml-py/#history
