### ISSUE TITLE
Need a license file...

### ISSUE THREAD

**Issue by fat-tire** [deepfakes/faceswap#122]
Is there a COPYING or LICENSE type of file for this?  I didn't really follow the original reddit post but is this GPL?  Apache?  Something else?

**Comment by gdunstone** [comment]
https://github.com/deepfakes/faceswap/issues/65

**Comment by Clorr** [comment]
Feel free to add a license file, stating the current situation if you have some idea about it

**Comment by fat-tire** [comment]
How can I add a license for someone else's code?  The license needs to come from the original author.  If they didn't choose one already, they can use [this](https://choosealicense.com/) to pick one.

Please either reopen this issue until the license is determined or add the correct license specified by the author... thanks much!

**Comment by gdunstone** [comment]
I'll reopen https://github.com/deepfakes/faceswap/issues/65

I think Clorr meant to add a license file describing the he current status of the licensing (that the original author hasn't provided a licence)
