### ISSUE TITLE
run python faceswap.py gui with an error on mac m1

### ISSUE THREAD

**Issue by AIfakes** [deepfakes/faceswap#1222]
Setting Faceswap backend to APPLE_SILICON
Traceback (most recent call last):
  File "faceswap.py", line 6, in <module>
    from lib.cli import args as cli_args
  File "/Users/qz/flab/faceswap/lib/cli/args.py", line 13, in <module>
    from lib.gpu_stats import GPUStats
  File "/Users/qz/flab/faceswap/lib/gpu_stats/__init__.py", line 20, in <module>
    from .apple_silicon import AppleSiliconStats as GPUStats  # noqa
  File "/Users/qz/flab/faceswap/lib/gpu_stats/apple_silicon.py", line 6, in <module>
    import psutil
  File "/Users/qz/miniforge3/envs/faceswap/lib/python3.8/site-packages/psutil/__init__.py", line 123, in <module>
    from . import _psosx as _psplatform
  File "/Users/qz/miniforge3/envs/faceswap/lib/python3.8/site-packages/psutil/_psosx.py", line 14, in <module>
    from . import _psutil_osx as cext
ImportError: dlopen(/Users/qz/miniforge3/envs/faceswap/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so, 0x0002): tried: '/Users/qz/miniforge3/envs/faceswap/lib/python3.8/site-packages/psutil/_psutil_osx.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))

mac os: 12.4 (21F79)
python version: 3.8.13
pip list 

```
Package                 Version
----------------------- -----------
absl-py                 1.0.0
astunparse              1.6.3
cached-property         1.5.2
cachetools              5.1.0
certifi                 2022.5.18.1
charset-normalizer      2.0.12
cycler                  0.11.0
fastcluster             1.2.6
ffmpy                   0.2.3
flatbuffers             1.12
fonttools               4.33.3
gast                    0.4.0
google-auth             2.6.6
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.46.3
h5py                    3.6.0
idna                    3.3
imageio                 2.19.2
imageio-ffmpeg          0.4.7
importlib-metadata      4.11.4
joblib                  1.1.0
keras                   2.9.0
Keras-Preprocessing     1.1.2
kiwisolver              1.4.2
libclang                14.0.1
Markdown                3.3.7
matplotlib              3.5.2
numpy                   1.22.4
oauthlib                3.2.0
opencv-python           4.5.5.64
opt-einsum              3.3.0
packaging               21.3
Pillow                  9.1.1
pip                     22.1.1
protobuf                3.20.1
psutil                  5.9.1
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pyparsing               3.0.9
python-dateutil         2.8.2
requests                2.27.1
requests-oauthlib       1.3.1
rsa                     4.8
scikit-learn            1.1.1
scipy                   1.8.1
setuptools              62.3.2
six                     1.15.0
tensorboard             2.9.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow-estimator    2.9.0
tensorflow-macos        2.9.0
tensorflow-metal        0.5.0
termcolor               1.1.0
threadpoolctl           3.1.0
tqdm                    4.64.0
typing_extensions       4.2.0
urllib3                 1.26.9
Werkzeug                2.1.2
wheel                   0.37.1
wrapt                   1.14.1
zipp                    3.8.0
```

**Comment by torzdf** [comment]
I'm not a MacOS expert by any means, but this:
```
but is an incompatible architecture (have 'x86_64', need 'arm64e'))
```
suggests to me that you are trying to run the M1 version of the software on an Intel Mac,

**Comment by AIfakes** [comment]
But my Mac is m1，why this

**Comment by torzdf** [comment]
In which case, I'm not sure. Tagging @geewiz94 @daniellivingston who did most of the work on M1 port in case they have any ideas.

**Comment by daniellivingston** [comment]
> @geewiz94 @daniellivingston please help me

You have installed a package (psutil) with the wrong architecture (x86 [Intel/AMD] instead of aarch64 [Apple Silicon/ARM]).

Easiest solution: use this to bootstrap your Python ARM environment: https://github.com/alexfromapex/tensorexperiments

**Comment by AIfakes** [comment]
Sorry, I still didn't succeed，i think it may be the problem of this library [psutil](https://github.com/giampaolo/psutil/issues/2016)

**Comment by torzdf** [comment]
Apple Silicon setup has now been rolled into the standard Faceswap install path (see here: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#macos-apple-silicon-install-guide)

Hopefully this solves your issue. If not, please open a new issue.
