### ISSUE TITLE
Multi GPU crash

### ISSUE THREAD

**Issue by Curisan** [deepfakes/faceswap#1224]
**Describe the bug**
When train the model, use one gpu is OK, but when I use multi gpu, crash occured.

**To Reproduce**
1. prepare dataset and extract face: done
2. python faceswap.py train -A exps/elon2iron/faces/elon/ -B exps/elon2iron/faces/iron/ -m exps/elon2iron/model/ -C config/train.elon2iron.ini -d

**Expected behavior**
Can run when use multi gpu

**Screenshots**
(faceswap) [yezj@gpu_71 faceswap]$ python faceswap.py train -A exps/elon2iron/faces/elon/ -B exps/elon2iron/faces/iron/ -m exps/elon2iron/model/ -C config/train.elon2iron.ini -d
Setting Faceswap backend to NVIDIA
05/26/2022 17:44:13 INFO     Log level set to: INFO
05/26/2022 17:44:18 INFO     Model A Directory: '/data/home/yezj/gitlab/faceswap/exps/elon2iron/faces/elon' (442 images)
05/26/2022 17:44:18 INFO     Model B Directory: '/data/home/yezj/gitlab/faceswap/exps/elon2iron/faces/iron' (310 images)
05/26/2022 17:44:18 INFO     Training data directory: /data/home/yezj/gitlab/faceswap/exps/elon2iron/model
05/26/2022 17:44:18 INFO     ===================================================
05/26/2022 17:44:18 INFO       Starting
05/26/2022 17:44:18 INFO       Press 'ENTER' to save and quit
05/26/2022 17:44:18 INFO       Press 'S' to save model weights immediately
05/26/2022 17:44:18 INFO     ===================================================
05/26/2022 17:44:19 INFO     Loading data, this may take a while...
05/26/2022 17:44:19 INFO     Loading Model from Original plugin...
05/26/2022 17:44:20 INFO     Using configuration saved in state file
05/26/2022 17:44:22 INFO     Setting allow growth for GPU: PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
05/26/2022 17:44:22 INFO     Setting allow growth for GPU: PhysicalDevice(name='/physical_device:GPU:1', device_type='GPU')
05/26/2022 17:44:22 INFO     Setting allow growth for GPU: PhysicalDevice(name='/physical_device:GPU:2', device_type='GPU')
05/26/2022 17:44:22 INFO     Setting allow growth for GPU: PhysicalDevice(name='/physical_device:GPU:3', device_type='GPU')
05/26/2022 17:44:25 INFO     Using MirroredStrategy with devices ('/job:localhost/replica:0/task:0/device:GPU:0', '/job:localhost/replica:0/task:0/device:GPU:1', '/job:localhost/replica:0/task:0/device:GPU:2', '/job:localhost/replica:0/task:0/device:GPU:3')
05/26/2022 17:44:27 INFO     Loaded model from disk: '/data/home/yezj/gitlab/faceswap/exps/elon2iron/model/original.h5'
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Reduce to /job:localhost/replica:0/task:0/device:CPU:0 then broadcast to ('/job:localhost/replica:0/task:0/device:CPU:0',).
05/26/2022 17:44:27 INFO     Loading Trainer from Original plugin...
05/26/2022 17:44:31 INFO     Error reported to Coordinator: in user code:\n\n    File "/data/home/yezj/gitlab/faceswap/lib/model/losses_tf.py", line 531, in call  *\n        loss += (func(n_true, n_pred) * weight)\n    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/losses.py", line 143, in __call__  **\n        losses, sample_weight, reduction=self._get_reduction())\n    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/losses.py", line 183, in _get_reduction\n        raise ValueError(\n\n    ValueError: Please use `tf.keras.losses.Reduction.SUM` or `tf.keras.losses.Reduction.NONE` for loss reduction when losses are used with `tf.distribute.Strategy` outside of the built-in training loops. You can implement `tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE` using global batch size like:\n    ```\n    with strategy.scope():\n        loss_obj = tf.keras.losses.CategoricalCrossentropy(reduction=tf.keras.losses.Reduction.NONE)\n    ....\n        loss = tf.reduce_sum(loss_obj(labels, predictions)) * (1. / global_batch_size)\n    ```\n    Please see https://www.tensorflow.org/tutorials/distribute/custom_training for more details.\n
Traceback (most recent call last):
  File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/training/coordinator.py", line 293, in stop_on_exception
    yield
  File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/distribute/mirrored_run.py", line 342, in run
    self.main_result = self.main_fn(*self.main_args, **self.main_kwargs)
  File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py", line 692, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/data/home/yezj/gitlab/faceswap/lib/model/losses_tf.py", line 531, in call  *
        loss += (func(n_true, n_pred) * weight)
    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/losses.py", line 143, in __call__  **
        losses, sample_weight, reduction=self._get_reduction())
    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/losses.py", line 183, in _get_reduction
        raise ValueError(

    ValueError: Please use `tf.keras.losses.Reduction.SUM` or `tf.keras.losses.Reduction.NONE` for loss reduction when losses are used with `tf.distribute.Strategy` outside of the built-in training loops. You can implement `tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE` using global batch size like:
    ```
    with strategy.scope():
        loss_obj = tf.keras.losses.CategoricalCrossentropy(reduction=tf.keras.losses.Reduction.NONE)
    ....
        loss = tf.reduce_sum(loss_obj(labels, predictions)) * (1. / global_batch_size)
    ```
    Please see https://www.tensorflow.org/tutorials/distribute/custom_training for more details.

05/26/2022 17:44:32 CRITICAL Error caught! Exiting...
05/26/2022 17:44:32 ERROR    Caught exception in thread: '_training_0'
05/26/2022 17:44:35 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/data/home/yezj/gitlab/faceswap/lib/cli/launcher.py", line 182, in execute_script
    process.process()
  File "/data/home/yezj/gitlab/faceswap/scripts/train.py", line 190, in process
    self._end_thread(thread, err)
  File "/data/home/yezj/gitlab/faceswap/scripts/train.py", line 230, in _end_thread
    thread.join()
  File "/data/home/yezj/gitlab/faceswap/lib/multithreading.py", line 121, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/data/home/yezj/gitlab/faceswap/lib/multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "/data/home/yezj/gitlab/faceswap/scripts/train.py", line 252, in _training
    raise err
  File "/data/home/yezj/gitlab/faceswap/scripts/train.py", line 242, in _training
    self._run_training_cycle(model, trainer)
  File "/data/home/yezj/gitlab/faceswap/scripts/train.py", line 327, in _run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/data/home/yezj/gitlab/faceswap/plugins/train/trainer/_base.py", line 194, in train_one_step
    loss = self._model.model.train_on_batch(model_inputs, y=model_targets)
  File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/engine/training.py", line 2093, in train_on_batch
    logs = self.train_function(iterator)
  File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 1147, in autograph_handler
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/engine/training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "/data/home/yezj/gitlab/faceswap/lib/model/losses_tf.py", line 531, in call  *
        loss += (func(n_true, n_pred) * weight)
    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/losses.py", line 143, in __call__  **
        losses, sample_weight, reduction=self._get_reduction())
    File "/data/home/yezj/miniconda3/envs/faceswap/lib/python3.8/site-packages/keras/losses.py", line 183, in _get_reduction
        raise ValueError(

    ValueError: Please use `tf.keras.losses.Reduction.SUM` or `tf.keras.losses.Reduction.NONE` for loss reduction when losses are used with `tf.distribute.Strategy` outside of the built-in training loops. You can implement `tf.keras.losses.Reduction.SUM_OVER_BATCH_SIZE` using global batch size like:
    ```
    with strategy.scope():
        loss_obj = tf.keras.losses.CategoricalCrossentropy(reduction=tf.keras.losses.Reduction.NONE)
    ....
        loss = tf.reduce_sum(loss_obj(labels, predictions)) * (1. / global_batch_size)
    ```
    Please see https://www.tensorflow.org/tutorials/distribute/custom_training for more details.

**Desktop (please complete the following information):**
 - CentOS Linux release 7.8.2003 (Core)
 - Python 3.8.13
 - conda 4.10.3]

**Crash Report**
see attach files
[crash_report.2022.05.26.174432175434.log](https://github.com/deepfakes/faceswap/files/8778104/crash_report.2022.05.26.174432175434.log)

**Comment by torzdf** [comment]
Should be fixed in latest commit.
