### ISSUE TITLE
error when convert video no swap face applied

### ISSUE THREAD

**Issue by gravitydeep** [deepfakes/faceswap#1226]
05/28/2022 23:24:01 WARNING  IMAGEIO FFMPEG_WRITER WARNING: input image is not divisible by macro_block_size=8, resizing from (1298, 726) to (1304, 728) to ensure video compatibility with most codecs and players. To prevent resizing, make your input image divisible by the macro_block_size or set the macro_block_size to 1 (risking incompatibility).

**Comment by torzdf** [comment]
This isn't the place for tech support. For that please visit our forums (https://forum.faceswap.dev/) or our discord (https://discord.gg/FC54sYg)

However, the most likely reason is this: https://forum.faceswap.dev/app.php/faqpage?sid=26c90023ef759be6f7a2e739aa02e9cc#f4r0
