### ISSUE TITLE
run python faceswap.py gui with an error "UnicodeDecodeError"

### ISSUE THREAD

**Issue by chaohuichen1024** [deepfakes/faceswap#1230]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte
06/03/2022 17:48:00 CRITICAL An unexpected crash has occurred. Crash report written to 'E:\VisualStudioIDE\AIProject\faceswap\crash_report.2022.06.03.174758316958.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting . can you help me find out what the problem is？

**Comment by torzdf** [comment]
>  You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
