### ISSUE TITLE
run python faceswap.py gui with an error

### ISSUE THREAD

**Issue by chaohuichen1024** [deepfakes/faceswap#1233]
Traceback (most recent call last):
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\cli\launcher.py", line 187, in execute_script
    process = script(arguments)
  File "E:\VisualStudioIDE\AIProject\faceswap\scripts\gui.py", line 179, in __init__
    self.root = FaceswapGui(arguments.debug)
  File "E:\VisualStudioIDE\AIProject\faceswap\scripts\gui.py", line 34, in __init__
    self.build_gui()
  File "E:\VisualStudioIDE\AIProject\faceswap\scripts\gui.py", line 58, in build_gui
    self.configure(menu=MainMenuBar(self))
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\gui\menu.py", line 47, in __init__
    self.help_menu = HelpMenu(self)
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\gui\menu.py", line 207, in __init__
    self.build()
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\gui\menu.py", line 220, in build
    if self._build_branches_menu():
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\gui\menu.py", line 241, in _build_branches_menu
    stdout = self._get_branches()
  File "E:\VisualStudioIDE\AIProject\faceswap\lib\gui\menu.py", line 271, in _get_branches
    retcode, stdout.decode().strip().replace("\n", " - "))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 6: invalid start byte

============ System Information ============
encoding:            cp936
git_branch:          Not Found
git_commits:         Not Found
gpu_cuda:            11.1
gpu_cudnn:           8.0.5
gpu_devices:         GPU_0: GeForce GTX 1650 Ti
gpu_devices_active:  GPU_0
gpu_driver:          457.07
gpu_vram:            GPU_0: 4096MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.19041-SP0
os_release:          10
py_command:          faceswap.py gui
py_conda_version:    conda 4.13.0
py_implementation:   CPython
py_version:          3.7.13
py_virtual_env:      True
sys_cores:           8
sys_processor:       Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
sys_ram:             Total: 16251MB, Available: 6914MB, Used: 9336MB, Free: 6914MB

=============== Pip Packages ===============
absl-py==1.1.0
astunparse==1.6.3
cachetools==5.2.0
certifi==2022.5.18.1
charset-normalizer==2.0.12
colorama==0.4.4
cycler==0.11.0
fastcluster==1.2.6
ffmpy==0.2.3
flatbuffers==2.0
fonttools==4.33.3
gast==0.5.3
google-auth==2.7.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.46.3
h5py==3.7.0
idna==3.3
imageio==2.19.3
imageio-ffmpeg==0.4.7
importlib-metadata==4.11.4
joblib==1.1.0
keras==2.8.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.2
libclang==14.0.1
Markdown==3.3.7
matplotlib==3.5.2
numpy==1.21.6
nvidia-ml-py==11.510.69
oauthlib==3.2.0
opencv-python==4.6.0.66
opt-einsum==3.3.0
packaging==21.3
Pillow==9.1.1
protobuf==3.19.4
psutil==5.9.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyparsing==3.0.9
python-dateutil==2.8.2
pywin32==304
requests==2.28.0
requests-oauthlib==1.3.1
rsa==4.8
scikit-learn==1.0.2
scipy==1.7.3
six==1.16.0
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.8.0
tensorflow-gpu==2.8.2
tensorflow-io-gcs-filesystem==0.26.0
termcolor==1.1.0
threadpoolctl==3.1.0
tqdm==4.64.0
typing_extensions==4.2.0
urllib3==1.26.9
Werkzeug==2.1.2
wincertstore==0.2
wrapt==1.14.1
zipp==3.8.0

**Comment by GKAYowo** [comment]
I have the same problem, how did you solve it?   ovo
