### ISSUE TITLE
copy and paste of the descriptions to be able to translate

### ISSUE THREAD

**Issue by gravitydeep** [deepfakes/faceswap#1235]
**Is your feature request related to a problem? Please describe.**

I have noticed that when I move my mouse over the options of faceswap there is a description that is displayed which is good! but since I am French I do not understand very well 

**Describe the solution you'd like**

Is it possible to add the copy and paste of the descriptions to be able to translate them which would allow a better comprehension of faceswap for the people who are not English because for the moment the copy and paste is not possible thanks

**Comment by torzdf** [comment]
It is not possible, I'm afraid. However we do welcome translation contributions:
https://github.com/deepfakes/faceswap/pull/1126
