### ISSUE TITLE
Apple M1: python -m pip install tensorflow-macos installs 2.9.2

### ISSUE THREAD

**Issue by joeybarrus** [deepfakes/faceswap#1237]
Be advised when following the M1 setup instructions, the tensorflow installation instructions at https://developer.apple.com/metal/tensorflow-plugin/ will now install 2.9.2, which will throw an error when you run `python faceswap.py gui`. 

Until faceswap supports TensorFlow 2.9, the following change worked for me:

use: 
```
conda install -c apple tensorflow-deps==2.8.0
python -m pip install tensorflow-macos==2.8.0
```

instead of:

```
conda install -c apple tensorflow-deps
python -m pip install tensorflow-macos
```

**Comment by torzdf** [comment]
The M1 install path has now been rolled into the standard path. The information here is now out of date
(related: #1238 )
