### ISSUE TITLE
Small error in lib/cli.py get_faces(self, image) 

### ISSUE THREAD

**Issue by andykdy** [deepfakes/faceswap#124]
@line 76
if faces_count > 0 and self.arguments.verbose:
    print('Note: Found more than one face in an image!')
    self.verify_output = True

Shouldn't it measure if the faces_count is greater than 1 instead?
Currently, converting an image sequence continuously bombards the shell with 
'Note: Found more than one face in an image!'
When in actuality, there is only one face.

**Comment by Clorr** [comment]
Good catch, you can modify the directly, it will be made as pull request, and we will accept it
