### ISSUE TITLE
Issue when execute on AMD

### ISSUE THREAD

**Issue by RojasAB** [deepfakes/faceswap#1240]
**Crash reports MUST be included when reporting bugs.**
![image](https://user-images.githubusercontent.com/52432007/174431658-825dcc5a-01de-4f30-b9b7-95567cfff84a.png)

**Describe the bug**
Just executed on an AMD PC with python version higher than 3.8

**To Reproduce**
Run the cmd or gui version

**Expected behavior**
Show this message
The AMD version of Faceswap cannot run on versions of Python higher than 3.8

The solution is to cast the device.get() to int (line 109)
![image](https://user-images.githubusercontent.com/52432007/174431757-dc5d37f5-60c4-4b44-a904-743451507f06.png)

**Comment by torzdf** [comment]
Fixed in latest commit

**Comment by RojasAB** [comment]
good thanks
