### ISSUE TITLE
How can I solve this problem ?

### ISSUE THREAD

**Issue by caliban511** [deepfakes/faceswap#1245]
07/05/2022 00:55:59 INFO     Log level set to: INFO
07/05/2022 00:55:59 ERROR    There was an error importing Tensorflow. This is most likely because you do not have TensorFlow installed, or you are trying to run tensorflow-gpu on a system without an Nvidia graphics card. Original import error: No module named 'tensorflow'
07/05/2022 00:55:59 INFO     Press "ENTER" to dismiss the message and close FaceSwap
![snipaste_20220705_005809](https://user-images.githubusercontent.com/13557387/177195672-ed684269-0a8e-400b-ab4d-ba49133fed63.jpg)

**Comment by torzdf** [comment]
https://forum.faceswap.dev/app.php/faqpage?sid=014ac600e22c9ef748b3bbb9b58719b3#f1r1

**Comment by caliban511** [comment]
> https://forum.faceswap.dev/app.php/faqpage?sid=014ac600e22c9ef748b3bbb9b58719b3#f1r1

thanks for your help.
