### ISSUE TITLE
Multi worker training support?

### ISSUE THREAD

**Issue by nomorecoding** [deepfakes/faceswap#1246]
Hello! I noticed that faceswap used MirroredStrategy, can it be changed to MultiWorkerMirroredStrategy smoothly? 
Or do I need to change the TrainingDataGenerator to make it work? 
Can u guys offer some suggestions please? many thanks!

**Comment by torzdf** [comment]
I don't have a MultiGPU setup to be able to test multi-gpu configurations, so only MirroredStrategy is directly supported, as MultiWorker requires more configuration to set up (which I cannnot easily test).

You can try configuring yourself with the steps here: https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/MultiWorkerMirroredStrategy and feedback with the steps required to get it working (if you are successful).

If you do get it set up correctly, then please do feedback as I can look to add configuration options within Faceswap itself.

We use our own dataloaders, not Tensorflow/Keras implementation, so it is entirely possible that MultiWorker is not possible within Faceswap's context, but I could not say with any certainty one way or the other.

The strategy used is defined here:
https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/MultiWorkerMirroredStrategy

**Comment by torzdf** [comment]
Strategies have now changed slightly, and as there has been no update for a while will close.

Please reply if you want to keep this issue open
