### ISSUE TITLE
Unable to use GPU

### ISSUE THREAD

**Issue by sdasdasddaaaa** [deepfakes/faceswap#1247]
Excuse me, everyone, I installed the software with the GPU version, but when running the software, I am not using the GPU, but running the CPU. What is going on and how to solve it, thank you!
![2345截图20220715071949](https://user-images.githubusercontent.com/87623989/179118519-dcdf651d-b7e3-4f76-9d49-3cae42ae5874.jpg)
![2345截图20220715072142](https://user-images.githubusercontent.com/87623989/179118539-fc194aa0-1921-4127-bd1b-d5e1d515e6e4.jpg)

**Comment by torzdf** [comment]
https://forum.faceswap.dev/app.php/faqpage?sid=1efb04eb03dec98ee85e71b7526fb47b#f0r3
