### ISSUE TITLE
Preview problem

### ISSUE THREAD

**Issue by machinbidule62** [deepfakes/faceswap#1249]
Hello, I’m new, preview does not match the output folder timelapse. Is that normal? Thank you! 

pictures are similar...

reinstall does not fix :/

**Comment by torzdf** [comment]
preview has nothing to do with timelapse.

Preview is a random output from your training folder.
Timelapse you choose the images and they are saved to the specified folder.

Usage questions are best asked in our [forum](https://faceswap.dev/forum) or in our [Discord](https://discord.gg/FC54sYg)

**Comment by machinbidule62** [comment]
I just understood thank you :)
