### ISSUE TITLE
TensorFlow Probability Requires Unsupported Version

### ISSUE THREAD

**Issue by Hexa3333** [deepfakes/faceswap#1253]
When i try to train my models **(with tensorflow version 2.8.0)** i get prompted with this error:
`ImportError: This version of TensorFlow Probability requires TensorFlow version >= 2.9; Detected an installation of version 2.8.0. Please upgrade TensorFlow to proceed.`

But when i replace my tensorflow version with **2.9** Faceswap tells me it does not support 2.9 and i should downgrade.
It's a frustrating loophole.

**System:**
 - OS: Ubuntu 22.04.1 LTS x86_64
 - Python Version: 3.10.4
 - Conda Version 4.6

**Crash Report:**
[crash_report.2022.08.02.171903148718.log](https://github.com/deepfakes/faceswap/files/9244388/crash_report.2022.08.02.171903148718.log)

**Comment by torzdf** [comment]
I have recently updated the repo to support Tensorflow 2.9.

Easiest way to fix would be to delete your environment and re-run the installer.

Otherwise, I have now pinned tensorflow probability to an earlier version.
