### ISSUE TITLE
Can't Open GUI on Windows

### ISSUE THREAD

**Issue by Tuba202** [deepfakes/faceswap#1254]
**Describe the bug**
Whenever I try to open the GUI of Faceswap, I get an error and it doesn't open. I am on Windows, and I have uninstalled and reinstalled multiple times, including redoing the conda environment. CLI functions work, but the main GUI does not open, either from the shortcut or a manual terminal run. I have also tried running with and without admin

**To Reproduce**
1. Uninstall old Faceswap versions
2. Install the latest windows version
3. Run the Faceswap program in GUI mode

**Expected behavior**
I want the Faceswap GUI to open. It doesn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/63259343/183342692-6f1c1bec-df9b-4f71-8a23-f2f77fccc008.png)
![image](https://user-images.githubusercontent.com/63259343/183342835-998834e0-66d6-4751-84e9-a1c150e22063.png)

**Desktop:**
 - OS: [Windows 11]
 - Python Version [3.9.12]
 - Conda Version [4.13.0]
 - Commit ID [6b2aac6]

**Crash Report**
[crash_report.2022.08.07.224753577271.log](https://github.com/deepfakes/faceswap/files/9278810/crash_report.2022.08.07.224753577271.log)

**Comment by torzdf** [comment]
You need typing-extensions>=4.0.0 as per our requirements
https://github.com/deepfakes/faceswap/blob/master/requirements/_requirements_base.txt#L15
