### ISSUE TITLE
How to transfer facial expression of source image and other body gestures and posture of destination image. 

### ISSUE THREAD

**Issue by rohaantahir** [deepfakes/faceswap#1255]
Hi I really like your work. I wanted to know that is there any option in which we can transfer facial expression along with our face to the destination. in simple words I want a complete face projection to the destination frame. So that my facial expressions also swapped along with my face. Kindly let me know.

**Comment by torzdf** [comment]
This is not possible in the context of Faceswap. Faceswap takes the expressions of the original face and transfers them to the new face.

**Comment by rohaantahir** [comment]
Can you please suggests some ways to do so?
