### ISSUE TITLE
Failed to convert image: 'data_dst_000001.png'  UnboundLocalError: local variable 'out' referenced before assignment

### ISSUE THREAD

**Issue by LongHuW** [deepfakes/faceswap#1256]
path:  \plugins\convert\mask\mask_blend.py -line 161
`

        mask = self._get_mask(detected_face, predicted_mask, centering, sub_crop_offset)
        raw_mask = mask.copy()

        if self._mask_type != "none":

            out = self._erode(mask) if self._do_erode else mask
            out = np.minimum(out, self._box)

        logger.trace(  # type: ignore
            "mask shape: %s, raw_mask shape: %s", mask.shape, raw_mask.shape)
        return out, raw_mask
`

I chage it:
`

        mask = self._get_mask(detected_face, predicted_mask, centering, sub_crop_offset)
        raw_mask = mask.copy()

        if self._mask_type != "none":

            mask = self._erode(mask) if self._do_erode else mask
            mask = np.minimum(mask, self._box)

        logger.trace(  # type: ignore
            "mask shape: %s, raw_mask shape: %s", mask.shape, raw_mask.shape)
        return mask, raw_mask
`

**Comment by torzdf** [comment]
Thanks for the heads up. Bug squashed in latest commit.
