### ISSUE TITLE
The converted video is extremely wierd

### ISSUE THREAD

**Issue by 20040714Mike** [deepfakes/faceswap#1258]
For the bug:
In the GUI, I can choose the format for the converted video, but I think the format isn't the format I chose, thus I can't open it like I did with other videos. Even if I did find a video player that can play it, the video is unwatchable in a way that I don't know how to describe. 

For recommendations:
Why not just output a video at the end of "convert" stage.

**Comment by torzdf** [comment]
You'd need to be more specific on this issue. This is not an issue I've seen and I'd need reproducible steps to look into it.

You can choose the file format and codec, as well as set some other common ffmpeg parameters within the ffmpeg writer configuration file. This should be enough to generate a playable video.

**Comment by 20040714Mike** [comment]
While I might found the problem: I don't have full access to configurations while converting images to video.

I am using GUI in mac.

In tools =>  ( Image <> video ) , I can see there are plenty configurations options down there but there isn't a scroll bar for me to scroll down there and see all of them. I can barely see options like: JPG, JPEG etc... But my images are all PNGs.

So my suggestion is, add a scroll bar to that page like every other pages has.

**Comment by torzdf** [comment]
Can you screengrab that, as I'm not sure what you. mean. The display is generally handled by the OS. Unfortunately I don't have a macOS system to test on.

**Comment by 20040714Mike** [comment]
As you can see, there are still plenty options down below the "extract file type" where I don't have access to.
The problem now is, the produced mp4 file _**lost its audio**_ and I can _**only**_ open it with browser, none of other video players I have can open it. 
<img width="366" alt="截屏2022-08-20 下午7 58 13" src="https://user-images.githubusercontent.com/76523934/185748005-fff00cb9-a6b6-4340-8afb-5b4e02ae5711.png">
.

**Comment by torzdf** [comment]
The EFFMPEG tool is just a convienience wrapper for ffmpeg. The filetype option isn't important for you. It's for extracting images from a video.

Either just convert straight into a video (as shown in my earlier screenshot) or stitch the video back yourself in ffmpeg.

I don't have a Mac, so can't do anything about how it chooses to render the GUI.
