### ISSUE TITLE
Uninstalled now all my general desktop files are gone?

### ISSUE THREAD

**Issue by 4hench** [deepfakes/faceswap#1260]
all desktop icons and everything vanished ????

**Comment by torzdf** [comment]
This doesn't sound like a faceswap problem. Faceswap does not install like a normal program. It is just a local install in a local folder. There isn't even an uninstall candidate for it. You just delete the folder.

https://forum.faceswap.dev/app.php/faqpage#f1r2

**Comment by 4hench** [comment]
> 

ohh unistalled it with geek uninstaller it was named anaconda something sat at like 13gb guess i fucked up lol
