### ISSUE TITLE
Problems at modifying the FSA alignment file

### ISSUE THREAD

**Issue by 20040714Mike** [deepfakes/faceswap#1262]
I don't know how to modify the FSA alignments file to improve my results since the AI either recognized someone else's face or something that is similar to a face during the extracting process.

I have tried many ways to open and edit that FSA file, but none of them worked, all methods returned a corrupt file and there's no way I can edit it like that.

However, that FSA file did work during the converting process, and it did swap out other people's faces ( not the face of the person I intended to swap for ) or attempt to change something that look like a face to a face.

Anyway I believe it's my problem, so how to edit that FSA file?

**Comment by torzdf** [comment]
You aren't meant to be able to edit the fsa file directly. It's a binary file as it contains masks etc. as well as landmarks.

See here for how to clean up data:
https://forum.faceswap.dev/viewtopic.php?t=27#sort

Also, usage questions should be posted to our [forum](https://faceswap.dev/forum) or [Discord](https://discord.gg/FC54sYg), not to Github, which is meant for bugs.
