### ISSUE TITLE
Training fails on dfaker mod

### ISSUE THREAD

**Issue by vlccdl** [deepfakes/faceswap#1265]
after lasted update,i can't train my Existing dfaker model.
ValueError: Input 0 of layer "dfaker" is incompatible with the layer: expected shape=(None, 64, 64, 3), found shape=(20, 128, 128, 3)

full log attached below
[crash_report.2022.08.22.222618241236.log](https://github.com/deepfakes/faceswap/files/9395273/crash_report.2022.08.22.222618241236.log)

**Comment by torzdf** [comment]
I cannot recreate this issue using the exact same settings as you.

I do notice that this model is over 2.5 years old! The fact that you can still run a model that old in current faceswap amazes me.

Do you get the same issue if you start a new model?

**Comment by vlccdl** [comment]
yes，it's ok when start a new dfaker model.
thanks a lot for your work.it time to say goodbye to my old dfaker model.
now , start with phaze-a model:)

**Comment by torzdf** [comment]
For what it's worth, I just fixed another bug, which *may* solve this issue (it also may not, but worth checking)

**Comment by vlccdl** [comment]
o my god,it's work,thanks a lot.
and before this update,i found a way to pass error.it about "output_size".
when the model created,the "output_size" is 128 by defalut.then i edit "dfaker_state.json",output_size be changed to 256.run for years.
when i change back to 128,it run again.
why i found this way?beacause when i trainning phaze-a model,i edit "phaze_a_state.json" again,to change "enc scaling".
and recieved ValueError: Input 0 of layer "phaze_a" is incompatible with the layer: expected shape=(None, 64, 64, 3), found shape=(6, 272, 272, 3)\n
