### ISSUE TITLE
Error message when trying to extract faces

### ISSUE THREAD

**Issue by ktsi** [deepfakes/faceswap#1293]
Hi all.

I have installed faceswap on a MacBook Air M1 with 8GB (I know, I should have gone for more...) of total memory.
Problem is that it crashes when I am trying to extract faces.

This is what I get from the GUI:

_Loading...
Setting Faceswap backend to APPLE_SILICON
Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

01/12/2023 10:31:22 INFO     Log level set to: INFO
01/12/2023 10:31:23 INFO     Loading Detect from S3Fd plugin...
01/12/2023 10:31:23 INFO     Loading Align from Fan plugin...
01/12/2023 10:31:23 INFO     Loading Mask from Components plugin...
01/12/2023 10:31:23 INFO     Loading Mask from Extended plugin...
01/12/2023 10:31:23 WARNING  Not enough free VRAM for parallel processing. Switching to serial
01/12/2023 10:31:23 INFO     Starting, this may take a while...
01/12/2023 10:31:23 INFO     Output Directory: /Users/aaa/Downloads/aaa

01/12/2023 10:31:23 INFO     Initializing S3FD (Detect)...

/Users/aaa/miniforge3/envs/faceswap/lib/python3.9/multiprocessing/resource_tracker.py:216: **UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d '
Process exited._**

This is what I see in terminal after I run the faceswap.py GUI command:

_Setting Faceswap backend to APPLE_SILICON
Metal device set to: Apple M1

systemMemory: 8.00 GB
maxCacheSize: 2.67 GB

2023-01-12 10:31:10.773554: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2023-01-12 10:31:10.774097: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
01/12/2023 10:31:10 INFO     Log level set to: INFO_

I have searched online about this error msg and I see some comments relating this to insufficient memory. 

Any ideas what is really happening and a possible remedy hopefully? 

Thanks.

**Comment by ktsi** [comment]
I tried changing batch size in the GUI but nothing worked.

**Comment by kalebshah** [comment]
I am having the exact same problem

`/Users/usrname/miniforge3/envs/faceswap/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
warnings.warn('resource_tracker: There appear to be %d 'Process exited.`

**Comment by kalebshah** [comment]
> 

I also have a 2020 M1 Macbook Pro with 8gb of ram and 250gb of storage. Is the limited memory the issue?

**Comment by torzdf** [comment]
Ok, I think this is to do with a tensorflow-metal version incompatibility. See here for potential fix:

https://forum.faceswap.dev/viewtopic.php?f=6&t=2449&p=8389#p8389
