### ISSUE TITLE
alignment problem since last update

### ISSUE THREAD

**Issue by gravitydeep** [deepfakes/faceswap#1294]
Hello there is no error or crash however when I extract the frames from image the alignment file is created but it does not work with a video download or a video capture, the frames are extracted but the alignment file is missing.
Does anyone have an idea?

**Comment by torzdf** [comment]
Have not seen this before. Are you definitely looking in the correct place (the alignments file will be stored next to the source video).

If you continue to have issues, this might be better discussed/resolved on our [discord server](https://discord.gg/FC54sYg)
