### ISSUE TITLE
easy install completed but Can't Open GUI on Windows

### ISSUE THREAD

**Issue by hutuxianer** [deepfakes/faceswap#1295]
Describe the bug

Whenever I try to open the GUI of Faceswap, I get an error and it doesn't open. I am on Windows,it have installed success.it showing  nvmlInitWithFlags not found ,just  the shortcut or a manual terminal run

**To Reproduce**
1. Install the latest windows version
2. Run the Faceswap program in GUI mode
3. update latest NVIDIA drivers  do/don't 

**Expected behavior**
I want the Faceswap GUI to open and it can run.

**Screenshots**
<img width="459" alt="faceswap问题" src="https://user-images.githubusercontent.com/122772174/212615396-2b91def8-5cce-477c-b08f-6de195d58157.png">

**Comment by torzdf** [comment]
What GPU are you using?

Either your GPU is too old to be supported, or you need to update the drivers for it. If the latter, then I suggest using [DDU](https://www.guru3d.com/files-details/display-driver-uninstaller-download.html) to remove your drivers and then install the latest.


Closing this issue. Please open a new one if you continue to have problems.
