### ISSUE TITLE
No output in the extraction phase running on colab

### ISSUE THREAD

**Issue by juhonkang** [deepfakes/faceswap#1304]
![image](https://user-images.githubusercontent.com/67153600/222637756-915448e9-7fbf-49e8-bf09-4240dc3a4ef9.png)

![image](https://user-images.githubusercontent.com/67153600/222636980-24f4e545-bca7-4fba-accf-6db2188a8cfe.png)

**Comment by torzdf** [comment]
Unfortunately we don not directly support Colab, especially since Google blocks the use of our software on Colab.
