### ISSUE TITLE
feat: set how much images to be extracted from video

### ISSUE THREAD

**Issue by jjangga0214** [deepfakes/faceswap#1309]
**Is your feature request related to a problem? Please describe.**
Sometimes, the number of images extracted from a video is too large (or the opposite).

**Describe the solution you'd like**
A new CLI and GUI option for adjusting it would be cool.

What do you think about this idea?

Thanks :)

**Comment by torzdf** [comment]
This already exists. It's the "Extract Every N" option.

You should follow the guides as it covers all this kind of stuff:
https://forum.faceswap.dev/app.php/tag/Guide?sid=af4d6d7c7bf7ccb54f305193d0d84ee7
