### ISSUE TITLE
Dependency Issues on Apple Sillicon Macbook

### ISSUE THREAD

**Issue by daongochieu2810** [deepfakes/faceswap#1318]
**Describe the bug**

Dependency issues with `matplotlib`, `pillow`, `kiwisolver`, `numexpr`, `scipy`

**To Reproduce**
1. Follow INSTALL.md for MacOS (Apple Sillicon) (with miniconda3 instead of miniforge3)
2. Run `python setup.py`
3. Run `python faceswap.py gui`

**Expected behavior**
GUI to be opened without exceptions

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.2.1 (M1)
 - Python Version: 3.9
 - Conda Version: 23.3.1
 - Commit ID: 216ef387636eb7b84819c1b77d9a2f631ed97ab5

**Additional context**
Can be resolved by uninstalling and installing again (without versioning)

**Crash Report**
[crash_report.2023.04.26.205610686768.log (matplotlib)](https://github.com/deepfakes/faceswap/files/11333881/crash_report.2023.04.26.205610686768.log)
[crash_report.2023.04.26.205719962583.log (pillow)](https://github.com/deepfakes/faceswap/files/11333883/crash_report.2023.04.26.205719962583.log)
[crash_report.2023.04.26.205831130337.log (kiwisolver)](https://github.com/deepfakes/faceswap/files/11333884/crash_report.2023.04.26.205831130337.log)
[crash_report.2023.04.26.214057013012.log (numexpr)](https://github.com/deepfakes/faceswap/files/11333885/crash_report.2023.04.26.214057013012.log)
[crash_report.2023.04.26.214313273209.log (scipy)](https://github.com/deepfakes/faceswap/files/11333886/crash_report.2023.04.26.214313273209.log)

**Comment by torzdf** [comment]
Closing as should be fixed by python update + new install script
