### ISSUE TITLE
Error installing requirements...

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#132]
I installed sucessfull: **pip install virtualenvwrapper-win**

Then i ejecute:

**mkvirtualenv faceswap
setprojectdir .**

Then: pip install -r requirements.txt

And then a lot of errors appeared
https://pastebin.com/gpnWNfpM

**Comment by IUsedToBeAPygmy** [comment]
First of all why are you doing all this in your System\Win32 folder??????

**Comment by ZeroCool22** [comment]
You see the code i paste in pastebin?

> (faceswap) C:\Windows\System32>cd C:\faceswap-master
  
> (faceswap) C:\faceswap-master>pip install -r requirements-gpu.txt

I was in the folder C:\faceswap-master **before ejecute** pip install -r requirements-gpu.txt

I'm following step by step the **guide** of the repo: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md

**Comment by IUsedToBeAPygmy** [comment]
> 
> (faceswap) C:\Windows\System32>setprojectdir .
>  
>     "C:\Windows\System32" is now the project directory for
>     virtualenv "C:\Users\ZeroCool22\Envs\faceswap"
>  
>     "C:\Windows\System32" added to
>     C:\Users\ZeroCool22\Envs\faceswap\Lib\site-packages\virtualenv_path_extensions.pth

You are setting up your project directory to be C:\Windows\System32 instead of C:\faceswap-master
