### ISSUE TITLE
Missing tf. contrib module and unable to downgrade tf

### ISSUE THREAD

**Issue by cczdy** [deepfakes/faceswap#1321]
There seems to be a contradictory issue here. The code reported an error and lacked the TensorFlow.contrib module, which was included before TensorFlow 1.5. However, this project requires TensorFlow 2.7 to start the GUI. How can this issue be resolved? Thank you.
This is the error prompt after clicking on the training:
[crash_report.2023.06.06.214524461845.log](https://github.com/deepfakes/faceswap/files/11665646/crash_report.2023.06.06.214524461845.log)
![5`QE07$((9{YWRO0D_ CTPL](https://github.com/deepfakes/faceswap/assets/104202935/470d619f-3bf2-4fec-9f52-b5f8ff475746)

**Comment by torzdf** [comment]
Ok, this is a weird issue that I haven't seen before, and is related to tensorflow-probability rather than tensorflow itself. Most likely a version conflict somewhere.

How did you install Faceswap? The quickest and easiest fix I can suggest is to remove your environment and re-install through the installer.

**Comment by cczdy** [comment]
I installed using anaconda virtual environment and git (both cuda and cudaa have been installed), but some packages were missing during the installation process. I used pip for installation. During this period, there were some package version conflicts that were fortunately resolved. I will follow your prompts to solve the problem. Thank you for answering my question during your busy schedule.

**Comment by torzdf** [comment]
TBH, I'm not sure why tf-probability would be looking to access tf.contrib. Annoyingly, we only import it for 1 function, but the code we use from there is quite involved, which is why I haven't just manually brought the module in. I may revisit this at some point.

**Comment by torzdf** [comment]
tf probability has been removed as a requirement, so this issue should no longer occur
