### ISSUE TITLE
Faceswap won't load after today's update (Apple silicon)

### ISSUE THREAD

**Issue by vyjio** [deepfakes/faceswap#1327]
Hello, I was running Training in Faceswap with no problem this morning (up to 137,220 iterations), but following a crash and before re-starting I checked for updates and installed the latest update.  Tried to re-start Faceswap and got this in Terminal:-

Last login: Tue Jun 27 07:50:26 on ttys001
(base) paulsultra@PaulsMacStudio ~ % conda activate faceswap
(faceswap) paulsultra@PaulsMacStudio ~ % cd faceswap
(faceswap) paulsultra@PaulsMacStudio faceswap % python faceswap.py gui
Setting Faceswap backend to APPLE_SILICON
Traceback (most recent call last):
  File "/Users/paulsultra/faceswap/faceswap.py", line 12, in <module>
    from lib.cli import args as cli_args  # pylint:disable=wrong-import-position
  File "/Users/paulsultra/faceswap/lib/cli/args.py", line 18, in <module>
    from .actions import (DirFullPaths, DirOrFileFullPaths, DirOrFilesFullPaths, FileFullPaths,
  File "/Users/paulsultra/faceswap/lib/cli/actions.py", line 49, in <module>
    class FileFullPaths(_FullPaths):
  File "/Users/paulsultra/faceswap/lib/cli/actions.py", line 72, in FileFullPaths
    def __init__(self, *args, filetypes: str | None = None, **kwargs) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
(faceswap) paulsultra@PaulsMacStudio faceswap % 

Please help,
many thanks
Paul

**Comment by torzdf** [comment]
You will need to remove your environment and re-install Faceswap as per the updated instructions here: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#macos-apple-silicon-install-guide

The lowest supported version of Python has been updated to 3.10
