### ISSUE TITLE
AssertionError in setup.py

### ISSUE THREAD

**Issue by meerfrau** [deepfakes/faceswap#1328]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
```
  File "./src/faceswap/setup.py", line 1661, in <module>
    ENV = Environment()
  File "./src/faceswap/setup.py", line 83, in __init__
    self._packages = Packages(self)
  File "./src/faceswap/setup.py", line 296, in __init__
    self._update_backend_specific_conda()
  File "./src/faceswap/setup.py", line 342, in _update_backend_specific_conda
    assert self._env.backend is not None
AssertionError
```

**To Reproduce**
`python setup.py install --root="$pkgdir/" --optimize=1`

**Expected behavior**
successful installation

**Desktop (please complete the following information):**
 - OS: ArchLinux at core but without Python 3.11
 - Python Version: 3.9
 - Conda Version: pulled in from setup.py
 - Commit ID: git master

**Comment by torzdf** [comment]
Unsupported Python version.
Unsupported command line switches.
See install guide here:
https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#linux-and-windows-install-guide
