### ISSUE TITLE
converted face with obvious texture

### ISSUE THREAD

**Issue by mqcui** [deepfakes/faceswap#1329]
When I  converted both A and B to a video or images, I find there was a texture between face B and head A. It was so obvious that kept excellence from the ideal result. How can it be done for this issue?
Thx a lot!
Regards!

**Comment by torzdf** [comment]
There is no way near enough information here to even begin to understand your problem.

Either way, the Github issues are for bugs in code, and not for general usage support. For that use our [Discord](https://discord.gg/FC54sYg) or our [Forum](https://forum.faceswap.dev/index.php)
