### ISSUE TITLE
Unable to launch faceswap

### ISSUE THREAD

**Issue by UdayKumarR** [deepfakes/faceswap#1332]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

Go to Anaconda Navigator -> Environments
Click on Faceswap environment and open terminal
Navigate to faceswap using "cd faceswap" command in the terminal

While running "python faceswap.py -h" command 

Setting Faceswap backend to DIRECTML
Traceback (most recent call last):
  File "C:\Users\Admin\faceswap\faceswap.py", line 12, in <module>
    from lib.cli import args as cli_args  # pylint:disable=wrong-import-position
  File "C:\Users\Admin\faceswap\lib\cli\args.py", line 14, in <module>
    from lib.gpu_stats import GPUStats
  File "C:\Users\Admin\faceswap\lib\gpu_stats\__init__.py", line 20, in <module>
    from .directml import DirectML as GPUStats  # type:ignore
  File "C:\Users\Admin\faceswap\lib\gpu_stats\directml.py", line 14, in <module>
    from comtypes import COMError, IUnknown, GUID, STDMETHOD, HRESULT  # pylint:disable=import-error
ModuleNotFoundError: No module named 'comtypes'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python Version [e.g. 3.5, 3.6]
 - Conda Version [e.g. 4.5.12]
 - Commit ID [e.g. e83819f]
 - 
**Additional context**
![image](https://github.com/deepfakes/faceswap/assets/16185159/750b8153-ae76-4c11-98b6-b013a2e1c47f)

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by torzdf** [comment]
Zero context. Zero information. Completely ignores the issue requirements.

Bad install. Cleanup and install properly.

https://forum.faceswap.dev/app.php/faqpage#f1r1
