### ISSUE TITLE
model download error in GUI

### ISSUE THREAD

**Issue by 20040714Mike** [deepfakes/faceswap#1333]
Loading...
Setting Faceswap backend to NVIDIA
07/31/2023 18:22:00 INFO     Log level set to: INFO
07/31/2023 18:22:03 INFO     Loading Detect from S3Fd plugin...
07/31/2023 18:22:03 INFO     Downloading model: 's3fd_keras' from: https://github.com/deepfakes-models/faceswap-models/releases/download/v11.2/s3fd_keras_v2.zip
07/31/2023 18:22:07 WARNING  Error downloading model (<urlopen error [Errno 2] No such file or directory>). Retrying 2 of 6...
Terminating Process...
Terminated
Process exited.

Hi. It seems like the URL generated somewhere in the code is no longer working, which part of the code should I change for it to use working urls?
Thx.

**Comment by torzdf** [comment]
That URL works just fine for me.
