### ISSUE TITLE
" if "==" not in pkg:" won't find manually-installed packages ...

### ISSUE THREAD

**Issue by jiapei100** [deepfakes/faceswap#1334]
```python
        for pkg in installed:
            if "==" not in pkg:
                continue
            item = pkg.split("==")
            installed_packages[item[0]] = item[1]
```

only finds packages installed by 'pip install pkg`. But what if the packages are installed manually? For instance, my **tensorflow** is manually built as:

`tensorflow @ file:///tmp/tensorflow_pkg/tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl#sha256=cc31b12714e13d35aeb5584aa977e5597e22dd7f089ceb75d9bee1656846757a` .

**Comment by torzdf** [comment]
Sure.

But you're talking about a manually installed Tensorflow wheel which is not officially supported by Faceswap, so it's kinda edge case. If you have got to the point that you can get Faceswap to run with an unsupported version of Tensorflow, then you're probably at the point where you can also code around this issue, no?

You're welcome to PR a solution that catches and handles any matching manually installed wheels though.

**Comment by jiapei100** [comment]
@torzdf 
Thank you... I found out a dirty way to handle this particular **tensorflow**, but not a generalized solution.

Thank you anyway...
