### ISSUE TITLE
fewer image to swap.

### ISSUE THREAD

**Issue by flydragon2018** [deepfakes/faceswap#1336]
**Is your feature request related to a problem? Please describe.**
can't  train with fewer images.

**Describe the solution you'd like**
either training model with a few images or swap directly without training?

 08/03/2023 17:50:02 INFO     Log level set to: INFO
08/03/2023 17:50:04 INFO     Model A Directory: '/home/zzl/faceswap/input/faces/s1' (3 images)
08/03/2023 17:50:04 INFO     Model B Directory: '/home/zzl/faceswap/input/faces/t1' (1 images)
08/03/2023 17:50:04 ERROR    At least one of your input folders contains fewer than 25 images.
08/03/2023 17:50:04 ERROR    You need to provide a significant number of images to successfully train a Neural Network. Aim for between 500 - 5000 images per side.

**Comment by torzdf** [comment]
This isn't an error. What you are requesting is not how Faceswap works.
