### ISSUE TITLE
12gb Vram

### ISSUE THREAD

**Issue by TheWorldIsOur** [deepfakes/faceswap#1337]
Is there any chance to make it work on a rtx 3060 with 12 vram?

**Comment by torzdf** [comment]
Yes.

However, this area is for issues and bugs with the software, it is not a support forum.

Please see our FAQs at:
https://forum.faceswap.dev/app.php/faqpage?sid=896912e96449945d0960adc4c964e05b

and guides at:
https://forum.faceswap.dev/app.php/tag/Guide
