### ISSUE TITLE
Some applications failed to install. Process Aborted. Check Details.

### ISSUE THREAD

**Issue by lyx102** [deepfakes/faceswap#1338]
Could you please tell me the reason for this? How can I solve it?
![2a352185d7223213fcac4269a914b4c](https://github.com/deepfakes/faceswap/assets/118903019/8c6bef6c-ddba-44b9-ab7f-760fb275f874)

**Comment by torzdf** [comment]
I need the full error text. Right click on the text window in the installer, hit "copy" and paste here

**Comment by lyx102** [comment]
**Is it related to the Python 3.11 I installed in advance**  Here is the complete error code


(check) MiniConda installed: conda 23.7.2
(check) CPU Supports AVX Instructions
(check) CPU Supports SSE4 Instructions
(check) Completed check for installed applications
(check) Setting up for: nvidia

Miniconda3 installed.
Initializing Conda...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
# All requested packages already installed.
Creating Conda Virtual Environment...
Removing existing Conda Virtual Environment...
Remove all packages in environment C:\Users\Administrator\MiniConda3\envs\faceswap:
Deleting stale Conda Virtual Environment files...
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\Library\bin\ffi.dll.conda_trash
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\Library\bin\libbz2.dll.conda_trash
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\Library\bin\liblzma.dll.conda_trash
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\Library\bin\libssl-3-x64.dll.conda_trash
Remove folder: C:\Users\Administrator\Miniconda3\envs\faceswap\Library\bin\
Remove folder: C:\Users\Administrator\Miniconda3\envs\faceswap\Library\
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\msvcp140.dll.conda_trash
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\vcruntime140.dll.conda_trash
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\vcruntime140_1.dll.conda_trash
Delete file: C:\Users\Administrator\Miniconda3\envs\faceswap\zlib.dll.conda_trash
Remove folder: C:\Users\Administrator\Miniconda3\envs\faceswap\
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Users\Administrator\MiniConda3\envs\faceswap
  added / updated specs:
    - python=3.10
The following NEW packages will be INSTALLED:
  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0 
  ca-certificates    pkgs/main/win-64::ca-certificates-2023.05.30-haa95532_0 
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0 
  openssl            pkgs/main/win-64::openssl-3.0.10-h2bbff1b_0 
  pip                pkgs/main/win-64::pip-23.2.1-py310haa95532_0 
  python             pkgs/main/win-64::python-3.10.12-he1021f5_0 
  setuptools         pkgs/main/win-64::setuptools-68.0.0-py310haa95532_0 
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0 
  tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0 
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1 
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2 
  wheel              pkgs/main/win-64::wheel-0.38.4-py310haa95532_0 
  xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0 
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0 
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate faceswap
#
# To deactivate an active environment, use
#
#     $ conda deactivate
Installing Git...
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Users\Administrator\MiniConda3\envs\faceswap
  added / updated specs:
    - git
The following NEW packages will be INSTALLED:
  git                pkgs/main/win-64::git-2.40.1-haa95532_1 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Downloading Faceswap...
Cloning into 'C:\Users\Administrator\faceswap'...
fatal: unable to access 'https://github.com/deepfakes/faceswap.git/': Recv failure: Connection was reset
Error Downloading Faceswap
Install Aborted

**Comment by torzdf** [comment]
You are having some kind of connection error connecting to git. This could be a proxy or port issue, but I can't really help you beyond that as it is outside of the scope of the project.

You will need to try to solve the issue with your connection:
https://www.google.com/search?q=fatal%253A+unable+to+access+Recv+failure%253A+Connection+was+reset

Alternatively you can try a manual install:
https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#manual-install
