### ISSUE TITLE
No CMAKE_C_COMPILER could be found (EDITED).

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#134]
![screenshot_4](https://user-images.githubusercontent.com/13344308/35907448-bc42936a-0bcc-11e8-8ed7-08745c9d453f.png)

![screenshot_5](https://user-images.githubusercontent.com/13344308/35908209-b876b3b8-0bce-11e8-9c85-01b9301e01ea.png)

**Comment by IUsedToBeAPygmy** [comment]
It literally says "ERROR: virtualenv "faceswap" already exists.

You haven't properly removed your old virtualenv.

**Comment by ZeroCool22** [comment]
OK, thx for the help, now, i followed your instructions, still get: **Is not installable. File 'setup.py' not found.**

![screenshot_1](https://user-images.githubusercontent.com/13344308/35910213-a0f718e4-0bd4-11e8-9569-916c0e206a8a.png)

**Comment by ZeroCool22** [comment]
Thx for your help, i got the others errors solved, but now i get:

**Failed building wheel for dlib and more errors....**

After ejecute pip install -r requirements-gpu.txt

https://pastebin.com/3wvEZQXP

**Comment by IUsedToBeAPygmy** [comment]
Can you type lsvirtualenv and paste the output?
And do the same for cdvirtualenv?

**Comment by ZeroCool22** [comment]
Yes, ofc. i did that steps, i'm in the part of **pip install -r requirements-gpu.txt** but get a lot of errors (red text).

I make a video to show you i'm doing the things like you told me (and the guide installation): https://www.youtube.com/watch?v=kEaS2eXDhLc

What you ask me for:

![screenshot_2](https://user-images.githubusercontent.com/13344308/35912547-a6ecc2b0-0bdb-11e8-9484-6b87f8a6da3a.png)

**Comment by IUsedToBeAPygmy** [comment]
Which exact version of Python are you using?  
Can you try
> pip install dlib
to see what happens?

**Comment by ZeroCool22** [comment]
What happened is, a lot of errors... :/

https://pastebin.com/EPA2NjRQ

**Comment by IUsedToBeAPygmy** [comment]
The error is  No CMAKE_C_COMPILER could be found.

I think this should point you in the right direction.
https://stackoverflow.com/questions/41912372/dlib-installation-on-windows-10

**Comment by ZeroCool22** [comment]
I already have CMAKE installed since 2017, i do the PIP ypu told me anyways?

![screenshot_3](https://user-images.githubusercontent.com/13344308/35914862-acbb028a-0be3-11e8-8790-d6a4321288ef.png)
**CMake (cmake-gui)**

**Comment by IUsedToBeAPygmy** [comment]
Sigh, I'm sorry, I'm out of ideas :(

**Comment by ZeroCool22** [comment]
OK, thx anyway for try to help me.

**Comment by Dri0m** [comment]
I was having wheel issues too. I can't recally if it was the same issue. but try installing http://landinghub.visualstudio.com/visual-cpp-build-tools 2015 version. This fixed everything for me.

**Comment by ZeroCool22** [comment]
@IUsedToBeAPygmy After i ejecuted the command you told me **"pip install dlib"**, now **nothing related with Python works**, not even the FAKEAPP, neither virtualenv, what could happened?

**Comment by ZeroCool22** [comment]
@Dri0m Already have it.

![screenshot_4](https://user-images.githubusercontent.com/13344308/35916475-452bf43e-0be9-11e8-8d6e-5df9a7638ffa.png)

**Comment by Clorr** [comment]
@ZeroCool22 sorry you have trouble installing, but anyway the install process is still very rough, especially on windows.

What i can tell you from my windows experience is:
- dlib is hard to setup with pip on python 3.5 because it lacks a precompiled version. With python 3.6, there is a precompiled version of dlib that is the 19.7.0
- The problem if you go for the 3.6 version is that tensorflow 1.4.0 does not work with it
- BUT tensorflow 1.5.0 has been released and should work with python 3.6

Otherwise, instead of pip, there is conda that can help you setup things because it has more precompiled libs, but I never tried conda

**Comment by IUsedToBeAPygmy** [comment]
FWIW, I'm running Python 3.6, Tensorflow 1.5, Cuda 9 and cuDNN 7 without any problems.

**Comment by ZeroCool22** [comment]
The only Python's i have are the Intel One from this guide (https://www.reddit.com/r/deepfakes/comments/7nq173/v2_tutorial_intelbased_python_easy_to_follow/) and Python 3.6.3 (Anaconda3 5.0.1 64bit).

I just finished to reinstall everything to get working again the Original Code and the APP 1.1.

I still wanna try your REPO guys, but i don't want to fuck everything again, so if someone of you want to help to install it trough **TEAMVIEWER** tell me.

**PC SPECS:** 7700k, 32 ram, MSI 1080TI, Windows 10 creators.
