### ISSUE TITLE
tensorflow install error

### ISSUE THREAD

**Issue by SydrrO** [deepfakes/faceswap#1342]
**Desktop (please complete the following information):**
 - OS: ubuntu (latest) 64bit
 - Python Version 3.10

## I cannot install **tensorflow-cpu**,am i going to use anaconda or something?
![Cache_71a8960bd6b52c27](https://github.com/deepfakes/faceswap/assets/129657153/f274471c-b03f-4b3d-bb16-76e42b741f26)

**Comment by torzdf** [comment]
Please provide the file `faceswap_setup.log` from your faceswap folder.

And if you are actually running this on an orange pi zero, then you have zero chance of getting this to work.

**Comment by SydrrO** [comment]
> 

why orangepi zero cannot run faceswap？

**Comment by torzdf** [comment]
Because you need a decently powered GPU, which the Orange Pi Zero does not have, and Tensorflow requires an x86_64 processor (or an Apple M1/2 processor), whilst the Orange Pi Zero has an Arm64 processor.

**Comment by SydrrO** [comment]
> Because you need a decently powered GPU, which the Orange Pi Zero does not have, and Tensorflow requires an x86_64 processor (or an Apple M1/2 processor), whilst the Orange Pi Zero has an Arm64 processor.

thanks,so if i choose cpu to train,it still cannot work successfully,right?what i have to do is to use my own computer?

**Comment by torzdf** [comment]
Even on a modern, high powered x86_64 processor, training would take so long as to not be worth it. You really need a GPU (Nvidia or AMD) with at least 4GB of VRAM to even start thinking about training a model.

This is not a limitation of Faceswap, it's just the way that Machine Learning works. Faceswap models are quite large so it is not feasible to train them without a GPU.

**Comment by SydrrO** [comment]
> 

OK，thanks
