### ISSUE TITLE
cannot install miniconda

### ISSUE THREAD

**Issue by SydrrO** [deepfakes/faceswap#1345]
# windows11
## i open the install exe
![Cache_-53709b1202da3e13](https://github.com/deepfakes/faceswap/assets/129657153/734eb319-23be-47f8-aa9c-dc7be15e2abf)
**now it is greatly moving**
## then i wait,it just break,every time! at this step
![Cache_645849245537f823](https://github.com/deepfakes/faceswap/assets/129657153/0bb277c3-3c3e-42e7-9709-f72576df91bc)
![Cache_-299a6ac62ca4fe0e](https://github.com/deepfakes/faceswap/assets/129657153/f17b2ae2-19ba-4059-a98b-b0bba74f42e0)

**Comment by torzdf** [comment]
It's most likely an internet connection issue. You can just download and install miniconda separately from here: 

https://docs.conda.io/en/latest/miniconda.html

Also, you are best of posting (and searching) for these kind of problems on our website: https://forum.faceswap.dev/index.php?sid=5dd29bc3fc8162a0b2107f78c4a01923 as support is provided there.

Github issues is more for software bugs/improvements

**Comment by SydrrO** [comment]
> It's most likely an internet connection issue. You can just download and install miniconda separately from here:
> 
> https://docs.conda.io/en/latest/miniconda.html
> 
> Also, you are best of posting (and searching) for these kind of problems on our website: https://forum.faceswap.dev/index.php?sid=5dd29bc3fc8162a0b2107f78c4a01923 as support is provided there.
> 
> Github issues is more for software bugs/improvements

thanks，i don't know why,but when i install the conda in the website,it just work,on my win10 equipment don't need to do this.but on my win11 equipment,i have to do,it is not the connection issues,because i can install the whole miniconda on your exe.but i cannot use your exe to add to local.greatly thanks
