### ISSUE TITLE
The video is very blurry

### ISSUE THREAD

**Issue by SydrrO** [deepfakes/faceswap#1346]
Hello, no offense. I am using the original training model and after interate 120000 times, the face in the video is still very blurry, and there is no difference compared to 90000 times. Is it normal ?

## preview
![Screenshot_2023-08-27-00-22-11-122_com miui video](https://github.com/deepfakes/faceswap/assets/129657153/c7edaaed-5c52-4e53-9ab8-e1a736eb1cd4)
![Screenshot_2023-08-27-00-22-43-198_com miui gallery](https://github.com/deepfakes/faceswap/assets/129657153/e9b52b67-6898-4e8f-b978-e04abfe01438)

# my gpu: rtx3060
# my cpu: i5

**Comment by torzdf** [comment]
Please, please, please read our faqs and the forums rather than using github as you personal support platform.
https://forum.faceswap.dev/app.php/faqpage?sid=9d5c723510161f1f6c556b1054a6f7ff
