### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by oolYang** [deepfakes/faceswap#1351]
(faceswap3.9) zcb@zcb:~/ys1/faceswap-master$ python faceswap.py -h
Setting Faceswap backend to CPU
Traceback (most recent call last):
  File "faceswap.py", line 12, in <module>
    from lib.cli import args as cli_args  # pylint:disable=wrong-import-position
  File "/home/zcb/ys1/faceswap-master/lib/cli/args.py", line 14, in <module>
    from lib.gpu_stats import GPUStats
  File "/home/zcb/ys1/faceswap-master/lib/gpu_stats/__init__.py", line 9, in <module>
    from ._base import set_exclude_devices, GPUInfo
  File "/home/zcb/ys1/faceswap-master/lib/gpu_stats/_base.py", line 11, in <module>
    _EXCLUDE_DEVICES: list[int] = []
TypeError: 'type' object is not subscriptable

**Comment by YashIngle21** [comment]
please use just.... (_EXCLUDE_DEVICES  = []) or (_EXCLUDE_DEVICES: List[int] = []) instead. I am new to open source so please pardon if its now the right way to contribute..

**Comment by deepfakes** [comment]
You are using the wrong minimum Python version.

Minimum is 3.10

**Comment by YashIngle21** [comment]
So can you please tell me what the solution was.

**Comment by deepfakes** [comment]
Install a new version of Python or, even easier, use our installer in https://github.com/deepfakes/faceswap/releases/tag/v2.10.0 as it handles all of this for you

**Comment by YashIngle21** [comment]
ok thx.....Can you please give me any tips on how to start open source contributions and how to read large codebases. I tried to find answers online but didnt get any satisfactory answers?

**Comment by deepfakes** [comment]
This is not a support forum, it is for issues with the code. If you require support please use our [forum](https://forum.faceswap.dev/) or our [Discord](https://discord.gg/FC54sYg)

**Comment by YashIngle21** [comment]
ok
