### ISSUE TITLE
i have installed numpy but still it shows numpy not installed

### ISSUE THREAD

**Issue by haydenbanz** [deepfakes/faceswap#1353]
i have installed numpy but still it shows numpy not installed              while running python faceswap.py gui

**Comment by torzdf** [comment]
Then you are doing something wrong. 

You do not provide anyway near enough information to diagnose the issue. This is also an issue with your setup and not with faceswap.

See here for more remedial methods:
https://forum.faceswap.dev/app.php/faqpage?sid=c6e8313d10e2337cd3f53f966ec88875#f1r1
