### ISSUE TITLE
GPU not working

### ISSUE THREAD

**Issue by Cashew-wood** [deepfakes/faceswap#1355]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/deepfakes/faceswap/assets/84235524/550fee77-9cda-4346-808d-2970be913b96)

**Desktop (please complete the following information):**
 - OS: Window11 23H2 22635.2486
 - Python Version [e.g. 3.5, 3.6]
 - Conda Version [e.g. 4.5.12]
 - Commit ID [e.g. e83819f]
 - 
**Additional context**
Loading...
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\cui19\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "d:\faceswap\lib\gui\display.py", line 169, in _update_displaybook
    self._command_display(command)
  File "d:\faceswap\lib\gui\display.py", line 99, in _command_display
    build_tabs()
  File "d:\faceswap\lib\gui\display.py", line 123, in _train_tabs
    GraphDisplay(self, "graph", helptext, 5000)
  File "d:\faceswap\lib\gui\display_command.py", line 177, in __init__
    super().__init__(parent, tab_name, helptext, wait_time, command)
  File "d:\faceswap\lib\gui\display_page.py", line 172, in __init__
    DisplayPage.__init__(self, parent, tab_name, helptext)
  File "d:\faceswap\lib\gui\display_page.py", line 25, in __init__
    ttk.Frame.__init__(self, parent)
  File "C:\Users\cui19\MiniConda3\envs\faceswap\lib\tkinter\ttk.py", line 735, in __init__
    Widget.__init__(self, master, "ttk::frame", kw)
  File "C:\Users\cui19\MiniConda3\envs\faceswap\lib\tkinter\ttk.py", line 552, in __init__
    tkinter.Widget.__init__(self, master, widgetname, kw=kw)
  File "C:\Users\cui19\MiniConda3\envs\faceswap\lib\tkinter\__init__.py", line 2601, in __init__
    self.tk.call(
_tkinter.TclError: window name "!graphdisplay2" already exists in parent
Setting Faceswap backend to NVIDIA
10/21/2023 23:44:33 INFO     Log level set to: INFO
10/21/2023 23:44:35 INFO     Model A Directory: 'C:\Users\cui19\Downloads\video' (564 images)
10/21/2023 23:44:35 INFO     Model B Directory: 'C:\Users\cui19\Downloads\video1' (193 images)
10/21/2023 23:44:35 WARNING  At least one of your input folders contains fewer than 250 images. Results are likely to be poor.
10/21/2023 23:44:35 WARNING  You need to provide a significant number of images to successfully train a Neural Network. Aim for between 500 - 5000 images per side.
10/21/2023 23:44:35 INFO     Training data directory: C:\Users\cui19\Downloads\model
10/21/2023 23:44:35 INFO     ===================================================
10/21/2023 23:44:35 INFO       Starting
10/21/2023 23:44:35 INFO     ===================================================
10/21/2023 23:44:35 INFO     Loading data, this may take a while...
10/21/2023 23:44:35 INFO     Loading Model from Original plugin...
10/21/2023 23:44:35 INFO     No existing state file found. Generating.
10/21/2023 23:44:35 INFO     Storing Mixed Precision compatible layers. Please ignore any following warnings about using mixed precision.
10/21/2023 23:44:36 WARNING  Mixed precision compatibility check (mixed_float16): WARNING
The dtype policy mixed_float16 may run slowly because this machine does not have a GPU. Only Nvidia GPUs with compute capability of at least 7.0 run quickly with mixed_float16.
If you will use compatible GPU(s) not attached to this host, e.g. by running a multi-worker model, you can ignore this warning. This message will only be logged once
10/21/2023 23:44:37 INFO     Loading Trainer from Original plugin...

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by Cashew-wood** [comment]
Need to manually install cuda

**Comment by sebastianliu** [comment]
> Need to manually install cuda

May I know what's your means of manually install cuda? I have the same issue with you

**Comment by torzdf** [comment]
Manually installing Cuda is rarely the correct course of action.... Most likely this issue is caused by system conflicts.

See here:
https://forum.faceswap.dev/app.php/faqpage?sid=7fc24223c108f5c54472b7a1db812bec#f1r1


And if it doesn't solve your issue, then see here for the information that needs to be provided when reporting an issue:
https://forum.faceswap.dev/app.php/rules#rule-4a
https://forum.faceswap.dev/app.php/rules#rule-4b

**Comment by ericosmic** [comment]
I met same question, training doesn't make use of gpu existed.  Have you found the answer.

**Comment by E0011012** [comment]
> I met same question, training doesn't make use of existing gpu. I;m sure my server has installed cuda correctly.

`tensorflow 2.10.0` need `cuda 11.2`, `cudnn 8.7`
