### ISSUE TITLE
BLURRED VIDEO AFTER TRAINED

### ISSUE THREAD

**Issue by gjin10969** [deepfakes/faceswap#1357]
HOW TO FIX THIS BLURRED VIDEO I HAVE 2 MINS VIDEO AND 1 HOUR TRAINED MODEL
THIS IS THE RESULT I USE 

HERE ARE THE CODE:

!python faceswap.py train -A /content/faceswap/A -B /content/faceswap/B -m /content/faceswap/Model/

!python faceswap.py convert -i /content/faceswap/B.mp4 -o /content/faceswap/converted/ -m /content/faceswap/Model/ -w ffmpeg
RESULT:
![image](https://github.com/deepfakes/faceswap/assets/113190973/a3b8b437-4d44-41c1-8b7c-539b68b7f771)

**Comment by torzdf** [comment]
> *Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*
