### ISSUE TITLE
Bounding boxes coordinates

### ISSUE THREAD

**Issue by SOBAN50** [deepfakes/faceswap#1361]
It has been 2 weeks I have been working on it but cannot find the solution.

I want the bounding boxes on the original image, of the result that is produced by the "Extract" process of faceswap code.

"Extract" writes the faces extracted from the input image(s). I just want the coordinates from which this face is extracted (from original image).

If you could help me. I would be very grateful and would also help other people searching for the same problem.
Thank you.

**Comment by torzdf** [comment]
The bounding box is stored in the alignments file and is populated from here:
https://github.com/deepfakes/faceswap/blob/2a3845152b9db9bf6298c58529b761f715502604/lib/align/detected_face.py#L84
