### ISSUE TITLE
DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead

### ISSUE THREAD

**Issue by BaseMax** [deepfakes/faceswap#1362]
### C:\Users\MAX\Projects\faceswap>python faceswap.py gui

```
C:\Users\MAX\Projects\faceswap\faceswap.py:10: DeprecationWarning: 'locale.getdefaultlocale' is deprecated and slated for removal in Python 3.15. Use setlocale(), getencoding() and getlocale() instead.
  os.environ["LANG"], _ = locale.getdefaultlocale()
```

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

**To Reproduce**
1. Install Python 
2. Git clone the repository
3. Cd into the project
4. Run `python faceswap.py gui`
5. See error

**Expected behavior**

**Screenshots**

![image](https://github.com/deepfakes/faceswap/assets/2658040/81c9316f-ff43-4509-818a-ef989ea7e65f)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Python Version  3.12.1
 - Pip Version 23.3.2

**Comment by torzdf** [comment]
This is just a depracation warning. There is no issue here.
