### ISSUE TITLE
There are model on project?

### ISSUE THREAD

**Issue by DaeseungLee** [deepfakes/faceswap#1364]
Hello!

Is there a pretrained model in project
if then, Can I use it for commercial purpose?

Thanks!

**Comment by torzdf** [comment]
No there is not. Faceswap models can only be trained on 2 specific identities so providing pre-trained models would be of limited use.

It is fine to use Faceswap for commercial purposes (assuming you are just talking about the output). Any use of the code in a product is covered by [our license](https://github.com/deepfakes/faceswap/blob/master/LICENSE)

**Comment by DaeseungLee** [comment]
Thanks for response.

Then, Can I train model for general person face swap?
Please let me know How Can I make trained model.

Thanks!
