### ISSUE TITLE
[Announcement] Latest updates

### ISSUE THREAD

**Issue by Clorr** [deepfakes/faceswap#137]
Hi,

I merged my latest modifications in order to be able to move on on the GAN plugin.

Latest changes are:
- There is a face filter to extract/convert only one person (argument -f/--filter in extract convert, pass a filename of a jpgportrait of the person you want to filter)
- Extract is possible on all cpu cores, but the default is single core because there is still a debate on which is the best method. Also current method seems to fail on python 3.6 on Windows. Help is needed on that (argument -j/-processes in extract. provide an int)
- There is a support for `mmod_human_face_detector` which detects more faces in various angles but maybe slow if dlib is not compiled with CUDA support (argument -D/--detector in extract and convert. value is cnn to enable mmod)

Feel free to report bugs and features as it is done now. Install problem should ideally go in "https://github.com/deepfakes/faceswap-playground" and model realted discussion in "https://github.com/deepfakes/faceswap-model"

For those who follow reddit, please report here the new scripts or script updates because I can't follow everything ;-)

**Edit:** GAN is also merged ;-)

**Comment by IUsedToBeAPygmy** [comment]
How well does the face filter perform?
I mean, I'd expect the facefilter to not be able to recognize the same face all the time because it's only using one reference picture..?

oh and for those who follow reddit, please visit /r/deepfaketechtalk :)

**Comment by Clorr** [comment]
Ah thanks for the link, I was tired of looking /r/deepfakes ...

for the face filter, it is the one from https://github.com/ageitgey/face_recognition . It is quite good for most common poses, but has limits with very weird poses

**Comment by modelsex** [comment]
Which  dlib version is compiled with CUDA? Now I using dlib-19.9.  Only extract 38 pictures in 24 minutes. 
My GTX1080 GPU log:
GPU Core Clock [MHz] : 164.5
Memory Used [MB]      :  438
GPU Load [%]               :  13

GPU in low use, is there any solution can fix this? Thanks.

**Comment by Clorr** [comment]
You have to compile it manually AFAIK. CPU version is really slow, yes...

**Comment by modelsex** [comment]
Thanks, use dlib git fixed. 1 suggestion for all Windows user: better not switch Command window while extracting.

**Comment by LordVulkan** [comment]
> ZeroCool22 commented 11 hours ago •  edited 
> @modelsex Can you help me to install this REPO via TEAMVIEWER?
> I'm not being lazy, really tried (#134) and it end in a totally disaster, after that nothing related with Python was working, i must uninstall/reinstall everything to get the original code working again, (with original code i mean the first one posted on the DeepFakes READDIT) even the FAKEAPP wasn't working.
> 
> So if could give me a hand would be nice.
> 
> PC SPECS: Windows 10, 7700k, 32gb RAM, SMi 1080TI, SSD.

Try with Linux, Windows gave me a lot of problems.
