### ISSUE TITLE
Images found:        439 Faces detected:      0

### ISSUE THREAD

**Issue by Solenyalyl** [deepfakes/faceswap#1370]
the extract and train part is fine,but when I use 
python faceswap.py convert -al donald_trump_alignments_20240129_140240.fsa -i faces -o converted -m trump_cage_model -M vgg-clear -w ffmpeg -ref donald_trump.mp4 -fr 10-50
it returns 
01/29/2024 17:49:54 INFO     Images found:        439
01/29/2024 17:49:54 INFO     Faces detected:      0
01/29/2024 17:49:54 INFO     -------------------------
01/29/2024 17:49:54 INFO     Process Succesfully Completed. Shutting Down...
and no new video output,
can someone help me?

**Comment by torzdf** [comment]
This is not a support forum.

Please use our [Discord](https://discord.gg/FC54sYg) or our [Forum](https://faceswap.dev/forum)
