### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'type'

### ISSUE THREAD

**Issue by zhidaoai** [deepfakes/faceswap#1371]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**
python setup.py
/data/xu/faceswap/setup.py:18: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import parse_requirements
Traceback (most recent call last):
  File "/data/xu/faceswap/setup.py", line 20, in <module>
    from lib.logger import log_setup
  File "/data/xu/faceswap/lib/logger.py", line 425, in <module>
    def _stream_handler(loglevel: int, is_gui: bool) -> logging.StreamHandler | TqdmHandler:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos/Linux]
 - Python Version [e.g. 3.9.16]
 - 
**Additional context**

**Crash Report**
The crash report generated in the root of your Faceswap folder

**Comment by zhidaoai** [comment]
python faceswap.py gui
First time configuration. Please select the required backend
1: CPU, 2: DIRECTML, 3: NVIDIA, 4: APPLE SILICON, 5: ROCM: 3
Faceswap config written to: /data/xu/faceswap/config/.faceswap
Setting Faceswap backend to NVIDIA
Traceback (most recent call last):
  File "/data/xu/faceswap/faceswap.py", line 12, in <module>
    from lib.cli import args as cli_args  # pylint:disable=wrong-import-position
  File "/data/xu/faceswap/lib/cli/args.py", line 18, in <module>
    from .actions import (DirFullPaths, DirOrFileFullPaths, DirOrFilesFullPaths, FileFullPaths,
  File "/data/xu/faceswap/lib/cli/actions.py", line 49, in <module>
    class FileFullPaths(_FullPaths):
  File "/data/xufaceswap/lib/cli/actions.py", line 72, in FileFullPaths
    def __init__(self, *args, filetypes: str | None = None, **kwargs) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by zhidaoai** [comment]
No display detected. GUI mode has been disabled.

**Comment by torzdf** [comment]
Your Python version is too old. Use the installer in releases and you will not have this problem.

**Comment by zhidaoai** [comment]
install python=3.10.13, but 
```
python faceswap.py gui
Setting Faceswap backend to NVIDIA
02/01/2024 09:34:35 INFO     Log level set to: INFO
02/01/2024 09:34:37 ERROR    No display detected. GUI mode has been disabled.
```

**Comment by torzdf** [comment]
Use the installer.

We do not support custom install paths.

**Comment by zhidaoai** [comment]
GPU single , nvidia T4, Linux/Centos service

**Comment by torzdf** [comment]
This makes no difference to me.

Either you know what you are doing with Python and can troubleshoot issues yourself, in which case by all means, install how you see fit.

Otherwise, you do not know how to troubleshoot these issues yourself and need help. In these instances we will **only** provide support if you use our installers.

It is too much of a burden to support anyone's and everyone's esoteric custom installation methods.

There is an installer for Linux at the link I posted above.

**Comment by zhidaoai** [comment]
i tried the `bash ./faceswap_setup_x64.sh`
bug got 
```
ERROR   This install script should not be run with root privileges. Please
ERROR   run as a normal user.
```
