### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhidaoai** [deepfakes/faceswap#1372]
python 3.10.13
CentOs/Linux 
Nvidia single V100
ERROR   This install script should not be run with root privileges. Please
ERROR   run as a normal user.
by using [forum](https://forum.faceswap.dev/viewtopic.php?t=68)

**Comment by torzdf** [comment]
The error and the solution is right in your message :/

If you want more support use our [Discord](https://discord.gg/FC54sYg) or our [Forum](https://faceswap.dev/forum). This is not the place for support on trivial issues.
