### ISSUE TITLE
just installed new graphic card and it stopped working

### ISSUE THREAD

**Issue by eassa** [deepfakes/faceswap#1381]
it worked on my last graphic card "rtx 2027" and i just bought  this one and exchanged it  "ASUS TUF Gaming Radeon™ RX 7900 XT OC Edition 20GB GDDR6"
and it stopped working .
it returns this error :

> C:\Users\Nassar>"C:\Users\Nassar\Miniconda3\scripts\activate.bat"   && conda activate "faceswap"   && python "C:\Users\Nassar\faceswap/faceswap.py" gui
> Setting Faceswap backend to NVIDIA
> Traceback (most recent call last):
>   File "C:\Users\Nassar\faceswap\lib\gpu_stats\nvidia.py", line 47, in _initialize
>     pynvml.nvmlInit()
>   File "C:\Users\Nassar\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 1945, in nvmlInit
>     nvmlInitWithFlags(0)
>   File "C:\Users\Nassar\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 1935, in nvmlInitWithFlags
>     _nvmlCheckReturn(ret)
>   File "C:\Users\Nassar\MiniConda3\envs\faceswap\lib\site-packages\pynvml.py", line 897, in _nvmlCheckReturn
>     raise NVMLError(ret)
> pynvml.NVMLError_NoPermission: Insufficient Permissions
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\Nassar\faceswap\faceswap.py", line 12, in <module>
>     from lib.cli import args as cli_args  # pylint:disable=wrong-import-position
>   File "C:\Users\Nassar\faceswap\lib\cli\args.py", line 23, in <module>
>     _GPUS = GPUStats().cli_devices
>   File "C:\Users\Nassar\faceswap\lib\gpu_stats\_base.py", line 95, in __init__
>     self._initialize()
>   File "C:\Users\Nassar\faceswap\lib\gpu_stats\nvidia.py", line 55, in _initialize
>     raise FaceswapError(msg) from err
> lib.utils.FaceswapError: There was an error reading from the Nvidia Machine Learning Library. The most likely cause is incorrectly installed drivers. If this is the case, Please remove and reinstall your Nvidia drivers before reporting. Original Error: Insufficient Permissions

Note: i am using windows 10

**Comment by torzdf** [comment]
You have installed the Nvidia version of faceswap, but you have an AMD GPU.

Follow these steps to remove faceswap + libs:
https://forum.faceswap.dev/app.php/faqpage?sid=47859b5acaac6c66cf49a85c70d6b1bd#f1r1

Follow these instructions to install the AMD version:
https://forum.faceswap.dev/viewtopic.php?t=20
