### ISSUE TITLE
Alignment File Requirement During Model Training

### ISSUE THREAD

**Issue by Miuneyh** [deepfakes/faceswap#1393]
Hello everyone,

I have a question regarding the training process of models. Specifically, do we need to specify an alignment file during model training? If it is required, where should it be placed or specified? Is there a default location where the training script expects to find the alignment file?

I appreciate any guidance or documentation references you can provide on this topic.

Thank you!

**Comment by torzdf** [comment]
An alignment file is not required. Full guides available at:

- Extraction Guide : https://forum.faceswap.dev/viewtopic.php?f=25&t=27
- Training Guide: https://forum.faceswap.dev/viewtopic.php?f=27&t=146
- Convert Guide: https://forum.faceswap.dev/viewtopic.php?f=24&t=1083
