### ISSUE TITLE
Future Development Plans for FaceSwap

### ISSUE THREAD

**Issue by ruidazeng** [deepfakes/faceswap#1407]
Just wondering, are there any new features or updates or new releases coming soon, or is the project wrapping up and going into the archives soon?

**Comment by torzdf** [comment]
There will be, but unfortunately I am  short on time at the moment. I have a lot on the roadmap, but also have bills to pay

**Comment by w07root** [comment]
> There will be, but unfortunately I am short on time at the moment. I have a lot on the roadmap, but also have bills to pay

This project is really amazing. I hope it can be optimized and a new version released as soon as possible
