### ISSUE TITLE
During convert, 'ConvertImage' object has no attribute 'check_skip'

### ISSUE THREAD

**Issue by dabeeeenster** [deepfakes/faceswap#143]
This appears to have just cropped up - if I revert to code from 5/Feb it works fine. Trying to convert some images throws the error

Failed to convert image: C:\Users\solidstate\Documents\deepfakes\face-swap\data\trump\831967292.jpg. Reason: 'ConvertImage' object has no attribute 'check_skip'

## Expected behavior

The images were converted

## Actual behavior

The error message above was shown and nothing was converted

## Steps to reproduce

Train Model
Run ```python .\faceswap.py  convert -i ..\..\Desktop\convert -o ..\..\Desktop\converted\ -m ..\deepfakes\face-swap\models\ -s```

## Other relevant information

Windows, Python 3.6.4 GPU commit hash 6bea4c2b276f105624e18793082734f31c683743

**Comment by gdunstone** [comment]
This should be fixed in this commit https://github.com/deepfakes/faceswap/commit/f3bb0bba072f0bfc4c11480cd6f0728aaf1e3db6

Thanks for the bug report
