### ISSUE TITLE
How are people reaching high quality swaps?

### ISSUE THREAD

**Issue by andykdy** [deepfakes/faceswap#144]
I just wanted to open a discussion because I've been having pretty bad results.
The applied mask often has different colouration, is very low resolution, and is susceptible to alignment problems.

I've seen examples with Nic Cage and Henry Cavill that seem to blend perfectly and maintain the original resolution of the image. 

Do people have tips and tricks they can share?

**Comment by Tvde1** [comment]
Lots of training data and lots of hours of training (weeks)

**Comment by GSonderling** [comment]
Basically what @Tvde1  said. In addition, you could try renting some cloud services for the job or, and I think this is a better solution, obtain existing model from someone. However I'm not sure how much data would fit if it wasn't the exact same person.

**Comment by k3erg** [comment]
Is there a way to adapt chroma/color in the trained model, or would you have to assimilate the color of the training data before training?

**Comment by Clorr** [comment]
Please open this in faceswap-playground. Thanks

**Comment by kaz63** [comment]
Is it not possible to extend the scope of application to the range of hair other than parts of the face?
