### ISSUE TITLE
/r/deepfakes banned and moved

### ISSUE THREAD

**Issue by x0x7** [deepfakes/faceswap#145]
Your repository references the Reddit /r/deepfakes subreddit. It is now closed. The community has moved to https://voat.co/v/deepfake

**Comment by IUsedToBeAPygmy** [comment]
discussing the code and technology without any NSFW connotation can still be done in the /r/deepfaketechtalk subreddit.

https://www.reddit.com/r/deepfaketechtalk/

**Comment by modelsex** [comment]
hahah, no surprise.

**Comment by flosth** [comment]
@IUsedToBeAPygmy 
/r/deepfaketechtalk is dead though. If you want to discuss tech do it at /r/fakeapp or /r/sfwdeepfakes, which are still up.

**Comment by Ianmcmill** [comment]
IMO github should be/stay the common way to do techtalk. /r/deepfake%%% is mostly frequented by end users not interested in tech but rather hard facts. If you know what I mean. Also not a big loss. Just my 5 cents.
