### ISSUE TITLE
do i have to rename the given training data to src? 

### ISSUE THREAD

**Issue by ccs1605** [deepfakes/faceswap#15]
if not, where to put the unzip data into directory. sorry for asking newby questions. 
i am using pycharm and docker. thanks

**Comment by Ganonmaster** [comment]
Could you please describe the problem you are encountering in more detail? What training data? What are you trying to accomplish? What have you tried?

**Comment by deepfakes** [comment]
Hi,

**Short answer**
(I assume you have all dependencies installed)
Put the sample data (`data ` + `models`) in the same folder as the code. 
Create a `output` folder
Run `convert_trump_cage.py`, and _voila!_
The converted photos will be in the output folder
