### ISSUE TITLE
GPU out of memory while extracting with CNN face detector.

### ISSUE THREAD

**Issue by LordVulkan** [deepfakes/faceswap#152]
## Expected behavior

Same behaviour as using the CPU.

## Actual behavior

After a few images:

`Failed to extract from image: images-dir/32341.jpg. Reason: Error while calling cudaMalloc(&data, n) in file dlib-dir/dnn/cuda_data_ptr.cpp:28. code: 2, reason: out of memory`

## Steps to reproduce

Using dlib with CUDA support:
Extract a folder with a few hundred images using CNN detector.

## Other relevant information

- **Operating system and version:** x86_64 GNU/Linux
- **Python version:** 3.6.4
- **Faceswap version:** 20753a64b76a156aea17724348269d60dd525f87
- **Faceswap method:** GPU
- **Specs:** Intel i5 6600 8GB RAM GTX 960 4GB

**Comment by IUsedToBeAPygmy** [comment]
What are the width and height and the filesize of 32341.jpg ?

**Comment by LordVulkan** [comment]
1080x1262

I have tried to remove it and the same happens with other images of similar size.

Dammit, I suppose it is a problem of face_recognition, but 4GB should be enough for those images.

**Comment by Clorr** [comment]
The problem does not come from `face_recognition`, which uses dlib methods. The [dlib's author also has no other advice than reducing image size](https://github.com/davisking/dlib/issues/790)

**Comment by IUsedToBeAPygmy** [comment]
just crop the face and resize to 512-is. It gets scaled to 256x256 anyway.

**Comment by LordVulkan** [comment]
I'm trying to find the max size I can safety use and resize all images bigger than that automatically.

**Comment by IUsedToBeAPygmy** [comment]
Use ImageResizer. Select all images, right click -> Resize pictures.
Then select Custom : Scale to 900x900 pixels.

It'll make sure the max(width, height) is 900 pixels (keeping the aspect ratio)

http://www.bricelam.net/ImageResizer/

**Comment by Clorr** [comment]
You can do this but keep in mind you will have the same problem on the convert command (unless we do save alignments, see #135 )

**Comment by LordVulkan** [comment]
Thanks.

For those interested, in Linux install ImageMagick and then:

for file in *.png *.jpg *.jpeg; do convert $file -resize 1000\>x1000\> $file; done

That will downscale all images if either their high or width is bigger than 1000 while keeping its aspect ratio.
