### ISSUE TITLE
Problems with GPU training.

### ISSUE THREAD

**Issue by Tvde1** [deepfakes/faceswap#154]
I have a <2 gb gpu (960M) and setting the trainer to `LowMem` did not help and combining it with a batch size of 16, 8, 4 or 2 did not improve much.

I read that you should change `ENCODER_DIM`. How do I do this?

I am running it on the latest ubuntu version. CPU training works.

Also, can I resume training a model after I exit the application?

**Comment by andykdy** [comment]
Actually, the LowMem model is just the Original Model with the ENCODER_DIM set to 512 instead of 1024.
I think you can try going down all the way to 256... But at that point I would rather invest time on cloud computing instead.

**Comment by Clorr** [comment]
To answer your questions:
- ENCODER_DIM is located inside plugins/Model_LowMem.py
- yes you can resume

But as @andykdy said, with less than 2GB it may be hard/impossible to make it run. In some attempt, you can try the patch in #140
