### ISSUE TITLE
Suggestion: Google Dataflow / ML support

### ISSUE THREAD

**Issue by greenboxal** [deepfakes/faceswap#156]
Do anyone plan to support that?

I was studying it and seems like it would very cheap to achieve high quality output.

Basically I'm thinking on doing the following:

**Extract:**
A dataflow pipeline that:

* Extracts all frames into PNGs with ffmpeg
* Extracts audio channels with ffmpeg
* Extract and filters faces from the frames, if requested (you don't need to do this if you're not going to train with a frameset)
* Cache faces from each frame
* Everything is saved to GCS

**Train:**
A cloud ML pipeline that will run the Keras models with distributed Tensorflow.

**Convert:**
A dataflow pipeline that:

* Applies one or more models to all faces of a frameset.
* Combines all frames and audio back into a video
* Saves output to GCS

Any opinions here? I'll start working on it.

**Comment by Clorr** [comment]
Feel free to propose a PR when you have code to push
