### ISSUE TITLE
Masks dissappears as training progresses

### ISSUE THREAD

**Issue by slundell** [deepfakes/faceswap#158]
## Expected behavior
The masks shown when training using GAN is expected to be refined during training and correspond to the shown areas of the face. 

## Actual behavior
The masks seems to start as flat 50% and then quickly progresses to something that resambles a face. As training progresses they are more and more whitened out, to become 100% transperant.

## Steps to reproduce
Use GAN, train a few batches 

## Other relevant information
From-face has ~900 samples
To-face has ~3000 samples, many with hands etc obstructing the face.
Ubuntu 16.04 Python 3.5.2
Version: 20753a6  (head atm)
1x1060 3Gb 1x1060 6Gb

**Comment by shaoanlu** [comment]
It's normal. Masks will be learnt  once the L1 reconstruction loss is low enough. i.e., generated faces before masking should be good enough so that masking make sense.

**Comment by slundell** [comment]
OK. I think I understand :)
What is the general way to handle obstructions? Should these samples be removed from the training sets? If so, can it generate frames where the face is obstructed in the final target?
