### ISSUE TITLE
Adding 1adrianb/face-alignment to project

### ISSUE THREAD

**Issue by Apollo122** [deepfakes/faceswap#16]
As deepfakes suggested on Reddit Face alignment scripts based on 1adrianb/face-alignment works better.
It would be great if its added to project and pipeline. It maybe automatic but as deepfakes points out there might be  bad aligned images needed to be deleted so maybe readme can be updated about how to use the script manually.

https://www.reddit.com/r/deepfakes/comments/7lae4c/face_alignment_scripts_based_on/
https://github.com/1adrianb/face-alignment

**Comment by Clorr** [comment]
Yes, I have seen that and it looks promising. Do you want to take a look at it ?

There is also a Gist with a sample:
https://gist.github.com/anonymous/5832a6fffb8309ac851a29874c3dbb7b

**Comment by Clorr** [comment]
Btw, note that face recognition seems to be better with the `face_recognition` module integrated here. So the `dlib.get_frontal_face_detector()` whould be replaced where relevant

**Comment by Clorr** [comment]
I pushed a first draft on my repo, inside the `align` folder, it is the GIST code reworked to separate program logic from processing logic. It is not intended to work, but if you want to work on it, start please from there.

CC @Ganonmaster

**Comment by Apollo122** [comment]
@clor would love to but I can't nowadays. coming months I will be helping other issues and features though

**Comment by Clorr** [comment]
A better merge function is also provided

https://gist.github.com/anonymous/8f468972d6286f403318c94bc6dbe382

**Comment by Ganonmaster** [comment]
The face alignment script seems to rely on PyTorch, which is not supported on Windows at this time. This could be blocking if we want it to be accessible for non-tech users.

**Comment by Clorr** [comment]
Yes and it is also heavy as hell....

I'm still investigating because if it used just for faces landmarks, `face_recognition` does it pretty well also...

**Comment by Clorr** [comment]
Closing this issue because the referenced scripted has evolved and should not be integrated as is in the project.

I'll reopen an issue to handle the new script when I'll be more available on the project

**Comment by 1adrianb** [comment]
Hey guys @Clorr @Ganonmaster  just accidentally found this :) I have recently addressed some accuracy issues and now the code should be on par (or very close) with the results reported in the paper.

Regarding support on windows, while official support will be added soon, there is already a conda package available that works fine on windows: https://anaconda.org/peterjc123/pytorch

With respect to the speed, the slowest bit is dlib face detector, however, one can replace it with almost any other face detection method.

**Comment by Clorr** [comment]
Hi @1adrianb , and welcome around!

Thanks for the info. Meanwhile we switched to `face_detection` lib since we are just using 2D landmarks and that `face_detection` was already used for face extraction.

If you think we can take advantage of any part of your work, feel free to suggest or even make a PR, we will take care of it with great pleasure!
