### ISSUE TITLE
Not installed under Windows

### ISSUE THREAD

**Issue by TomskDiver** [deepfakes/faceswap#164]
I try install last version https://github.com/deepfakes/faceswap/tree/20753a64b76a156aea17724348269d60dd525f87
Follow instructions in INSTALL.md
It says _pip install -r requirements.txt_ but it's FAIL! tensorflow==1.4.1 not exist for Windows in pypi. See https://pypi.python.org/pypi/tensorflow/1.4.1
May be use 1.4.0? In 1.4.1 have only one fix: LinearClassifier fix for CloudML Engine. In 1.4.1 release notes write: NOTE: There is no Windows binary for 1.4.1. The only difference to 1.4.0 is the CloudML Engine fix, and since CloudML Engine only supports Linux, Windows is unaffected.

## Steps to reproduce

Try install on Windows.

## Other relevant information

- **Operating system and version:** Windows 10 x64
- **Python version:** 3.6.4
- **Faceswap version:** commit hash 20753a64b76a156aea17724348269d60dd525f87

**Comment by modelsex** [comment]
Just <pip install tensorflow>, working fine on my windows env with latest version.

**Comment by iperov** [comment]
I installed faceswap even on python embeddable lol, and rebuild dlib with cuda. But spent 1 day.

**Comment by TomskDiver** [comment]
@Clorr why closed if not fixed?

**Comment by iperov** [comment]
@TomskDiver
try tensorflow==1.5.0 for 3.6
https://github.com/deepfakes/faceswap/pull/183

**Comment by TomskDiver** [comment]
I have already installed faceswap for a long time. I just do not understand why the issue was closed and not repaired.

**Comment by Clorr** [comment]
1. Installation problems are not issues.
2. They should go in https://github.com/deepfakes/faceswap-playground
3. There was 2 answers and no further activity in 3 days
