### ISSUE TITLE
is this CNN extract normal ?

### ISSUE THREAD

**Issue by iperov** [deepfakes/faceswap#165]
![2018-02-09_15-16-51](https://user-images.githubusercontent.com/8076202/36025734-8d648192-0dad-11e8-88b7-aef07dc87999.gif)

## Expected behavior

normal aligned ?

## Actual behavior

not aligned ?

## Steps to reproduce

[bugged footage.zip](https://github.com/deepfakes/faceswap/files/1710891/bugged.footage.zip)
cnn extract

## Other relevant information

- **Operating system and version:** Windows 7
- **Python version:** 3.5.4
- **Faceswap version:** 20753a64b76a156aea17724348269d60dd525f87
- **Faceswap method:** GPU

**Comment by LordVulkan** [comment]
Same issue here, many images are not properly aligned.

**Comment by dfaker** [comment]
Seems like a relatively good attempt seeing as the face is melting through bars /s.

Realistically there's very strong side lighting which neither the face defector nor landmark detectors will have an easy time with, the whole thing is very much edge cases for the modules that this project has the least control over.
