### ISSUE TITLE
Training start from scratch. Files of existing trained model was removed.

### ISSUE THREAD

**Issue by qzmenko** [deepfakes/faceswap#166]
For two days everything worked well for me. I already several times stopped and continued training. But today I tried to continue training using already existing model and it couldn't be loaded. After that, training started immediately from scratch, overwriting the already trained model.

I think this is not the correct behavior and the training should be terminated instead of overwriting the model by creating new files.

Or at least a model backup should be created to avoid such embarrassment.
```
...
Loading data, this may take a while...
Using live preview
Loading Model from Model_LowMem plugin...
Using TensorFlow backend.
2018-02-10 00:48:13.997893: E tensorflow/core/common_runtime/direct_session.cc:168] Internal: failed initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_OUT_OF_MEMORY; total memory reported: 2085093376
Failed loading existing training data.
Failed to create session.
Loading Trainer from Model_LowMem plugin...
...
```

**Comment by IUsedToBeAPygmy** [comment]
Have you by any chance gotten the latest version of the code and tried to continue training a previous model with that?

I found out the latest code uses a different "face coverage" factor (160) than previous versions (220) which invalidates previous training data...

I think this happened by accident; if you have a backup of your previous training data you'll probably be able to continue once the face-coverage value is set back to the previous value of 220.

**Comment by qzmenko** [comment]
No, I've only been training the model with the latest version. I think the problem is different from #168 and #159.

**Comment by Clorr** [comment]
Please reopen in faceswap-playground if still relevant. Thanks
