### ISSUE TITLE
[Clorr please check this out!] change b3ae613 modified the face coverage factor, invalidating old training data. I think this was a mistake???

### ISSUE THREAD

**Issue by IUsedToBeAPygmy** [deepfakes/faceswap#168]
Just in case I'm reporting it as a new issue.

In this change:

https://github.com/deepfakes/faceswap/commit/b3ae6130ed4714852211a6e8cb56de66450da83c#diff-cd6853ac48b3d61ae96f466bcc2c393eR41

the face-coverage value was changed from 220 to 160, invalidating previous training data resulting in zoomed-in face data (in some cases causing parts of the face to go out of bounds).

Please revert the face coverage value to 220.

On a side-note, this value probably should not be stored/used in the training-loop; it could be included in the extraction phase saving performance and image quality.

**Comment by Deadfishzzway** [comment]
I change the value back to 220. In preview I can see entire face being changed. However after convert, only the middle chunk of faces were changed (eyebrow to chin)(I used lowmem trainer and masked converter). Is that also related to some size change? Can I alter the mask size?

**Comment by Clorr** [comment]
Hi, Original face coverage was 160. Faceswap-GAN has decided to use 220, and it seemed to be a good idea to just change that value to have a better coverage. However someone came and posted the #96 issue. So I thought it was better not to play with this on my own and that it was better to stick to the original parameters as I prefer having plugins that reflect the authors intention.

However as this is an int, it is totally possible to do an argument from this...
