### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'windowpath' and 'str'

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap#170]
Error as title found when running --trainer GAN with -p preview window.

## Expected behavior

*it should continue run after the first epoch

## Actual behavior

*it run the first epoch and stop with this error message after the first preview window comes out

## Steps to reproduce

*python faraway.py train --trainer GAN -p

## Other relevant information

- **Operating system and version:** Windows, 
- **Python version:** 3.6.4
- **Faceswap version:** latest one 
- **Faceswap method:** CPU
- ...

**Comment by ruah1984** [comment]
Not sure is GAN training not include the preview window ?

**Comment by iperov** [comment]
@ruah1984 gan include preview

**Comment by iperov** [comment]
what is faraway.py ?

**Comment by ruah1984** [comment]
Sorry , is faceswap.py, the auto correction in iphone suck . Do you know the error message ?

**Comment by iperov** [comment]
post full error message with call stack

**Comment by ruah1984** [comment]
How to post extract full error message ? It only show the error message as title only ?

**Comment by iperov** [comment]
u launch it from .bat file ?
then add pause
and copy error message.

**Comment by ruah1984** [comment]
No fakeapps .bat file, is from the repo. I now checking if normal training or low memory training will having the same issue or not.

**Comment by iperov** [comment]
check my end-user windows build 155 https://github.com/deepfakes/faceswap-playground/issues/39

**Comment by ruah1984** [comment]
Thanks, I am New for python, but I hope to know if the issue is related to "str", and what does it mean, any other found the same issue. The link you share is application is it?

**Comment by ruah1984** [comment]
solve, after update using the latest repo.
