### ISSUE TITLE
Training loop design

### ISSUE THREAD

**Issue by GSonderling** [deepfakes/faceswap#172]
I have question about the way the training works. Now, if it is actually a bug and it's not supposed to do that, then just tell me and I will close this.

https://github.com/deepfakes/faceswap/blob/20753a64b76a156aea17724348269d60dd525f87/scripts/train.py#L133-L161

The loop runs for predetermined number of epochs. And the loop itself is in try/except block. So far this makes sense.

But what happens after the loop finishes?  

The process just hangs, no exit, no message nothing. Because it waits for:

https://github.com/deepfakes/faceswap/blob/20753a64b76a156aea17724348269d60dd525f87/scripts/train.py#L97-L113

Until either of these is fulfilled the process hangs, leaving user guessing what is going on.

Now again, this might be a bug. But otherwise it's just weird design. Is there any special reason for it?

**Comment by IUsedToBeAPygmy** [comment]
I think the idea is that it's running indefinitely (1000000 epochs is an absurdly high number) and only quits when the user presses return.

A "while return not pressed" loop would have been more clear. On the other hand, if your model hasn't produced good results after 1000000 epochs, it never will :)

**Comment by Clorr** [comment]
I think the same as @IUsedToBeAPygmy , but anyhow, thanks @GSonderling for providing a PR
