### ISSUE TITLE
Hull_mask not functional?

### ISSUE THREAD

**Issue by Deadfishzzway** [deepfakes/faceswap#173]
Hi, I tried to use different mask type when converting, and my default (facehullandrect) and rect Mask yield similar results, while facehull don't seem to apply any change at all

I think I might find the problem in Covert_Masked.py
in line 18   
self.mask_type = mask_type.lower() # Choose in 'FaceHullAndRect','FaceHull','Rect'
I suppose it read in -M option in lower case.
But when it tried to use the self.mask_type value It uses  **'faceHull'**which isn't lower case but I m not sure if this caused the problem.
line 75-83
        
        hull_mask = numpy.zeros(image.shape,dtype=float)
        if 'hull' in self.mask_type:
            hull = cv2.convexHull( numpy.array( face_detected.landmarksAsXY() ).reshape((-1,2)).astype(int) ).flatten().reshape( (-1,2) )
            cv2.fillConvexPoly( hull_mask,hull,(1,1,1) )

        if self.mask_type == 'rect':
            image_mask = face_mask
        elif self.mask_type == 'faceHull':
            image_mask = hull_mask
-**Operating system and version:** Windows 10 64
Python version:3.6.4, 
Faceswap version: 20753a64b76a156aea17724348269d60dd525f87
Faceswap method: GPU
- ...

**Comment by dfaker** [comment]
You're quite right: #181
