### ISSUE TITLE
Extracting no/few faces

### ISSUE THREAD

**Issue by NewWine1** [deepfakes/faceswap#174]
Simple problem of detecting few faces and the faces I do extract are not the ones I need(obscure figures in the background). Is there a specific size i should crop/scale the images?

**Comment by Clorr** [comment]
Are the faces you want to extract rotated or side views?

**Comment by NewWine1** [comment]
slight tilt. Fakeapp would extract the face but faceswap.py would not.
![out337](https://user-images.githubusercontent.com/36125909/36081197-0e5213aa-0f61-11e8-8167-8cdad0fbfc0f.png)

**Comment by Clorr** [comment]
there is an option to activate the mmod_human_face_detector which is the same than FakeApp. It is not activated by default as it is slow. Add `-D cnn` to your command line
