### ISSUE TITLE
Suggestion: Focal length of source images

### ISSUE THREAD

**Issue by Migano** [deepfakes/faceswap#182]
I have taken a look at some results and think that the focal lenght of the sources images would make a good feature to enhance the results of the face sawp. 

Extracting the focal length from the training images is not trivial and could also be achieved by means of learning like [deepfocal](http://cs.uky.edu/~scott/resources/deepfocal.pdf).

**Comment by Clorr** [comment]
Please better post this in https://github.com/deepfakes/faceswap-model
