### ISSUE TITLE
Landmarks not matching with CNN/MMOD detector

### ISSUE THREAD

**Issue by Clorr** [deepfakes/faceswap#187]
From: https://github.com/deepfakes/faceswap-playground/issues/43

Aligning faces does not work on some faces found with the `cnn` option. See below for the landmarks returned.

Can someone tell where the problem come from?

![frame10](https://user-images.githubusercontent.com/873943/36110904-9e5ff872-1024-11e8-8c03-eeb8e2c3b1c7.png)
![frame20](https://user-images.githubusercontent.com/873943/36110905-9ea28d5e-1024-11e8-8fe8-09bf4703c2cb.png)
![frame30](https://user-images.githubusercontent.com/873943/36110909-a311f06e-1024-11e8-8f86-254ee12d2506.png)

Code to reproduce (put in plugins/Extract_Align.py):
```
    def extract(self, image, face, size):
        if face.landmarks == None:
            print("Warning! landmarks not found. Switching to crop!")
            return cv2.resize(face.image, (size, size))

        # Draws landmarks for debug
        for (x, y) in face.landmarksAsXY():
            cv2.circle(image, (x, y), 1, (0, 0, 255), -1)

        alignment = get_align_mat( face )
        return self.transform( image, alignment, size, 48 )
```

**Comment by iperov** [comment]
![1](https://user-images.githubusercontent.com/8076202/36117312-92ed4bec-1052-11e8-8832-c860d2ab0fcb.gif)

need mp4 file ?

**Comment by Clorr** [comment]
There is no picture zooming, it is the extract as it is done by the code just now with the source you can find on the [original issue](https://github.com/deepfakes/faceswap-playground/issues/43)

The qustion is to know why the landmarks are incorrect here, and also what we can do to correct this.

But as you say, there may be another problem which is that the face is framed too narrow. However, I don't think it is the origin of the landmarks defect as the landmarks are calculated on the original image (in `lib/faces_detect.py`)

**Comment by LordVulkan** [comment]
This is weird:

` return [pose_predictor(face_image, face_location) for face_location in face_locations]`

The shape predictor receives as an argument the face box. According to dlib examples, it tries to get the landmark points inside that box, not the full image.

`print("Detection {}: Left: {} Top: {} Right: {} Bottom: {}".format(
            k, d.left(), d.top(), d.right(), d.bottom()))
        # Get the landmarks/parts for the face in box d.
        shape = predictor(img, d)`
http://dlib.net/face_landmark_detection.py.html

That would explain why the landmarks are wrong if the cnn model extracts a zoomed-in image.

Passing the face box to the predictor outputs the expected(and wrong) result:

![image](https://user-images.githubusercontent.com/562386/36126060-1a0aeec8-1057-11e8-82e9-39cc95bdbbf5.png)

Not passing the box too gets the landmarks right as expected:

![image](https://user-images.githubusercontent.com/562386/36126033-f662b5e6-1056-11e8-81b9-62822106f191.png)

But then the unexpected happened. Pass the hog face box to the predictor, it just ignores it.

![image](https://user-images.githubusercontent.com/562386/36126119-6965e162-1057-11e8-8ffb-f15b5e15702a.png)

**Comment by iperov** [comment]
so how to fix problems?

**Comment by iperov** [comment]
fakeapp align without zoom glitches:

![1](https://user-images.githubusercontent.com/8076202/36134212-b51fa026-109c-11e8-95dc-0ba8ef6d05b0.gif)

**Comment by iperov** [comment]
may be use https://github.com/1adrianb/face-alignment as in fakeapp ?

**Comment by iperov** [comment]
I think problem in landmarks detector, not face detector.
FaceSwap using ageitgey/face_recognition_models
fakeapp using 1adrianb/face-alignment

**Comment by Clorr** [comment]
Thank you @LordVulkan for the awesome report!

> The shape predictor receives as an argument the face box. According to dlib examples, it tries to get the landmark points inside that box, not the full image.

- I think it is intended, because if you give an image with many faces the landmarks detector would be lost I presume.
- From what you show, there is a slight difference between the box returned by hog and cnn, which I wasn't aware of. Maybe that explains also the "zooming" that @iperov reports?
- My first option would be to try to enlarge the box returned by the cnn detector and see if it solves our problem. Also we can ask @ageitgey to have a look as it would be an enhancement for all `face_recognition` users.

**Comment by LordVulkan** [comment]
I have tried with 1adrianb/face-alignment and it seems to get the right landmarks, but I don't know why it is horribly slow even with CUDA.

**Comment by Clorr** [comment]
Have you an idea on the zooming effect noticed by @iperov ? Because the 1adrianb/face-alignment repo also uses [mmod detector](https://github.com/1adrianb/face-alignment/blob/fecdd1084df5d52246d26a9eb210e3404b4f6345/face_alignment/api.py#L75)

**Comment by LordVulkan** [comment]
1adrianb also gets wrong the face box and for some reason it is a different box than the one in face_recognition. It also doesn't affect the landmarks.

Comparison of different face boxes:

Red: Extracted by face_recognition using cnn.
Green: Extracted by face-alignment using cnn.
White: Extracted with hog. Same result in both repos.

![image](https://user-images.githubusercontent.com/562386/36147468-a7d1c7de-10b8-11e8-8555-aa848721a5bc.png)

**Comment by iperov** [comment]
yeah problem in face landmarks detector.

**Comment by iperov** [comment]
face-alignment better, but cant build it for windows :((

**Comment by Clorr** [comment]
Strange that the cnn detector returns a different box. Where did you get the values for the box? Also, there is a [preprocessing of the recognized face done in 1adrianb repo](https://github.com/1adrianb/face-alignment/blob/fecdd1084df5d52246d26a9eb210e3404b4f6345/face_alignment/api.py#L171):
```
                center = torch.FloatTensor(
                    [d.right() - (d.right() - d.left()) / 2.0, d.bottom() -
                     (d.bottom() - d.top()) / 2.0])
                center[1] = center[1] - (d.bottom() - d.top()) * 0.12
                scale = (d.right() - d.left() + d.bottom() - d.top()) / 195.0

                inp = crop(image, center, scale)
                inp = torch.from_numpy(inp.transpose(
(2, 0, 1))).float().div(255.0).unsqueeze_(0)
```

However my skills are too low to understand what this does. Have you some idea?

**Comment by LordVulkan** [comment]
The face_location object is the box itself, it is a 4-tuple: (top,right,left,bottom)
face-alignment seems to be centering and resizing the face box before calculating landmarks, I will take a look at it.

Comparison of face-alignment and face_recognition landmarks:

face_recognition landmarks with cnn face box:
![image](https://user-images.githubusercontent.com/562386/36148432-55a525d8-10bc-11e8-85a2-78de595d8f11.png)

face_recognition landmarks with hog face box:
![image](https://user-images.githubusercontent.com/562386/36148473-83c3c244-10bc-11e8-96b3-9353c3539db8.png)

face-alignment landmarks with cnn face box:
![image](https://user-images.githubusercontent.com/562386/36148546-d1292498-10bc-11e8-8ba8-224b16d508f2.png)

face-alignment landmarks with hog face box:
![image](https://user-images.githubusercontent.com/562386/36148578-eff7d96e-10bc-11e8-8370-e5263478f9e4.png)

**Comment by Clorr** [comment]
Yes, from what I understand it takes the center, but i don't understand the line with the 0.12. It moves the center a bit or something?

Then the scale is computed so that the box is 195 wide, doesn't it?

Then the [crop method](https://github.com/1adrianb/face-alignment/blob/fecdd1084df5d52246d26a9eb210e3404b4f6345/face_alignment/utils.py#L79) returns a 256 wide image, so maybe it adds some margin around, which could explain that it gets the right landmarks as the face is not cropped too narrow?

I let you have a look when possible ;-)

**Comment by LordVulkan** [comment]
I have just replaced the landmarks for the ones from face-alignment and it works a lot better, but it is also notably slower. I let it here if someone wants to try it, don't forget to import face_alignment

face_detect.py
```
def detect_faces(frame, model="hog"):
    face_locations = face_recognition.face_locations(frame, model=model)

    if model=="cnn":
        fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,enable_cuda=True,enable_cudnn=True,use_cnn_face_detector=True)
    else:
        fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,enable_cuda=True,enable_cudnn=True,use_cnn_face_detector=False)

    raw_landmarks = fa.get_landmarks(frame,all_faces=True)
    landmarksXY = []
    if raw_landmarks is not None:
        for raw_landmark in raw_landmarks:
            landmarksXY.append([(int(p[0]), int(p[1])) for p in raw_landmark])

        for ((y, right, bottom, x), landmarks) in zip(face_locations, landmarksXY):
            yield DetectedFace(frame[y: bottom, x: right], x, right - x, y, bottom - y, landmarks=landmarks,landmarksXY=landmarks)
```

**Comment by iperov** [comment]
@LordVulkan thx, only need to build pytorch for me :D

**Comment by LordVulkan** [comment]
Take a look at this:

https://github.com/peterjc123/pytorch-scripts

**Comment by iperov** [comment]
i dont want deal with conda, trying to build from python...

**Comment by iperov** [comment]
I suggest open 2DFAN-4.pth.tar in torch, research network structure and tensors, and port it to keras. 
:D

**Comment by LordVulkan** [comment]
@shaoanlu has added to his repo a new algorithm for face detection better than cnn.

https://github.com/shaoanlu/faceswap-GAN

Comparison gif:
![68747470733a2f2f7777772e64726f70626f782e636f6d2f732f64697a74786e746b737334647437762f6d61736b5f646c69625f6d74636e6e2e6769663f7261773d31](https://user-images.githubusercontent.com/562386/36173639-fc9d0b74-1109-11e8-9a5b-3fb799670767.gif)

**Comment by iperov** [comment]
need test with 90deg rotated face

**Comment by ppmdo** [comment]
@LordVulkan I can confirm the suggested code finds the correct landmarks. Indeed it's slower, but a lot more precise. 

As a side note. I had to tu user an older version of PyTorch (0.3.0) because 0.3.1 requires CUDA with compute capability > 3.0.

**Comment by iperov** [comment]
@LordVulkan thx for code
I found prebuilt win64 python 3.5 torch 0.3.0 package.
and tested your code
Its works slow because you reinitialize face_alignment every frame

my temporary fix is

```
fa = None

def detect_faces(frame, model="hog"):
    face_locations = face_recognition.face_locations(frame, model=model)
    global fa
    
    if fa == None:
        if model=="cnn":
            fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,enable_cuda=True,enable_cudnn=False,use_cnn_face_detector=True)
        else:
            fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,enable_cuda=True,enable_cudnn=False,use_cnn_face_detector=False)

    raw_landmarks = fa.get_landmarks(frame,all_faces=True)
    landmarksXY = []
    if raw_landmarks is not None:
        for raw_landmark in raw_landmarks:
            landmarksXY.append([(int(p[0]), int(p[1])) for p in raw_landmark])

        for ((y, right, bottom, x), landmarks) in zip(face_locations, landmarksXY):
            yield DetectedFace(frame[y: bottom, x: right], x, right - x, y, bottom - y, landmarks=landmarks,landmarksXY=landmarks)
        
```

**Comment by iperov** [comment]
@LordVulkan , hmmm , no...
I got same zooming bug even with mmod+face_alignment from fakeapp.

**Comment by iperov** [comment]
:(
![untitled-1](https://user-images.githubusercontent.com/8076202/36193385-17adf2e6-117f-11e8-9ea1-adbd84cd3ea6.gif)

**Comment by iperov** [comment]
that was my bad, flip_input must be False

now all fine !!

![untitled-1](https://user-images.githubusercontent.com/8076202/36197812-4f5febea-118e-11e8-859e-fe6250253fba.gif)

dlib cnn suxx, face_alignment pytorch cnn rules.

@Clorr @gdunstone will you adapt face_alignment to faceswap?

**Comment by iperov** [comment]
@Clorr @gdunstone
**face_alignment pytorch cnn** VS **face_recognition dlib cnn**
![1](https://user-images.githubusercontent.com/8076202/36199118-0ba6be7a-1192-11e8-96d6-e564e33f4987.gif)

**Comment by Deadfishzzway** [comment]
So much improvement! @iperov How do I make pytorch work for windows?

**Comment by LordVulkan** [comment]
Maybe we could add face-alignment optional support for Linux and macOS users and leave pytorch out of the official requirements.

**Comment by iperov** [comment]
@Deadfishzzway  I downloaded package from there https://anaconda.org/peterjc123/pytorch/files
and just copied lib to site-packages

**Comment by Clorr** [comment]
It is totally possible to add face-alignment as an option, however something still bothers me.

From what has been seen, landmarks detection seems to fail because of a too narrow crop which can be solved by adding some margin to the image before passed to the detector.

The other issue mentioned by @iperov is that we have a zooming effect that is not in `face-alignment`. What bothers me here is that this zooming effect is not related to the landmarks, it is related to cnn detector that is the same in `face_recognition` and in `face-alignment`. So I'm still wondering where this come from, and I strongly suspect the preprocessing done in `face-alignment` is the key

**Comment by iperov** [comment]
@Clorr face detector same, but landmarks solver different

**Comment by LordVulkan** [comment]
The zooming effect is also present in face-alignment as you can see here (I have no clue why it is a different box though):

https://github.com/deepfakes/faceswap/issues/187#issuecomment-365238963

I think face-alignment fixes it this way:

1. Gets face location box from the image with cnn algorithm.
2. Modifies center and size of the box.
3. Crops the face from the image using the new box.
4. Calculates landmarks inside that cropped image.

**Comment by Clorr** [comment]
That's what I think too, and it would be nice if we could include this "normalization" step in our code

**Comment by LordVulkan** [comment]
So, as it turned out the problem is the shape_predictor, maybe switching to face-alignment completely as it also supports hog would be a good idea.

**Comment by KMMR156** [comment]
> What bothers me here is that this zooming effect is not related to the landmarks, it is related to cnn detector that is the same in face_recognition and in face-alignment

@Clorr i think the zooming is because the wrong landmarks if you check the gif by @iperov 

![11](https://user-images.githubusercontent.com/36402882/36223870-0cd10d26-11c6-11e8-8d8b-c73d94c414d0.gif)
![114](https://user-images.githubusercontent.com/36402882/36223879-12e8def0-11c6-11e8-8bad-034862ce5063.gif)
![120](https://user-images.githubusercontent.com/36402882/36223882-152f629c-11c6-11e8-90e0-8d748eb1e77b.gif)

**Comment by Clorr** [comment]
@KMMR156 In the Extract_Align plugin, the final output is done with the help of the landmarks. And indeed, if the landmarks are wrong, the aligned output will be wrong.

[However, the landmarks are computed over the box returned by the face detector](https://github.com/deepfakes/faceswap/blob/51f1993d93e0ffb581d44416f327f0cf731c34e8/lib/faces_detect.py#L7) and it seems to me that the failure of finding landmarks is due to the too narrow box returned by the face detector

**Comment by Clorr** [comment]
Also note that there is no dependency between face detector and landmarks detector outside the box delimiting the face, so if it works with hog and not with cnn, it means it is a problem of the box

**Comment by iperov** [comment]
I checked problem picture directly in face_recognition/examples/find_facial_features_in_picture.py

result:

![tmpbaurvr6x](https://user-images.githubusercontent.com/8076202/36225783-37826f00-11e5-11e8-9035-d0ced1477e3d.jpg)

**Comment by Clorr** [comment]
Yes, this is because the script you mention does not do a face_search before, and passes the full picture to the landmarks detector. That still adds to my conviction it is a problem of the box returned by the cnn detector

**Comment by Clorr** [comment]
So I played a bit with the box ;-) And it actually does not improve anything... 

I could not reproduce [@LordVulkan second example](https://github.com/deepfakes/faceswap/issues/187#issuecomment-365103341). @LordVulkan could you call `shape_predictor` without the box argument? Because I couldn't...

Also [@iperov example](https://github.com/deepfakes/faceswap/issues/187#issuecomment-365731325) uses hog AFAIK

So `face-alignment` seems the way to go.

**Comment by iperov** [comment]
`Also @iperov example uses hog AFAIK`

> face_locations =  face_recognition.face_locations(image, 1, 'cnn')
> face_landmarks_list = face_recognition.face_landmarks(image, face_locations)

same result

**Comment by kcimit** [comment]
Even with iperov fix hog detection is terribly slow not to mention cnn detection which was always very slow for me.
Detecting a face in single 1280x720 snapshot takes from 4-10 minutes. Is it normal? Perhaps problem with tf/cuda/pyhon config.

What time does it takes normally to process single picture in your case?

**Comment by iperov** [comment]
@kcimit actually this is LordVulkan fix for use face_alignment in faceswap.
pytorch must be installed with cuda support, then speed is normal, ~1.3 images per sec

**Comment by kcimit** [comment]
thanks @iperov and @LordVulkan but I think I miss something. Tried every method here for pytorch including building it under win10 - still same performance.

**Comment by Apollo122** [comment]
I think CNN implementation can be improved. I use hd images for extract, if I use CNN with cuda support I get out of memory crash. If I use CNN without cuda it takes forever to complete. 

There's a implementation here I think pretty efficient. It first downsizes the image by four then use CNN with cuda to detect face then upsizes the image again and use hog to extract face. It works good but because it's not a part of the plugin system it doesn't output alignment.json file. Also It has the same zoomed in output problem.

**Comment by kcimit** [comment]
For the fix suggested by @iperov  and @LordVulkan I wonder whether we need at all use face_recognition.
face_alignment when calculating landmarks already establish face location box. The question that it is impossible to get without changing get_landmarks
Provided that it returns bounding rect, the code in faces_detect could be.
`def detect_faces(frame, model="hog"):
    #face_locations = face_recognition.face_locations(frame, model=model)
    global fa
    
    if fa == None:
        if model=="cnn":
            fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,enable_cuda=False,enable_cudnn=False,use_cnn_face_detector=True)
        else:
            fa = face_alignment.FaceAlignment(face_alignment.LandmarksType._2D,enable_cuda=False,enable_cudnn=False,use_cnn_face_detector=False)

    raw_rects, raw_landmarks = fa.get_landmarks(frame,all_faces=False)
    landmarksXY = []
    face_locations =[]
    if raw_landmarks is not None and raw_rects is not None:
        for raw_landmark in raw_landmarks:
            landmarksXY.append([(int(p[0]), int(p[1])) for p in raw_landmark])

        for raw_rect in raw_rects:
            face_locations.append((int(raw_rect.top()), int(raw_rect.right()), int(raw_rect.bottom()), int(raw_rect.left())))
            
        for ((y, right, bottom, x), landmarks) in zip(face_locations, landmarksXY):
            yield DetectedFace(frame[y: bottom, x: right], x, right - x, y, bottom - y, landmarks=landmarks,landmarksXY=landmarks)`

Kind of removes calculation overhead, which makes it a bit faster especially for cnn

**Comment by petergerten** [comment]
@kcimit do you have the above code with face_alignment-only working? Is there anything else required?

**Comment by kcimit** [comment]
Yes, I have it but it involves changing face_alignment

**Comment by iperov** [comment]
almost ported face_alignment from PyTorch to Keras

**Comment by deepfakesclub** [comment]
In my own testing, I found that face_recognition outperforms face-alignment (pytorch version) for speed, sensitivity, and errors in everything BUT the zooming stability issue. In particular, for dynamic scenes with complex backgrounds and lots of motion, face-alignment has a much higher error rate and also misses more faces. However, in "easy" scenes, face-alignment is probably better because of the more stable tracking.

Given the constraints of the whole faceswap package (want nice neat, slowly moving faces anyways), face-alignment is probably better for most use cases. Face_recognition is still handy to keep around for tough scenes pushing the limits, though.

**Comment by Clorr** [comment]
Closing this as #228 adresses this. Feel free to open new issue if there are still problems
