### ISSUE TITLE
Rolling loss numbers?

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#188]
after an update I noticed that the loss numbers seem to change in real time and my loss numbers (which before took days) have declined in minutes! I've gone from 0.15 to 0.04 in just a few minutes. Should I be watching another metric? What does this mean?

in addition, the same command with -t GAN yielded a process where the loss numbers did not decrease for 2 days.

saved model weights loss_A: 0.19750, loss_B: 0.15107
saved model weights loss_A: 0.15105, loss_B: 0.10045
saved model weights loss_A: 0.10557, loss_B: 0.07693
saved model weights loss_A: 0.08569, loss_B: 0.06992
saved model weights loss_A: 0.07518, loss_B: 0.06174
saved model weights loss_A: 0.06855, loss_B: 0.05906
saved model weights loss_A: 0.06181, loss_B: 0.05596
saved model weights loss_A: 0.06101, loss_B: 0.05102
saved model weights loss_A: 0.05953, loss_B: 0.04613
saved model weights loss_A: 0.05362, loss_B: 0.04610
saved model weights loss_A: 0.05193, loss_B: 0.04854
saved model weights loss_A: 0.05163, loss_B: 0.04388

**Comment by Clorr** [comment]
Note that the log that is printed does not make one line per iteration (as previously) but makes one new line when it saves your model.

Also please indicate number of iterations, and not a duration (the duration varies depending on how powerful your machine is)

**Comment by Clorr** [comment]
Otherwise, the loss can decrease fast when you start training on a new person with an existing model, so be more precise in your request as it is hard here to understand what you did.

**Comment by fetchlister** [comment]
Apologies. Its two minutes and thirty seconds between model saves (100 iterations) and I'm running on an Quadro M2200. I am not starting with an existing model.
