### ISSUE TITLE
Columns full white it's normal?

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#189]
![screenshot_12](https://user-images.githubusercontent.com/13344308/36137913-0b69719a-1076-11e8-9759-ec14d1f07892.png)

(Don't have much time of training yet).

**Comment by Apollo122** [comment]
That's alpha masks preview. It's supposed to look like that. So yeah normal.

**Comment by iperov** [comment]
GAN creator told that is not normal.

https://github.com/shaoanlu/faceswap-GAN/issues/50

**Comment by Apollo122** [comment]
He asked about white images not dots. That column should look white.
