### ISSUE TITLE
Failure to load existing training data

### ISSUE THREAD

**Issue by flipflopbboi** [deepfakes/faceswap#190]
Hello I was training ok on an ipython notebook but got an error message and the process hung (sadly i did not keep a copy of the error).
Now when I try to train again, I get the following error:

```
Loading Model from Model_Original plugin...

Failed loading existing training data.

Cannot interpret feed_dict key as Tensor: Tensor Tensor("Placeholder:0", shape=(5, 5, 3, 128), dtype=float32) is not an element of this graph.
```

I have tried loading older models or a 'clean' model but the error persists.
Anby ideas? thanks

**Comment by Clorr** [comment]
A failure in loading data should not stop the program. Try resetting the code to the original and check your modifications if you have done some
