### ISSUE TITLE
How use the PLUGINS, some help is weclome...

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#191]
![screenshot_13](https://user-images.githubusercontent.com/13344308/36156745-babac1fe-10b6-11e8-9456-e2721ba27265.png)

Let's say i use `python faceswap.py convert -i C:/faceswap/A -o C:/faceswap/A/merged -m C:/faceswap/models -t GAN -c GAN -D cnn`

How i can use **Convert_Adjust.py** on that command?

**Comment by Clorr** [comment]
run python `faceswap.py convert -h` (works for `convert`, `train` and also `extract`) to get all possible values. 

- -t will enable you to choose the model plugin (refered as `trainer`)
- -c will help you choose the convert plugin
