### ISSUE TITLE
GAN plugin Stalls at losses independent of GPU

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#193]
I have migrated my faceswap onto a machine with better graphics capability from my mobile workstation because no matter how long I trained with the GAN plugin, my Loss_GA would not go below 17, and the preview window showed poor faces. I migrated from a GPU with 640 cuda cores to one with 3584, but to no avail. Still stuck at 17. Everything *runs* flawlessly, everything is installed properly and I have the latest version but I am stumped. Should I be looking at different numbers? Any help would be appreciated. this new GPU came at substancial cost.

**Comment by Clorr** [comment]
Result not only depends on the power you have but on the training images you provide. Are they well aligned? How many iterations did you? What is your actual output? You should post these details to get help

**Comment by Clorr** [comment]
And also I would better fit in faceswap-playground...
