### ISSUE TITLE
GAN plugin stalls losses at 17 percent regarless of GPU setup.

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#198]
GAN plugin stalls losses at 17 percent regarless of GPU setup.

Would really like to use gan as I hear it gives better results, and my results from training have been spotty with the default trainer.

Tested on a m2200 (640 cores, 4gb ram) and then a p100 (3584 cores, 16gb ram)
Am using -t GAN in addition to normal training command, first two numbers fluctuate wildly, but the latter two seem to steadily decrease until 17.xyz. Any help would be appreciated.

**Comment by dfaker** [comment]
The progress of GAN training should be a competition between generator and discriminator where they're both hovering around 50% accuracy, if either pull too far ahead the system fails, what you're describing here sounds like such a failure, probably due to too low a sample size.

**Comment by dfaker** [comment]
https://github.com/soumith/ganhacks

**Comment by fetchlister** [comment]
thank you. I'll update my facesets @dfaker
