### ISSUE TITLE
Encoder weights stored twice in GAN model

### ISSUE THREAD

**Issue by leijurv** [deepfakes/faceswap#200]
In the original model, encoder decoder_A and decoder_B have their weights stored separately.
https://github.com/deepfakes/faceswap/blob/master/lib/ModelAE.py#L24

```
try:
            self.encoder.load_weights(str(self.model_dir / encoderH5))
            self.decoder_A.load_weights(str(self.model_dir / face_A))
            self.decoder_B.load_weights(str(self.model_dir / face_B))
            print('loaded model weights')
            return True
```

In the new GAN model, weights are stored as a combination in two files, one with encoder and decoder_A, and another with the same encoder and decoder_B. 

https://github.com/deepfakes/faceswap/blob/master/plugins/Model_GAN/Model.py#L126

```
        encoder = Encoder(self.img_shape)
        decoder_A = Decoder_ps(self.img_shape)
        decoder_B = Decoder_ps(self.img_shape)    
        x = Input(shape=self.img_shape)
        netGA = Model(x, decoder_A(encoder(x)))
        netGB = Model(x, decoder_B(encoder(x)))           
        try:
            netGA.load_weights(str(self.model_dir / netGAH5))
            netGB.load_weights(str(self.model_dir / netGBH5))
            print ("Generator models loaded.")
        except:
            print ("Generator weights files not found.")
            pass
        return netGA, netGB, 
```

**Comment by leijurv** [comment]
Is there a reason for this change? Since the encoder is the same between the two models, what is the purpose of storing it in two different places on disk?

**Comment by shaoanlu** [comment]
To prevent overwriting encoder weights of non-GAN models.
