### ISSUE TITLE
FaceApp Mobile Version

### ISSUE THREAD

**Issue by flosth** [deepfakes/faceswap#204]
also while we're working on getting this thing on mac, let's start on a phone version? i'm thinking something like FaceApp where we put it up on camera and it transforms the video.

**Comment by Alexander01998** [comment]
You do realize that phones don't have nearly enough processing power to run something like this?

**Comment by flosth** [comment]
@Alexander01998 then how does Faceapp do it

**Comment by Alexander01998** [comment]
@flosth I don't know what FaceApp does, but FakeApp/FaceSwap has to train a neural network for every pair of faces that you want it to swap.

This process already takes many hours and sometimes more than a day on a high-end desktop computer. A phone would need weeks, maybe months, if it could even run the code in the first place. Not to mention that it would overheat and/or drain its battery after a couple of hours.

**Comment by h1vem1nd85** [comment]
Faceapp actually uploads your content to their servers to process against their model. There is no actual calculation done on your phones hardware

**Comment by gdunstone** [comment]
Closing because this is out of scope.

This repo is not a service. The developers are not going to donate gpu time.
