### ISSUE TITLE
Failed building wheel for scikit-image, Failed building wheel for dlib

### ISSUE THREAD

**Issue by dover** [deepfakes/faceswap#205]
----------------------------------------
  Failed building wheel for scikit-image
  Running setup.py clean for scikit-image
  Running setup.py bdist_wheel for dlib ... error
  Failed building wheel for dlib
  Running setup.py clean for dlib
  Running setup.py bdist_wheel for pyyaml ... done
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\2c\f7\79\13f3a12cd723892437c0cfbde1230ab4d82947ff7b3839a4fc
  Running setup.py bdist_wheel for absl-py ... done
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\45\07\0e\6880381ca521796cf6cc18ba4ab502c2232e5777099b4df4ae
  Running setup.py bdist_wheel for html5lib ... done
  Stored in directory: C:\Users\User\AppData\Local\pip\Cache\wheels\6f\85\6c\56b8e1292c6214c4eb73b9dda50f53e8e977bf65989373c962
Successfully built pathlib pyyaml absl-py html5lib
Failed to build scikit-image dlib
Installing collected packages: pathlib, scandir, six, numpy, h5py, scipy, pyyaml, Keras, opencv-python, protobuf, html5lib, markdown, werkzeug, bleach, tensorflow-tensorboard, absl-py, tensorflow-gpu, pyparsing, python-dateutil, pytz, cycler, matplotlib, decorator, networkx, pillow, PyWavelets, scikit-image, dlib, Click, face-recognition-models, face-recognition, tqdm
  Running setup.py install for scikit-image ... done
  Running setup.py install for dlib ... error
Exception:
Traceback (most recent call last):
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 36: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\user\envs\faceswap\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 36: invalid continuation byte

- **Operating system and version:** Windows 
- **Python version:** 3.6.4 (64-bit)
- **Faceswap version:** commit hash or version number
- **Faceswap method:** GPU
- ...

**Comment by Alexander01998** [comment]
I had the same issue. Switching to Python 3.5.4 (64 bit) fixed it.

**Comment by kcimit** [comment]
For me installing dlib like this was resulting in no cuda support in dlib.
Try getting repo for dlib and build it from source.
