### ISSUE TITLE
train.py loop behavior

### ISSUE THREAD

**Issue by GSonderling** [deepfakes/faceswap#207]
I'm speaking about: 
https://github.com/deepfakes/faceswap/blob/51f1993d93e0ffb581d44416f327f0cf731c34e8/scripts/train.py#L145-L173

As you know pressing enter sends stops the loop after current iteration. Unfortunately the method is rather inflexible:
https://github.com/deepfakes/faceswap/blob/51f1993d93e0ffb581d44416f327f0cf731c34e8/scripts/train.py#L121-L123

This can cause the thread to hang after last iteration.

I did look into the issue, and unfortunately there are only two ways to solve it.

1. Complicated way with additional imports. Sadly, baseline python doesn't include tools we would need to implement desired behavior. We would need to import package with specialized key listeners.
In my opinion that is an overkill. We could also just write our own code from scratch. But the readability would suffer and for very minimal gain. Therefore I would prefer option 2.

2. Drop the `Enter` interrupt and revert to traditional `Ctrl + c` behavior. Everybody who works with cli is familiar with it and python has all the necessary stuff. It is omniplatform code for it is as simple as humanly possible. On chance that somebody doesn't understand it, we can always add some message explaining it. 
Right now the old behavior provides little benefit anyway, since we can already limit the epochs.

I'm asking because I don't want to make mess, submitting useless PR and so on. Granted we could always keep things as they are. But you have to agree, right now it feels sloppy.

**Comment by Clorr** [comment]
I close this as your PR is already sufficient ;-)
