### ISSUE TITLE
Merging w/ multiple faces in frame

### ISSUE THREAD

**Issue by enniowatson** [deepfakes/faceswap#208]
Running into an issue when I try to convert. If there are multiple faces in the frame, Face B gets swapped onto all the faces. Face B also gets swapped onto solo faces in different shots that are not the target face. I'm coming from FakeApp, where any faces deleted from the /aligned folder are skipped during conversion. That doesn't appear to be the case here (though it does appear to skip those files during training). I tried using the filter, with the clearest front view of the target face I had. That resulted in several frames of the desired face getting skipped while several frames of the non-target faces were still swapped. Do I have to manually edit the alignments.json file or is there an easier workaround?

**Comment by Apollo122** [comment]
I raised this issue before but no changes yet. https://github.com/deepfakes/faceswap/pull/155#issuecomment-365079915
I proposed a utility function to check entries in json against data/A and delete the absent ones. But until it is implemented manual work is only way

**Comment by enniowatson** [comment]
Any idea why this hasn't been addressed? Seems like an easy fix, as other versions have this functionality. It's already tedious enough deleting unwanted frames from the /aligned folder. Having to then delete parts of the .json file is a hundred times more annoying, and can cause probably even more problems if you mess up the syntax.

**Comment by Apollo122** [comment]
Because all of our programmers on strike :) no seriously they are all missing so either we wait for them or do it ourselves. I'm c#/Java guy so don't really know python.

**Comment by ruah1984** [comment]
You mean in UK right now, all University staff strike haha.

**Comment by cojosao** [comment]
How difficult would it be to create a standalone script that would parse the alignments file and delete entries that don't have corresponding pictures in A/aligned? I'm no programmer but perhaps this would be a temporary fix until something can be incorporated into the main branch? I'm also in a similar spot since most of what I want to do involves two people in a scene.

**Comment by oatssss** [comment]
Seems simple enough to do in Python, I'll try and do this today.

**Comment by Apollo122** [comment]
Great! Just mind that alignment file is not necessary to be a json file. I think there are couple supported extension. You can see them in script

**Comment by Apollo122** [comment]
Will try this. Can you make the default path for this to "./aligned"? Like in the original scripts? People are used to copy this folder to the folder that contains the photos that they want to convert.

**Comment by oatssss** [comment]
It's in already.

**Comment by Apollo122** [comment]
@cojosao  @enniowatson can you test this? Mind that you have to run extract script again to get the alignment file. Its format has been changed.

**Comment by RunetX** [comment]
Sorry for bad English, I use translator.
It would be great if the program automatically divided similar faces into separate directories with its alignments.json file. In this case, it would be possible to replace individually any of the found faces

**Comment by Apollo122** [comment]
Don't think it would be reliable.

**Comment by RunetX** [comment]
I thought that the mechanisms of machine learning is sometimes used to split the dataset by category.
For example https://github.com/ankonzoid/artificio/tree/master/similar_images_AE

**Comment by Apollo122** [comment]
What I mean is face detector often gives wrong results. Maybe it can be used for initial results but you would have to go through each folder to remove false-positive and put wrongly recognized faces to appropriate folders.

**Comment by RunetX** [comment]
1. We can use extractor same as usual. Then we have dataset of several faces (wrong detections). 
A1, B1, A2, A3, A4, B4, A5, B5, A6, A7, C7
2. To run similar images app with this dataset we get several sets with different faces
[A1, A2, A3, A4, A5, A6, A7], [B1, B4, B5], [C7]
3. Generate alignments.json for sets
4. Run train or extract with any set separately
5. Profit

**Comment by Clorr** [comment]
@RunetX It is always possible to have a utility to parse extracted photos and group them by similarity, but as @Apollo122 said it won't be perfect. But please open a new issue to discuss about it, as it is a different subject from the original issue

**Comment by RunetX** [comment]
@Clorr execuse me, I don't understand English very well.

**Comment by Apollo122** [comment]
@oatssss I checked the code. It seems default value is still none

**Comment by oatssss** [comment]
@Apollo122 do you have this commit? https://github.com/oatssss/faceswap/commit/b4dc203e4c9f1f019666e4b447bc1be97d7df0c8

**Comment by Apollo122** [comment]
Aah okay I was looking at the cl parameters

**Comment by oatssss** [comment]
Yea I didn't know of a way to set the default value of an option to a value based on another option.

**Comment by cojosao** [comment]
Sorry for the late reply, but I’ve just managed to get back to being able to try this out. The new convert.py is able to find the aligned folder but it doesn’t check the images, instead, it claims every frame was deleted and doesn’t do any swapping. This is after running the new extract script with the better filenames and removing faces of everyone except for the target.

**Comment by oatssss** [comment]
@cojosao which commit on what branch did you try?

**Comment by cojosao** [comment]
I tried it with both https://github.com/oatssss/faceswap/commit/b6be9db0ee8357f4f5a8af42e20bc77ec7bf0278 and https://github.com/oatssss/faceswap/commit/b4dc203e4c9f1f019666e4b447bc1be97d7df0c8 linked in this thread, with both having the same result.

**Comment by babilio** [comment]
I am having the same issue as @cojosao , with a recent pull of https://github.com/oatssss/faceswap/tree/update-GAN-v2

**Comment by babilio** [comment]
Also using match histogram -mh gives this error 

`Failed to convert image: E:\data\a\10\3\0066.png. Reason: local variable 'mask' referenced before assignment
Failed to convert image: E:\data\a\10\3\0067.png. Reason: local variable 'mask' referenced before assignment
Failed to convert image: E:\data\a\10\3\0068.png. Reason: local variable 'mask' referenced before assignment
Failed to convert image: E:\data\a\10\3\0069.png. Reason: local variable 'mask' referenced before assignment
Failed to convert image: E:\data\a\10\3\0070.png. Reason: local variable 'mask' referenced before assignment
Failed to convert image: E:\data\a\10\3\0071.png. Reason: local variable 'mask' referenced before assignment
Failed to convert image: E:\data\a\10\3\0072.png. Reason: local variable 'mask' referenced before assignment
  1%|██                                                                                                                                                                                                                                                | 73/8580 [00:02<05:26, 26.02it/s]Traceback (most recent call last):
  File "faceswap.py", line 29, in <module>
    arguments.func(arguments)
  File "E:\faceswap\lib\cli.py", line 73, in process_arguments
    self.process()
  File "E:\faceswap\scripts\convert.py", line 187, in process
    self.convert(converter, item)
  File "E:\faceswap\scripts\convert.py", line 214, in convert
    image = converter.patch_image(image, face, 64 if "128" not in self.arguments.trainer else 128)
  File "E:\faceswap\plugins\Convert_Masked.py", line 30, in patch_image
    new_face = self.get_new_face(image,mat,size)
  File "E:\faceswap\plugins\Convert_Masked.py", line 110, in get_new_face
    new_face = self.encoder(normalized_face)[0]
  File "E:\faceswap\plugins\Model_Original\Model.py", line 28, in <lambda>
    return lambda img: autoencoder.predict(img)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1790, in predict
    verbose=verbose, steps=steps)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1299, in _predict_loop
    batch_outs = f(ins_batch)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2357, in __call__
    **self.session_kwargs)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
    return fn(*args)
  File "C:\Users\AppData\Local\conda\conda\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
    target_list, status, run_metadata)`

**Comment by cagkanciloglu** [comment]
@oatssss could you make a separate PR for this? So we can use it rather than waiting GAN to merge

**Comment by Apollo122** [comment]
@oatssss could you please make a separate PR for this? So people can use it for master

**Comment by babilio** [comment]
Original convert is does not work for me still, whether the alignments have format x0.png or x__0.png, it just copies the original image without the swap.

**Comment by Apollo122** [comment]
@oatssss added new features for convert also such as histogram matching.  Maybe he changed some parts of it. I wonder if he can make a separate PR for that too. I don't think histogram matching exclusive to GAN.

**Comment by oatssss** [comment]
@Apollo122 make a separate PR for the histogram matching? Yea I'll do that.

@cojosao @babilio I just tried the branch and convert is working for me, both the histogram matching and skipping deleted faces.

**Comment by cojosao** [comment]
It looks like the issue was the Masked converter not working, which it seems you just fixed in the branch an hour ago :P 
Sorry for the confusion, I will check back if anything else occurs but it seems to work great!

**Comment by oatssss** [comment]
#260 should fix this

**Comment by oatssss** [comment]
Yup, #260 addresses this and it's already closed.
