### ISSUE TITLE
why the face swap area color different from original image?

### ISSUE THREAD

**Issue by DLSeed** [deepfakes/faceswap#212]
I had done data extraction, model training, and image convert followed the instruction, and finally the result like this:
![506463756](https://user-images.githubusercontent.com/28498769/36434250-9183f9fc-1699-11e8-800e-83d3e2ffb69b.jpg)

the face swap area color obviously different from original image, something i missed?

**Comment by babilio** [comment]
I think this could be low variety of lighting in your Nick cage pictures. It's important not only to get different angle but different lighting settings that way it is more adaptable to other skin tones

**Comment by babilio** [comment]
I think this could be low variety of lighting in your Nick cage pictures. It's important not only to get different angle but different lighting settings that way it is more adaptable to other skin tones

**Comment by DLSeed** [comment]
oh, I generated this image just used the pre-trained model on 'README.md' , not my own. What i mean is  using pre-trained model and my own model occured the same problem.

**Comment by DLSeed** [comment]
@babilio 
oh, I generated this image just used the pre-trained model on 'README.md' , not my own. What i mean is using pre-trained model and my own model occured the same problem.

**Comment by DLSeed** [comment]
It's my environment issue actually, finally i clean & reclone project to test, and the result became right. thanks for all!

**Comment by room3dev** [comment]
This happens sometimes when enabling histogram match (color correction) in GAN version.
