### ISSUE TITLE
Dark corners on face map

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#215]
For awhile now I have been training different models but every time one completes (at around 0.01x) and I convert/merge converted photos into a video I almost always have this sort of blackish grey points at three or four corners of the face map that really kills the realism, or the face is quite plainly square and overlaps even the widest faces. I cannot get anywhere near these professional looking renders that always appear. The faces on theirs look seamless. In addition, during the convert process when processing pictures, it complains that alignments.json isnt found; I'm thinking this has to do with th poor mapping/ dark edges? It always seems that deepfakes made with FakeApp are way more realistic, and FakeApp generates a alignments.json faceswap does not.

I have attached both examples of squarishness and dark corners - nothe that this happens no matter the donor body and no mattery the celeb.

http://i68.tinypic.com/2cwo36p.png

http://i68.tinypic.com/az81v6.png

**Comment by flipflopbboi** [comment]
You should definitely adjust the convert parameters; `-b 8` seems to be working well.
Also, you can turn on the seamless option via `-S` which makes a big difference. However seamless, from what I ve seen, introduces more flickering and also takes a lot longer to process.

**Comment by fetchlister** [comment]
thanks @flipflopbboi I'll give it a go.

**Comment by fetchlister** [comment]
@flipflopbboi Worked like a charm. most videos of people looking down/tilted sideways kinda make the face turn off until its in a more upright position. is that just me or are more, say, non head-on-ish frames not recognized?
