### ISSUE TITLE
Basic usage question

### ISSUE THREAD

**Issue by lactoseintolerant** [deepfakes/faceswap#219]
Sorry, I have a very basic usage question.

The training data is specified in img_dirA and img_dirB. I couldn't find the requirements for the images in these directories. Are these raw images of a certain size? Or should these be the 256x256 cropped and aligned faces such as from the faceswap github? What is the specification of the images in these directories?

**Comment by Apollo122** [comment]
Training images should be aligned and cropped. You can use extract script here to get alignment.json if you don't want to detect faces again on merge part.

**Comment by Apollo122** [comment]
Mind that if you delete a training image make sure that you delete its entry as well from the json. And yeah you have to do this manually for now

**Comment by lactoseintolerant** [comment]
Thanks, damn I realized I posted in the wrong github. Meant for the GAN one. Whoops.
