### ISSUE TITLE
[DISCUSSION] Would utilizing super-resolution improve the quality of generated faces?

### ISSUE THREAD

**Issue by Apollo122** [deepfakes/faceswap#221]
First check this out, original paper included. https://github.com/titu1994/Image-Super-Resolution

One of the big problems with faceswaping is close-ups because generated faces are 64x64 -if it's not gan128-. So how about we increase resolution of the generated faces by super-resolution? We would train super-resolution with the same training set and use it on generated faces to double or triple the resolution. What do you guys think?

**Comment by oatssss** [comment]
Maybe we can add an option to separate convert into 2 stages: swap and patch.
Swap will use the alignments to grab the face from the frame and swap it with the target.
Patch just puts the face back into the frame.
This would open up the possibility to perform any intermediate actions between the 2, like for example applying super resolution before patching.

**Comment by Apollo122** [comment]
In original scripts there is a script called init.py . What it does is just swapping the faces using the trained model, it doesn't do the merging. You put those swapped faces into aligned folder and run merge script. Merge reads from alignment file also.
I think you are suggesting the same thing. And yes if we do this we can augment generated faces before merge them back into original frames.

**Comment by ruah1984** [comment]
How about neural enhance ?improve the resolution through neural network as well.

**Comment by oatssss** [comment]
The way I understood it is the super resolution will produce 2x bigger image, but then that image will just be rescaled down back to the original size. The end result is an image of the same size, just better image quality.

I thought neural enhance and super resolution are the same thing.

**Comment by Apollo122** [comment]
Yes that would improve the quality but if we scale it down again wouldn't the quality of close-ups remain the same? Which is terrible :)

**Comment by oatssss** [comment]
The original image would be the enlarged face that's blurry. SR will scale it up to improve the quality, then scale it back down to the original size (which is still relatively large).

**Comment by Apollo122** [comment]
Might be. Only problem with that is vram: max batch size I can do with gan128 is 20 so for gan256 it would be 10 :) I guess we can try it when current gan in our repo works same as well as the convert script. But as i said because of the vram SR might be faster.

**Comment by oatssss** [comment]
I haven't tried to train an SR model, what if it requires the same amount of vram! :P

**Comment by Apollo122** [comment]
The readme in the git page I shared says something about 4gb 980m. Only extremely high resolution pictures might be problem its written, such as 6000x6000 so I think we are clear :) haven't read the whole thing but it our 256x256 might be used as training images for it also

**Comment by Clorr** [comment]
I'm closing this as we should discuss it more in https://github.com/deepfakes/faceswap-model

**Comment by Apollo122** [comment]
I'll reopen there when gan stuff is finished.
