### ISSUE TITLE
when I can stop the trainging?

### ISSUE THREAD

**Issue by chengjunjiecn** [deepfakes/faceswap#226]
I start training, and screen showing like:
0.01676407 0.031689048

when I can stop training?

**Comment by ruah1984** [comment]
How's the preview ?

**Comment by Apollo122** [comment]
usually below 0.08 is good enough. so if you like the preview so can stop the training.

**Comment by oatssss** [comment]
@Apollo122 those loss values look more like the non-GAN model. @chengjunjiecn you can convert with just a few images to see what it's like. If you're not happy, keep training!
