### ISSUE TITLE
Latest commit extraction fails: Expected numpy.ndarray of uint8

### ISSUE THREAD

**Issue by deepfakesclub** [deepfakes/faceswap#237]
The commit before with the memory issue extracts other than memory issues on lower end GPUs. (I guess 2GB cards will not work anymore for extractions, even with the memory fix?)

I tested the newest commit with the memory fix and I get the above error thrown by the extraction error handler. I tested jpg, png, 2 sets of hardware with 2 different conda environments. I verified the commit before, and 2 commits before worked fine on all the hardware and data sets.

Maybe I am missing something obvious with the newest commit.

**Comment by iperov** [comment]
check this in interpreter
```
import cv2
img = cv2.imread('your_image.png')
img.shape
```

**Comment by iperov** [comment]
I understood your bug, wait fix.

**Comment by iperov** [comment]
https://github.com/deepfakes/faceswap/pull/236
