### ISSUE TITLE
EOL Error when training

### ISSUE THREAD

**Issue by DLSauron** [deepfakes/faceswap#239]
After pulling the latest commit today I am now getting the below error when trying to train.

**Command**
python faceswap.py train -A "D:\Fakes\Data\Dataset_A\Faces" -B "D:\Fakes\Data\Dataset_B\Faces" -m "D:\Fakes\Model" -p -s 100 -bs 80 -t LowMem

**Error**
Traceback (most recent call last):
  File "faceswap.py", line 12, in <module>
    from scripts.convert import ConvertImage
  File "D:\Fakes\faceswap\scripts\convert.py", line 100
    help="Erosion kernel size. (Masked converter only). Positive values apply erosion which reduces the edge \
                                                                                                              ^
SyntaxError: EOL while scanning string literal

**Comment by Ianmcmill** [comment]
remove the whitespace after \ in line 100

**Comment by Clorr** [comment]
@babilio is that due to the #238 PR?

**Comment by Ianmcmill** [comment]
I cannot speak for babilio but yes. #238 . Just a typo in his commit.

**Comment by Clorr** [comment]
I updated the code, can anyone confirm it is ok?

**Comment by DLSauron** [comment]
I can confirm the problem appears to be fixed.

**Comment by babilio** [comment]
Oops sorry guys I edited the helper just in github. Thanks for fixing this. I will be more careful in future commits.
