### ISSUE TITLE
Training is not stopping when press "q"

### ISSUE THREAD

**Issue by nerdprogrammergm** [deepfakes/faceswap#24]
Had been training the model from past 36 hours on MAC OS HIGH SIERRA. 
Now the issue I am facing is when I press "q" to stop the training process, nothing happens, it's continuing to train the model. 
Please help as I don't want to terminate the program using ctrl+c to stop it as the trained model will also be lost and all my time/eletricity/etc will get wasted!
![image](https://user-images.githubusercontent.com/20768297/34334884-76e4b7a4-e970-11e7-8c88-99fd203e50c8.png)

**Comment by Clorr** [comment]
Hello,

It is a problem I encountered also, and indeed, it should be fixed. Luckily, the model is saved every 100 epoch/iterations so you should find a model in your models folder.

Go there, copy your model somewhere safe, and then you will be able to kill the program without loosing anything

**Comment by nerdprogrammergm** [comment]
Well, I already figured it out after posting it here. It takes around 50 minutes for 100 iteration on my system, thinking to move stuff to cloud.
Thanks for quick reply.

**Comment by lukaville** [comment]
> It takes around 50 minutes for 100 iteration on my system
By the way, what configuration do you use? Is it just MacBook Pro? Do you use GPU?

**Comment by nerdprogrammergm** [comment]
It's mac book pro early 2015 model.
No I am not using any gpu yet. Once I get success using it on my mac, I will move it to powerful system.
I am just playing around with damn warning and error.
