### ISSUE TITLE
Add improvements to work with YouTube videos?

### ISSUE THREAD

**Issue by goberoi** [deepfakes/faceswap#243]
Hi folks, first off, thank you for your hard work on this repo.

I spent some time exploring what this code can do, you can see results here: https://goberoi.com/exploring-deepfakes-20c9947c22d9

More importantly, I wrote a script to help working with YouTube videos. This code may be interesting to this audience, and could be pulled into this repo down the road:
https://github.com/goberoi/faceit

Thanks,
Gaurav

**Comment by Clorr** [comment]
Hi @goberoi ,
Welcome and thanks for your post. If you want to contrib, feel free to make some PR if you want. You can either add a `convert-youtube` in the `scripts` folder or create a new `tools` directory with your youtube grabbing tool. Just beware of hardcoded values, but beside of that there is no problem for adding this type of script to the repo
