### ISSUE TITLE
tensorflow 1.6.0?

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#245]
I noticed that tensorflow 1.6.0 is out, which can use cuda 9.1 I think. And uses AVX instructions.

Would it be useful to use it?

https://github.com/tensorflow/tensorflow/releases/tag/v1.6.0

https://developer.nvidia.com/cuda-toolkit/whatsnew

Edit: Oops, looks like tensorflow 1.6.0 is NOT built against CUDA 9.1 as was planned.

https://github.com/tensorflow/tensorflow/issues/15140

" We are not going to move the default builds to CUDA 9.1 or 9.2 we will stick with CUDA 9 likely until CUDA 10"

Edit 2 : I updated tensorflow to 1.6.0 (pip install tensorflow==1.6.0) and it works normally.

**Comment by i5L4NDOF5T4BiLiTY** [comment]
I already updated to 1.6.0 a few days ago, it works fine with the faceswap scripts on windows 10.
pip3 install --upgrade tensorflow-gpu.
Not sure what performance increase was from them activating AVX in the builds from our point of view, using mostly gpu.
It did feel slightly faster in a unscientific way.

**Comment by luiscosio** [comment]
Yes, it works as expected without issues on Windows 10.

**Comment by DLSauron** [comment]
I tested it and while training in Windows 10 it was displaying the below message every few seconds. It did not error out and training appeared to keep going but it was annoying and filling up the screen.

018-03-07 13:25:11.713373: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_dnn.cc:3492]

**Comment by kvrooman** [comment]
The new standard build for TF 1.6 will include the AVX instruction set so unless you've already been compiling your own, you should see improvements on some problems.  AVX2 and MKL enabled cpu's will be still faster than AVX ( ~20% ) for inferences if you still compile your own...
I found this install/compile guide helpful .
http://www.python36.com/install-tensorflow-gpu-windows/

Dlib, and some other dependencies can also be compiled with faster instruction sets.  I was experimenting with changing some of the requirements.txt for gpus somewhere along the lines of ...

pip install dlib --install-option="--yes USE_AVX_INSTRUCTIONS" --install-option="--yes DLIB_USE_CUDA"

Will post something when I get it all ironed out ( the cpu requirement can drop the cuda reference and use just AVX ). PS - DLib without AVX or CUDA is much much slower

**Comment by Kirin-kun** [comment]
@DLSauron This issue appeared suddenly for me too. It sometimes writes

C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\stream_executor\cuda\cuda_dnn.cc:3492]

Several times for a while, then stops... then it comes back from time to time.

It happened in a training session which eventually stopped with a OOM problem after a long while (leak?).

**Comment by Kirin-kun** [comment]
Doesn't seem to have prominent issues, but 1.5.0 doesn't produce warning outputs. So, I'll revert back to 1.5.0
