### ISSUE TITLE
Change to resolve that can't generate image no shape issue

### ISSUE THREAD

**Issue by mansonami** [deepfakes/faceswap#250]
def process(self):
        extractor_name = "Align" # TODO Pass as argument
        self.extractor = PluginLoader.get_extractor(extractor_name)()
        processes = self.arguments.processes
        try:
            if processes != 1:
                files = list(self.read_directory())
                for filename, faces in tqdm(pool_process(self.processFiles, files, processes=processes), total = len(files)):
                    self.num_faces_detected += 1
                    self.faces_detected[os.path.basename(filename)] = faces
            else:
                
                for filename in tqdm(self.read_directory()):
                    try:
                        image = cv2.imread(filename)
                        self.faces_detected[os.path.basename(filename)] = self.handleImage(image, filename)
                    except Exception as e:
                        continue
                        print('Failed to extract from image: {}. Reason2: {}'.format(filename, e))
        finally:
            self.write_alignments()

**Comment by Clorr** [comment]
Can you directly edit the file, it will make a pull request that we can review. Thanks

**Comment by mansonami** [comment]
has changed it through git commit.

**Comment by Clorr** [comment]
sry, I don't understand

**Comment by Clorr** [comment]
seems to be fixed in #262
