### ISSUE TITLE
Latest commit breaks training.

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#268]
I made a pull before starting a training session:

Loading Trainer from Model_Original plugin...
__init__() takes from 4 to 5 positional arguments but 6 were given

I made a `git reset --keep HEAD@{1}` to get back and it works again.

**Comment by Clorr** [comment]
Should be fixed, can you confirm?

**Comment by Kirin-kun** [comment]
Yes, it's fixed.

**Comment by Kirin-kun** [comment]
Reopening, because it breaks at conversion now: 

Failed to convert image: ...0255.png. Reason: '<' not supported between instances of 'NoneType' and 'int'

**Comment by Clorr** [comment]
Can you remove the `try: except:` in convert.py and provide the full exception message? Otherwise provide the command line options you are using, thx

**Comment by Kirin-kun** [comment]
python faceswap.py convert -i H:\Fakes\pics -o H:\Fakes\pics\merged -m H:\Fakes\model -b 20 -e 30 -D cnn

```
  0%|                                       | 11/4820 [00:00<00:47, 100.73it/s]Traceback (most recent call last):
  File "c:\users\kirin\faceswap\faceswap.py", line 29, in <module>
    arguments.func(arguments)
  File "c:\users\kirin\faceswap\lib\cli.py", line 87, in process_arguments
    self.process()
  File "c:\users\kirin\faceswap\scripts\convert.py", line 199, in process
    self.convert(converter, item)
  File "c:\users\kirin\faceswap\scripts\convert.py", line 224, in convert
    for idx, face in faces:
  File "c:\users\kirin\faceswap\lib\cli.py", line 146, in get_faces_alignments
    if face.r != 0: image = rotate_image(image, face.r)
  File "c:\users\kirin\faceswap\lib\utils.py", line 37, in rotate_image
    if angle < 0: angle = sum((360, angle))
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by Clorr** [comment]
Ah... Do you use a previously generated alignments.json? Because the rotation is likely to be missing. I can check how to handle that.

CC @torzdf

**Comment by torzdf** [comment]
Are you converting with frames you extracted with an older version?

**Comment by Kirin-kun** [comment]
Probably. I extracted yesterday, then this morning pulled the repo and tried to train : it errored as mentioned first in the PR.  I then reverted my repo and trained. 

I re-pulled it to test the earlier fix and restarted the training correctly, so I let it run.

Then I went on to convert: boom.

**Comment by torzdf** [comment]
Basically the alignments.json file had to change a little bit. @Clorr would you like me to code something in? It seems a bit obsolete to handle backwards compatibility as there should only be a small window.

@Kirin-kun the easiest fix would be to open your alignments.json and do a find replace all:

Look for:

> [
>     {

Replace with:

> [
>     { "r": 0,

If you are using notepad++, go to find replace, check the box which says "Extended(\n,\r,\t,\0,\x...)

and find:

> [\n    {\n

replace with:

> [\n    {\n      "r": 0,\n


Alternatively you can re-extract the frames to generate a new alignments.json

**Comment by torzdf** [comment]
goddamit, spaces got stripped...

**Comment by Clorr** [comment]
Isn't it possible to give a default value? Or just to test for None?

**Comment by torzdf** [comment]
It is given a default value... if an alignments.json value isn't present. 2 mins, I'll put in a fix

**Comment by Kirin-kun** [comment]
Well, it can be useful to allow people to re-use their previously extracted data to continue a training session or try another trainer. I have a set of  training data on which I test original, gan and gan128 to see the differences and various convert settings.

**Comment by torzdf** [comment]
I've put in a pull request to apply a default value of 0. Hopefully it will be added soon. Very quick test appears to have fixed the issue.

Any problems, let me know

Cheers.

**Comment by Clorr** [comment]
@kirin-kun ok for you?

**Comment by Kirin-kun** [comment]
Ok, for me. I pulled the last commit and it converted without a hitch.

Can be closed.
