### ISSUE TITLE
Histogram matching overreach?

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#270]
Not sure if it's unavoidable (and it's not the optimal use case), but when the face is partially hidden, the color of the obstacle, if really different from the colors of the face, spills into the converted face in patches with histogram matching:

With Seamless and no histogram matching (a bit blurry on the border, but that's to be expected):

![tae0256a](https://user-images.githubusercontent.com/36699120/37245935-5e508450-24a0-11e8-80de-adda4cdfe2aa.png)

Without Seamless but with histogram matching, becomes a leper:

![tae0256](https://user-images.githubusercontent.com/36699120/37245941-70d3e2e8-24a0-11e8-8bc7-49e421e2783a.png)

With Seamless AND histogram matching: 

![tae0256c](https://user-images.githubusercontent.com/36699120/37245997-7594c0a8-24a1-11e8-94c2-e6ff4a0524b2.png)

Maybe if the color deviates too much, it can be ignored?

**Comment by oatssss** [comment]
How do you detect that the color deviates too much though?

**Comment by iperov** [comment]
same problem
![37238911-ea9ea790-2449-11e8-8e44-724d7aa98104 1](https://user-images.githubusercontent.com/8076202/37251001-0780ed54-2522-11e8-9a1f-068452d788fd.png)

**Comment by Kirin-kun** [comment]
@oatssss I don't know precisely. If we have an histogram of the colors, there should be a peak corresponding to the "odd" color(s). With setting a threshold, you could drop them before doing your matching.

Just a suggestion, I'm not knowledgeable enough in image processing to know if it's possible or not.

**Comment by Kirin-kun** [comment]
On this frame, landmarks debug shows this:

![tae0256_0](https://user-images.githubusercontent.com/36699120/37256390-55b7a12e-255a-11e8-9b93-9232bf86e402.png)

I suppose the landmarks for mouth and chin are defaults calculated relatively to eyes and nose? The chin is much shorter than the real one.

Would there be a way to store in the alignments file which landmarks were effectively detected, and then at convert time, cut them out? I don't know if the face detector is able to output that information.

**Comment by oatssss** [comment]
@Kirin-kun That's an interesting idea, we need a method to detect which landmarks weren't effectively detected though. Dlib [doesn't have this feature out-of-the-box](https://github.com/davisking/dlib/issues/718). We could do what you suggest and have some threshold for the ratio of distances between eyes/nose vs chin/mouth but this seems very specific to your use case where the mouth is covered. Training an another classifier as suggested by the dlib author may be the way to go.

**Comment by Kirin-kun** [comment]
@oatssss it would probably be also useful with other kind of obstacles, like hair in front of eyes, hats covering eyebrows, scarves, in order to avoid for their color to spill on the color correction.

**Comment by bryanlyon** [comment]
I wonder if we can use the mask from GAN for color matching too.

**Comment by Kirin-kun** [comment]
Also, I'm not sure why it appears in blotches. That it would show on the edges of the merged face would be understandable, but why does it appear between the eyes or on the cheeks?
