### ISSUE TITLE
IAE Plugin model not working

### ISSUE THREAD

**Issue by babilio** [deepfakes/faceswap#274]
I tried running the new IAE model here and I am getting this error.

My input was 
python faceswap.py train -A E:\...\aligned -B E:\...\aligned -m E:\data\models\trbl -p -t IAE -bs 128

Loading Trainer from Model_IAE plugin...
__init__() takes from 4 to 5 positional arguments but 6 were given

**Comment by Kirin-kun** [comment]
Also, should be mentioned it is not compatible with previously trained original model:

```
Failed loading existing training data.
You are trying to load a weight file containing 7 layers into a model with 4 layers.
```

Will have to start from scratch.

**Comment by seranus** [comment]
you can load partial weights into Keras, haven't tested it 

https://keras.io/models/about-keras-models/

`model.load_weights(filepath, by_name=False): loads the weights of the model from a HDF5 file (created by  save_weights). By default, the architecture is expected to be unchanged. To load weights into a different architecture (with some layers in common), use by_name=True to load only those layers with the same name.`

**Comment by Clorr** [comment]
Ah I assumed it was ok, did not test. However that's not a bad thing as I will add a suffix to distinguish these model files from original at the same time of fixing

**Comment by JayantPythonLover** [comment]
Here's what you can do to fix this.

Go to plugins/Model_IAE/ folder and open the Trainer.py folder.

Replace

> def __init__(self, model, fn_A, fn_B, batch_size=64):

with > 

def __init__(self, model, fn_A, fn_B, batch_size, *args):

----

And yes, the model files for the IAE model are different from the original. So you will need to create a new folder for those and start the process anew.

**Comment by Clorr** [comment]
Your fix is merged

Important notice: I renamed the model files so that users who try this don't overwrite their original model
