### ISSUE TITLE
Got 6GPU's, faceswap only works with one

### ISSUE THREAD

**Issue by Crypt1cBunny** [deepfakes/faceswap#282]
## Expected behavior

*When I pass on the -g parameter with a value of 6, I would expect 6GPU's to be processing*

## Actual behavior

*Only one GPU is found *

`o callmulti_gpu_modelwithgpus=2, we expect the following devices to be available: ['/cpu:0', '/gpu:0', '/gpu:1']. However this machine only has: ['/cpu:0', '/gpu:0']. Try reducinggpus.`

**In the above message I tried with -g 2**

## Steps to reproduce

*Just run with -g 6*

## Other relevant information

- ** Linux (Ubuntu 16.04
- **Python 3.5.2
- **Faceswap version:** f6cb3941ad688a77f1c7e72b053a3429345167e4
- **Faceswap method:** GPU

When I added the following to the code:

`from tensorflow.python.client import device_lib print(device_lib.list_local_devices())`

I can see there are 6 GPU's detected:

`80 Ti, pci bus id: 0000:06:00.0, compute capability: 6.1) [name: "/device:CPU:0" device_type: "CPU" memory_limit: 268435456 locality { } incarnation: 17778470088000163189 , name: "/device:GPU:0" device_type: "GPU" memory_limit: 10968950375 locality { bus_id: 1 } incarnation: 7118498837639450771 physical_device_desc: "device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1" , name: "/device:GPU:1" device_type: "GPU" memory_limit: 10968950375 locality { bus_id: 1 } incarnation: 13404147881441786455 physical_device_desc: "device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1" , name: "/device:GPU:2" device_type: "GPU" memory_limit: 10968950375 locality { bus_id: 1 } incarnation: 2884322652126053938 physical_device_desc: "device: 2, name: GeForce GTX 1080 Ti, pci bus id: 0000:03:00.0, compute capability: 6.1" , name: "/device:GPU:3" device_type: "GPU" memory_limit: 10968950375 locality { bus_id: 1 } incarnation: 12057677249504026410 physical_device_desc: "device: 3, name: GeForce GTX 1080 Ti, pci bus id: 0000:04:00.0, compute capability: 6.1" , name: "/device:GPU:4" device_type: "GPU" memory_limit: 10968950375 locality { bus_id: 1 } incarnation: 2997181041019046505 physical_device_desc: "device: 4, name: GeForce GTX 1080 Ti, pci bus id: 0000:05:00.0, compute capability: 6.1" , name: "/device:GPU:5" device_type: "GPU" memory_limit: 10968950375 locality { bus_id: 1 }`

**Comment by Kirin-kun** [comment]
Looks like a problem with keras, according to google.

And holy shit. 6 GTX 1080ti? Even if it's a cloud provided rig, that must cost an arm and a leg.

**Comment by Clorr** [comment]
According to https://keras.io/utils/#multi_gpu_model , keras should behave well with that much gpus. Check if you have the equivalent in keras of the `list_local_devices`.

FYI source of keras multi gpu is [here](https://github.com/keras-team/keras/blob/master/keras/utils/multi_gpu_utils.py), maybe you will find a way to see where your error comes from. Keep us posted if you find

**Comment by iperov** [comment]
btw you can train 6 different models simultaneosly
by set env var
CUDA_VISIBLE_DEVICES="0"

**Comment by Crypt1cBunny** [comment]
What do you exactly mean 6 different models @iperov ? You mean one training session on 6GPU's ?

**Comment by iperov** [comment]
@Crypt1cBunny 1 session per 1 gpu. 6 different folders with different data's
set CUDA_VISIBLE_DEVICES="0"
python faceswap.py ...

set CUDA_VISIBLE_DEVICES="1"
python faceswap.py ...

**Comment by Kirin-kun** [comment]
@Crypt1cBunny he means that you can launch 6 faceswap at the same time.

The env variable tells the library which GPU bind the process to (0, 1, 2, 3, 4 or 5)

**Comment by bryanlyon** [comment]
With Linux, please make sure that your backend ~/.keras/keras.json is using tensorflow.  It looks like it's using something else as it's backend.  Right now, mutli GPU support only works with the tensorflow backend,  By default it's using torch and will only see 1 GPU.

**Comment by Crypt1cBunny** [comment]
It's definitely set to tensorflow.

**Comment by bryanlyon** [comment]
If it's set to tensorflow, it should be seeing all the same GPUs as tensorflow since Keras literally just calls the fuction in tensorflow.  If your backend is set correctly, please make sure that you're not using sudo or virtualenv.

**Comment by Crypt1cBunny** [comment]
Looks like there is a bug in keras.

https://github.com/keras-team/keras/issues/8213

I can see someone forked and fixed it, however looks like it isn't in the latest version. I tried to edit the local files with this patch (dirty), but couldn't get it working yet.

Python is all new to me :-)

**Comment by bryanlyon** [comment]
This is strange, because it works for me in Windows and Ubuntu.

I don't think that this is a keras bug, since it's actually calling the backend (tensorflow) directly.  In fact, the bug that you submitted showed all the video cards detected, but not working due to showing a different name.  In your case, faceswap is not detecting additional video cards at all.

Can you post a log of the whole startup of faceswap through to the error?  That may help me discover what is happening.

**Comment by Crypt1cBunny** [comment]
`/usr/local/lib/python3.5/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Model A Directory: /home/riggy/fakes/output/putin
Model B Directory: /home/riggy/fakes/output/trump
Training data directory: /home/riggy/fakes/models
2018-03-12 19:47:50.885142: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
2018-03-12 19:47:51.321063: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-12 19:47:51.321929: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties:
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.607
pciBusID: 0000:01:00.0
totalMemory: 10.91GiB freeMemory: 10.75GiB
2018-03-12 19:47:51.321949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
Loading data, this may take a while...
Loading Model from Model_Original plugin...
To call `multi_gpu_model` with `gpus=6`, we expect the following devices to be available: ['/cpu:0', '/device:GPU:0', '/device:GPU:1', '/device:GPU:2', '/device:GPU:3', '/device:GPU:4', '/device:GPU:5']. However this machine only has: ['/job:localhost/replica:0/task:0/device:CPU:0', '/job:localhost/replica:0/task:0/device:GPU:0']. Try reducing `gpus`.`

This is the output with the latest version of keras (master, did a checkout hour ago).

**Comment by bryanlyon** [comment]
Hmm, this is odd.

What about echo $CUDA_VISIBLE_DEVICES

or the deviceQuery from CUDA?

**Comment by Crypt1cBunny** [comment]
echo $CUDA_VISIBLE_DEVICES => result empty

deviceQuery => https://pastebin.com/6wuujMy8

**Comment by bryanlyon** [comment]
The weird part is that TensorFlow shows that only one GPU is found in the log you posted above, yet when run separately it's showing all the GPUs.

I'm checking this out to see what other troubleshooting or logs might help, but this seems to be caused outside of faceswap.

Can you try running again with first setting CUDA_VISIBLE_DEVICES="0,1,2,3,4,5" and see if that helps?

**Comment by Crypt1cBunny** [comment]
Same, settings the env variable has no impact.

**Comment by Clorr** [comment]
Can you provide keras and tensorflow version? (I assume it is tensorflow-gpu?)

**Comment by Crypt1cBunny** [comment]
Is there a way to easily find these?

**Comment by bryanlyon** [comment]
Did you install from the correct requirements.txt files?

Each version of Python and Cuda needs the matching file.

For Python 3.5 and Cuda 8 it is as follows:
requirements-gpu-python35-cuda8.txt
pathlib==1.0.1
scandir==1.6
h5py==2.7.1
Keras==2.1.2
opencv-python==3.3.0.10
tensorflow-gpu==1.4.0
scikit-image
dlib
face_recognition
tqdm

For Python 3.6 and Cuda 9 it is as follows:
requirements-gpu-python36-cuda9.txt
pathlib==1.0.1
scandir==1.6
h5py==2.7.1
Keras==2.1.2
opencv-python==3.3.0.10
tensorflow-gpu==1.5.0
scikit-image
dlib
face_recognition
tqdm

This might be the source of your problem, because if you are using different versions that haven't been tested, it might be loading the wrong libraries.

**Comment by Crypt1cBunny** [comment]
I know I installed the requirements.txt file for cuda8 in the beginning. But is there any way to verify it?

https://gist.github.com/Crypt1cBunny/f8599bb89df960d45b324d9f7beb6966

**Comment by Clorr** [comment]
it is something like `pip list` or `pip freeze` (or pip3 if you are using python3)

**Comment by Crypt1cBunny** [comment]
Jup looks good (pip3 as I'm using python3)

https://gist.github.com/Crypt1cBunny/58a57306087cc42e99366721bd118e83

**Comment by bryanlyon** [comment]
You're running the correct TensorFlow for Cuda 8 and Python 3.5.

What is your 
python3 -V

Did you install Cuda 8? 

I recommend you install all cudnn versions for Cuda 8 (they can exist independently).  All in your Cuda 8 folder.
cudnn-8.0-linux-x64-v5.1.tgz  cudnn-8.0-linux-x64-v6.0.tgz  cudnn-8.0-linux-x64-v7.1.tgz

**Comment by Clorr** [comment]
Hmm, you have both tensorflow and tensorflow GPU, not sure if it is safe...

**Comment by Clorr** [comment]
@Crypt1cBunny can you uapdte us so that we know if it's ok or not?
