### ISSUE TITLE
GAN128 trainer broken

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#284]
Can't train with GAN128 anymore:

Loading Model from Model_GAN128 plugin...
__init__() takes 2 positional arguments but 3 were given

Same old.

Original, GAN and IAE have been updated to take the gpus parm. 

Not GAN128.

**Comment by Clorr** [comment]
Add a fix, and your name will live in a forever glory as contributor to this repo ;-)

**Comment by Clorr** [comment]
Likely fixed by #280

**Comment by Kirin-kun** [comment]
Fixed!
