### ISSUE TITLE
question: GAN in this repo

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap#286]
May i know GAN in this repo have include the Unsupervised segmentation mask?? if yes, when convert how we activate this function?

**Comment by oatssss** [comment]
It's automatic when you use the converter with a gan trained model. I haven't been getting good results with gan though. The kinks still need to be worked out.

**Comment by ruah1984** [comment]
Try a few model for GAN, unable to get a good result after convert. Preview is good, but after convert the result is bad

**Comment by ruah1984** [comment]
how about the mask refinement ?
