### ISSUE TITLE
LowMem trainer no longer available?

### ISSUE THREAD

**Issue by 3xtr3m3d** [deepfakes/faceswap#290]
with latest code downloaded today i'm getting below error when trying to use lowmem trainer

`faceswap.py train: error: argument -t/--trainer: invalid choice: 'LowMem' (choose from 'GAN', 'GAN128', 'IAE', 'Original')`

**Comment by Kirin-kun** [comment]
It seems the LowMem model hasn't been ported to the plugin infrastructure. But if you look at the code, the differences between LowMem and Original are very few. 

The ENCODER_DIM (aka nodes) variable is lowered to 512 and there's a commented line 
`x = self.conv(1024)(x)`

Really, that's about all. 

I suspect you could just use notepad and savagely change the Original model and it will work.

**Comment by 3xtr3m3d** [comment]
Thanks. yeah already got it working but this should be fix

**Comment by Clorr** [comment]
Merged #292
