### ISSUE TITLE
Extract error: Extract() Takes 4 Positional Arguments but 5 were given 

### ISSUE THREAD

**Issue by gessyoo** [deepfakes/faceswap#294]
**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

## Expected behavior
Extract faces from jpg images

## Actual behavior
No images extracted, error message: Failed to extract from ***.jpg Reason: Extract() takes 4 positional arguments but 5 were given 

## Steps to reproduce: python facewap.py extract -A (dir) -B (dir) -D cnn

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*
The extract process worked as expected with an earlier build.
## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows 10 x64
- **Python version:** Anaconda 3.6.4
- **Faceswap version:** commit hash or version number: Extract # 242
- **Faceswap method:** GPU 
- **Other related issues:**  GPU active (20%-30% load) during extract process, but no images are extracted.  Prior versions of faceswap.py extract worked as expected.  Dlib and OpenCV compiled to use CUDA (9.1). 
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by bryanlyon** [comment]
This issue is missing critical information, please read the instructions and at the requested information.  We can't help you without knowing what is happening.

**Comment by Clorr** [comment]
There is a 5th argument added by #242 but it seems you're using an older version of `scripts/extract.py`
