### ISSUE TITLE
Improve command line usage

### ISSUE THREAD

**Issue by Clorr** [deepfakes/faceswap#3]
Adding a command line args parsing with an help would be great !

Preferably with `argparse`

**Comment by deepfakes** [comment]
Also if you have ideas for a better folder structure, feel free to suggest!

**Comment by Ganonmaster** [comment]
I would propose to keep the different "actions" or steps in their current files (`train.py`, `convert.py`, `extract.py`) and then allow for model data directory names to be used as input/output arguments. Example:

`train.py --data-dirs="./data/trump;/data/cage" --model-dir="./models/trump-cage/"`

**Comment by deepfakes** [comment]
seems fine to me

**Comment by Ganonmaster** [comment]
`extract.py` now has basic command line options for specifying paths and verbose output. I'm going to be looking at `convert.py` next.

**Comment by Ganonmaster** [comment]
Merged #13 and #14 which takes care of the conversion script.

**Comment by Ganonmaster** [comment]
Updated `train.py` and accidentally pushed results to upstream. I'm very drunk, so if someone could verify if the scripts are still working, please do so.

Now that all these scripts are using the same basic classes, we can probably consolidate them to a single file so they can be called from a single entrypoint. (like how `git` has several subcommands, faceswap.py could have `extract`, `train` and `convert` commands) That's my next objective, which I will be looking to tackle tomorrow. (after the hangover passes)

**Comment by Clorr** [comment]
I pushed also accidentally yesterday and I was not even drunk...

No problem, have a look tomorrow. Me I'll be on the way back to my family...

**Comment by Yutsa** [comment]
If we could manage to create a program with different commands it would be way easier to use indeed.

Something like `faceswap extract`, `faceswap train` and `faceswap convert`

**Comment by Ganonmaster** [comment]
Thank you, @Yutsa for implementing this functionality.

**Comment by Ganonmaster** [comment]
This issue should probably be closed and split up into more specific issues since we have some basic command line usage now.
