### ISSUE TITLE
two tricks to improve results.

### ISSUE THREAD

**Issue by yangchen8710** [deepfakes/faceswap#30]
1.
adjust the new face's average color as same as the old face's

2.
use the old face's edge to apply a smoothing mask to new one

![before](https://user-images.githubusercontent.com/26502257/34369346-05037d50-eaf6-11e7-9336-bd2552935492.jpg)
![after](https://user-images.githubusercontent.com/26502257/34369380-3b1aa97c-eaf6-11e7-915f-6d8ea8d7ad44.jpg)

![887989700](https://user-images.githubusercontent.com/26502257/34373419-ed32b1f8-eb15-11e7-97e9-8d829dee4981.jpg)
![new_3](https://user-images.githubusercontent.com/26502257/34376293-f369d8b6-eb25-11e7-9a06-3f0c846445fb.jpg)

**Comment by Apollo122** [comment]
Looks good. Can this be done automatically in the pipeline?

**Comment by yangchen8710** [comment]
This is a result of automatic.

**Comment by Apollo122** [comment]
@yangchen8710
Great. You can make a pull request if it's ready

**Comment by Ganonmaster** [comment]
These changes have been merged. Share your results in the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues)!

**Comment by deepfakes** [comment]
@yangchen8710 many thanks for this amesome contrib!

It's amazing how you did it with such simple approach! I added you as collab on the 2 side projects (playground and models) so you can freely make things move on if you want. On the main project, I let @Ganonmaster handle things as he does this like a boss ;-) But feel free to push other things...

One question though. Does this cover the issues #8 and #16 about masking and alignment ? What should we do with them, close them or continue ?

**Comment by Apollo122** [comment]
I think they should remain being open. So that other people may come and improve those. #8 may use an edit though as it's not the current case anymore

**Comment by Clorr** [comment]
Hmm, we can't let issues opened just for improvement. We already have the faceswap-model for that.

The question is then:
- should we add seamlessclone?
- how is this code on the alignment? Is it worth continuing on #16 ? (Considering pytorch is a heavy dependency)

**Comment by Apollo122** [comment]
Now that you put it like that agreed.
As for the questions, 
yes seamlessclone should be added; 
In my view most significant problem with pytorch is that it's not working for Windows. But there are people working on it. https://github.com/pytorch/pytorch/issues/494
So in time we may get an update
