### ISSUE TITLE
ImportError: No module named pathlib

### ISSUE THREAD

**Issue by nerdprogrammergm** [deepfakes/faceswap#32]
I have already installed pathlib in python3.6:Requirement already satisfied: pathlib in /usr/local/lib/python3.6/dist-packages

Command executed: python3 faceswap.py extract -i ~/faceswap/photo/trump -o ~/faceswap/data/trump

Traceback (most recent call last):
  File "faceswap.py", line 3, in <module>
    from scripts.extract import ExtractTrainingData
  File "/home/ubuntu/data/faceswap/scripts/extract.py", line 2, in <module>
    from lib.cli import DirectoryProcessor
  File "/home/ubuntu/data/faceswap/lib/cli.py", line 6, in <module>
    from lib.utils import get_image_paths, get_folder, load_images, stack_images
  File "/home/ubuntu/data/faceswap/lib/utils.py", line 4, in <module>
    from pathlib import Path
ImportError: No module named pathlib

Can anyone help me out with this issue?

**Comment by yangchen8710** [comment]
use python3.6 instead of python3?

**Comment by Ganonmaster** [comment]
Make sure you are running python 3.6 or otherwise try adding `pathlib` through pip:

```bash
pip install --upgrade pathlib
```

**Comment by Ganonmaster** [comment]
Otherwise, try running the script in a virtualenv as described in the guide.

**Comment by nerdprogrammergm** [comment]
Thanks for quick reply.
I figured out the issue and now working on further part.
Presently I am getting this error:
Using TensorFlow backend.
usage: faceswap.py [-h] {extract,train,convert} ...
faceswap.py: error: invalid choice: 'extract/trump' (choose from 'extract', 'train', 'convert')

**Comment by lukaville** [comment]
Most likely you are trying to start the script with invalid arguments. You have to specif 'extract', 'train' or 'convert' right after `faceswap.py`

**Comment by nerdprogrammergm** [comment]
I am following the instructions mentioned on this lnk:https://github.com/deepfakes/faceswap/blob/master/USAGE.md

which says to execute the following command to train the model!
python3.6 faceswap.py -A ~/faceswap/data/trump -B ~/faceswap/data/cage -m ~/faceswap/models/

**Comment by lukaville** [comment]
Looks like it's a typo in the doc. Use `python faceswap.py train -A ~/faceswap/data/trump -B ~/faceswap/data/cage -m ~/faceswap/models/` instead.

**Comment by nerdprogrammergm** [comment]
Got the issue, its the "train" missed out from the command!
This command should be used to train the model: python3.6 faceswap.py train -A extract/trump -B extract/cage -m models -p 
@lukaville @yangchen8710  @Ganonmaster

**Comment by nerdprogrammergm** [comment]
Yes, thanks man. Have you tried to setup this on aws ec2 p2 instance?
Overthere, I am dealing with the issue for cuda9, got to wait until tensorflow support cuda9.
For cuda8, I tried but somewhere dlib through error about lib related to 9.so . Try to troubleshoot it but found that its tensorflow which is not compatible with cuda9 yet :/
You got any solution for this?

**Comment by nerdprogrammergm** [comment]
There is also a typo in the doc for converting:
 Using TensorFlow backend.
usage: faceswap.py [-h] {extract,train,convert} ...
faceswap.py: error: invalid choice: 'data/trump' (choose from 'extract', 'train', 'convert')


Proper command to convert is: python3.6 faceswap.py convert -i data/trump -o output/trump -m models

@Ganonmaster  @yangchen8710 

Sorry for tagging ya all, m new to github!

**Comment by lukaville** [comment]
@nerdprogrammergm I successfully used floydhub, I made a post about it https://www.reddit.com/r/deepfakes/comments/7mgpki/floydhub_cloud_training/

**Comment by nerdprogrammergm** [comment]
Cool @lukaville , great job.
Will give it a try ;)
In the mean time can you have a look on this link and help me out?
https://github.com/deepfakes/faceswap-playground/issues/10
Thanks once again.

**Comment by Ganonmaster** [comment]
The doc changes have been merged. I'll look at your other issue shortly. 👍
