### ISSUE TITLE
Unused variables in histogram matching

### ISSUE THREAD

**Issue by kimphysics** [deepfakes/faceswap#322]
In the `hist_match` of Convert_Masked.py, `masked_source` and `masked_template` are defined but not used. Therefore, the mask is never applied to the template image (including `get_new_face`). Is this behaviour intended? 

Simply replacing `masked_template = template * mask` to `template = template * mask` in `hist_match` gives much better results, removing white spots commonly appearing on the face with `-mh` option.

**Comment by Apollo122** [comment]
yeah seems like a bug. although `mask ` is used only for GAN convert and this bug shouldn't have any effect on other trainers. Which trainer did you tried it with?

**Comment by kimphysics** [comment]
Apparently I made a mistake T_T.. I'm using Original trainer. Image sets used were different, please forget about 
> hist_match gives much better results
Should I close this issue? Maybe this would be accidentally helpful for GAN users.

**Comment by Clorr** [comment]
If there is a bug, it should be corrected. What do you think @bryanlyon ?

**Comment by kvrooman** [comment]
addressed in convert refactor
