### ISSUE TITLE
Consider using face_segmentation library

### ISSUE THREAD

**Issue by alexgan04** [deepfakes/faceswap#324]
Consider using https://github.com/YuvalNirkin/face_segmentation library for better area coverage of the face

**Comment by Kirin-kun** [comment]
Already been mentioned in #306

**Comment by iperov** [comment]
There is no examples of side faces and how mask will flickering in video.

**Comment by agilebean** [comment]
any updates on this?
i think a better face segmentation would greatly improve results for visual perception and higher versatility!

**Comment by iperov** [comment]
There is no neural model to morph segments of one face to other face . For example area of skin of source face smaller than target face, and target face has more hair. You think autoencoder will draw more skin and hair ? No.
Therefore subj is not relevant.

**Comment by bryanlyon** [comment]
All devs are currently busy on our own priorities.  We welcome PRs if you add support.
