### ISSUE TITLE
OOM with GTX 980 while training

### ISSUE THREAD

**Issue by Hunterwolf88** [deepfakes/faceswap#327]
`tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,3,64,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: training_1/Adam/gradients/model_1/conv2d_1/convolution_grad/Conv2DBackpropFilter-0-TransposeNHWCToNCHW-LayoutOptimizer = Transpose[T=DT_FLOAT, Tperm=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](_arg_input_4_0_0/_477, PermConstNHWCToNCHW-LayoutOptimizer)]]
`
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.48                 Driver Version: 390.48                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 980     Off  | 00000000:01:00.0  On |                  N/A |
|  0%   46C    P0    58W / 196W |   3868MiB /  4040MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1136      G   /usr/lib/xorg/Xorg                           640MiB |
|    0      1781      G   /opt/teamviewer/tv_bin/TeamViewer             17MiB |
|    0      1958      G   compiz                                       456MiB |
|    0      2391      G   ...-token=DAF6E1B7D2D5B5E9DFDF4E432544C3CF    63MiB |
|    0     17774      C   python                                      2672MiB |
+-----------------------------------------------------------------------------+

```

How can this be avoided? I actually tried almost everything:
different versions of tensorflow-gpu, installed from pip, from conda, and from source code
different versions of python (Anaconda)
reducing batch size until 2
different versions of cuda / cudnn
uninstall/reinstall nvidia cuda and cudnn and drivers

**Comment by torzdf** [comment]
Try:
Run with low-mem model (if not already).
Kill X-Server entirely and run from console.

**Comment by enmoment** [comment]
same problem in GTX 750ti。

**Comment by enmoment** [comment]
I ran the script  with  gtx750ti 2Gb . I can run the extract script correct ,but when I run the train script , the oom happens. I tried run the script in the text command line and with the -bs 32 or -bs 16.But it’s not working.

**Comment by bryanlyon** [comment]
Only lowmem can work on 2gb of vram.  Also, it requires the full 2gb, so you cannot be running anything else like window managers or graphics like compiz or aero.  Even just a framebuffer might be too much.  When dealing with that little vram, it's very hard to fit all the data needed for training.

The original is not currently working in 4gb of vram either.

**Comment by ramontheleo** [comment]
Previously the scripts worked using 2gb gtx960. But after using the latest commit, I can't even extract the image even by resizing the image to 500x500, the memory seems to be used up by something else.

**Comment by jasterph** [comment]
Im using the same card. set -bs to 32. and it will work.
