### ISSUE TITLE
Filter image doesn't work?

### ISSUE THREAD

**Issue by frosty3907** [deepfakes/faceswap#328]
Tried using a filter image to remove other actors from the scene but it doesn't seem to work.
Would be great if it did since my current workflow involves manually masking out other actors in after effects which is time consuming.

**Comment by Kirin-kun** [comment]
Did you try with the nfilter? See #262 

You can add a pic of the person you do not want (-n)

**Comment by bryanlyon** [comment]
I find that no single filter image will ever work perfectly.  The goal is to reduce the time you spend pruning your extract folder.  I recommend getting at least a few pictures of everyone in the video and using -n like @Kirin-kun said on all the faces you don't want.

Unless you're just trying to build your images for training, then I use the -k with a couple photos of your target face.

**Comment by frosty3907** [comment]
neat I'll give those a try, didn't see them in the -h output so I didn't know they existed.
