### ISSUE TITLE
CAN I stop "training" after epoch "number"? automatically

### ISSUE THREAD

**Issue by LLALLA0925** [deepfakes/faceswap#330]
If  I do train.py -ep 400, this sequence stops at 399, and do NOTHING!!
I want to make train.py to stop( like I push "ENTER" or "ctrl + c" ) when epoch reachs to 400... 
and get out to CMD(i am using cmd version python) to use other COMMAND without "ENTER"...

I am not good at ENGLISH and python.
Can u help me?

**Comment by andykdy** [comment]
I haven't tested this but it should work. 
First time submitting a PR.

**Comment by torzdf** [comment]
@LLALLA0925 I have a PR currently up for testing (#367) that finishes training when target epochs are reached. It only works, however, if the -p (preview) flag is enabled. Feel free to test.

**Comment by torzdf** [comment]
see #372

**Comment by torzdf** [comment]
Fixed in latest commit for preview mode
