### ISSUE TITLE
GUI breaks faceswap.py on non-display machines.

### ISSUE THREAD

**Issue by fat-tire** [deepfakes/faceswap#334]
I guess this is for @torzdf primarily.

A few quick observations on that recent [GUI pull](https://github.com/deepfakes/faceswap/commit/2c11eb164988b6beda5805d2c5034ac91982cc70):

1.  As stated in #325, Linux does crash without tk support in python installed  On Ubuntu/Mint/debian for example you'll need to do a `sudo apt install python3-tk`.

2.  You also get an error if you're running on a system without an active x session (such as w/ a headless server-- google cloud instance, etc.)

`_tkinter.TclError: no display name and no $DISPLAY environment variable`

Reverting that commit fixes the issue.  The error occurs even when you don't use the "gui" command.  Probably should do a few checks:

*  If the DISPLAY env variable isn't set, [skip the creation of the gui](https://github.com/deepfakes/faceswap/blob/2c11eb164988b6beda5805d2c5034ac91982cc70/faceswap.py#L29).

*  Ditto if the gui argument isn't there.  This should be runnable w/ any dependency on a ui session.  Could even bypass the import of tk if it isn't installed, no display, (or gui command isn't being used) as it uses memory...

Aside from that this looks like a cool addition.  Nice job.  Any reason you're not using a prettier toolkit?  Doesn't qt look native in Linux/Windows/Mac OS these days?

**Comment by dfacct** [comment]
GUI also breaks faceswap.py if you aren't currently in the faceswap directory, which was never a requirement before.
`_tkinter.TclError: couldn't open "icons/open_folder.png": no such file or directory`

**Comment by torzdf** [comment]
Of, thanks, I'll look to push commits to squash these today

**Comment by torzdf** [comment]
@fat-tire 

> Aside from that this looks like a cool addition. Nice job. Any reason you're not using a prettier toolkit? Doesn't qt look native in Linux/Windows/Mac OS these days?

Yeah, there are definitely prettier tools out there. tkInter is used as it is part of the standard Distribution. I wanted to avoid adding more requirements where necessary. Whether it should still be part of the standard distro is another question. Ultimately, though, it gets the job done, even if it looks like it was built for WindowsXP ;)

Of course, if someone wants to make a GUI in qt, there is nothing stopping them adding another option ;)

**Comment by fat-tire** [comment]
[Updated](https://github.com/deepfakes/faceswap/pull/336#issuecomment-379501812) #336 with some errors I saw.

**Comment by fat-tire** [comment]
And this is fixed now so I'm going to close it.  Thanks!
