### ISSUE TITLE
import error libcublas.so.9.1 (I have Cuda 9.0)

### ISSUE THREAD

**Issue by Hunterwolf88** [deepfakes/faceswap#340]
`ImportError: libcublas.so.9.1: cannot open shared object file: No such file or directory`

I have only Cuda 9.0 installed right now, but I had Cuda 9.1 installed in the past.
How to overcome this?

environment installed from requirements-gpu-python36-cuda9.txt

**Comment by bryanlyon** [comment]
Install cuda 9.1 as well.  Cuda supports multiple parallel installations.

**Comment by Hunterwolf88** [comment]
isn't this going to create issues with tensorflow?

**Comment by Hunterwolf88** [comment]
solved installing also cuda 9.1.

thanks :)
