### ISSUE TITLE
GUI v0.2.0a Ready for testing...

### ISSUE THREAD

**Issue by torzdf** [deepfakes/faceswap#345]
Hi. Thanks to some help from @AbysmalBiscuit  I now have version 0.2.0 ready for testing, and there is quite a lot added. I'm putting it here before I raise a PR as I want to make sure I iron out any bugs that may impact the rest of the scripts, so I'm looking for testers please, with a view to getting this merged into the main repo soon. Expect bugs. There will be bugs.

For background see here: #325. In a nutshell this is a cross-platform GUI for faceswap.py

#### New since last version:

- More robust subprocess handling
- Layout changes
- GUI support for tools.py (thanks @AbysmalBiscuit)
- Tooltips
- Graphing (finally!) - You will need to install the matplotlib python module
- Console out within GUI
- Preview pane within GUI
- Size adjustable panels

Pressing 'Enter' on the Preview Window will not work within the GUI. You must press the 'Terminate' button to stop and save (It may look like it's hanging the GUI, but that's just it doing it's thing).

As before, use at your own risk, and please report bugs/feature requests here. Bug fixing will take priority and any new features will probably not go in until v0.3.0

Run it with:

`python faceswap.py gui`

When posting bug reports, please include the full traceback (if relevant). You should be able to pull it from the embedded console out, but if you can't the gui can be run in debug mode as:

`python faceswap.py gui -d`

This will print the console out to the main terminal window instead of the embedded window in the GUI.

Please clone from my master branch:
https://github.com/torzdf/faceswap.git

You can raise issues there or in this message.

#### Known issues:

- DPI for high resolution monitors (will look at for next release)
- Sometimes graphs don't reset when training is terminated. This is annoying but not game changing (will look at for next release)
- ToolTips don't work on macOS (will look at for next release)
- FIXED: ~~~GAN not graphing.~~~
- FIXED: ~~~Warning output when generating graphs~~~
- FIXED: ~~~Windows version not saving model when terminating training~~~
- FIXED: ~~~tools.py did not actually load the GUI~~~
- USER ACTION REQUIRED. ~~~~macOS fails to detect DISPLAY.~~~~ macOS needs to have xquartz installed to work. Will add hint in error message
- FIXED: ~~~macOS locks up when changing tabs.~~~

#### Feature Requests and possible implementations (to be looked at for next release):

- Extract video frames and recompile swapped frames back to video
- Include trend stats with graph (e.g average loss over each quarter, rolling average etc)
- For the GAN trainer, add Preview tabs for: Masked, Raw, and Mask Previews
- Keep a continuous graph of all training activity (maybe store data in a sqlite db?)
- Current session, and all time spent training record (e.g. 24 hours current session ; 160 hours total)
- Save graphs to file
- Zoom in/out graphs
- Add progress bar
- Load tools.py into the main faceswap.py gui

#### Screenshots:
X-Forwarding on Windows from Ubuntu:
![gui_preview1](https://user-images.githubusercontent.com/36920800/38684353-694a5710-3e67-11e8-9c48-0a1f8a075736.png)

![gui_preview2](https://user-images.githubusercontent.com/36920800/38684362-70ccc342-3e67-11e8-9134-42e92265e75a.png)

Windows 10 Native:
![guiwin10](https://user-images.githubusercontent.com/36920800/38684430-9ad7fb48-3e67-11e8-9173-828d50009a16.png)

macOS Native:
![screen shot 2018-04-14 at 02 52 29](https://user-images.githubusercontent.com/36920800/38763294-67937170-3f90-11e8-8698-e717ef5a817f.png)

GAN graphing:
![splitgraph](https://user-images.githubusercontent.com/36920800/38750382-ae2c5320-3f4c-11e8-875c-b279464e056c.png)

**Comment by andenixa** [comment]
Could you make it DPIAware @ MS Windows?

**Comment by andenixa** [comment]
Also I think this very minor trick would be found useful by most.
Convert while aligning is super memory intensive specially with cnn and would fail at high resolution. While two step operation of:
 1) find faces&write alignments file 
2) converting 
would never run out of memory.

**Comment by torzdf** [comment]
@andenixa 

> Also could you add video->img and img->video tabs (through ffmpeg). I am not sure what GUI engine you use, but I could add the code for invoking those.

These are scheduled for v0.3.0 :)

**Comment by andenixa** [comment]
I am actually running only 1440p (would probably be 2k). It ait much of a problem with GUI, but preview would also be unscaled which is undesirable. When I had 1080p I still used 125% at MS Windows thus the same issue.
Perhaps that is a fancier way, but the most straight forward would be:

`import sys
import ctypes

mswindows = sys.platform== 'win32'

if mswindows:    
    from ctypes import*
    user32 = ctypes.WinDLL('user32')
    user32.SetProcessDPIAware(False)`

**Comment by torzdf** [comment]
Thanks for the tip. I'm going to see if I can find a more platform agnostic way first, as I'm trying to avoid OS specific code as much as possible.

Feel free to edit your clone and let me know if this works though, because I may end up having to go with it.

**Comment by andenixa** [comment]
Thais true about OS specific but unfortunately DPI thing is king of manifests at Vista/7 (perhaps 8.1). Unless you use QT5 I think.

**Comment by torzdf** [comment]
`Please whatever you do don't make it corrupt the saves`

It definitely doesn't corrupt saves under Linux (well, no more than the standard scripts do anyway). Unfortunately I can't run training on my windows test VM as it doesn't have enough power to get going... well it might do, I just got bored waiting for it to get through it's first iteration!

**Comment by andenixa** [comment]
If you have save&quit option its ok. Actually I think I can bundle faceswap into an executable so there is no need to install python and dependencies for every OS that runs cudnn (with all faceswap code fully exposed).

**Comment by johnc2k** [comment]
Graph does not appear to work with GAN trainer

**Comment by torzdf** [comment]
I haven't tested GAN. I'll need to check the console outputs and see if I can implement.

**Comment by johnc2k** [comment]
Some example output of the GAN trainer:

```
[22:52:31] [0/num_epochs][7] Loss_DA: 0.161376 Loss_DB: 0.208782 Loss_GA: 0.175283 Loss_GB: 0.184821
[22:52:33] [0/num_epochs][8] Loss_DA: 0.174376 Loss_DB: 0.212959 Loss_GA: 0.179937 Loss_GB: 0.181621
[22:52:36] [0/num_epochs][9] Loss_DA: 0.179386 Loss_DB: 0.198652 Loss_GA: 0.183544 Loss_GB: 0.181443
[22:52:39] [0/num_epochs][10] Loss_DA: 0.187953 Loss_DB: 0.201906 Loss_GA: 0.178671 Loss_GB: 0.186508
[22:52:41] [0/num_epochs][11] Loss_DA: 0.172193 Loss_DB: 0.203566 Loss_GA: 0.180436 Loss_GB: 0.182778
[22:52:44] [0/num_epochs][12] Loss_DA: 0.158577 Loss_DB: 0.203690 Loss_GA: 0.176769 Loss_GB: 0.185355
```

**Comment by torzdf** [comment]
Thanks! Hopefully have this patched in the next 30 mins

**Comment by torzdf** [comment]
Ok, I've pushed a patch for this to my dev_gui branch.

I'm not particularly happy with it, although it works. I'll probably clean it up a bit tomorrow and push it over to master, but it should be graphing GAN fine now.

**Comment by ruah1984** [comment]
in GUI mode  under extract tab, how i should use the rotation image. something i need to fill up into the blank>??

**Comment by johnc2k** [comment]
The patch for the GAN Trainer appears to be working fine; Attached is a session from overnight:

<img width="816" alt="gangraph" src="https://user-images.githubusercontent.com/11442993/38722971-9a493fd0-3ef7-11e8-8763-d7cc4602057c.png">

**Comment by torzdf** [comment]
@ruah1984 Rotations changed with this PR: #309 

It still supports the old method, so you could enter either:
`on`
or
`90`
for it to perform as before (these will both check for faces at 90 degree image rotations)

**Comment by torzdf** [comment]
@johnc2k Thanks for the confirmation. The current implementation is a little too 'hard-coded' for my liking, so I'm going to rework it. I'm probably going to split Loss D and Loss G into separate graphs as I notice that their ranges are quite different.

**Comment by johnc2k** [comment]
A couple of feature requests: :)
- For the GAN trainer, add Preview tabs for: Masked, Raw, and Mask Previews
- Keep a continuous graph of all training activity (maybe store data in a sqlite db?)
- Current session, and all time spent training record (e.g.  24 hours current session ; 160 hours total)

**Comment by Apollo122** [comment]
Thank you for your efforts.
Btw there's a bug in gan128 preview. Raw and masked previews are switched. So if you are gonna implement it be sure to swap those outputs.

**Comment by torzdf** [comment]
I've pushed an update to rewrite the graphing area. There a couple of minor bugs (listed in original post), but nothing that can't wait until version 0.3.0. GAN graphing is now split into separate graphs:

![splitgraph](https://user-images.githubusercontent.com/36920800/38750336-84a9f0ac-3f4c-11e8-959a-544f52384030.png)

I will add the requests to the todo list for the next release.

**Comment by torzdf** [comment]
Latest version in Master: 

- Fixed warning message when generating graph on first iteration
- Windows version now saves the model when terminating training

If nothing else comes up in the next 24 hours I will raise a PR for this.

**Comment by testdoe** [comment]
Thanks for your efforts.

On MacOs 10.13.1 with v0.2.0a I get "_Could not detect a display. The GUI has been disabled_"

No such issues with earlier version(s).

**Comment by torzdf** [comment]
Hmmm, that's strange. I'm testing on macOS 10.13.2, albeit on hackintosh, and it loads (although tends to lock up). When did you clone, as I pushed some changes late last night?

**Comment by testdoe** [comment]
just got the most recent, same with that one.

**Comment by torzdf** [comment]
Could you do me a favour. Could you fire up terminal in macOS and return the results from each of the following from within the environment that you're running faceswap:

`echo $DISPLAY`

next launch a Python Interactive Shell

`python`
or 
`python3`

import the os module:

`import os`

and enter each of the following returning the results:

`print(os.name)`

`print(os.environ['DISPLAY'])`

As an example, my output looks like this:

![screen shot 2018-04-14 at 14 44 21](https://user-images.githubusercontent.com/36920800/38768948-034204e4-3ff3-11e8-89c4-021c12b761a0.png)

**Comment by testdoe** [comment]
>>> print(os.name)
posix
>>> 
>>> print(os.environ['DISPLAY'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/anaconda3/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DISPLAY'
>>> 
>>>

**Comment by torzdf** [comment]
Ok, that's weird. What about:

`echo $DISPLAY`

from the command line?

Also, from the Python Interactive shell, could you also get the output of:

`print(os.environ)`

**Comment by torzdf** [comment]
Ah, I think you may need to install xquartz https://www.xquartz.org/

Could you try that and let me know if it works

**Comment by torzdf** [comment]
In fairness, it isn't obvious. Strange that my High Sierra seemed to come with it (unless it got installed with something else). I'm going to look into why it locks up on macOS and see if I can push a fix in this release.

**Comment by torzdf** [comment]
@testdoe macOS lockup issue should be fixed.

**Comment by torzdf** [comment]
pr #352 opened

**Comment by testdoe** [comment]
I confirm. Lockup issue is fixed. Great work. Thanks!
