### ISSUE TITLE
Really slow extraction

### ISSUE THREAD

**Issue by fakinated** [deepfakes/faceswap#348]
I'm currently extracting with roughly 25 seconds per item (yes, I'm not kidding, it's not the other way round). I just finished extracting for 600 images in 4-5 hours. What am I doing wrong?

These are my parameters for extracting:

`python faceswap.py extract -i ./tmp -o ./tmp/aligned -ae -D cnn`

According to the console output the extraction process *is* using my GPU (GTX 970).

I tried extracting with the hog model before, which was faster but yielded very bad results (many faces had been missed). My images are 16x900 png files.

My system:

OS: Ubuntu 17.10
GPU: GTX 970 4GB
CPU: Intel i5-6600k

**Comment by torzdf** [comment]
Did you compile DLIB yourself? If not then you are probably using the CPU for extraction. See here: https://github.com/davisking/dlib/issues/909

**Comment by fakinated** [comment]
Okay, I reinstalled dlib with CUDA support - nothing changed.

According to nvidia-smi, python is using 3.6 GB of my VRAM, so I guess it's running on the GPU(?).

**Comment by MT-4ier** [comment]
I had a similar problem with a different solution.
For me, it turned out to be a broken version of a dlib extension module in the main 'site-packages' folder. Once I removed that, the good version of dlib in 'site-packages/dlib-[version]' is able to be called correctly, and everything works.

**Comment by fakinated** [comment]
Finally found it! I somehow ended up with multiple versions of dlib installed next to each other... :man_facepalming: 

Thanks for your time!
