### ISSUE TITLE
python faceswap.py train unormal message!!!!!

### ISSUE THREAD

**Issue by visonpon** [deepfakes/faceswap#35]
when i train using above command,  it doesn't start training and just print the positional arguments and optional arguments message ,then it stop and receive no error.
do you know why? @joshua-wu @Clorr

**Comment by Ganonmaster** [comment]
Hi, visonpon. Could you please fill out the issue template or otherwise expand on your problem description? You have given us very little information to go on.

If you could, would you be so kind as to provide us with information about the command that you are running that results in this error and perhaps some information on the operating system you are using?

**Comment by visonpon** [comment]
yeah.
@Ganonmaster 
the command : **sudo CUDA_VISIBLE_DEVICES=1 python3 faceswap.py train**
**running log message:**
-------------------------------------------------------
Using Theano backend.
usage : faceswap.py [-h]{extract,train,convert}....
positional arguments:
{extract,train,convert}
extract 
train
convert
optional arguments:
-h, --help
--------------------------------------------------
Then it return to the dir that i run the command,  and there is no other error message.

**Comment by Ganonmaster** [comment]
Hi, you seem to have not specified input, output and/or model directories. Could you try specifying any of those options and see what the command does then? Also note that these directories must exist for the script to work.

Also note that I'm assuming you have made changes to the script to use the Theano backend. The default is the Tensorflow backend. If you could share your experiences with this backend, we'd be very grateful.

**Comment by visonpon** [comment]
@Ganonmaster 
as how to use Theano , i follow this link [https://github.com/keras-team/keras/issues/3794](url) and do as ch3ll0v3k said:
$ nano ~/.keras/keras.json
{
"image_dim_ordering": "th",
"epsilon": 1e-07,
"floatx": "float32",
"backend": "theano"
}

btw, i have set the input_A, input_B and models' dir, otherwise there should be warning that: input dir not found. but i didn't receive this warning.

**Comment by Ganonmaster** [comment]
There is no such warning at this time. I have made a issue for creating it, but if you wish to implement it yourself, you are free to submit a pull request.

**Comment by ruah1984** [comment]
HI @lukaville , same error message found when using cloud base GPU
as below 

2017-12-31 04:42:30,364 INFO - Unable to open file (unable to open file: name = '/output/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
2017-12-31 04:42:30,603 INFO - usage: faceswap.py [-h] {extract,train,convert} ...
2017-12-31 04:42:30,603 INFO - 
2017-12-31 04:42:30,604 INFO - positional arguments:
2017-12-31 04:42:30,604 INFO - {extract,train,convert}
2017-12-31 04:42:30,604 INFO - extract             Extract the faces from a pictures.
2017-12-31 04:42:30,604 INFO - train               This command trains the model for the two faces A and
2017-12-31 04:42:30,604 INFO - B.

can't figure what's go wrong

**Comment by Clorr** [comment]
did you create a folder named `output` ?

**Comment by lukaville** [comment]
@Clorr, looks like @ruah1984 uses Floydhub, where output folder should be pre-created and writable https://docs.floydhub.com/guides/data/storing_output/

**Comment by Clorr** [comment]
Ah ok. I think the printing of the help message after termination is a reported issue (#43)

Beside that, I can't help for now. What's the command line that is used here?

**Comment by ruah1984** [comment]
hi @Clorr  this is the command line i use,

floyd run --gpu --env tensorflow-1.4:py2 --data ruah1984/datasets/faces_a:/faces_a --data ruah1984/datasets/faces_b:/faces_b 'python faceswap.py train -A /faces_a -B /faces_b -v -m /output/models'
--
as other mention in the reddit, i have create an output folder . same issue as well

**Comment by Clorr** [comment]
I'm not into floyd for now, so that was a guess from your error message. I checked [this page](https://www.reddit.com/r/deepfakes/comments/7mgpki/floydhub_cloud_training/) that gives pretty handy instructions. Did you follow everything? (there is a mention of a "models" folder also...)

- [ ] Install floyd-cli: pip install -U floyd-cli
- [ ] Login: floyd login
- [ ] Then inside faceswap project directory run: floyd init faceswap
- [ ] Outside project directory create directories with training data for face A and B and run inside each directory: 
```
floyd data init faces_a # in the first directory
floyd data upload
floyd data init faces_b # in the second directory
floyd data upload
```

- [ ] Inside faceswap directory create empty `models` folder. If the folder contains models it may not work because there is a size limit for code directory.
- [ ] Copy requirements-gpu.txt to floyd_requirements.txt
- [ ] Remove "lib" from .floydignore file
- [ ] Finally, run the training :) `floyd run --gpu --env tensorflow-1.4:py2 --data faces_a:/faces_a --data faces_b:/faces_b "python faceswap.py train -A /faces_a -B /faces_b -v -m /output/models"`

**Comment by ruah1984** [comment]
all process have been follow,
the latest one is create an output folder inside the faceswap directory 
--faceswap1\output\models

You can refer below link
https://www.floydhub.com/ruah1984/projects/quick-start-trial-and-error/10

Data set is here
https://www.floydhub.com/ruah1984/datasets/faces_b
https://www.floydhub.com/ruah1984/datasets/faces_a

all above is public, you can view it from the link

**Comment by lukaville** [comment]
@ruah1984 you can start job using `--mode jupyter` mode and open terminal in jupyter web interface. So you can inspect directories using command line utils (`ls`, `cd`, etc.), or you can use built-in jupyter file manager and check that this directory exists.

**Comment by Clorr** [comment]
Ok. That will help someone who may know more than me on that... 

One question though, there is a quote at the end of your command line, is that a copy/paste bug, or do you use it in your run?

**Comment by ruah1984** [comment]
@Clorr here is the command line i use in cmd
floyd run --gpu --env tensorflow-1.4:py2 --data faces_a:/faces_a --data faces_b:/faces_b "python faceswap.py train -A /faces_a -B /faces_b -v -m /output/models

in floydhub, the command will show
floyd run --gpu --env tensorflow-1.4:py2 --data ruah1984/datasets/faces_a:/faces_a --data ruah1984/datasets/faces_b:/faces_b 'python faceswap.py train -A /faces_a -B /faces_b -v -m /output/models'

**Comment by Clorr** [comment]
oh ok, the quote is closing the one before `python...` , so it seems fine. As @lukaville suggested, you should check with the `--mode jupyter` flag to have more visibility on what is going on...

**Comment by Clorr** [comment]
What I understand from your issue, is that it tries to load an encoder.h5 from the `/output/models `folder. But what is not clear for me is if you have to upload this file before launching the training or not. In desperate case, try uploading the 3 h5 files in `/output/models` folder

**Comment by lukaville** [comment]
Hmm, I just realized that probably "Unable to open file" error may be irrelevant to the real issue because even when everything is OK and script creates models for the first time this message still printed.

**Comment by Clorr** [comment]
Messy issue. Reopen for a specific question if needed

**Comment by ruah1984** [comment]
just for your information, the issue only happen if we are using floyd cloud. what i am thinking, it possible the dataset cannot mount to the project for training. It never occur when i using my personal laptop.

this issue can consider close, i not sure other members also facing the same issue or not.

**Comment by kumaranvpl** [comment]
@ruah1984 @Clorr @lukaville This issue exists for me too. But I am running it in my laptop. And I have all needed files and folders already created

**Comment by ruah1984** [comment]
@kumaranvpl , are you using the floydhub?? 
You can check the forum here if it happen in floydhub 
https://forum.floydhub.com/t/data-mounting-problem-cannot-mount-data/591/2.

**Comment by ruah1984** [comment]
not sure is the input and output problem or not. i have this problem previously,but after i put all input and output folder to C:\Users\xxx , it not happen any more.  

here is how i run python with the 
python faceswap.py train -A ~/faceswap/data/faceB -B ~/faceswap/data/faceA -m ~/faceswap/models/ -p.
