### ISSUE TITLE
How can I run it in distributed mode to speed it up

### ISSUE THREAD

**Issue by shiqwang** [deepfakes/faceswap#350]
I actually want to generate the models fast.
If I use same Model A, can I just train Model B to save the time? I saw there are 3 files in model file, decoderA, decoderB, encoder, so I dont know which step I can save the time...

Can I change the code to distributed mode if there is nothing step I can save time...

Anyone can solve it ? Thank you . :)

**Comment by bryanlyon** [comment]
This is unfortunately not feasible due to how much data most be synchronized between each client code every epoch.  This is even the bottleneck with multiple gpus in one system.  I'd suggest having each node working on different models and just giving it time.
