### ISSUE TITLE
Staging Branch... your thoughts please

### ISSUE THREAD

**Issue by torzdf** [deepfakes/faceswap#351]
I'd like to implement a staging branch where new PRs will get merged to and be tested before pushing into the Master branch. I know @Clorr had reservations about this, so wanted to check whether a) this is ok and b) this is wanted.

My thinking is that PRs can get merged quicker into staging and be tested more thoroughly before committing into Master. It should also make it easier to amend code and put it out to a wider test base without worrying about breaking anything for everyone else. It also means we could take a laxer approach about whether a change is actually required by merging it into staging and seeing how it impacts workflow.

For the end user, the average user can stick with the Master branch, where the most stable code will reside. More adventurous users can use the staging branch which will be more 'bleeding edge' but more susceptible to things just not working, with the hope and understanding that they will feedback on what works and what doesn't.

Thoughts?

**Comment by bryanlyon** [comment]
I've always supported the idea, and as a contributor, you are welcome to run whatever branches you want.  The problem is that it'll be up to you to keep it up to date if there are issues.  I don't see any issues though.

**Comment by torzdf** [comment]
My thinking is that Master gets baselined now (or when staging is started), and does not get updated unless it is an urgent bugfix, which should be applied to both branches anyhow. 

PRs get merged into staging, tested, fixed, removed etc there then the staging branch is merged with master and everything is in sync again.

Of course it only works if everyone merging follows the same process. 

And development never really goes as planned ;)

**Comment by bryanlyon** [comment]
I'm okay with that.  Create the branch and I'll only commit to the staging.  I think we'll need to run fairly rapid merges to master at least for the next few weeks, until people get used to the split branches and we get Master working more stable.

**Comment by torzdf** [comment]
Sounds good to me. I'll sync up staging to master tomorrow (it's getting late here), and look to get some of the outstanding PRs put into there. As I said in another PR, I'm doing a fairly hefty re-factoring of the scripts section, so it would give me a bit of piece of mind if it wasn't coming straight out of my repo and into master.

**Comment by torzdf** [comment]
Has been implemented
