### ISSUE TITLE
Questions about swap face

### ISSUE THREAD

**Issue by xiangcong** [deepfakes/faceswap#354]
The model can convert A -> B, or B -> A.
However, can it convert C -> A or C -> B ? (C means another person which do not show in the train dataset).

I trained a GAN128 model，and A B can successfully converted to each other. But when I try to convert C to A or B, I comes out horrible results...

**Comment by ruah1984** [comment]
@xiangcong, which convert function you are using right now?

**Comment by bryanlyon** [comment]
@xiangcong No, it cannot be used to replace someone with another person, it's only for use with swapping A and B.

**Comment by torzdf** [comment]
People have been experimenting with using lots of different faces in A to train the algorithm to learn what a face is and using a single face in B. I've never tried it myself though, so I'm not sure if it would have the desired result.

**Comment by bryanlyon** [comment]
It would undoubtedly not.  Even with many A-single B you have to do a final "fit" train with the A face to get the NN to know that face, it's just that it will (probably) be faster to do that final fit train than training a model from scratch.   This is useful for Nic Cage for example where the goal is to put Nic in every movie, they can train the NN to put Nic's face on another actor's body faster than running from scratch.

It still requires training and the initial model takes a LOT longer (My experience shows (N/2)^2 with N face sources) to build than a specific model and requires a very carefully selected initial set of faces.

**Comment by xiangcong** [comment]
@ruah1984  Do you mean "Masked" or "Adjust" of "--converter" parameter? I use the default "masked" version.

**Comment by ruah1984** [comment]
@xiangcong can share the result photo with occlusion ??

**Comment by xiangcong** [comment]
@ruah1984  I just have the final result. https://github.com/xiangcong/faceswap/blob/myBranch/results/image-201458.jpg

**Comment by xiangcong** [comment]
@bryanlyon  Thanks a lot~!
