### ISSUE TITLE
when using GUI recent version, A converting error has occurred.

### ISSUE THREAD

**Issue by bigsea00001** [deepfakes/faceswap#355]
I am testing the gui version downloaded today. But when converting,  the following error has occurred.
Can anyone tell me what I am doing wrong or how to solve it?

(1) error message 
"Failed to convert image: ...\faceA_source_gui\out1.png. Reason: argument of type 'NoneType' is not iterable"

(1) train image : 
https://imgur.com/tLB15CB

(2) convert error image : 
https://imgur.com/OAzWKdR

**Comment by torzdf** [comment]
In the first instance, I'd try leaving the Serializer and Alignments file blank and run again. I *think* there's a bug where if you specify alignment file, then it fails. Please confirm if this is the case and I'll look into it.

If that doesn't work, what happens if you try to run from the commandline:
`
python faceswap.py convert -i J:/__now_working/faceA_source_gui/ -o J:/__now_working/output -v -m models -a J:/__now_working/faceA_gui/ -t GAN128 -b 20 -S -M facehull -e 20`

(You may want to double check that before executing)

**Comment by bigsea00001** [comment]
I got the same error when I run the Serializer and Alignments file empty.

So I ran commandline. The result is shown in the image below. Please refer to it. Thank you.

command line image: https://imgur.com/B5d1I05

**Comment by torzdf** [comment]
Sorry, I don't use Windows. You may want to change those forward slashes in the paths to backslashes, because the output there is telling you that the alignments directory (J:/__now_working/faceA_gui/) is empty and that it can't find the alignments file in J:/__now_working/faceA_source_gui/

**Comment by torzdf** [comment]
I don't know if you've solved this, but I would suspect that it is not a gui specific issue as the GUI is just a frontend to call the command line arguments. I'd be interested to know if it is though, as I would like to hunt the issue down if that is the case.

**Comment by bigsea00001** [comment]
Thank you for reply. Even though I did change those forward slashes in the paths to backslashes, I still get results like the following image. For reference, the folder before updating to the gui version works well without any problems. I hope my case will help you.

command line image : https://imgur.com/AD3Z6WM

**Comment by Kirin-kun** [comment]
It looks like a codepage problem. I think your cmd is set with a Korean double byte codepage which allows you to display Korean characters in the consoles. However, the Korean code page puts the Won symbol at the backslash position. The Japanese codepage is the same with the Yen symbol.

Type "chcp" in your console. You'll probably see something like 949 or some large number.

The gui is probably using unicode but the backslash character is translated to a won symbol when interpreted by the exec function.

See https://msdn.microsoft.com/en-us/library/dd317748%28v=vs.85%29.aspx for more information from Microsoft.

Eventually, before launching the gui in the console, try to set the codepage to an international one, like 850 or 437.

"chcp 850" or "chcp 437". 

It can be changed permanently in the language settings of the system for non unicode programs.

**Comment by Kirin-kun** [comment]
Normally, the / is automatically translated to \ when in Windows by the path functions. But in this instance, it's translated to Won.

I guess the OP could use the Won symbol on his keyboard to specify the directory separator in the gui.

However,  Ithink it should be up to the gui program to use unicode in the os.path functions and not assume the locale is UTF-8. The problem could show up in Linux too with other locales and accents in the filepaths. I already noticed that faceswap crashes if there are accents in the images filenames. That's easily solved by renaming the files, but for the directory separator it's another story.

**Comment by torzdf** [comment]
I will look into a locale fix for the next release

**Comment by bigsea00001** [comment]
To be honest, I do not know what to do. However, my image file names are all numbers.

**Comment by frosty3907** [comment]
I'm getting similar error using portable winpython install after git clone to new version with convert:
Failed to convert image: D:\faceswap\data_A\sbla0305.png. Reason: expected str, bytes or os.PathLike object, not NoneType

**Comment by frosty3907** [comment]
I wonder if this is due to incorrect upgrade procedure? I basically just git cloned the url into the winpython /faceswap folder and i've just tried restoring the previous version archive I had used to get the functionality back but now it doesn't work either (TypeError: __init__() missing 1 required positional argument: 'gpus')

**Comment by torzdf** [comment]
@frosty3907 I'd say that this is a different issue than the first one raised.

That first issue should be catchable, but without a traceback it's a little hard to diagnose. At some point it may be worth implementing logging to better support these kind of bugs.

The second one is strange as, afaik gpus has never been a required positional argument

**Comment by torzdf** [comment]
I'm closing this for now, as I will pick up the locale issue with my next GUI version. @frosty3907 if you are still having problems, please open another issue.
