### ISSUE TITLE
Prompt to create new directories if they do not exist

### ISSUE THREAD

**Issue by Ganonmaster** [deepfakes/faceswap#36]
The current iteration of the tool will simply error out or quit if the model and output directories do not exist. To improve this behavior for new users, we can prompt to create these directories automatically.

**Comment by lukaville** [comment]
Also, it will be nice to print an error if we can't write to the directory. Currently, the script fails without error description and for some reason prints help information if models directory is read-only. This is very confusing and took me some time to figure out where is the problem :)

**Comment by Clorr** [comment]
Just thinking here. Can we also check for installed dependencies ? 

(Note: I did not look at the latest commits so maybe it's on its way...)

**Comment by Ganonmaster** [comment]
Checking on dependencies would be neat, but if we intend to distribute this tool as a self contained executable, it's not necessary. Other than that, catching some obvious `ImportError`s for the main libs (keras, tensorflow, dlib, face_recognition) here and there might be sufficient.

**Comment by Clorr** [comment]
Ok, fine for me 😉

**Comment by Clorr** [comment]
lib/utils.py has now the mkdir activated, so it won't fail anymore if the directory does not exist. If we have to add a prompt, the issue can be reopened.
