### ISSUE TITLE
How do I determine when to stop training ?

### ISSUE THREAD

**Issue by parkourcx** [deepfakes/faceswap#361]
I have been training model for almost 300 iterations,but I didn’t get a very good result , the output in the terminal shows “[#00285] loss_A: 0.07463, loss_B: 0.08287”,so when should I stop training?

**Comment by torzdf** [comment]
Are you training cpu? if so, probably weeks.

You want to be aiming for less than 0.02 in both loss_A and loss_B

10k iterations would probably be the bare minimum to get close, depending on the sources.

**Comment by parkourcx** [comment]
@torzdf I see, I have 4000+ pics for faceA and 906 pics for faceB,and 6vCPU,no GPU,thanks for your comment!
