### ISSUE TITLE
New tool effmpeg ("easy"-ffmpeg) with gui support. Alpha test.

### ISSUE THREAD

**Issue by AbysmalBiscuit** [deepfakes/faceswap#364]
Hey,

I have just opened a new PR with a new `effmpeg` ("easy"-ffmpeg), I'd appreciate it if some people were willing to help me test it to find bugs, especially for platforms other than GNU/Linux. :smiley: 

<s>PR: #363</s>
PR: #373 

`effmpeg` provides the following functionality:
* extract: extract video into individual frames
* gen-vid: generate a video when given individual frames (with the option to mux in audio during generation using a reference video)
* get-fps: prints the video fps to the terminal
* get-info: prints all the information about the video (includes all meta-data)
* mux-audio: muxes audio from reference video into the input video (output is saved as a separate video)
* rescale: rescales the input video to a new resolution using the provided 'scale'
* rotate: rotates the video using the chosen transpose variable or degrees (if transpose is set, then degree rotation is ignored)
* slice: cuts out a chosen portion of the input video into a new video using the start time and either the stop time or duration (if both duration and end time are set, then duration will be ignored and the end time will be used)

In addition to the `effmpeg` there is also added functionality to the GUI wherein it should ask for video file types based on which action you have chosen to perform.

**Comment by torzdf** [comment]
#363

**Comment by torzdf** [comment]
FYI this has been merged into the staging branch. To test this and any other new features that will hopefully make their way into Master, please clone the staging branch of this repo.

Feedback, either good or bad, is appreciated as it enables us to get it as correct as possible prior to merging into Master.

**Comment by AbysmalBiscuit** [comment]
New PR: #373

**Comment by torzdf** [comment]
This is now merged into https://github.com/deepfakes/faceswap/tree/staging

**Comment by torzdf** [comment]
merged
