### ISSUE TITLE
faceswap gui deletes save file if it's in the same directory than the model files

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#369]
I  saved training parameters for later use with the gui, so it created a .fsw file. Everything was cool. I looked in the file (it's a txt file) and it looked ok.

At some point, python crashed for a reason or another (or the PC rebooted) and when I relaunched the gui and wanted to load the settings, the .fsw file was nowhere to be found. It happened twice, so I think there's something fishy.

On the other hand, when I quit the gui "properly", the file stays there.

**Comment by torzdf** [comment]
The file shouldn't be touched, so there must be something else going on.

A file object is only created twice: Once when it is opened to read the data, and once when it is opened to save. Other than that it is not touched.

**Comment by Kirin-kun** [comment]
Maybe it's because I saved it in the same directory than the model files?

**Comment by Kirin-kun** [comment]
Is there some house cleaning on startup that would remove it?

**Comment by torzdf** [comment]
Oh, yeah. You'll lose them in the model files for sure. The model files now backs up the old model before saving the new model, so at a save iteration you fsw file will have been moved to model_bk, then at the next iteration it would have been removed entirely.

**Comment by torzdf** [comment]
I get what you're saying, it's a fairly edge case though.

**Comment by Kirin-kun** [comment]
Since every model saves files prefixed with the model name (except the original), I sometimes used the same directory to store the files for a specific dataset to compare result between models.

With this problem, all my previous trainings with other models would have been wiped out. 

In general, assuming the directory is dedicated to this training session is a bad idea, because it deletes files without the user's knowledge.

**Comment by torzdf** [comment]
Should be addressed with #371

**Comment by torzdf** [comment]
Fix pushed

**Comment by Kirin-kun** [comment]
Nope, it's broken. I pulled it and tried to train (with good args this time):
```

Loading data, this may take a while...
Loading Model from Model_Original plugin...
Failed loading existing training data.
Unable to open file (unable to open file: name = 'H:\Fakes\modelo.src_data.gamer
\encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0,
 o_flags = 0)
Loading Trainer from Model_Original plugin...
Starting. Press "Enter" to stop training and save model
Exception in thread Thread-5:.19475, loss_B: 0.20574
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inn
er
    self.run()
  File "C:\Program Files\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\kirin\faceswap\scripts\train.py", line 225, in processThread
    raise e
  File "c:\users\kirin\faceswap\scripts\train.py", line 207, in processThread
    model.save_weights()
  File "c:\users\kirin\faceswap\plugins\Model_Original\AutoEncoder.py", line 37,
 in save_weights
    backup_file(model_dir, model)
  File "c:\users\kirin\faceswap\lib\utils.py", line 41, in backup_file
    os.rename(origfile, backupfile)
FileNotFoundError: [WinError 2] Le fichier spécifié est introuvable: 'H:\\Fakes\
\modelo.src_data.gamer\\encoder.h5' -> 'H:\\Fakes\\modelo.src_data.gamer\\encode
r.h5.bk'
```

It shows a preview window, but it seems it can't save.

It seems it doesn't create the files if they don't exist?

**Comment by torzdf** [comment]
I've rolled back for now. It will be when it first creates the model

**Comment by torzdf** [comment]
Should be fixed now.
