### ISSUE TITLE
Preview and loss in gui for GAN models

### ISSUE THREAD

**Issue by Kirin-kun** [deepfakes/faceswap#375]
With the gui, if you run a training session with the GAN models, you only get the preview of the mask in the preview tab (the last preview to open). I think it should dynamically add 2 other tabs with raw and masked.

Also, the loss graph only show Loss_GA and Loss_GB.

With cli, every preview shows up  (but no graph, of course).

**Comment by Kirin-kun** [comment]
And the preview tab actually contains only part of the original window, which is not very useful.

Maybe the preview windows should be detached and not in a tab.

**Comment by torzdf** [comment]
In gui 0.3.0 the other previews will be added and the preview window will dynamically resize.

See here for status: #352 

Those marked with [x] I have implemented, the rest are outstanding, but you can follow progress.

**Comment by torzdf** [comment]
> And the preview tab actually contains only part of the original window, which is not very useful


Actually, it contains it all. You may need to resize the window or shrink the console/command frame
.

**Comment by Kirin-kun** [comment]
With GAN128 and a batch size of 20, the preview is so huge that it doesn't fit on a 1600x1200 screen anyway.

That's why I suggested to detach them. Or make them scrollable?

**Comment by Kirin-kun** [comment]
I tried a GAN (64) training with batch size 128 and the preview window is even bigger. 

I can't see the bottom of the window.

**Comment by Kirin-kun** [comment]
Anyway, planned in #352
