### ISSUE TITLE
I made a web site for making faceswaps in browser, upload models and save detections

### ISSUE THREAD

**Issue by seranus** [deepfakes/faceswap#383]
I've been working on this site for about last 2 months I got it to a prototype/alpha version, buggy but functional. I'm looking for feedback about the site/idea. Posting it here since a few of us watches playgrounds

The idea was to make it more accessible to do faceswaps and lower the technical barrier for making them. It could be be a good introduction to new users on how faceswap works. The images/video created are meant for fun and experimentation.

Site page: http://www.machine.tube

**Features**

Browse and compare generated with original
![browse](https://user-images.githubusercontent.com/590231/39408391-c8fea140-4bd5-11e8-8a40-521df1e3e746.gif)

Edit any image/video
![edit image](https://user-images.githubusercontent.com/590231/39408671-18794d02-4bda-11e8-8c91-054b21176bfa.gif)

Load models
![select model](https://user-images.githubusercontent.com/590231/39408668-150bb01a-4bda-11e8-90c7-600f0b17643a.gif)

Load detections
![browse detections](https://user-images.githubusercontent.com/590231/39408172-eb669b14-4bd2-11e8-9e80-0c52be5001a1.gif)

shift+click to select multiple and work on a set of frames, resize and drag face rect
![select frames](https://user-images.githubusercontent.com/590231/39408471-fb5950da-4bd6-11e8-979d-f68f8e37def8.gif)

debug merging fraces
![debug image](https://user-images.githubusercontent.com/590231/39408710-c1e5be16-4bda-11e8-81bf-3fa550d30b44.gif)

**Some notes:**
- I don't have the model converter worker up, if you wan't to upload a model you have to manually convert it to KerasJs
download the py file here: https://github.com/seranus/faceswap-browser/tree/master/convertor
to resave faceswap model with configuration
`faceswap_export.py [file] -t Encoder/Decoder`
after that convert it, in the end you should have a .bin file
`encoder.py -q [file]`

- Don't upload video longer than 10 sec, that's already 300 images to process

- Open the browser console when when processing video to know whats going on

- LowMem models don't work, only use Original, it would try to allocate a texture that's too large 

- Face detection is done with opencv haar, waiting for tensorflowjs to get some updates

Thank you for reading this

**Comment by clarle** [comment]
Interesting, so is this all done in the browser with Keras.js? 

No external service or anything like that?

**Comment by seranus** [comment]
Faceswaping is done with KerasJS but I had to write PixelShuffler layer, it's all done client side. Server is just used for hosting stuff

Currently waiting on tensorflowjs updates so I can port detection models, should be in next montth

I'm going to have anonymous access in a few days to make it more accessible

**Comment by mansonami** [comment]
How do you train the model? with whole frame to whole frame?

**Comment by seranus** [comment]
@mansonami models are trained in the faceswap app and then uploaded and shared between users. The site does the conversion part of the faceswap app.

**Comment by torzdf** [comment]
I'm going to close this, as it's probably better placed in faceswap_playground

**Comment by seranus** [comment]
@torzdf I appreciate for allowing this, going to repost it to playground after I make a few updates
