### ISSUE TITLE
GAN128 preview issues

### ISSUE THREAD

**Issue by feepdakenoob** [deepfakes/faceswap#386]
I'm experimenting with the gan128 model using the GUI v0.2.1b and am noticing 2 things.

First, the preview window shows the source face, mask, mask. Only when the save interval is met does it switch to converted faces for a split second and then blurs are applied. Then back to face, mask, mask.

Second, the converted frames look nowhere even close to the quality of the preview window. Any idea why that would be? I'm only training with faces taken from the video.

Are these expected behavior?

**Comment by ruah1984** [comment]
can you share you result?

**Comment by Kirin-kun** [comment]
See #375 for the preview issue.

**Comment by torzdf** [comment]
Yeah, as @Kirin-kun said, full previewing for GAN isn't yet supported in GUI. It will be available in the next release. You can track the project progress here:
https://github.com/torzdf/faceswap/projects/1

**Comment by torzdf** [comment]
Hopefully in the next week or two. It's quite a significant overhaul (2000 lines added, 1000 removed so far), and I have 2 of the biggest tasks to do, but I'm considering scrapping job queue for now.
