### ISSUE TITLE
Don't reload models everytime `convert_one_image` is called

### ISSUE THREAD

**Issue by Ganonmaster** [deepfakes/faceswap#39]
## Expected behavior

Use the convert command to convert a directory. `convert_one_image` loads the model once.

## Actual behavior

Use the convert command to convert a directory. `convert_one_image` loads the model every time that it is called.

**Comment by Clorr** [comment]
I'm adding a Convert class which will load models on __init__

It will be in my branch until I do a PR, but feel free to have a look

**Comment by Clorr** [comment]
The class is in my PR. However, I did not solve the fact that the model is reloaded for each image.

@Ganonmaster , let me know if you want to tackle this separately, or if you are ok with my plugins folder. If so I'll make it run so it can be integrated quickly

**Comment by Clorr** [comment]
This is handled in PR #52 in a dedicated commit
