### ISSUE TITLE
Github repo- public but requires a logged in user

### ISSUE THREAD

**Issue by aishvarma** [deepfakes/faceswap#392]
Hi
This repo looks like its a public repo but only allows a valid logged in github user to access it. Is there a reason its set up this way? There are external tools (im trying to use) that check for vulnerabilities etc that dont work with this repo as a result of the permissions. Just wanted to check if there is a reason you dont allow anonymous read only access. 

thanks!

**Comment by bryanlyon** [comment]
Not in our control.  We think that Github has tripped this requirement on their end.  You can set up a fork on your own account if you want to access it without login.

**Comment by aishvarma** [comment]
that is what i ended up doing- thanks!
