### ISSUE TITLE
requirements-docker.txt missing

### ISSUE THREAD

**Issue by wiso** [deepfakes/faceswap#395]
The dockerfile https://github.com/deepfakes/faceswap/blob/master/Dockerfile.gpu on line 7 is

    COPY requirements-docker.txt /opt/

but there is no requirements-docker.txt files in the repository

**Comment by LordOEQJen** [comment]
They changed the structure with last update.

In version before command for docker install was :
```
COPY ./requirements-python35.txt .
RUN pip3 --no-cache-dir install -r ./requirements-python35.txt
```
As there were different requirement-files they now have been bundled in a single file called "requirements.txt"
I would suggest to simply replace "requirements-docker.txt" with "requirements.txt" in the docker-file(s).

**Comment by torzdf** [comment]
@DKingCN could you look to push a fix for this?

**Comment by DKingCN** [comment]
Simplely updating the file name is enough to fix it.
Dont forget it while merging staging branch, which has not been fixed.

That dockerfile should work cos I even successfully built that on docker hub.
