### ISSUE TITLE
how to apply a swap on a particular part

### ISSUE THREAD

**Issue by Nexxxxxxxxxx** [deepfakes/faceswap#399]
Hi,
I'm interested in applying a swap on a particular part of a face.
e.g eyes or mouth.
what would be the best approach for that?

Thanks!

**Comment by torzdf** [comment]
The process isn't really built for that.

The best way would probably be to perform a swap on the full frames, and then apply some kind of masking between the frames with something like Adobe Premiere.

In all honesty, it would be quite a lot of work.

**Comment by iperov** [comment]
tracking mask in Adobe After Effects
