### ISSUE TITLE
Improve Dockerfile

### ISSUE THREAD

**Issue by Clorr** [deepfakes/faceswap#4]
Dockerfile does contains basic dependencies to run the program.

It creates bugs with `os.scandir` or `mkdir` parameter `exist_ok`

Please feel free to improve it and provide better support for the program.

Please take care of CPU only users if you update Tensorflow. Provide a Dockerfile.gpu for optimised usages.

**Comment by Ganonmaster** [comment]
I would recommend using separate `requirement.txt` files for Python dependencies. This keeps the dependencies in sync for people who prefer not to use Docker and those who do.

**Comment by deepfakes** [comment]
Also if it possible to make the Dockerfile not depend on the keras image it would be better. Perhaps it should be based on some debian (or any other distribution)...

**Comment by Clorr** [comment]
I removed the keras image dependency, so it means a clearer view for newcomers on how to setup a machine from scratch.

Migrating it to a full Python3 setup would be even better. I'll try this later on....
