### ISSUE TITLE
Conversion with "seamless" enabled takes lot time

### ISSUE THREAD

**Issue by beroelbo** [deepfakes/faceswap#405]
Is that behaviour normal ? If seamless in disabled, the conversion runs very fast, no matter what settings: detector hog or cnn, match histogram, etc.

But when seamless is enabled , the conversion needs much more time, aprox. 13seconds/frame.
Is that normal ?

Dlib with CUDA support already enabled while install btw.

**Comment by torzdf** [comment]
Yeah, seamless is hideously inefficient. If anyone wants to take a look, be my guest.

**Comment by beroelbo** [comment]
I just tried @iperov 's fork (https://github.com/iperov/OpenDeepFaceSwap),
and the seamless conversion runs very fast. 

Taking a look at the GPU-Monitor (watch nvidia-smi) while converting with faceswap:
The gpu doesn't seem to do anything, Vram is in Usage, but gpu volatile stucks at 0%, while exactly 1 CPU core is performing at 100%.
Conversion with disabled "seamless" gets the gpu volatile at 30%, and the conversion is running fast.

**Comment by iperov** [comment]
very fast conversion in my fork result of multicore usage, while faceswap uses only 1 core.
