### ISSUE TITLE
AI tool controls people in videos - Deep Video Portraits - SIGGRAPH 2018

### ISSUE THREAD

**Issue by frosty3907** [deepfakes/faceswap#407]
https://youtu.be/qc5P2bvfl44

**Comment by wackyphillwillis** [comment]
Yeah, replacing faces is nothing compared to replacing full heads.

**Comment by iperov** [comment]
@wackyphillwillis subj is not replacing full head

**Comment by frosty3907** [comment]
@iperov you removed your deepfacelab variation from github?
