### ISSUE TITLE
Sort.py issue: ModuleNotFoundError: No module named 'lib.cli'

### ISSUE THREAD

**Issue by deepfaceswap12345** [deepfakes/faceswap#408]
## Expected behavior

Launch the sort.py tool and do some sorting on folders

## Actual behavior

sort.py doesn't launch, instead I get an error where the "lib.cli" module is not found:

I type this: python .\sort.py and get this:

Traceback (most recent call last):
  File ".\sort.py", line 11, in <module>
    from lib.cli import FullPaths
ModuleNotFoundError: No module named 'lib.cli'

## Steps to reproduce

launch python .\sort.py in the tools folder and this will happen.

What package is needed to be installed for this module to be loaded? (so that I can try to reload the package and see if that fixes it)

All the requirements seem to be met, no red flag that I can see otherwise, and the train and convert scripts work great otherwise.

## Other relevant information
- **Operating system and version:** Windows 10 - 64 bit
- **Python version:** 3.6.4
- **Faceswap version:** latest commit 6f004e4b24b2c7abb25c94e8466c1c3614576025
- **Faceswap method:** tried on both CPU and GPU

**Comment by torzdf** [comment]
It's not meant to be launched directly. Go into your root faceswap folder and type:
`python tools.py sort -h`

**Comment by torzdf** [comment]
Get the latest version. I believe this was bugfixed in 80cde77a6de03aaef6bd5e6e4691341f04290227

**Comment by deepfaceswap12345** [comment]
that fixed it!
thanks!! closing this issue then.
