### ISSUE TITLE
-j Multi CPU process Extract script crashing

### ISSUE THREAD

**Issue by deepfaceswap12345** [deepfakes/faceswap#409]
## Expected behavior

Trying to use more than 1 process in the extract script

## Actual behavior

When trying to extract with more than 1 process, using the -j option, the script crashes and here's the error I'm getting (works great with no -j option specified)

> python .\faceswap.py extract -i [my input-dir] -o [my output-dir] -D all -j 2 -ae

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Output Directory: [my output dir]
Input Directory: [my input dir]
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: [my input dir]\alignments.json
Starting, this may take a while...
  0%|                                                                                          | 0/283 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "faceswap-master\lib\multithreading.py", line 16, in runner
    return method(item)
TypeError: 'NoneType' object is not callable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\faceswap.py", line 33, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "faceswap-master\lib\cli.py", line 39, in execute_script
    process.process()
  File "faceswap-master\scripts\extract.py", line 35, in process
    self.extract_multi_process()
  File "faceswap-master\scripts\extract.py", line 59, in extract_multi_process
    file=sys.stdout):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tqdm\_tqdm.py", line 955, in __iter__
    for obj in iterable:
  File "faceswap-master\lib\multithreading.py", line 12, in pool_process
    for i in pool.imap_unordered(runner, data):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 735, in next
    raise value
TypeError: 'NoneType' object is not callable

## Other relevant information
- **Operating system and version:** Windows 10 64 bit
- **Python version:** 3.6.4
- **Faceswap version:** 6f004e4b24b2c7abb25c94e8466c1c3614576025
- **Faceswap method:** CPU only

**Comment by torzdf** [comment]
I've just tested on cpu with -j4 and it works fine for me (both CNN and HOG).
CNN is slow on cpu anyway, so you could try:
`-D hog`

**Comment by bryanlyon** [comment]
Did you install the tensorflow-GPU?  If you use the GPU version then you can't use -j for multiple threads.

**Comment by deepfaceswap12345** [comment]
No tensorflor-gpu on the system I'm using Extract -j [x], and -D hog gives me the same error as well.
I'm running it on a VM, with multiple cores, but a VM nonetheless. I'm assuming this would be the issue then?

**Comment by torzdf** [comment]
No, I'm testing on a VM, and it's fine :/
