### ISSUE TITLE
Create pre-built packages

### ISSUE THREAD

**Issue by Ganonmaster** [deepfakes/faceswap#41]
PyInstaller or some other means to create pre-built packages for the most common OSes. Alternatively, look for other similar tools that would allow us to manage most of the dependencies. Perhaps Conda or others.

Target OSes:
- [ ] Windows
- [ ] macOS

For Linux users the manual setup with virtualenv or Dockerfile will most likely suffice.

**Comment by Suicidman** [comment]
Would appreciate it. i would discribe me as an user somewhere around a noob when it goes on things like that. building under windows is just too annoying. gotta setup a virtual machine for doing shit.

**Comment by GSonderling** [comment]
@Suicidman  I recommend Ubuntu subsystem for windows. It allows you to run almost anything like you would in normal linux, using familiar command line. 
https://docs.microsoft.com/en-us/windows/wsl/install-win10
Granted, it is a developer feature. But the benefits are massive.

**Comment by Suicidman** [comment]
@GSonderling Well, god damn thanx mate. I read your post yesterday and started reminding that i allready heard of this new windows feature. I set up an ubuntu env and got everything (finaly!) working yesterday in a few hours. Super important hint you made there.

**Comment by torzdf** [comment]
I'm closing this, as it seems no one has the time/inclination to create pre-built packages, and also @deepfakesclub  has picked up a bit of the slack on deepfakes.club.

Feel free to re-open if any progress is likely to be made.
