### ISSUE TITLE
Extracted faces are too small

### ISSUE THREAD

**Issue by luiscosio** [deepfakes/faceswap#413]
## Expected behavior

Extract faces from frames
 
## Actual behavior

Whenever extracting faces, the process takes too long to start and then the extracted faces are too small.

Example of an extracted face:

![image](https://user-images.githubusercontent.com/1666/40993201-8dd29710-68be-11e8-9891-dd7922f285ee.png)

This is from an 720 video.

Additionally getting random issues like this

C:\Users\Administrator\faceswap\lib\align_eyes.py:66: RuntimeWarning: overflow encountered in long_scalars
0%|          | 9/8456 [22:19<349:09:59, 148.81s/it]eyesCenter = ((leftEyeCenter[0,0] + rightEyeCenter[0,0]) // 2, (leftEyeCenter[0,1] + rightEyeCenter[0,1]) // 2)

## Steps to reproduce

Same conda enviroment as local, the only difference is that I'm using AWS with p3 instances

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows 2016 on AWS
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** latest on master
- **Faceswap method:** GPU
- **Other related issues:** #123, #124...

absl-py                   0.2.0                     <pip>
astor                     0.6.2                     <pip>
bleach                    1.5.0                     <pip>
certifi                   2018.4.16                py36_0    conda-forge
click                     6.7                       <pip>
cycler                    0.10.0                    <pip>
Cython                    0.28.2                    <pip>
decorator                 4.3.0                     <pip>
dlib                      19.9                np111py36_0    conda-forge
face-recognition          1.2.2                     <pip>
face-recognition-models   0.3.0                     <pip>
ffmpeg                    4.0                  hf48ec3a_0    conda-forge
ffmpy                     0.2.2                     <pip>
ffprobe                   0.5                       <pip>
gast                      0.2.0                     <pip>
grpcio                    1.11.0                    <pip>
h5py                      2.7.1            py36he54a1c3_0
hdf5                      1.10.1                   vc14_2  [vc14]  conda-forge
html5lib                  0.9999999                 <pip>
icc_rt                    2017.0.4             h97af966_0
intel-openmp              2018.0.0                      8
Keras                     2.1.6                     <pip>
keras-vggface             0.5                       <pip>
kiwisolver                1.0.1                     <pip>
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
Markdown                  2.6.11                    <pip>
matplotlib                2.2.2                     <pip>
mkl                       2018.0.2                      1
mkl_fft                   1.0.1            py36h452e1ab_0
mkl_random                1.0.1            py36h9258bd6_0
networkx                  2.1                       <pip>
numpy                     1.14.3                    <pip>
numpy                     1.11.3           py36h4a99626_4
opencv-python             3.4.0.12                  <pip>
pathlib                   1.0.1                    py36_0    conda-forge
Pillow                    5.1.0                     <pip>
pip                       10.0.1                   py36_0
protobuf                  3.5.2.post1               <pip>
pyparsing                 2.2.0                     <pip>
python                    3.6.5                h0c2934d_0
python-dateutil           2.7.2                     <pip>
pytz                      2018.4                    <pip>
PyWavelets                0.5.2                     <pip>
PyYAML                    3.12                      <pip>
scandir                   1.5                      py36_0
scikit-image              0.13.1                    <pip>
scipy                     1.1.0                     <pip>
setuptools                39.1.0                   py36_0    conda-forge
six                       1.11.0           py36h4db2310_1
tensorboard               1.8.0                     <pip>
tensorflow-gpu            1.8.0                     <pip>
termcolor                 1.1.0                     <pip>
tqdm                      4.23.3                    <pip>
vc                        14                   h0510ff6_3
vs2015_runtime            14.0.25123                    3
Werkzeug                  0.14.1                    <pip>
wheel                     0.31.0                   py36_0    conda-forge
wincertstore              0.2              py36h7fe50ca_0
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

**Comment by luiscosio** [comment]
Updated the environment and changed conda to virtualenv:

```
absl-py                 0.2.2
astor                   0.6.2
bleach                  1.5.0
click                   6.7
cloudpickle             0.5.3
cycler                  0.10.0
dask                    0.17.5
decorator               4.3.0
dlib                    19.10.9
face-recognition        1.2.2
face-recognition-models 0.3.0
ffmpy                   0.2.2
gast                    0.2.0
grpcio                  1.12.1
h5py                    2.8.0
html5lib                0.99999
Keras                   2.1.6
kiwisolver              1.0.1
Markdown                2.6.11
matplotlib              2.2.2
networkx                2.1
numpy                   1.14.3
opencv-python           3.4.1.1
pathlib                 1.0.1
Pillow                  5.1.0
pip                     10.0.1
protobuf                3.5.2.p
pyparsing               2.2.0
python-dateutil         2.7.3
pytz                    2018.4
PyWavelets              0.5.2
PyYAML                  3.12
scandir                 1.7
scikit-image            0.14.0
scipy                   1.1.0
setuptools              39.2.0
six                     1.11.0
tensorboard             1.8.0
tensorflow-gpu          1.8.0
termcolor               1.1.0
toolz                   0.9.0
tqdm                    4.23.4
Werkzeug                0.14.1
wheel                   0.31.1
```

Still having the same issue, even though face_recogntion works just fine.

**Comment by torzdf** [comment]
This looks to be almost definitely a dlib issue. What happens if you debug landmarks?

Which Cuda and CuDNN versions are you using?

**Comment by luiscosio** [comment]
@torzdf The landmarks are a mess.

 CUDA 8 & 9, cuDNN 6 & 75 and NVidia Driver 385.54.

But I just found out it was related to using TESLA V100

Exact same stack in Pascal works like a charm.
