### ISSUE TITLE
no detecting faces

### ISSUE THREAD

**Issue by dardan** [deepfakes/faceswap#414]
Everything seems ok but when it comes to the result this happens why its not detecting faces
-------------------------
Images found:        378
Faces detected:      0
-------------------------
I am running this on a windows 10 pc, Cuda 9.0 and Cunn 7.05, python 3.6 x64
python faceswap.py extract -i c:\Users\XXXXX\images -o  c:\Users\XXXXX\out

**Comment by dardan** [comment]
>>> import dlib
>>> dlib.DLIB_USE_CUDA
False
thanks man

**Comment by dardan** [comment]
@Kirin-kun still doesent work I reinstalled everything and still this, any link where i can follow instruction step by step to install dependecies in the right order thanks.
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import dlib
>>> dlib.DLIB_USE_CUDA
False
>>>

**Comment by Kirin-kun** [comment]
I compiled dlib on windows 7 with CUDA support and made a wheel of it some time ago:

[dlib-19.10.99-cp36-cp36m-win_amd64.whl](https://owncloud.dspnet.fr/index.php/s/f3EYLma84LKsBLw/download)

Up to you to test it on Windows 10 with `pip install dlib-19.10.99-cp36-cp36m-win_amd64.whl`

And scan it for malicious software too, because one can never be too cautious.

Eventually, report if it answers True to dlib.DLIB_USE_CUDA

**Comment by LordOEQJen** [comment]
I switched to Ubuntu for performance enhancement, but in the past I used Win10.

I cloned dlib from https://github.com/davisking/dlib
And run python setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA

**Comment by luiscosio** [comment]
@Kirin-kun I found your wheel elsewhere and saved me a bunch of time.

Works just fine on Windows 2016 + Tensorflow 1.8 + Python 3.6.5. 

Any chance you can update it to 19.13?

**Comment by gessyoo** [comment]
Kirin-kun, your wheel works for me on Win 10 x64 and Ananconda 3.6, thanks.  I've had mixed results compiling dlib from source.  Compilation under VS 2017 15.7.3 is still buggy I think and not working with CUDA 9.1 or 9.2.  If you don't mind, an updated wheel or a brief how-to guide would be appreciated.

**Comment by Kirin-kun** [comment]
Here's latest pull of dlib (19.13.99) compiled for Windows 7 x64 and CUDA 9.0/cudnn 7.0.5

[dlib-19.13.99-cp36-cp36m-win_amd64.whl (3 MB)](https://owncloud.dspnet.fr/index.php/s/4dkQtdIn7GlnI3A/download)

As for a how-to, there's nothing special to do, really. I installed cmake and Microsoft Build Tools 2015 (visualcppbuildtools_full.exe) on top of Cuda 9.0 and Cudnn 7.0.5

Then python setup.py build then install.

Newer version of Visual Studio 2017 doesn't seem to work.
