### ISSUE TITLE
Conversion tool request

### ISSUE THREAD

**Issue by samsonsite1** [deepfakes/faceswap#415]
It would be useful to have a conversion tool that could preview a single video frame, while adjusting blur size and kernel size as sliders in real-time or by a mouse click.  Whatever the case, it would save hours of guesswork of finding the perfect conversion settings. Thanks.

**Comment by torzdf** [comment]
I agree, that would be useful, but it isn't a minor undertaking, so it's certainly not a priority for me.

Anyone is welcome to implement such a feature though and raise a PR. In the meantime, I will tag this with feature request and close.

**Comment by deepfakes** [comment]
This has been implemented (Preview Tool)
