### ISSUE TITLE
train.py doesn't stop after specified number of epochs

### ISSUE THREAD

**Issue by agilebean** [deepfakes/faceswap#427]
First of all, a big thanks to all contributors for technical work and ethical standards.
Love the contributors' spirit!

## Expected behavior
I want to automate the whole pipeline of extraction, training, conversion and stitching back to a video. So each script needs to finish in a defined state.

## Actual behavior

This works almost perfectly with one exception:
The train.py script doesn't stop automatically, it requires a manual input of CTRL+C.

## Steps to reproduce

This may be trivial but nevertheless:

# training: this doesn't stop automatically
python3 faceswap.py train -A  $INPUT_FACE_DIR -B  $STYLE_FACE_DIR -ep $NUM_EPOCHS

# conversion: this process needs to run after the training has finished
python3 faceswap.py convert -i $INPUT_IMAGE_DIR -o $OUTPUT_IMAGE_DIR -m $MODEL_DIR

## Other relevant information
- **Operating system and version:** Ubuntu 16.04 LTS 
- **Python version:** 3.5
- **Faceswap version:** 8d9de4c
- **Faceswap method:** GPU

**Comment by torzdf** [comment]
This is a slightly frustrating quirk of how the process waits for Enter to terminate. There is no obvious way to bypass it at the moment if you don't generate a preview (as you will have noticed, it reaches the target epoch then just waits for CTRL+C or <ENTER>).

However, there is a workaround. If you use the -p flag to show a preview, when it reaches the target epoch, the preview will close and training will terminate.

**Comment by bryanlyon** [comment]
You're also welcome to patch out the waiting for enter in your copy.  See previous requests for this feature for details.

**Comment by agilebean** [comment]
Thanks for the tip -
very unfortunately the models are not saved with the -p flag set.
maybe because I'm running headless ubuntu?
@torzdf was that the reason you told me to run vnc4server? 
and how would I pipe the preview - right after the `faceswap.py train ... -p | <pipe into sth>` ?

**Comment by torzdf** [comment]
What do you mean that the models are not saved with the -p flag set? They should be. It should act just like the command line, just with generating a preview. Actually, it may be like you say, because it can't generate the preview.

to pipe the display, first launch vnc4server on an unused display (in my example I'lll use display 3):

`vnc4server :3`

Then launch faceswap pointing at that display:

`DISPLAY=:3 ; python faceswap.py ...`

The added advantage of this is that you can connect via vnc client to see how the preview is getting on.

For added security I usually run all of this in a screen session so it carries on if I lose connection

**Comment by agilebean** [comment]
Thanks again for the tip. 
I deeply appreciate your great spirit to help!
And that's why I am even more sad that I couldn't get it running. Your instructions with piping to vncserver worked, but as before, the models are not saved. I tried it three times to be sure. The model folder only contains the encoder files `encoder.h5  encoder.h5.bk`.
Any ideas here? I included the stack trace below.
Apart from that, would you consider any modifications to the source code so the training stops by CTR+C, Enter *AND* after finishing the specified number of epochs? I think that would be a small step but a great improvement because it allows to automate the whole process. 

```
/home/agilebean/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Model A Directory: /home/agilebean/faceswap/input_faces
Model B Directory: /home/agilebean/faceswap/style_faces
Training data directory: models
Loading data, this may take a while...
Using live preview.
Press 'ENTER' on the preview window to save and quit.
Press 'S' on the preview window to save model weights immediately
Loading Model from Model_Original plugin...
WARNING:tensorflow:From /home/agilebean/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1264: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /home/agilebean/.local/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py:1349: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Failed loading existing training data.
"Can't open attribute (can't locate attribute: 'weight_names')"
Loading Trainer from Model_Original plugin...
: cannot connect to X server .23394, loss_B: 0.18140
8: line 155: 24356 Segmentation fault      (core dumped) python3 faceswap.py train -A $INPUT_FACE_DIR -B $STYLE_FACE_DIR -ep $NUM_EPOCHS -p
```

**Comment by agilebean** [comment]
Dear @torzdf, for your tips I want to [buy you a coffee](https://www.buymeacoffee.com) - if you have an account please send it to me. 

For everyone who is desperate for automation:
I found a workaround without preview that works!
It waits (wait $!) for the process to finish (&), and then just continues.
```
python3 faceswap.py train -A  $INPUT_FACE_DIR -B  $STYLE_FACE_DIR -ep $NUM_EPOCHS &
echo $!; ps way "$!"
wait $!
```

**Comment by torzdf** [comment]
Glad you got a solution that works 👍
