### ISSUE TITLE
Secondary masks/artifacts/blur in converted images, even thou secondary aligned images have been deleted

### ISSUE THREAD

**Issue by minersday** [deepfakes/faceswap#439]
running latest github version.

**Comment by torzdf** [comment]
More detail needed.

**Comment by minersday** [comment]
So when I delete an image from aligned images folder, like some extract image that is not a face, this object will show up as a blur/articfact. This used to work, but with the latest releases in github this is a problem.

Steps to reproduce, delete a extra image(like something that is not a face) from aligned images, convert image.

**Comment by minersday** [comment]
05874.png has the right face artifact,
but 05875.png has an extra artifact that is deleted from the aligned faces as it was garbage and now it shows up in the converted images.

  "05874.png": [
    {
      "r": 0,
      "x": 187,
      "w": 212,
      "y": -5,
      "h": 234,
      "landmarksXY": [
        [
          205,
          142
        ],
        [
          223,
          160
        ],
        [
          241,
          178
        ],
        [
          259,
          189
        ],
        [
          280,
          207
        ],
        [
          301,
          214
        ],
        [
          319,
          217
        ],
        [
          344,
          217
        ],
        [
          373,
          207
        ],
        [
          391,
          185
        ],
        [
          394,
          164
        ],
        [
          398,
          146
        ],
        [
          398,
          125
        ],
        [
          394,
          100
        ],
        [
          384,
          82
        ],
        [
          376,
          60
        ],
        [
          359,
          42
        ],
        [
          216,
          114
        ],
        [
          219,
          100
        ],
        [
          230,
          85
        ],
        [
          241,
          78
        ],
        [
          251,
          74
        ],
        [
          291,
          46
        ],
        [
          301,
          39
        ],
        [
          312,
          28
        ],
        [
          323,
          24
        ],
        [
          337,
          24
        ],
        [
          294,
          89
        ],
        [
          305,
          103
        ],
        [
          316,
          117
        ],
        [
          323,
          128
        ],
        [
          312,
          146
        ],
        [
          319,
          142
        ],
        [
          330,
          139
        ],
        [
          334,
          132
        ],
        [
          337,
          125
        ],
        [
          244,
          121
        ],
        [
          248,
          110
        ],
        [
          259,
          103
        ],
        [
          269,
          103
        ],
        [
          262,
          110
        ],
        [
          251,
          117
        ],
        [
          312,
          74
        ],
        [
          316,
          64
        ],
        [
          326,
          57
        ],
        [
          334,
          57
        ],
        [
          330,
          64
        ],
        [
          319,
          71
        ],
        [
          312,
          178
        ],
        [
          319,
          167
        ],
        [
          330,
          153
        ],
        [
          337,
          150
        ],
        [
          344,
          146
        ],
        [
          359,
          142
        ],
        [
          369,
          142
        ],
        [
          366,
          157
        ],
        [
          362,
          171
        ],
        [
          355,
          178
        ],
        [
          344,
          182
        ],
        [
          330,
          182
        ],
        [
          316,
          178
        ],
        [
          334,
          164
        ],
        [
          341,
          157
        ],
        [
          348,
          153
        ],
        [
          366,
          142
        ],
        [
          355,
          160
        ],
        [
          348,
          167
        ],
        [
          337,
          171
        ]
      ]
    }
  ],
  "05875.png": [
    {
      "r": 0,
      "x": 186,
      "w": 208,
      "y": 0,
      "h": 227,
      "landmarksXY": [
        [
          201,
          143
        ],
        [
          218,
          164
        ],
        [
          235,
          178
        ],
        [
          253,
          189
        ],
        [
          274,
          206
        ],
        [
          295,
          216
        ],
        [
          316,
          216
        ],
        [
          340,
          216
        ],
        [
          368,
          209
        ],
        [
          385,
          185
        ],
        [
          389,
          164
        ],
        [
          392,
          147
        ],
        [
          392,
          126
        ],
        [
          389,
          101
        ],
        [
          382,
          84
        ],
        [
          371,
          63
        ],
        [
          354,
          46
        ],
        [
          211,
          115
        ],
        [
          218,
          101
        ],
        [
          229,
          88
        ],
        [
          239,
          81
        ],
        [
          249,
          77
        ],
        [
          288,
          49
        ],
        [
          298,
          39
        ],
        [
          305,
          32
        ],
        [
          319,
          28
        ],
        [
          333,
          28
        ],
        [
          291,
          91
        ],
        [
          302,
          105
        ],
        [
          312,
          119
        ],
        [
          319,
          129
        ],
        [
          309,
          147
        ],
        [
          316,
          143
        ],
        [
          326,
          140
        ],
        [
          330,
          133
        ],
        [
          333,
          126
        ],
        [
          239,
          122
        ],
        [
          246,
          112
        ],
        [
          253,
          105
        ],
        [
          267,
          105
        ],
        [
          260,
          112
        ],
        [
          249,
          119
        ],
        [
          305,
          77
        ],
        [
          312,
          67
        ],
        [
          323,
          60
        ],
        [
          330,
          56
        ],
        [
          326,
          67
        ],
        [
          316,
          74
        ],
        [
          312,
          182
        ],
        [
          316,
          171
        ],
        [
          326,
          157
        ],
        [
          333,
          154
        ],
        [
          340,
          147
        ],
        [
          354,
          143
        ],
        [
          364,
          147
        ],
        [
          364,
          161
        ],
        [
          357,
          171
        ],
        [
          350,
          182
        ],
        [
          340,
          185
        ],
        [
          326,
          185
        ],
        [
          312,
          182
        ],
        [
          330,
          164
        ],
        [
          337,
          161
        ],
        [
          347,
          154
        ],
        [
          361,
          147
        ],
        [
          350,
          161
        ],
        [
          344,
          168
        ],
        [
          333,
          175
        ]
      ]
    },
    {
      "r": 0,
      "x": 515,
      "w": 579,
      "y": 79,
      "h": 661,
      "landmarksXY": [
        [
          521,
          196
        ],
        [
          501,
          205
        ],
        [
          491,
          355
        ],
        [
          501,
          225
        ],
        [
          501,
          345
        ],
        [
          531,
          504
        ],
        [
          541,
          533
        ],
        [
          561,
          563
        ],
        [
          620,
          603
        ],
        [
          561,
          583
        ],
        [
          998,
          146
        ],
        [
          630,
          186
        ],
        [
          918,
          643
        ],
        [
          928,
          663
        ],
        [
          650,
          235
        ],
        [
          1057,
          434
        ],
        [
          888,
          603
        ],
        [
          531,
          196
        ],
        [
          908,
          315
        ],
        [
          630,
          225
        ],
        [
          640,
          225
        ],
        [
          640,
          235
        ],
        [
          1008,
          444
        ],
        [
          988,
          474
        ],
        [
          1037,
          265
        ],
        [
          610,
          196
        ],
        [
          1077,
          305
        ],
        [
          620,
          374
        ],
        [
          888,
          623
        ],
        [
          1107,
          335
        ],
        [
          630,
          355
        ],
        [
          571,
          285
        ],
        [
          571,
          285
        ],
        [
          571,
          295
        ],
        [
          531,
          394
        ],
        [
          590,
          295
        ],
        [
          571,
          265
        ],
        [
          571,
          265
        ],
        [
          580,
          265
        ],
        [
          610,
          275
        ],
        [
          590,
          285
        ],
        [
          571,
          285
        ],
        [
          918,
          613
        ],
        [
          928,
          613
        ],
        [
          948,
          424
        ],
        [
          561,
          255
        ],
        [
          918,
          623
        ],
        [
          918,
          613
        ],
        [
          640,
          225
        ],
        [
          571,
          215
        ],
        [
          521,
          205
        ],
        [
          521,
          205
        ],
        [
          471,
          404
        ],
        [
          610,
          255
        ],
        [
          690,
          563
        ],
        [
          670,
          513
        ],
        [
          759,
          -131
        ],
        [
          590,
          215
        ],
        [
          630,
          225
        ],
        [
          630,
          215
        ],
        [
          640,
          215
        ],
        [
          541,
          265
        ],
        [
          521,
          255
        ],
        [
          670,
          504
        ],
        [
          720,
          533
        ],
        [
          749,
          -62
        ],
        [
          561,
          235
        ],
        [
          580,
          205
        ]
      ]
    }
  ],

**Comment by minersday** [comment]
Just a guess, should this be on the other deleted image "r": 1 ? and not the same as the correct face image?
