### ISSUE TITLE
Can’t handler occluded face such as using microphone 

### ISSUE THREAD

**Issue by g0147** [deepfakes/faceswap#441]
GAN (use perceptual loss) and Org are can’t handler occluded case such as microphone cover the mouth, may I know whether it is config problem or bug so that to solve it? Thank you.

**Comment by bryanlyon** [comment]
This is not a bug, it's a model limitation,  It may try to remove any occlusions, but it's trained to recreate a source accurately so it will keep occlusions.  We'd need to define a new loss function to enable occlusions removal without losing things like expression and lighting, which we want to keep.

**Comment by g0147** [comment]
Would you explain more details for action step by step?It is look like difficult...

**Comment by bryanlyon** [comment]
It's not a bug, try selecting a different video/images instead.

**Comment by g0147** [comment]
That mean’s It is no solution at now, please wait for new function development for handler the occlusion training?

**Comment by torzdf** [comment]
Yes, someone needs to develop a model that can handle it.
