### ISSUE TITLE
Error when convert in GAN / GAN128 mode.

### ISSUE THREAD

**Issue by g0147** [deepfakes/faceswap#446]
.....faceswap-master\scripts\convert.py", line 74, in load_model
self._image_shape = model.IMAGE_SHAPE
AttributeError: 'GANModel' object has no attribute 'IMAGE_SHAPE'

**Comment by FurtherGazer** [comment]
I have also encountered this problem. Have you solved it?

**Comment by torzdf** [comment]
Try latest commit. Looks like a bug was implemented with a recent model change
