### ISSUE TITLE
Attribute Error during convert

### ISSUE THREAD

**Issue by AWildRando** [deepfakes/faceswap#448]
Convert fails while initializing. Command to run (with local paths redacted):
`python faceswap.py convert -i test -o out --alignments alignments.json --serializer json -D cnn -l 0.6 -m models -a complete -t LowMem -c Adjust -b 2 -M facehullandrect -g 1 -fr 26242-26400 -sm -aca`
Key thing to note is I am running in low mem mode. I can upload the model if needed as I don't know how easy it is to reproduce without it.

Full log:
```
Loading...
Using TensorFlow backend.
Output Directory: D:\Downloads\temp\FakeApp3.0\gibi\out
Input Directory: D:\Downloads\temp\FakeApp3.0\gibi\test
Loading Extract from Extract_Align plugin...
Using json serializer
Alignments filepath: D:\Downloads\temp\FakeApp3.0\gibi\test\alignments.json
Loading Model from Model_LowMem plugin...
loaded model weights
Traceback (most recent call last):

File "faceswap.py", line 36, in <module>
ARGUMENTS.func(ARGUMENTS)
File "lib\cli.py", line 81, in execute_script
process.process()
File "scripts\convert.py", line 42, in process
model = self.load_model()
File "scripts\convert.py", line 74, in load_model
self._image_shape = model.IMAGE_SHAPE
AttributeError: 'Model' object has no attribute 'IMAGE_SHAPE'
Process exited.
```

**Comment by torzdf** [comment]
There was a bug introduced in a recent commit. this should have been fixed in f90cd92ec36a0860c58a75631f762069419149de

Re-pull.
