### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok' when running OriginalHighRes

### ISSUE THREAD

**Issue by gessyoo** [deepfakes/faceswap#449]
## Expected behavior

Want to use the OriginalHighRes model to train

## Actual behavior
Training with OriginalHighRes model throws error message "TypeError: makedirs() got an unexpected keyword argument 'exist_ok'" 

## Steps to reproduce
python faceswap.py train -A dir -b dir -t OriginalHighRes -pl -ag -p -bs 32

- **Operating system and version:** Windows 10 x64
- **Python version:**  3.6.5  Anaconda x64
- **Faceswap version:** commit hash or version number: 346 
- **Faceswap method:** GPU
- **Other related issues:**  Google searching indicates that python 3.6 supports makedirs() with keyword argument 'exist_ok', but that Python 2.7 does not.  But I'm running 3.6, as verified by experimentally adding import sys  print(sys.version) to utils.py.  
If "exist_ok" is deleted from the line 21: output_dir.mkdir(parents=True, exist_ok=True) of utils.py, then training works as expected, but the models directory must be deleted for every new training.   The top line of the training preview window shows "training using <OriginalHighRes: ver=2.7, dense_dim=1024, img_size=128x128> bs=32"

 
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment]
output_dir.mkdir hasn't been touched since February 1st (c3e15089fe355d8783a8b00b2a4d8b89e4f90870), so it's likely the problem is with your install, I'm afraid.

You could try using Python 3.5 which is the version that faceswap is developed in
