### ISSUE TITLE
some test question on trained model.

### ISSUE THREAD

**Issue by visonpon** [deepfakes/faceswap#45]
I followed the guide
[https://github.com/deepfakes/faceswap/blob/master/USAGE.md#testing-out-our-bot](url) to test the trained model's output
`python faceswap.py convert -i ~/faceswap/photo/trump/ -o ~/faceswap/output/ -m ~/faceswap/models/`
 but the results  are like this:

![847277056](https://user-images.githubusercontent.com/11517731/34458709-a7551d4c-ee17-11e7-8ba1-4290e717b280.jpg)
Am i missed something? @joshua-wu @Ganonmaster

**Comment by Ganonmaster** [comment]
What does the training preview output look like?

**Comment by duoyu5555** [comment]
I had a similar problem. Is it caused by a too-short-training time or some problems of resolution or something else?

**Comment by visonpon** [comment]
@Ganonmaster @duoyu5555 i just use the trained model provided by the author to generate the output, and didn't train the model.

**Comment by Clorr** [comment]
Reopen on faceswap-playground if still relevant
