### ISSUE TITLE
What is the use of alpha ?

### ISSUE THREAD

**Issue by cookie-yang** [deepfakes/faceswap#451]
Sorry for asking questions instead of reporting bugs here since I found this issues repo is more active than issues in playground.

My question is what is the use of alpha? 

Since in GAN model, decoder part, the output of decoder is concatenate of alpha and rgb, I wonder what is the alpha and why it is used here? Thanks A lot！

<img width="569" alt="screen shot 2018-06-27 at 5 09 32 pm" src="https://user-images.githubusercontent.com/17507081/41964635-1bca0dee-7a2d-11e8-834e-06c8f6addd99.png">

**Comment by Kirin-kun** [comment]
The way I see it, it's to have a different activation function for the alpha (transparency) channel than for the rgb channels and then concatenate the convolution kernels.

**Comment by cookie-yang** [comment]
Thanks so much for replying, but could you please further explain the transparency(alpha) channel means? And what is the purpose to use it here?
