### ISSUE TITLE
Modify extractor to focus on mouth

### ISSUE THREAD

**Issue by rosenb0rg** [deepfakes/faceswap#462]
I'd like to modify the extractor script to focus on the lower half of the face - specifically the mouth area. 

I'm experimenting with changing people's mouth movements, and I want to train a higher resolution "mouth only" network, so I can create new speech patterns that are re-composited onto the original footage. 

Is there a way to modify which facial landmarks the extractor looks at so it just takes the mouth?

**Comment by bryanlyon** [comment]
You can easily do that by modifying the extract to focus only on the points around the mouth. Feel free to use the landmarks around the mouth (49-68) instead of the landmarks that are used now.
a good place to start:
https://stackoverflow.com/questions/41794191/dlib-facial-landmark-starting-index

**Comment by rosenb0rg** [comment]
Thanks - I'm a little confused about this.

It seems like I'd want to modify "process_single_image" in extract.py so that instead of pulling an entire face, it just pulls the region around landmarks 49 to 68. This leads to "get_faces" in fsmedia.py, which in turn leads to "detect_faces" in faces_detect.py. Here I tried this modification to use only the mouth subset of the landmarks:

`    for face in face_detect.landmarks:
        ax_x, ax_y = face[0][0], face[0][1]
        right, bottom = face[0][2], face[0][3]
        landmarks = face[1]
        **landmarks = landmarks[49:68]**
`

but i get the following error:

`failed to extract from image <image path> Reason: shapes (2,51) and (2,2) not aligned: 51 (dim 1) != 2 (dim0)`

**Comment by torzdf** [comment]
In scripts/extract.py, line 101 insert raise to get the traceback.

that is change the block to:
```

        except Exception as err:
            if self.args.verbose:
                print("Failed to extract from image: "
                      "{}. Reason: {}".format(filename, err))
                raise
return retval
```

**Comment by rosenb0rg** [comment]
I get this:

Failed to extract from image: C:\local\src\deepfakes\test\test.jpg. Reason: shapes (2,51) and (2,2) not aligned: 51 (dim 1) != 2 (dim 0)

Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "C:\local\src\deepfakes\lib\cli.py", line 81, in execute_script
    process.process()
  File "C:\local\src\deepfakes\scripts\extract.py", line 43, in process
    self.extract_single_process()
  File "C:\local\src\deepfakes\scripts\extract.py", line 56, in extract_single_process
    filename, faces = self.process_single_image(filename)
  File "C:\local\src\deepfakes\scripts\extract.py", line 94, in process_single_image
    for idx, face in process_faces]
  File "C:\local\src\deepfakes\scripts\extract.py", line 94, in <listcomp>
    for idx, face in process_faces]
  File "C:\local\src\deepfakes\scripts\extract.py", line 115, in process_single_face
    self.faces.align_eyes)
  File "C:\local\src\deepfakes\plugins\Extract_Align.py", line 11, in extract
    alignment = get_align_mat(face, size, align_eyes)
  File "C:\local\src\deepfakes\lib\aligner.py", line 29, in get_align_mat
    mat_umeyama = umeyama(numpy.array(face.landmarks_as_xy()[17:]), landmarks_2D, True)[0:2]
  File "C:\local\src\deepfakes\lib\umeyama.py", line 49, in umeyama
    A = np.dot(dst_demean.T, src_demean) / num
ValueError: shapes (2,51) and (2,2) not aligned: 51 (dim 1) != 2 (dim 0)

**Comment by torzdf** [comment]
Yeah. You'll need to play around with lib\aligner.py. It expect 68 landmarks

**Comment by rosenb0rg** [comment]
Ok so in extract.py the "resized_face" output come from Extract_Align.py, whose "extract" function in turn calls aligner.py. So it should be the facial landmarks in there that determine what part of the face gets cropped?

It looks like the mean_face_x and mean_face_y values in aligner.py are referencing the last 51 facial landmarks (i.e. everything but the jawline). I tried modifying alignery.py after line 24 so it only uses the last 20 landmarks (i.e. just the mouth region), and then passing only the last 20 detected facial landmarks into umeyama. 

```
mean_face_y = mean_face_y[-20:]
mean_face_x = mean_face_x[-20:]

landmarks_2D = numpy.stack( [ mean_face_x, mean_face_y ], axis=1 )

def get_align_mat(face, size, should_align_eyes):
    mat_umeyama = umeyama(numpy.array(face.landmarks_as_xy()[-20:]), landmarks_2D, True)[0:2]

    if should_align_eyes is False:
        return mat_umeyama
```

This modification gets a working output (no more matrix dimension mismatch errors), but I just get the same result as with the unmodified script. I would expect this to crop just around the mouth area, but I'm not getting anything different. When I play around with the parameters - using the last 10 landmarks, or 5 random landmarks in the middle, sometimes the output will rotate, or crop slightly - but I can't isolate a single feature.

**Comment by rosenb0rg** [comment]
Well, I couldn't figure out how to modify the extractor script, so for the moment I just wrote a short extraction script that will isolate individual facial features, kick out a 256x256 jpeg, along with a json file with the coordinates to re-composite after training/conversion. The json file feeds into a second "replacer" script to recomposite the extracted face part after it's been altered.

Linking to the [repo](https://github.com/rosenb0rg/feature_extractor) here if anyone in the future is trying something similar and closing the issue.
