### ISSUE TITLE
Sort tool issues

### ISSUE THREAD

**Issue by kellurian** [deepfakes/faceswap#465]
Been having problems with the sort tool recently, though in the past it seemed to work fine. Currently, if I have it sort through a set of images, I can get rename blur option to work, but no others. Specifically, lets say that I want it to sort by hist and move the images to a new folder, it will typically move about 300-400, and the rest I get this error:
```
[WinError 2] The system cannot find the file specified: 'C:\\faceswap\\data\\Kayla 2\\file30499_0.png' -> 'C:\\faceswap\\data\\Sort\\0\\file30499_0.png'
Failed to move C:\faceswap\data\Kayla 2\file30499_0.png to C:\faceswap\data\Sort\0\file30499_0.png
```
But instead of saying that for each image, it seems to pick like 3 images and gives this error like a thousand times.  If I change the options to say keep the files and move/rename them, it will give me the same number of images moved, but it copies like 4 or 5 images and all the images are of those copies. So I will have like 6500 images that are really just copies of 4 or 5 images.  Blur seems to work ok, but all the rest give me similar bugs. I have the most recent master version.
In addition, I had a backup of faceswap master from July 2, and just copied out the tools folder and tools.py file, and used the sort tool through the gui, and everything worked fine. It seems to be a problem with the version done 22 days ago.

*Edited for code markup

**Comment by nigh8w0lf** [comment]
I can confirm that this issue happens with the latest version

**Comment by torzdf** [comment]
Please try latest commit in staging branch

**Comment by torzdf** [comment]
Now merged to Master
