### ISSUE TITLE
extract.py without alignment file exits with AttributeError: 'Namespace' object has no attribute 'multiprocess'

### ISSUE THREAD

**Issue by agilebean** [deepfakes/faceswap#467]
## Expected behavior
In CPU mode, if alignments file doesn't exist, run self-generation of alignment file by extract_single_process() by this code:
```
    def process(self):
        """ Perform the extraction process """
        ...
        if self.args.multiprocess and GPUStats().device_count == 0:
            ...
            self.extract_multi_process()
        else:
            self.extract_single_process()
```
## Actual behavior

```
Traceback (most recent call last):
  File "faceswap.py", line 36, in <module>
    ARGUMENTS.func(ARGUMENTS)
  File "/Users/Chaehan/faceswap/lib/cli.py", line 81, in execute_script
    process.process()
  File "/Users/Chaehan/faceswap/scripts/convert.py", line 38, in process
    self.generate_alignments()
  File "/Users/Chaehan/faceswap/scripts/convert.py", line 60, in generate_alignments
    extract.process()
  File "/Users/Chaehan/faceswap/scripts/extract.py", line 36, in process
    if self.args.multiprocess and GPUStats().device_count == 0:
AttributeError: 'Namespace' object has no attribute 'multiprocess'
```
During final conversion, convert.py only calls extract.py if the alignment file doesn't exist.
However, this is a valid use case when the training is done in a cloud-based GPU, and the conversion is done afterwards on the local machine to save cloud time.

## Steps to reproduce
1. delete alignments.json file in images directory
2. run final conversion 

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py convert 
- **Operating system and version:** macOS High Sierra
- **Python version:** 3.6.5
- **Faceswap version:** latest
- **Faceswap method:** CPU

**Comment by torzdf** [comment]
Try latest commit in staging branch

**Comment by richard-bmc** [comment]
I had the sample problem while calling "faceswap convert", but I was using GPU mode.
After trying the latest staging branch, now I can convert faces using GPU mode.

**Comment by torzdf** [comment]
Thanks now merged to Master
