### ISSUE TITLE
Feature request: Add noise to converted image.

### ISSUE THREAD

**Issue by minersday** [deepfakes/faceswap#469]
Option to add noise to converted image and amount.
This will make the conversions look more realistic for now.

**Comment by minersday** [comment]
Maybe, like?
Parameters
----------
image : ndarray
    Input image data. Will be converted to float.
mode : str
    One of the following strings, selecting the type of noise to add:

    'gauss'     Gaussian-distributed additive noise.
    'poisson'   Poisson-distributed noise generated from the data.
    's&p'       Replaces random pixels with 0 or 1.
    'speckle'   Multiplicative noise using out = image + n*image,where
                n is uniform noise with specified mean & variance.


import numpy as np
import os
import cv2
def noisy(noise_typ,image):
   if noise_typ == "gauss":
      row,col,ch= image.shape
      mean = 0
      var = 0.1
      sigma = var**0.5
      gauss = np.random.normal(mean,sigma,(row,col,ch))
      gauss = gauss.reshape(row,col,ch)
      noisy = image + gauss
      return noisy
   elif noise_typ == "s&p":
      row,col,ch = image.shape
      s_vs_p = 0.5
      amount = 0.004
      out = np.copy(image)
      # Salt mode
      num_salt = np.ceil(amount * image.size * s_vs_p)
      coords = [np.random.randint(0, i - 1, int(num_salt))
              for i in image.shape]
      out[coords] = 1

      # Pepper mode
      num_pepper = np.ceil(amount* image.size * (1. - s_vs_p))
      coords = [np.random.randint(0, i - 1, int(num_pepper))
              for i in image.shape]
      out[coords] = 0
      return out
  elif noise_typ == "poisson":
      vals = len(np.unique(image))
      vals = 2 ** np.ceil(np.log2(vals))
      noisy = np.random.poisson(image * vals) / float(vals)
      return noisy
  elif noise_typ =="speckle":
      row,col,ch = image.shape
      gauss = np.random.randn(row,col,ch)
      gauss = gauss.reshape(row,col,ch)        
      noisy = image + image * gauss
      return noisy

**Comment by tryzombie501** [comment]
Noise could help but it might also ruin some photos. (For example if the photos are really clear) This is something that should be done by a human if they wanted to give it a more realistic feeling.

Devices save images differently with different types of noise. This seems like more work than what it's worth in my view.

**Comment by torzdf** [comment]
This could be written as a post-processing tool. I assume Noise would be added to the whole frame, not just the swap area. As @tryzombie501 says, this could currently be done by batch processing by a human in GIMP or Photoshop. 

If anyone were to write this as a tool, it would get merged, but it isn't a priority for me.

**Comment by minersday** [comment]
Actually I was thinking that, it would be added only to the swap area, as the the other area in the frame has already original noise or other compress artifacts.

**Comment by torzdf** [comment]
@telecast-git The alignments tool currently in PRs (and soon to be merged to staging) allows to re-extract faces. If you were to point the frames directory at your output folder rather than the source frames, it would output the swapped faces.

I haven't used it for this purpose, but it should work fine. Any feedback is appreciated.

Closing this for now, as any other action is unlikely to be taken.
