### ISSUE TITLE
Recent merge, dlib-cnn doesn't find faces

### ISSUE THREAD

**Issue by kellurian** [deepfakes/faceswap#471]
Working previously, but dlib-cnn no no longer finds faces, at least not in the videos I have tried. Mtcnn still works. Anyone else have this issue with the new merge?

**Comment by torzdf** [comment]
Please could you run with the -v switch and post your command and output.

**Comment by kellurian** [comment]
I am away for a few days but will when I get the chance

**Comment by leeeeeeo** [comment]
In my case, mtcnn doesn't work. But my dlib-cnn works fine. 
When using default mtcnn, no face can be detected.
But dlib-cnn can detect the same image. Weird.

**Comment by deepfaceswap12345** [comment]
same thing here, mtcnn works when extracting with the most recent Master, but dlib-cnn doesn't work anymore, used to before

**Comment by torzdf** [comment]
> Please could you run with the -v switch and post your command and output.

**Comment by minersday** [comment]
Same here dlib-cnn does not work, 
Adding DLib - CNN detector
Failed to extract from image: xxxxx.png. Reason: Error while calling cudnnConvolutionForward( context(), &alpha, descriptor(data), data.device(), (const cudnnFilterDescriptor_t)filter_handle, filters.device(), (const cudnnConvolutionDescriptor_t)conv_handle, (cudnnConvolutionFwdAlgo_t)forward_algo, forward_workspace, forward_workspace_size_in_bytes, &beta, descriptor(output), output.device()) in file xxxxxx\dlib\dlib\cuda\cudnn_dlibapi.cpp:1007. code: 3, reason: CUDNN_STATUS_BAD_PARAM

**Comment by torzdf** [comment]
Closing as can't replicate and not enough info.

**Comment by minersday** [comment]
dlib-hog works

**Comment by torzdf** [comment]
Which cuDNN version are you using?

**Comment by torzdf** [comment]
Also, just to eliminate it as a possibility, could you go into the file:
`lib/face_alignment/vram_allocation.py`
and edit line 122 from:

`buffer = 64 # 64MB overhead buffer`

to

`buffer = 2048 # 2GB overhead buffer`

try running, and let me know if that fixes it.

**Comment by torzdf** [comment]
I have implemented a new cli option to hold back more VRAM from DLib, implemented in this commit:

3c83a068ffbd991b69c81dac9ea1f8b9e881b217

Upping the amount of MBs held back should solve any issues with running out of VRAM with DLib.

```
 -dbf DLIB_BUFFER, --dlib-buffer DLIB_BUFFER
                        This should only be increased if you are having issues
                        extracting with DLib-cnn. The calculation of RAM
                        required is approximate, so some RAM is held back in
                        reserve (64MB by default). If this is not enough
                        increase this figure by providing an integer
                        representing the amount of megabytes to reserve.
                        (DLIB-CNN Only)
```
