### ISSUE TITLE
MTCNN doesn't work

### ISSUE THREAD

**Issue by leeeeeeo** [deepfakes/faceswap#472]
When extracting faces. I used default setting, which is mtcnn. But no face can be detected. 
I tried dlib-cnn, and it works fine. What's the problem?

By the way, I'd like to know will it better if `--align-eyes` is True?

**Comment by torzdf** [comment]
Please could you run with the -v switch and post your command and output.

**Comment by leeeeeeo** [comment]
@torzdf And I have the third question: If I train with the -w switch, how often would save image once ?
Thank you soooooooo much!

**Comment by torzdf** [comment]
For your first issue, it looks like you are running an old version of TensorFlow. Try upgrading.

-- align-eyes won't impact performance, it just does a further alignment at the end of the extract process, you can try it with or without to see which you prefer. To be honest, the difference will probably be minor.

With the -w switch, the image will save with every save iteration (every 100 iterations at default)

**Comment by leeeeeeo** [comment]
@torzdf For the first issue, my tensorflow version is 1.4.0 from `tensorflow.__version__`.
In the setup.py, the required tensorflow version is 1.4.0.
I don't think it's an old version problem...

**Comment by torzdf** [comment]
We should probably bump the version.

Basically the command keepdims was called keep_dims in older versions of tensorflow. You can do one of 2 things:

1) Upgrade tensorflow to the latest version

or

2) Go into the file `lib/face_alignment/mtcnn.py` and do a find/replace for `keepdims changing it to `keep_dims` (lines 215 and 217)

**Comment by leeeeeeo** [comment]
@torzdf Thank you for your advice!
By the way, if I use MTCNN instead of dlib-cnn, will the final results be better?

**Comment by torzdf** [comment]
It won't impact training, but MTCNN tends to find more faces than DLIB

**Comment by leeeeeeo** [comment]
@torzdf Sorry that I'd like to ask one more question:
In these training modes, origin, original high res, gan, gan 128. Which one gets the best performance?

After tried origin and origin high res, I found it's harder to train origin high res than origin....: (
Does this mean I need more data for origin high res than origin?

**Comment by torzdf** [comment]
see: See: deepfakes/faceswap-playground#164
