### ISSUE TITLE
conversions done on extracted areas with no actual human faces

### ISSUE THREAD

**Issue by dawningo** [deepfakes/faceswap#474]
This really works quite well when the scene contains only one human face, really job well done and a lot of fun to play with. However, on some occasions mtcnn would extract areas that are not actually human faces and perform conversions, which makes the scene quite weird.
So what I am trying to say is, is there a way to avoid conversions on certain extraction areas? Thanks a lot!

**Comment by torzdf** [comment]
Two ways, which ultimately boil down to the same thing: Manually remove the false positives from the extracted faces folder.

You can then set the `-a` (`--input-aligned-dir`) flag to point at your extracted folder and it will skip any deleted faces.

There is also an alignment tool coming (check the PRs) which should make finding false positives a little easier, by identifying frames with multiple images. You can then use the same tool to remove false positives from the alignment file permanently.
