### ISSUE TITLE
Frames don't sync with audio

### ISSUE THREAD

**Issue by leeeeeeo** [deepfakes/faceswap#475]
@torzdf 
I want to merge frames and origin audio using command:
`ffmpeg -r 25 -i out.mp4 -r 25 -i origin.m4a -map 0:v -map 1:a -c copy -shortest output.mp4`
in which, input.mp4 comes from:
`ffmpeg -i video-frame-%0d.png -c:v libx264 -vf "fps=25,format=yuv420p" out.mp4` as USAGE.md.

But frames and audio don't sync in a few seconds later. 
They do sync in the first few seconds, but later, audio goes faster and frames go slower. 
For example, I heard the word 'factory' first, then I saw the mouth said 'factory' in about 2 seconds.

If some frames are not converted because faces are missed, frames would seems faster. But now, audio goes faster.
So I come for some advice.
I'm looking forward to your reply. Thank you!

**Comment by torzdf** [comment]
This isn't really the best place for these kinds of questions.

See: https://github.com/deepfakes/faceswap-playground/issues/164
