### ISSUE TITLE
Web UI?

### ISSUE THREAD

**Issue by lukaville** [deepfakes/faceswap#48]
I think it would be nice to have web UI for this project. It may be very helpful when running the script in a cloud, but also it may be convenient for local usage. Users can set up everything by executing one simple `docker run`/`nvidia-docker run` command which will start web ui server.

I made a few sketches to better understand the idea: https://www.figma.com/file/LCHSW0lMj8OAUo8dLOljPc9b/Deepfakes

![image](https://user-images.githubusercontent.com/725526/34470891-6cb2abec-ef4c-11e7-9f92-b10b5e0d03f8.png)
![image](https://user-images.githubusercontent.com/725526/34470896-89eb9836-ef4c-11e7-809d-dbbb8ffef8dc.png)

What do you think about it?

**Comment by Yutsa** [comment]
That'd be awesome and maybe not too hard to implement using Flask for instance. That would be really interesting to do

**Comment by Ganonmaster** [comment]
I would encourage this, but would prefer keeping it in a separate repository, perhaps importing this project as a library of some kind.

**Comment by Clorr** [comment]
This is nice indeed!

The main drawback I see here for a newbie wanting to launch this on his computer is the docker/nvidia-docker dependency. But for a cloud install, this would be very nice...

**Comment by Clorr** [comment]
Also did someone try a Jupyter / Notebook launch ?

**Comment by shaoanlu** [comment]
How about [colaboratory](https://colab.research.google.com)? It is a interactive notebook platform provided by Google that has tensorflow pre-installed. Maybe we can make a simple demo on it, e.g.,  using trained model to swap a single 64x64 face image.

**Comment by johndpope** [comment]
Please bring back -

**Comment by torzdf** [comment]
This never existed and there are no plans to implement.

The original image is a mock up from over 3 years ago
