### ISSUE TITLE
Extract working not working with GPU, only CPU, is there a way to get it to work with GPU?

### ISSUE THREAD

**Issue by deepfaceswap12345** [deepfakes/faceswap#481]
**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

## Expected behavior

I'm trying to get the extract portion of the code to work with the GPU, but it's only using the CPU, which makes it 10 or 20 time slower than if the GPU was doing it. Is there a way to get the GPU to do the Extract or is it only CPU enabled?

## Steps to reproduce

python faceswap.py extract -i [my folder with the sequence of frames] -o [the folder with the extracted frames] + parameters such as dlib-cnn or with ae as well

No matter what I choose for the parameters, only the CPU kicks in.
For the training, the GPU works like a charm.

## Other relevant information
- **Operating system and version: Windows OS 10
- **Python version: 3.6.4
- **Faceswap version: the latest current Master (163942f69ad37736c6424cbae56995e5a895b0a9)
- **Faceswap method: For Extract, CPU only, sadly

**Comment by bryanlyon** [comment]
Please give us the exact parameters you are using.  We can't troubleshoot without knowing what options you've selected.

**Comment by deepfaceswap12345** [comment]
python faceswap.py extract -i [my folder with the sequence of frames] -o [the folder with the extracted frames] -D dlib-cnn -ae

**Comment by torzdf** [comment]
Run Extract with the -v flag and post the output here please.

Also make sure dlib is compiled for GPU use:

- Open a python terminal 
- post the output from:
```
>>> import dlib
>>> dlib.DLIB_USE_CUDA
```

**Comment by deepfaceswap12345** [comment]
Yeah it's not compiled for CUDA:

>>> dlib.DLIB_USE_CUDA
False

Stupid question, but how do you compile it to use it?

I googled it and for Linux you run something like this (not even sure that's it)
sudo python3.5 setup.py install --yes USE_AVX_INSTRUCTIONS --yes DLIB_USE_CUDA --set CMAKE_PREFIX_PATH=/usr/local/cuda --set CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/bin/ --clean

but for Windows, what are the parameters and paths?
thanks!

**Comment by gessyoo** [comment]
Download and install VS 2015 Community Edition or Visual Studio 2015 Build Tools
Open a command prompt with Admin. rights
Change to your preferred directory
git clone https://github.com/davisking/dlib.git
cd dlib
python setup.py install -G "Visual Studio 14 2015" --yes DLIB_USE_CUDA
If all goes well, you should see DLIB WILL USE CUDA message.
