### ISSUE TITLE
Error extract (DeepFake)

### ISSUE THREAD

**Issue by mariocolino** [deepfakes/faceswap#486]
Hello to all,
I have a problem when extract face with fakeapp1.1 
.....
"align_faces.py", line 7, in <module>
  File "C:\FakeApp\alignment\torch\__init__.py", line 76, in <module>
    from torch._C import *
ImportError: DLL load failed: impossible......
[8640] Failed to execute script align_faces
Why?
CUDA is installed

**Comment by torzdf** [comment]
This isn't fakeapp.
