### ISSUE TITLE
Extract with dlib-cnn doesn't work on macOS

### ISSUE THREAD

**Issue by 1132719438** [deepfakes/faceswap#488]
**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

Extract with dnn-lib on mac OS X 10.13.5 failed:
```
Failed to extract from image: NoneType is not iterable
```
GPU: NVIDIA GTX 1080, 8GB
CUDA: 9.1
Python: 3.6.5

Reason is NVML library is not supported on macOS, so GPUStats.initialize() in [gpu_stats.py](https://github.com/deepfakes/faceswap/blob/master/lib/gpu_stats.py) fail with pynvml.NVMLError_LibraryNotFound, self.handles = None, get_free() gets Exception: "NoneType is not iterable" when extracting with dlib-cnn, no face will be dectected.
Can we work around it?

**Comment by torzdf** [comment]
NVML is kind of integral to extract. It may be that we may have to add some kind of manual config for macOS, but unfortunately it's not a priority right now. I will look into it when I have a chance (or someone else can raise a PR).

In the meantime you can rollback to the last pre-nvml build (https://github.com/deepfakes/faceswap/tree/f90cd92ec36a0860c58a75631f762069419149de)

**Comment by torzdf** [comment]
implemented in #510
