### ISSUE TITLE
When using alignments tool, it will crash when not supplying a faces folder.

### ISSUE THREAD

**Issue by Tvde1** [deepfakes/faceswap#490]
**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

## Expected behavior

Command will run

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

```
ERROR: The folder None could not be found
```

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

Try it with this:
```
python G:\Repositories\faceswap\tools.py alignments -j missing-frames -a (PATH)  -fr (PATH) -o console -v
```
Here it crashes.

And if I do supply the `-fc` parameter, it exits because it is only valid with multi faces:
```
WARNING: The selected folder is not valid. Only folder set with '-fc' is supported for 'multi-faces'
```

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment]
Are you running latest commit? Just tested:
```
python tools.py alignments -j missing-frames -a /mnt/fakes/Masters/A/test/frames/25fps/alignments.json  -fr /mnt/fakes/Masters/A/test/frames/25fps  -o console -v
Please backup your data and/or test the tool you want to use with a smaller data set to make sure you understand how it works.

[ALIGNMENT DATA]
Alignments file exists at /mnt/fakes/Masters/A/test/frames/25fps/alignments.json
Destination format set to json
Loading alignments from /mnt/fakes/Masters/A/test/frames/25fps/alignments.json
32821 items loaded

[FRAMES DATA]
Folder exists at /mnt/fakes/Masters/A/test/frames/25fps
Loading file list from /mnt/fakes/Masters/A/test/frames/25fps
32821 items loaded

[CHECK FRAMES]
No frames were found meeting the criteria
```

**Comment by Tvde1** [comment]
Hmm I'll check. On staging right?

**Comment by torzdf** [comment]
That was run from Master branch, but it wouldn't hurt to try staging. I've just tested staging myself, and it works.

**Comment by Tvde1** [comment]
Ah it's been fixed on staging.
