### ISSUE TITLE
Tester needed for extracting with dlib on OS X

### ISSUE THREAD

**Issue by 1132719438** [deepfakes/faceswap#493]
I have opened a repository [pynvx](https://github.com/1132719438/pynvx) to get GPU information on OS X, so that issue #488 should be solved. Please test if extracting with dlib works using this [fork](https://github.com/1132719438/faceswap).

```
python faceswap.py extract -i /input/path -o /output/path -D dlib-cnn -v
```

**Comment by torzdf** [comment]
implemented in #510
