### ISSUE TITLE
Amount of RAM needed?

### ISSUE THREAD

**Issue by cercata** [deepfakes/faceswap#5]
I'm trying to train the network with the example provided, and it crashes with this error:

_"Resource exhausted: OOM when allocating tensor with shape"_

Python reached 3.7GB, and my compute has 8GB, had a peak of 9.8GB used.

I'm using Tensor Flow on CPU, How Much RAM is needed ?

**Comment by Clorr** [comment]
This may be specific to your setup. Please tell us what env are you running on. Do you use Docker ? Docker-machine ?

Also, for standard errors, a little Google search can help. [This page](https://github.com/tensorflow/tensorflow/issues/136) for example has a couple of reasons/solutions.

**Comment by Ganonmaster** [comment]
You most likely ran out of memory. Your computer has 8GB of RAM and at its peak used 9.8GB. Which means it was most likely writing to the swap space on your hard disk. When your PC runs out of RAM space to write to, it will write to and read to a designated "swap" space on your hard drive as if it were part of your memory. This is to prevent your PC from crashing.

More than 8GB, but 16GB will probably be fine. Just be aware that running it on CPU will most likely be 10 times slower than running it on a GPU. So even if you have the RAM, but not a top of the line CPU or a compatible Nvidia GPU, training will take a long time.

**Comment by deepfakes** [comment]
I'm closing this. If you still have problem, please submit them on the "faceswap-playground" repo

**Comment by cercata** [comment]
So noboby has an Idea of the amount of RAM needed ?

**Comment by Ganonmaster** [comment]
@cercata I tested it on a laptop with 16GB of RAM inside a docker container; it used up roughly 4-6GB. Your mileage may vary.

**Comment by cercata** [comment]
@Ganonmaster Ok, perfect, so no need for huge ammounts of memory :)

**Comment by deepfakes** [comment]
I can start running the train.py on my old iMac with 4Gb, from within a Docker-machine. I never trained fully the model as it takes ages, but at least it starts.

When is your training failing ? At start ? After a while ?

**Comment by cercata** [comment]
@deepfakes it was in the first minute. After closing other programs, now it runs, and updates the h5 files.
The process has some 5.2GB peaks, using Python 3.6 x64 on a Windows 7 machine.

What do you mean by ages ?
If I install the GPU version of tensorflow, I'll need at least 5.2GB of VRAM ? Or it uses mainly RAM ?

**Comment by deepfakes** [comment]
"ages" means that it takes a very long time.
It is an old iMac 2009, so I don't really try to train a model on it. It is just to assess it works...

On the minimal requirements, feel free to share your experience in the faceswap-playground repo. There is no easy way to tell you that this or this platform is eligible or not for training or converting. The only way we have to know that is through the users feedback. 

After, if you want to crawl docs of the tools to gather minimal requirements of each tool, feel free, it is up to you.
