### ISSUE TITLE
How to generate a video ,when I trained the model?

### ISSUE THREAD

**Issue by shliang0603** [deepfakes/faceswap#507]
I use command the line "python faceswap.py gui"
But  I don't konw how to choice these folders
![image](https://user-images.githubusercontent.com/37186266/45859985-ade55780-bd97-11e8-9c61-e7692ba55cd4.png)
Can you give me some suggestions

**Comment by torzdf** [comment]
https://discord.gg/pMkWGC

**Comment by shliang0603** [comment]
@torzdf  now, the url status is "invite invaild".  Can you give me some your experience ?

**Comment by torzdf** [comment]
https://github.com/deepfakes/faceswap-playground/issues/164
