### ISSUE TITLE
Dlib alignment still available?

### ISSUE THREAD

**Issue by petergerten** [deepfakes/faceswap#517]
I figured out how to switch the detector between MTCNN and dlib but I notices that the biggest performance bottleneck is the alignment. I used an older version of the repo and the alignment was done by dlib. Now the FAN / deep learning aligner is used - which is indeed much better - but also much slower. Browsing the code I could not figure out if the old aligner is still available / or if there is a way to switch to that. Any hints?

**Comment by torzdf** [comment]
It isn't... Aligner shouldn't be the bottleneck though, Face Detection takes longer than alignment (assuming you're running on GPU).

Either way, Extractor is currently being reworked to offer speed increases (depending on GPU) and better parallelization, so I recommend holding tight for a week or two and keeping an eye on the staging branch.

**Comment by torzdf** [comment]
See #522
