### ISSUE TITLE
Stitching back png to video , gives blank video when using FFMPEG command

### ISSUE THREAD

**Issue by haarissiddiqie1** [deepfakes/faceswap#530]
i am using the recommended command to stitch pngs backk to a video. but giving me a blank video.

command using:

ffmpeg -i video-frame-%0d.png -c:v libx264 -vf "fps=25,format=yuv420p" out.mp4

## Expected behavior

video output with the stitched frames

## Actual behavior

blank video

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by torzdf** [comment]
ffmpeg problems are out of scope. Your best bet is to go to the Discord group where people will be able to help you.

https://discord.gg/FdEwxXd
