### ISSUE TITLE
Restrict the number of CPU cores used for training?

### ISSUE THREAD

**Issue by HighCommander4** [deepfakes/faceswap#536]
I don't have a GPU, I'm using CPU only. I know that means it'll be slower; that's fine.

However, is there a way to restrict the number of CPU cores used for the training? By default it seems to hog all of them and reduce the responsivity of other applications. I'd like to tell it via some flag to only use, say, half my cores, so I can let it run in the background while doing other things without interference. (I know that means it'll be even slower; that's also fine.) Is there such a flag? If not, can one be added?

**Comment by torzdf** [comment]
This should be doable.

Note for reference:
https://stackoverflow.com/questions/38187808/how-can-i-run-tensorflow-on-one-single-core

**Comment by manasan3010** [comment]
Is it possible to run faceswap with Intel HD Graphics card **or** Intel core i3 CPU @ 2.13GHz?
Can I use either a GPU or a CPU for face swap or is there any barriers???
![image_98](https://user-images.githubusercontent.com/44738527/48659414-a16b3b80-ea76-11e8-99a2-0d9eb3afea60.png)
![image_99](https://user-images.githubusercontent.com/44738527/48659415-a3cd9580-ea76-11e8-982c-c5e12ae162f6.png)

**Comment by HighCommander4** [comment]
The suggestion by @torzdf in [this comment](https://github.com/deepfakes/faceswap/issues/536#issuecomment-438616012) seems promising, but I haven't had the time to try it.

**Comment by bryanlyon** [comment]
Just a note: your CPU will require on the order of a month or two in order to train.  We *HIGHLY* recommend an nvidia GPU.  If you really don't have any way of one, you can try using AWS or Google Colab.  But CPU only is completely unsupported due to the time it'd take to train and run being unacceptably slow.

**Comment by HighCommander4** [comment]
> We HIGHLY recommend an nvidia GPU.

Is there a way of having an nvidia GPU and using it for this purpose, while still using integrated graphics for display? The main reason I don't have an nvidia GPU is that I run Linux and their Linux support is terrible.

**Comment by SagerMaeng** [comment]
@HighCommander4 @bryanlyon 
Thanks,i will try it. A month or two  is really too long.

**Comment by torzdf** [comment]
@HighCommander4 Nvidia GPU support is pretty good these days (for ML anyway, I don't use mine for gaming).

And yes. You can use integrated for display and GPU for training.
