### ISSUE TITLE
 Alignments file not found at /home/administrator/faceswap/ju/alignments.json

### ISSUE THREAD

**Issue by TXien** [deepfakes/faceswap#539]
why i don't get alignment.json after i extract file

## Expected behavior

start to convert

## Actual behavior

ValueError: Error: Alignments file not found at /home/administrator/faceswap/ju/alignments.json

## Steps to reproduce
python3.6 faceswap.py extract -i ~/secret/data/Julie/ -o ./ju/ -A fan
....
python3 faceswap.py convert -i ~/faceswap/ju -o ./train -m ./models

**Comment by torzdf** [comment]
Your convert command looks wrong. Please either look for help on https://github.com/deepfakes/faceswap-playground/issues

Or ask for help in the Discord:
https://discord.gg/FdEwxXd

**Comment by hi0001234d** [comment]
@TXien You should look for the file inside the input dir because in my case it is in the input directory where alignments file is created and if you look at extract command output the path is written there

**Comment by aa3222119** [comment]
@TXien   hi  are you fixed this?  i want know how, 
in my input dir. there is an xx_alignments.fsa file  
dont know how to use it
