### ISSUE TITLE
Restrict usage of GPUs to gpu:/2 

### ISSUE THREAD

**Issue by Atmyre** [deepfakes/faceswap#544]
Hello

I am trying to run the code on server which has 4 opus, but gpu:/0,1 are busy. When I run the code it runs out of memory on gpu 0. How can I restrict usage of you to gpu:/2,3 only?

Thank you in advance

**Comment by torzdf** [comment]
https://stackoverflow.com/questions/39649102/how-do-i-select-which-gpu-to-run-a-job-on
