### ISSUE TITLE
Should originalhighres not have a preview?

### ISSUE THREAD

**Issue by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [deepfakes/faceswap#548]
Just a quick question, im training fine, graph output etc. but no preview. Is this normal?

**Comment by torzdf** [comment]
It should have a preview. There is probably a bug in there somewhere.

This won't be immediately fixed as training section of code is currently being refactored, so this will be handled there.

**Comment by IEWbgfnYDwHRoRRSKtkdyMDUzgdwuBYgDKtDJWd** [comment]
ok cool, was just wondering. thanks for reply.
