### ISSUE TITLE
Can i use Intel Python or it can give me problems?

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#553]
I wonder if i can use Intel Python instead the regukar one or it could give me problems when use the repo? Thx.

**Comment by bryanlyon** [comment]
That release is interested and unsupported.  You can certainly try it, but you'll be in your own for installing supported libraries and troubleshooting the related issues.  I recommend installing anaconda dinner it can be installed alongside any version you're using without interference.

**Comment by ZeroCool22** [comment]
> 
> 
> That release is interested and unsupported. You can certainly try it, but you'll be in your own for installing supported libraries and troubleshooting the related issues. I recommend installing anaconda dinner it can be installed alongside any version you're using without interference.

Ok, thx.
