### ISSUE TITLE
ENABLE DOCKER?

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#555]
Sorry if i'm asking a noob question but have patience with me, since i'm not a python expert...
I come from using the **DeepFaceLab** (Prebuilt windows app) wich is very easy to use, but i want to try this repo to compare the results between each one.

I'm trying this repo for first time, i'm installing it right now following the **install.md** instructions. I'm at the point where i executed **python setup.py** and it ask me if i want to **ENABLE DOCKER**, isn't docker only for Linux? (i'm on Win. 10). Thx.

**Comment by ZeroCool22** [comment]
The installation itself suggest me to not install it, since it's for Linux.

I close it.

**Comment by DKingCN** [comment]
Docker supports windows.
