### ISSUE TITLE
Tell me if i'm right please...

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#556]
I want to be sure before let the PC training all the night...

https://i.postimg.cc/tCV4nmkp/faceswap-GUI-help.png

I'm correct or it's the other way around? Thx.

**Comment by MT-4ier** [comment]
It can work in either direction.
By default, Face B goes onto Body A.
There is a Swap Model checkbox in the Convert tab that can put Face A onto Body B.
