### ISSUE TITLE
Batch size recommended for my specs please...

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#557]
What **Batch Size** would you guys recommend me for this specs:

7700K. 
32gb. 
MSI GTX 1080TI Gaming X. 
SSD.

Also i have a doubt, long train sessions could fuck up my SSD **life spam**? 
It's better to use it on my **HDD** instead?

**Comment by torzdf** [comment]
Use the Discord for these kinds of questions:
https://discord.gg/FdEwxXd
