### ISSUE TITLE
Error Extracting!

### ISSUE THREAD

**Issue by ZeroCool22** [deepfakes/faceswap#558]
Extracting Error: 

Loading...
12/20/2018 01:41:59 INFO     Log level set to: INFO
12/20/2018 01:42:01 INFO     Output Directory: C:\Users\ZeroCool22\Miniconda3\envs\faceswap\output
12/20/2018 01:42:01 INFO     Input Directory: C:\Users\ZeroCool22\Miniconda3\envs\faceswap\input
12/20/2018 01:42:01 INFO     Loading Detect from Mtcnn plugin...
12/20/2018 01:42:01 INFO     Loading Align from Fan plugin...
12/20/2018 01:42:01 INFO     NB: Parallel processing disabled.You may get faster extraction speeds by enabling it with the -mp switch
12/20/2018 01:42:01 INFO     Starting, this may take a while...
12/20/2018 01:42:01 INFO     Initializing MTCNN Detector...
12/20/2018 01:42:02 ERROR    Caught exception in child process: 7588
12/20/2018 01:43:01 INFO     Waiting for Detector... Time out in 4 minutes
12/20/2018 01:44:01 INFO     Waiting for Detector... Time out in 3 minutes
12/20/2018 01:45:01 INFO     Waiting for Detector... Time out in 2 minutes
12/20/2018 01:46:01 INFO     Waiting for Detector... Time out in 1 minutes
12/20/2018 01:47:03 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "C:\Users\ZeroCool22\Miniconda3\envs\faceswap\lib\cli.py", line 90, in execute_script
process.process()
File "C:\Users\ZeroCool22\Miniconda3\envs\faceswap\scripts\extract.py", line 51, in process
self.run_extraction(save_thread)
File "C:\Users\ZeroCool22\Miniconda3\envs\faceswap\scripts\extract.py", line 149, in run_extraction
self.run_detection(to_process)
File "C:\Users\ZeroCool22\Miniconda3\envs\faceswap\scripts\extract.py", line 202, in run_detection
self.plugins.launch_detector()
File "C:\Users\ZeroCool22\Miniconda3\envs\faceswap\scripts\extract.py", line 386, in launch_detector
raise ValueError("Error initializing Detector")
ValueError: Error initializing Detector
12/20/2018 01:47:03 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\ZeroCool22\Miniconda3\envs\faceswap\crash_report.2018.12.20.014701426414.log. Please verify you are running the latest version of faceswap before reporting
Process exited.

I'm using the GUI: https://i.postimg.cc/J4vVZrn2/GUI-error-2.png

**Crash Report:** https://pastebin.com/MMiWRxmU

**Comment by torzdf** [comment]
At the very first time it runs it can time out when initializing. Just try it again.

Also, rather than spamming issues with user questions, please use the Discord:
https://discord.gg/FdEwxXd

Thanks

**Comment by Pluckypan** [comment]
Same Error.And I Try it many times。Mac & Docker & CPU only

```
12/23/2018 17:03:44 INFO     Log level set to: INFO
12/23/2018 17:03:47 INFO     Output Directory: /Users/xxx/github/python/face-data/lyf/out/lyf
12/23/2018 17:03:47 INFO     Input Directory: /Users/xxx/github/python/face-data/lyf/in
12/23/2018 17:03:47 INFO     Loading Detect from Mtcnn plugin...
12/23/2018 17:03:48 INFO     Loading Align from Fan plugin...
12/23/2018 17:03:48 WARNING  No GPU detected. Switching to CPU mode
12/23/2018 17:03:48 INFO     Starting, this may take a while...
12/23/2018 17:03:48 INFO     Initializing Face Alignment Network...
12/23/2018 17:03:48 WARNING  No GPU detected. Switching to CPU mode
12/23/2018 17:03:48 ERROR    Caught exception in child process: 68481
12/23/2018 17:03:49 INFO     Initializing MTCNN Detector...
12/23/2018 17:03:49 ERROR    Caught exception in child process: 68485
12/23/2018 17:04:48 INFO     Waiting for Detector... Time out in 4 minutes
```

**Comment by Pluckypan** [comment]
@torzdf  i resolved it .just run `python faceswap.py extract -i _data/in/lyf/ -o _data/out/lyf/ -A dlib` in docker bash

**Comment by torzdf** [comment]
Most likely it's a timeout. 

```12/23/2018 17:04:48 INFO     Waiting for Detector... Time out in 4 minutes```
means there's still 4 minutes remaining on the timeout. You should wait.

First time FAN runs always takes a long time. It's quick after that

**Comment by jlllweco** [comment]
![image](https://user-images.githubusercontent.com/36145675/51018505-cf6e8700-15b2-11e9-9d77-c5b2a9c9812d.png)

![image](https://user-images.githubusercontent.com/36145675/51018530-e90fce80-15b2-11e9-8b71-29f1a50bd00b.png)
the log is:
![image](https://user-images.githubusercontent.com/36145675/51018574-0cd31480-15b3-11e9-9365-7297e07d1381.png)


Would you please tell me how to fix it?

**Comment by torzdf** [comment]
This issue is closed. The original user had not setup faceswap properly.
