### ISSUE TITLE
Releasing Desktop App w/ GUI

### ISSUE THREAD

**Issue by fakeapp** [deepfakes/faceswap#56]
If anyone here is interested I've created a simple desktop app w/ GUI to distribute the deepfakes toolkit without the need to install python or other dependencies. [Here is a screenshot of it working.](https://imgur.com/BDX9ANb) The download and more info are in [this thread.](https://www.reddit.com/r/deepfakes/comments/7oc018/simple_desktop_app_with_gui/?st=jc2nfd9h&sh=16d48ac8)

Currently this app runs on the original scripts because I wasn't aware of this repo, but I think I'm eventually going to migrate it to the improved scripts here.

**Comment by Clorr** [comment]
Thanks for the link, and feel free to join!

If you have code for the GUI to put here, just make a `gui` folder at the root and do a PR, we will help you on that.

CC @Ganonmaster @Yutsa @lukaville @yangchen8710 @shaoanlu @junglewreck

**Comment by Ganonmaster** [comment]
Looking forward to see the code.

**Comment by Ianmcmill** [comment]
It seems the GUI version didn't manage to get it into here and the current version of fakeapp still runs on dated scripts. Sadly.

**Comment by fakeapp** [comment]
I don't think the original scripts -- which FakeApp runs on -- are dated. Is there a faceswap feature that isn't available in the app that you'd like to see there?

**Comment by Apollo122** [comment]
@fakeapp GAN masking, it doesn't blur the objects blocking the face. I'm sure you saw the gifs.
And 128x128 resolution for generated faces.
Also more realistic eyes.

Basically all the stuff that @shaoanlu did.

**Comment by fakeapp** [comment]
Ah. I thought the above poster was referring to something from this repo, but the GAN and 128x128 repos are on the agenda to implement eventually. Realistic eyes I'm not aware of, what's the repo?

**Comment by Apollo122** [comment]
https://github.com/rcmalli/keras-vggface

Btw all of these (128x128, masking and eyes and other stuff) are present in @shaoanlu 's repo

**Comment by IUsedToBeAPygmy** [comment]
Can someone tell me what the exact changes are for the 128x128 resolution? It's not entirely clear to me.
I'd like to try them locally in this codebase..

**Comment by Ianmcmill** [comment]
@IUsedToBeAPygmy This is offtopic but shaoanlu's is a GAN, isn't it. faceswap is not a GAN, is it?

**Comment by Clorr** [comment]
faceswap original script is an autoencoder, faceswap-GAN is a fork that uses a GAN, but all-in-all it does the same thing

**Comment by christophered** [comment]
@fakeapp any updates regarding your project?

**Comment by gotnull** [comment]
Link no longer available

https://www.reddit.com/r/deepfakes/comments/7oc018/simple_desktop_app_with_gui/?st=jc2nfd9h&sh=16d48ac8
