### ISSUE TITLE
ValueError: No Graphics Card Detected! FAN is not currently supported on CPU. Use another aligner

### ISSUE THREAD

**Issue by gitishard** [deepfakes/faceswap#564]
I'm sorry, but I don't know if the problem I encountered was bug or installation error. I installed all this in docker, and the software is up-to-date, including faceswap code, and cpu only, but when I entered the command "python faceswap.py extract -i ./photo/trump -o ./photo/data/trump" the following error occurred.

12/29/2018 12:53:48 INFO     Loading Detect from Mtcnn plugin...
12/29/2018 12:53:48 INFO     Loading Align from Fan plugin...
12/29/2018 12:53:48 WARNING  No GPU detected. Switching to CPU mode
12/29/2018 12:53:48 INFO     Starting, this may take a while...
12/29/2018 12:53:49 INFO     Initializing Face Alignment Network...
12/29/2018 12:53:49 WARNING  No GPU detected. Switching to CPU mode
12/29/2018 12:53:49 ERROR    Caught exception in child process: 6556
12/29/2018 12:53:49 INFO     Initializing MTCNN Detector...
12/29/2018 12:53:50 WARNING  No GPU detected. Switching to CPU mode
2018-12-29 12:53:50.907418: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
12/29/2018 12:53:52 WARNING  Using CPU
Extracting faces:   0%|                                                           | 0/30 [00:00<?, ?it/s]12/29/2018 12:53:52 INFO     Initialized MTCNN Detector.
12/29/2018 12:53:57 ERROR    Got Exception on main handler:
    raise ValueError("No Graphics Card Detected! FAN is not currently supported on CPU. "
ValueError: No Graphics Card Detected! FAN is not currently supported on CPU. Use another aligner.

I have a nvidia graphics card on my computer and it's mounted on docker, but the program doesn't work.
I want to know what is  " another aligner".

**Comment by torzdf** [comment]
@surahul You have no graphics card, so the error tells you exactly what to do

**Comment by garchingastronomy** [comment]
@surahul I don't know if I did it right. I also use Mac and change the default aligner from "fan" to "dlib" in cli.py line 394. It is running now.

**Comment by gitishard** [comment]
[crash_report.2018.12.31.025948062395.log](https://github.com/deepfakes/faceswap/files/2717691/crash_report.2018.12.31.025948062395.log)

**Comment by torzdf** [comment]
You've got a ton of packages installed there, so there is probably a conflict somewhere which will be next to impossible to troubleshoot.

```py_virtual_env:    False```

Set up a clean virtual environment, run setup.py in your environment and try again.

**Comment by zhangxiaodi** [comment]
./photo/trump -o ./photo/data/trump。 hi  where can i get those data？

**Comment by torzdf** [comment]
There's a link on the main readme page

**Comment by torzdf** [comment]
This issue is closed.

Please do not raise general enquiries here.

Use: https://github.com/deepfakes/faceswap-playground
or: https://discord.gg/FdEwxXd

**Comment by alsotang** [comment]
`python3 faceswap.py extract -A dlib`
