### ISSUE TITLE
Unable to deploy/install

### ISSUE THREAD

**Issue by rohitrameshrao** [deepfakes/faceswap#565]
File "/usr/local/lib/python3.5/dist-packages/pynvml.py", line 1831
    print c_count.value
                ^
SyntaxError: Missing parentheses in call to 'print'

I am running everything on python 3. Any idea what the issue is?

**Comment by torzdf** [comment]
Your pynvml looks wrong (my installed version doesn't have 1831 lines in it). Re-install pynvml or raise an issue with the author.

**Comment by jlllweco** [comment]
It seems you should use py3nvml instead, but the new error is 
`except (py3nvml.NVMLError_LibraryNotFound, py3nvml.NVMLError_DriverNotLoaded):
AttributeError: module 'py3nvml' has no attribute 'NVMLError_LibraryNotFound'
`
I'm trying to figure out.

**Comment by jlllweco** [comment]
> This looks like a problem with your setup. As long as you are in a Python3 environment `pynvml` will import from `nvidia-ml-py3`
> 
> ```
> $ python
> Python 3.5.6 (default, Aug  4 2018, 00:54:51)
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> 
> >>> import pynvml
> 
> >>> raise pynvml.NVMLError_LibraryNotFound
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> pynvml.NVMLError_LibraryNotFound: NVML Shared Library Not Found
> 
> >>> raise pynvml.NVMLError_DriverNotLoaded
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> pynvml.NVMLError_DriverNotLoaded: Driver Not Loaded
> ```

Yes. Thank you so much for your help. py3nvml is wrong.
The former code `import pynvml` is right and it can be installed 
`pip install nvidia-ml-py3`
