### ISSUE TITLE
Convert error

### ISSUE THREAD

**Issue by mak22223** [deepfakes/faceswap#566]
I was trying to convert images using "adjust" converter from GUI. Generated command -"C:\Faceswap\faceswap.py convert -L INFO -i C:/Workfolder/data_pre/ready -o C:/Workfolder/convert/ready3 -l 0.6 -m C:/fakes/model180_2gpu -a C:/Workfolder/data_A/aligned_3 -t GAN -c Adjust -b 2 -M facehullandrect -g 1"

It crashes after hasing images. There are two faces in the images. Masked converter works properly. 

Last faceswap version, PY 3.6.8. TF 1.12 without avx.

`12/30/2018 16:45:08 MainProcess     MainThread      convert         convert                   ERROR    Failed to convert image: 'C:\Workfolder\data_pre\ready\frame001.png'. Reason: could not broadcast input array from shape (160,160,4) into shape (160,160,3)
Traceback (most recent call last):
  File "C:\Faceswap\lib\cli.py", line 90, in execute_script
    process.process()
  File "C:\Faceswap\scripts\convert.py", line 61, in process
    self.convert(converter, item)
  File "C:\Faceswap\scripts\convert.py", line 213, in convert
    image = self.convert_one_face(converter, image, face)
  File "C:\Faceswap\scripts\convert.py", line 229, in convert_one_face
    size)
  File "C:\Faceswap\plugins\convert\Convert_Adjust.py", line 54, in patch_image
    new_face = self.superpose(src_face, new_face, crop)
  File "C:\Faceswap\plugins\convert\Convert_Adjust.py", line 104, in superpose
    new_image[crop, crop] = new_face
ValueError: could not broadcast input array from shape (160,160,4) into shape (160,160,3)`
[crash_report.2018.12.30.164508449869.log](https://github.com/deepfakes/faceswap/files/2717297/crash_report.2018.12.30.164508449869.log)

**Comment by torzdf** [comment]
Ah, yeah. Ok. Pretty sure adjust doesn't work with GAN.

This will be looked at in a future update
