### ISSUE TITLE
OriginalHighResRC4fix    Report errors

### ISSUE THREAD

**Issue by shuai700** [deepfakes/faceswap#570]
1/02/2019 11:01:07 ERROR    Failed to convert image: 'C:\faceswap_rc4\dataA\video-frame-1.png'. Reason: Error when checking input: expected input_5 to have shape (128, 128, 3) but got array with shape (192, 192, 3)
How to synthesize 192 model?

**Comment by andenixa** [comment]
@shuai700  In short you shouldn't. But I shall make another commit to aid in doing so. I realized that converter ain't up to snuff.
