### ISSUE TITLE
I can't touch the trained model and dataset. can I train this model without images

### ISSUE THREAD

**Issue by Mrfangfang** [deepfakes/faceswap#578]
**Note: Please only report bugs in this repository. Just because you are getting an error message does not automatically mean you have discovered a bug. If you don't have a lot of experience with this type of project, or if you need for setup help and other issues in using the faceswap tool, please refer to the [faceswap-playground](https://github.com/deepfakes/faceswap-playground/issues) instead. The faceswap-playground is also an excellent place to ask questions and submit feedback.**

## Expected behavior

*Describe, in some detail, what you are trying to do and what the output is that you expect from the program.*

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Steps to reproduce

*Describe, in some detail, the steps you tried that resulted in the behavior described above.*

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Windows, macOS, Linux 
- **Python version:** 2.7, 3.5, 3.6.4, ...
- **Faceswap version:** commit hash or version number
- **Faceswap method:** CPU/GPU
- **Other related issues:** #123, #124...
- ... (for example, installed packages that you can see with `pip freeze`)

**Comment by Mrfangfang** [comment]
the link of dataset and trained model lose efficiency.can I train this model without images  as train_set.

**Comment by torzdf** [comment]
You need to create images (use Extract). You don't need the pre-trained model.
