### ISSUE TITLE
when i want to convert ,i got the following errors

### ISSUE THREAD

**Issue by horizonheart** [deepfakes/faceswap#579]
ValueError: Error: Alignments file not found at /nfs/private/faceswap/data/trump/alignments.json

how should i generate the alignments.json

**Comment by kvrooman** [comment]
run the extract process to generate an alignments file

**Comment by horizonheart** [comment]
> run the extract process to generate an alignments file
i have run the following command, however don't generate the alignments.json
python faceswap.py extract -i /nfs/private/faceswap-GAN/faceB -o /nfs/private/faceswap/data/trump
python faceswap.py extract -i /nfs/private/faceswap-GAN/faceA -o /nfs/private/faceswap/data/cage

**Comment by bryanlyon** [comment]
Please don't open multiple issues for the same problem.  See my response in your duplicate issue https://github.com/deepfakes/faceswap/issues/580 for information on how to do every step.
