### ISSUE TITLE
The convert step shows error

### ISSUE THREAD

**Issue by stupidtong** [deepfakes/faceswap#58]
It shows that error with no picture output！
```
contrib/shape_predictor_68_face_landmarks.dat file not found.
Landmark file can be found in http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
Unzip it in the contrib/ folder.
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /io/opencv/modules/imgproc/src/resize.cpp, line 4044
Failed to extract from image:~path~/~photoname~.jpg. Reason: /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize
```
I don't know why  and it still shows error with another computer in linux.

**Comment by EdwardAutumn** [comment]
well.it's actually just missing a file in the contrib folder and it already told you where to download it.

**Comment by Clorr** [comment]
Yes, it is a heavy fil so it was not put in the code. You can download it from the url provided.

Note that the repo has just been updated and that the new version downloads everything by itself
