### ISSUE TITLE
python faceswap.py convert ,all the image were No alignment found for 887051092_0.jpg, skipping

### ISSUE THREAD

**Issue by horizonheart** [deepfakes/faceswap#580]
![image](https://user-images.githubusercontent.com/16372054/50811457-515b7780-1349-11e9-8748-4fd79b51b5c9.png)

**Comment by bryanlyon** [comment]
You need alignments to continue.  See https://github.com/deepfakes/faceswap/blob/master/USAGE.md for the process.  You can also come to our Discord server at https://discord.gg/FC54sYg if you have other questions about how to use the software.

**Comment by utmcontent** [comment]
> You need alignments to continue. See https://github.com/deepfakes/faceswap/blob/master/USAGE.md for the process. You can also come to our Discord server at https://discord.gg/FC54sYg if you have other questions about how to use the software.

Only `alignments.fsa` was created,no `alignment.json` file created after extract faces from video or images..and convert with the same errror:.
```
No alignment found for video-frame-1863.png, skipping


No alignment found for video-frame-18630.png, skipping


No alignment found for video-frame-18631.png, skipping


No alignment found for video-frame-18632.png, skipping


No alignment found for video-frame-18633.png, skipping


No alignment found for video-frame-18634.png, skipping
```

How to solve that..?

**Comment by utmcontent** [comment]
> You need alignments to continue. See https://github.com/deepfakes/faceswap/blob/master/USAGE.md for the process. You can also come to our Discord server at https://discord.gg/FC54sYg if you have other questions about how to use the software.

In the docs it says
`An alignments.json file will also be created and saved into your input folder. This file contains information about each of the faces that will be used by FaceSwap`
but only alignments.fsa was created...

**Comment by bryanlyon** [comment]
Do not attempt to revive closed issues.

Please view the forum for up to date documentation and guides to using faceswap.
