### ISSUE TITLE
It's not a technical issue.and some advice.

### ISSUE THREAD

**Issue by phpforlan** [deepfakes/faceswap#581]
hi, i am a faceswap fans from china, many china people want to lean faceswap technology.
so i want to build a china official website. it will help many people. it is amazing.
please contact with me.thanks. 
email: lubootisbadguy@gmail.com

**Comment by torzdf** [comment]
Please post this either in https://github.com/deepfakes/faceswap-playground/issues
or even better, on the Discord:
https://discord.gg/FdEwxXd
