### ISSUE TITLE
ERROR ：Caught exception in child process: 14128

### ISSUE THREAD

**Issue by dream80** [deepfakes/faceswap#582]
GUI  Extract  error

### GUI log

Loading...
01/08/2019 21:48:29 INFO     Log level set to: INFO
01/08/2019 21:48:31 INFO     Output Directory: F:\Python\faceswap-master\output
01/08/2019 21:48:31 INFO     Input Video: F:\Python\faceswap-master\input\1.mp4
01/08/2019 21:48:31 INFO     Loading Detect from Mtcnn plugin...
01/08/2019 21:48:31 INFO     Loading Align from Fan plugin...
01/08/2019 21:48:31 INFO     NB: Parallel processing disabled.You may get faster extraction speeds by enabling it with the -mp switch
01/08/2019 21:48:31 INFO     Starting, this may take a while...
01/08/2019 21:48:32 INFO     Initializing MTCNN Detector...
**01/08/2019 21:48:32 ERROR    Caught exception in child process: 14128**
01/08/2019 21:49:31 INFO     Waiting for Detector... Time out in 4 minutes
01/08/2019 21:50:31 INFO     Waiting for Detector... Time out in 3 minutes
01/08/2019 21:51:31 INFO     Waiting for Detector... Time out in 2 minutes
01/08/2019 21:52:31 INFO     Waiting for Detector... Time out in 1 minutes

### crash_report

01/08/2019 21:48:32 Detector.run    MainThread      mtcnn           initialize                INFO     Initializing MTCNN Detector...
01/08/2019 21:48:32 Detector.run    MainThread      _base           run                       ERROR    Caught exception in child process: 14128
01/08/2019 21:49:31 MainProcess     MainThread      extract         launch_detector           INFO     Waiting for Detector... Time out in 4 minutes
01/08/2019 21:50:31 MainProcess     MainThread      extract         launch_detector           INFO     Waiting for Detector... Time out in 3 minutes
01/08/2019 21:51:31 MainProcess     MainThread      extract         launch_detector           INFO     Waiting for Detector... Time out in 2 minutes
01/08/2019 21:52:31 MainProcess     MainThread      extract         launch_detector           INFO     Waiting for Detector... Time out in 1 minutes
Traceback (most recent call last):
  File "F:\Python\faceswap-master\lib\cli.py", line 90, in execute_script
    process.process()
  File "F:\Python\faceswap-master\scripts\extract.py", line 49, in process
    self.run_extraction()
  File "F:\Python\faceswap-master\scripts\extract.py", line 143, in run_extraction
    self.run_detection(to_process)
  File "F:\Python\faceswap-master\scripts\extract.py", line 194, in run_detection
    self.plugins.launch_detector()
  File "F:\Python\faceswap-master\scripts\extract.py", line 379, in launch_detector
    raise ValueError("Error initializing Detector")
ValueError: Error initializing Detector

============ System Information ============
git_branch:        Not Found
git_commits:       Not Found
gpu_cuda:          9.0
gpu_cudnn:         7.4.2
gpu_devices:       GPU_0: GeForce GTX 750
gpu_driver:        417.22
gpu_vram:          GPU_0: 1024MB
os_machine:        AMD64
os_platform:       Windows-10-10.0.17134-SP0
os_release:        10
py_command:        F:\Python\faceswap-master\faceswap.py extract -i F:/Python/faceswap-master/input/1.mp4 -o F:/Python/faceswap-master/output -l 0.6 --serializer json -D mtcnn -A fan -mtms 20 -mtth 0.6 0.7 0.7 -mtsc 0.709 -sz 256 -L INFO
py_conda_version:  N/A
py_implementation: CPython
py_version:        3.6.6
py_virtual_env:    False
sys_cores:         4
sys_processor:     Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
sys_ram:           Total: 8129MB, Available: 3269MB, Used: 4860MB, Free: 3269MB

-------------------------------

**Comment by torzdf** [comment]
Don't raise issues in multiple repos.

**Comment by jlllweco** [comment]
I have the same error. May I ask how to fix it?

**Comment by dream80** [comment]
see：https://github.com/deepfakes/faceswap-playground/issues/232#issuecomment-452345536 。
Maybe it's the same problem,   maybe it's the same problem, but for different reasons.
