### ISSUE TITLE
network_type in convert_multi_gpu

### ISSUE THREAD

**Issue by rgeorgi** [deepfakes/faceswap#583]
Very small bug in the #572 refactor - the debug statement in L106 in convert_multi_gpu() refers to a model property that no longer exists.

https://github.com/deepfakes/faceswap/blob/6acd3a0d9b7afc5eb2e4fb8ab50100df6f93c72d/plugins/train/model/_base.py#L106

**Comment by torzdf** [comment]
Thanks for the bug report. Squashed.
