### ISSUE TITLE
Setup.py looks for CUDNN in incredibly strange place

### ISSUE THREAD

**Issue by rail5** [deepfakes/faceswap#591]
Line 349 of setup.py:
 CUDA_PATH = chk[chk.find("=>") + 3:chk.find("targets") - 1]

sets CUDA_PATH as the found .so library - 1 character

and then proceeds in line 372:
 cudnn_checkfile = os.path.join(CUDA_PATH, "include", "cudnn.h")

to try to append /include/cudnn.h in the search for cudnn.

So, when my cuda installation is found at:
/usr/lib/x86_64-linux-gnu/libcudart.so.9.1
It searches in
/usr/lib/x86_64-linux-gnu/libcudart.so.9./include/
for cudnn.h

This directory would never exist

**Comment by sdlpkxd** [comment]
Hi @rail5
I encounter with the same problems with, have you solved it ?
Thanks.

**Comment by rail5** [comment]
> Hi @rail5
> I encounter with the same problems, have you solved it ?
> Thanks.

Unfortunately I haven't. I tried to edit setup.py to force it to look in a place that made sense, but that ended up with a bunch of other errors, and there's too much code for me to really dig through and find out where all the errors are. I imagine the devs just all use Windows, so they're not too concerned

**Comment by sdlpkxd** [comment]
Thanks for your reply.
When I print the CUDA_PATH, it shows bcudart.so.9, not a path at all. 
Maybe the script need to be rewrite, sounds terrible.

**Comment by bryanlyon** [comment]
For linux, we recommend following the install guide at https://github.com/deepfakes/faceswap/blob/master/INSTALL.md .  You can skip the Microsoft Visual C and use GCC instead.  It's actually much easier to install on Linux than Windows so there is no need for the script.

**Comment by sdlpkxd** [comment]
Dose it support anaconda installing? we flow the install guide but get the unsuspected error.
To fix this error, I change the line 372 in the setup.py script in function check_cudnn() from 
cudnn_checkfile = os.path.join(CUDA_PATH, "include", "cudnn.h") to 
cudnn_checkfile = os.path.join("/usr/local/cuda", "include", "cudnn.h"), 
and it can successfully setup the project.
Hope that can be useful.

**Comment by cnglen** [comment]
`
self.env.cuda_path = '/'.join(chk[chk.find("=>") + 3:- 1].split('/')[:-2])  # for debian
# self.env.cuda_path = chk[chk.find("=>") + 3:chk.find("targets") - 1]
`

**Comment by camperr** [comment]
My solution is to set self.env.cuda_path after line 391 instead of 406.
the total cuda_check_linux function is like below:
    def cuda_check_linux(self):
        """ Check Linux CUDA Version """
        chk = os.popen("ldconfig -p | grep -P \"libcudart.so.\\d+.\\d+\" | head -n 1").read()
        if self.env.ld_library_path and not chk:
            paths = self.env.ld_library_path.split(":")
            for path in paths:
                chk = os.popen("ls {} | grep -P -o \"libcudart.so.\\d+.\\d+\" | "
                               "head -n 1".format(path)).read()
                self.env.cuda_path = path+"/../" # set cuda_path to parent folder of directory that contains libcudart.so
                if chk:
                    break
        if not chk:
            self.output.error("CUDA not found. Install and try again.\n"
                              "Recommended version:      CUDA 9.0     cuDNN 7.1.3\n"
                              "CUDA: https://developer.nvidia.com/cuda-downloads\n"
                              "cuDNN: https://developer.nvidia.com/rdp/cudnn-download")
            return
        cudavers = chk.strip().replace("libcudart.so.", "")
        #self.env.cuda_version = cudavers[:cudavers.find(" ")]
        self.env.cuda_version = cudavers
        if self.env.cuda_version:
            self.output.info("CUDA version: " + self.env.cuda_version)
            #self.env.cuda_path = chk[chk.find("=>") + 3:chk.find("targets") - 1]

**Comment by ZhenjunCao** [comment]
Cudnn 7 uses different path instead of staying with the same path of cuda. I fixed setup.py/cudnn_check function like:
        chk = os.popen("ldconfig -p | grep -P \"libcudnn.so.\\d+\" | head -n 1").read()
        chk = chk.strip().replace("libcudnn.so.", "")
        cudnn_path = chk[chk.find("=>") + 3:chk.find("libcudnn") - 1]
        cudnn_path = cudnn_path.replace("lib", "include")
        cudnn_checkfile = os.path.join(cudnn_path, "cudnn_v7.h")

**Comment by YuTingLiu** [comment]
self.env.cuda_path = chk[chk.find("=>") + 3:chk.find("targets") - 1]
to
            self.env.cuda_path = "/usr/local/cuda"
fix the problem

**Comment by Lyle-Tafoya** [comment]
> chk = os.popen("ldconfig -p | grep -P "libcudnn.so.\d+" | head -n 1").read()

The nested double quotes aren't valid, so I had to change the outer quotes to single

**Comment by torzdf** [comment]
Should be fixed in latest commit
