### ISSUE TITLE
XQuartz has installed in my mac,but it still have an error:macOS users need to install XQuartz. See https://support.apple.com/en-gb/HT201341

### ISSUE THREAD

**Issue by codewine** [deepfakes/faceswap#593]
python3 faceswap.py gui
 Log level set to: INFO
WARNING  No display detected. GUI mode has been disabled.
INFO     macOS users need to install XQuartz. See https://support.apple.com/en-gb/HT201341

**Comment by codewine** [comment]
how to make my application XQuartz work

**Comment by torzdf** [comment]
A macOS user will need to get back to you. I do not currently have access to a macOS machine.

It should "just work"

**Comment by vladzima** [comment]
You should reboot your machine for XQuartz to work after install.

**Comment by SoalHuang** [comment]
> You should reboot your machine for XQuartz to work after install.

yes, thank you.
