### ISSUE TITLE
Adjust convert does not work for GAN and GAN128 model

### ISSUE THREAD

**Issue by temp-42** [deepfakes/faceswap#595]
Adjust Convert plugin fails in case of GAN or GAN128 model

## Expected behavior

Adjust convert completes w/o errors

## Actual behavior

GAN and GAN128 fails with errors (please see pic attached)

## Steps to reproduce
1) Extract faces from images and train GAN or GAN128 model
2) Perform python faceswap convert with Adjust plugin

## Other relevant information
- **Command lined used (GAN128)**: faceswap.py convert  -i "path/to/images" -o "output/path" -m "path/to/GAN128/model" -t GAN128 -c Adjust
- **Operating system and version:** Ubuntu 16.04.5 LTS
- **Python version:** 3.5,2,
- **Faceswap version:** 4376bbf4f85f9771b0e3752ccf9504efb4e43d21
- **Faceswap method:** GPU
![gan128_adjust](https://user-images.githubusercontent.com/15347623/51643846-10857480-1f7f-11e9-8613-d722a1f925eb.png)

**Comment by torzdf** [comment]
GAN is being removed with a view to add GAN2.2 in the future. Use masked converter.
