### ISSUE TITLE
ERROR   Please run this script with Python version 3.3, 3.4, 3.5 or 3.6 64bit and try again.

### ISSUE THREAD

**Issue by GideonWeng** [deepfakes/faceswap#596]
1. I updated the latest python(3.7.2) using homebrew. When using command `python3 setup.py`, it showed as following:  
```
INFO    The tool provides tips for installation and installs required python packages   
INFO    Setup in Darwin 17.7.0    
INFO    Installed Python: 3.7.2 64bit 
ERROR   Please run this script with Python version 3.3, 3.4, 3.5 or 3.6 64bit and try again    
```
Does it mean this repo still do not support `python3.7.2`? Cause it's kind of annoying to install different versions of python for a fresher, what else can I do?

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: python3 setup.py 
- **Operating system and version:** macOS
- **Python version:** 3.7.2
- **Faceswap version:** fd5c004967e46d3ca2df36f5a8cc7d10beeeacd9

**Comment by torzdf** [comment]
Run a virtual environment for python 3.6. Anaconda can do this. I don't know if homebrew can.

This is a Tensorflow limitation, not Faceswap.

**Comment by palmerabollo** [comment]
@torzdf Tensorflow 1.13.1 already supports Python 3.7 (https://github.com/tensorflow/tensorflow/releases/tag/v1.13.1) on all operating systems. Is it possible to remove the restriction in faceswap now. Thank you.

**Comment by bryanlyon** [comment]
We do not yet support tensorflow 1.13.  It's too new and only released last week along with the announcement that tensorflow 2.0 is coming soon.  We are evaluating the options but for now we have a known working solution.

Please install a supported version through anaconda since this is a good working solution.
