### ISSUE TITLE
ImportError: cannot import name run

### ISSUE THREAD

**Issue by ithirzty** [deepfakes/faceswap#603]
When running `python setup.py`, I get this error message : 
`Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    from subprocess import run, PIPE, Popen
ImportError: cannot import name run
`.
I'm running ubuntu with python 2.7.12.

**Additional context**
That may not be related but I don't have any graphic card installed, just two powerful CPUs.

**Comment by torzdf** [comment]
https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#installing-dependencies

**Comment by ithirzty** [comment]
> https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#installing-dependencies

I already installed all dependencies
