### ISSUE TITLE
ImportError: cannot import name QueueHandler

### ISSUE THREAD

**Issue by ithirzty** [deepfakes/faceswap#604]
When I run `python faceswap.py gui` for exemple, I get :
```
Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "/root/faceswap/lib/cli.py", line 11, in <module>
    from lib.logger import crash_log, log_setup
  File "/root/faceswap/lib/logger.py", line 5, in <module>
    from logging.handlers import QueueHandler, QueueListener, RotatingFileHandler
ImportError: cannot import name QueueHandler

```
 - OS: ubuntu
 - all dependencies installed and system up to date

**Comment by torzdf** [comment]
Crash report.

Ultimately if this isn't importing, you haven't set up correctly.

**Comment by torzdf** [comment]
Also, the issues area is not the place for looking for technical support. You're best off going to the discord.

https://discord.gg/FdEwxXd
