### ISSUE TITLE
Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/run_jupyter.sh\": stat /run_jupyter.sh: no such file or directory": unknown

### ISSUE THREAD

**Issue by smalike** [deepfakes/faceswap#614]
Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/run_jupyter.sh\": stat /run_jupyter.sh: no such file or directory": unknown
Error: failed to start containers: 072c53fbff85

**Related to the following tips?**
Successfully built f8bcd7471fd6
Successfully tagged deepfakes-cpu:latest
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.

window10
docker
Version 2.0.0.3 (31259)
Channel: stable
Build: 8858db3

**Comment by torzdf** [comment]
Whilst docker is technically supported, none of the primary Devs actually use it, so you're likely to get better support either in https://github.com/deepfakes/faceswap-playground or on the Discord server: https://discord.gg/FdEwxXd

I'd recommend following the Windows Install guide on the INSTALL.md page for better support.
