### ISSUE TITLE
Docker image is asking for run_jupyter.sh which does not exist

### ISSUE THREAD

**Issue by FrontMage** [deepfakes/faceswap#615]
**Describe the bug**
The docker gpu image build file is running `/run_jupyter.sh` at the end, but there is no such file in the repo or in the `tensorflow/tensorflow:latest-gpu-py3` image.

**To Reproduce**
1. `docker build -t deepfakes-gpu -f Dockerfile.gpu .`
2. `nvidia-docker run --rm -it -p 8888:8888 \
            --hostname faceswap-gpu --name faceswap-gpu \
            -v /opt/faceswap:/srv \
            deepfakes-gpu`
3. then should see the error
**Expected behavior**
`run_jupyter.sh` exists

**Screenshots**
None
**Desktop (please complete the following information):**
 - manjaro 4.14
 - chromium
 - 61

**Comment by torzdf** [comment]
https://github.com/deepfakes/faceswap-playground/issues/245

**Comment by Pantich78** [comment]
I have the same issue, I ended up installing it without Docker but it would be great to find a solution

**Comment by kartikey20** [comment]
You can change from CMD ['./run_jupyter.sh'] to CMD ['/bin/bash'] like @bigredbug47 said and after creating the image from the new Dockerfile, run it using:

docker run -it --name jupyter-container --net=host -v ~/docker_files/:/ds tutorial

when the container comes to life, just run inside it:

jupyter notebook --no-browser --allow-root --port=7745 --NotebookApp.token='tutorial'

Finally, go to the http://localhost:7745/ and see the magic :D

I hope this is useful for you

**Comment by FrontMage** [comment]
@kartikey20 I think it will have to use `--ip=0.0.0.0` for jupyter notebook as well.

**Comment by torzdf** [comment]
Should be fixed in #625
