### ISSUE TITLE
always get no such file when i try to use ffmpeg (exited with status 1)

### ISSUE THREAD

**Issue by Sn0wl3r0ker** [deepfakes/faceswap#617]
here's the crash log:
[crash_report.2019.02.23.040722851447.log](https://github.com/deepfakes/faceswap/files/2896778/crash_report.2019.02.23.040722851447.log)

**Comment by Sn0wl3r0ker** [comment]
02/23/2019 04:07:22 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
02/23/2019 04:07:22 MainProcess     MainThread      cli             execute_script            DEBUG    Executing: effmpeg. PID: 3020
02/23/2019 04:07:22 MainProcess     MainThread      effmpeg         process                   DEBUG    Running Effmpeg
02/23/2019 04:07:22 MainProcess     MainThread      effmpeg         __run_ffmpeg              DEBUG    Running ffmpeg: (exe: 'ffmpeg', inputs: {'C:\\faceswap_data\\final\\.%1_000001d.png': '-hide_banner ', 'C:\\faceswap_data\\1.mp4': None}, outputs: {'C:\\faceswap_data\\final.mpeg': '-c copy -map 0:0 -map 1:1 -y -vf fps="24" -c:v libx264'}
Traceback (most recent call last):
  File "C:\faceswap\tools\effmpeg.py", line 468, in __run_ffmpeg
    ff.run(stderr=subprocess.STDOUT)
  File "C:\Anaconda3\envs\py35\lib\site-packages\ffmpy.py", line 105, in run
    raise FFRuntimeError(self.cmd, self.process.returncode, out[0], out[1])
ffmpy.FFRuntimeError: `ffmpeg -hide_banner -i C:\faceswap_data\final\.%1_000001d.png -i C:\faceswap_data\1.mp4 -c copy -map 0:0 -map 1:1 -y -vf fps=24 -c:v libx264 C:\faceswap_data\final.mpeg` exited with status 1

STDOUT:


STDERR:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\faceswap\lib\cli.py", line 90, in execute_script
    process.process()
  File "C:\faceswap\tools\effmpeg.py", line 271, in process
    self.effmpeg_process()
  File "C:\faceswap\tools\effmpeg.py", line 290, in effmpeg_process
    action(**kwargs)
  File "C:\faceswap\tools\effmpeg.py", line 328, in gen_vid
    Effmpeg.__run_ffmpeg(exe=exe, inputs=_inputs, outputs=_outputs)
  File "C:\faceswap\tools\effmpeg.py", line 475, in __run_ffmpeg
    "{}".format(ffe))
ValueError: An unexpected FFRuntimeError occurred: `ffmpeg -hide_banner -i C:\faceswap_data\final\.%1_000001d.png -i C:\faceswap_data\1.mp4 -c copy -map 0:0 -map 1:1 -y -vf fps=24 -c:v libx264 C:\faceswap_data\final.mpeg` exited with status 1

STDOUT:


STDERR:


============ System Information ============
git_branch:        master
git_commits:       5ef7f8f Show samples... wrong input. a6c5f22 Creating Input Size config for models. b578e43 Update README.md. 6641c32 Change logfile dialog to SaveAs. c38cca0 bugfix: Alignments tool, missing-frames validation
gpu_cuda:          10.0
gpu_cudnn:         7.4.2
gpu_devices:       GPU_0: GeForce GTX 1070
gpu_driver:        419.17
gpu_vram:          GPU_0: 8192MB
os_machine:        AMD64
os_platform:       Windows-10-10.0.17763-SP0
os_release:        10
py_command:        tools.py effmpeg -a gen-vid -i C:\faceswap_data\final\ -o C:\faceswap_data\final.mpeg -fps 24 -m -r C:\faceswap_data\1.mp4
py_conda_version:  conda 4.6.4
py_implementation: CPython
py_version:        3.6.8
py_virtual_env:    False
sys_cores:         8
sys_processor:     Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
sys_ram:           Total: 16266MB, Available: 8533MB, Used: 7733MB, Free: 8533MB

=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
certifi==2018.11.29
Click==7.0
cloudpickle==0.8.0
cmake==3.13.3
cycler==0.10.0
dask==1.1.1
datashape==0.5.4
decorator==4.3.2
dlib==19.16.0
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpeg-python==0.1.17
ffmpy==0.2.2
future==0.17.1
gast==0.2.2
grpcio==1.18.0
h5py==2.8.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
mkl-fft==1.0.10
mkl-random==1.0.2
multipledispatch==0.6.0
networkx==2.2
numpy==1.15.4
nvidia-ml-py3==7.352.0
olefile==0.46
opencv-python==4.0.0.21
pathlib==1.0.1
Pillow==5.4.1
protobuf==3.6.1
psutil==5.5.0
pyparsing==2.3.1
pyreadline==2.1
pyshp==2.0.1
python-dateutil==2.7.5
pytz==2018.9
PyWavelets==1.0.1
PyYAML==3.13
scandir==1.7
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
tensorboard==1.12.2
tensorflow==1.12.0
tensorflow-gpu==1.12.0
termcolor==1.1.0
toolz==0.9.0
tornado==5.1.1
tqdm==4.31.1
Werkzeug==0.14.1
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Anaconda3\envs\py35:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.0                    pypi_0    pypi
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
click                     7.0                      pypi_0    pypi
cmake                     3.12.2               he025d50_0  
cmake-binary              3.9.1                h8f04fe6_1  
cudatoolkit               9.0                           1  
cudnn                     7.3.1                 cuda9.0_0  
cycler                    0.10.0           py36h009560c_0  
datashape                 0.5.4                    py36_1  
dlib                      19.16.0                  pypi_0    pypi
face-recognition          1.2.3                    pypi_0    pypi
face-recognition-models   0.3.0                    pypi_0    pypi
ffmpeg                    2.7.0                         0    menpo
ffmpeg-python             0.1.17                   pypi_0    pypi
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
future                    0.17.1                   pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
grpcio                    1.18.0                   pypi_0    pypi
h5py                      2.8.0            py36hf7173ca_2  
hdf5                      1.8.20               hac2f561_1  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
intel-openmp              2019.1                      144  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.6                    py36_0  
keras-base                2.2.4                    py36_0  
keras-gpu                 2.2.4                         0  
keras-preprocessing       1.0.5                    py36_0  
kiwisolver                1.0.1            py36h6538335_0  
libopencv                 3.4.2                h20b85fd_0  
libpng                    1.6.36               h2a8f88b_0  
libprotobuf               3.6.1                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.0.1                    py36_0  
matplotlib                3.0.2            py36hc8f65d3_0  
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h14836fe_0  
mkl_random                1.0.2            py36h343c172_0  
multipledispatch          0.6.0                    py36_0  
numpy                     1.15.4           py36h19fb1c0_0  
numpy-base                1.15.4           py36hc3f5095_0  
nvidia-ml-py3             7.352.0                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv                    3.4.2            py36h40b0b35_0  
openssl                   1.1.1a               he774522_0  
pillow                    5.4.1                    pypi_0    pypi
pip                       19.0.1                   py36_0  
protobuf                  3.6.1                    pypi_0    pypi
psutil                    5.5.0            py36he774522_0  
py-opencv                 3.4.2            py36hc319ecb_0  
pyparsing                 2.3.1                    py36_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
pyshp                     2.0.1                    py36_0  
python                    3.6.8                h9f7ef89_1  
python-dateutil           2.7.5                    py36_0  
pytz                      2018.9                   py36_0  
pyyaml                    3.13             py36hfa6e2cd_0  
qt                        5.9.7            vc14h73c81de_0  
scipy                     1.2.1            py36h29ff71c_0  
setuptools                40.8.0                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.26.0               he774522_0  
tensorboard               1.12.2           py36h33f27b4_0  
tensorflow                1.12.0          gpu_py36ha5f9131_0  
tensorflow-base           1.12.0          gpu_py36h6e53903_0  
tensorflow-gpu            1.12.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
tk                        8.6.8                hfa6e2cd_0  
tornado                   5.1.1            py36hfa6e2cd_0  
tqdm                      4.31.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_0  
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.32.3                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0

**Comment by torzdf** [comment]
This should be fixed in latest commit
