### ISSUE TITLE
Compatible Cuda and cuDNN installed, but no compatible tensorflow wheel available

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#620]
getting the following problem when running setup.py on linux, can't seem to find the issue. Any help would be appreciated.

WARNING Running without root/admin privileges
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Linux 4.20.11-1-MANJARO
INFO    Installed Python: 3.6.0 64bit
INFO    Encoding: UTF-8
INFO    Upgrading pip...
INFO    Installed pip: 19.0.3
Enable  Docker? [y/N] n
INFO    Docker Disabled
Enable  CUDA? [Y/n] y
INFO    CUDA Enabled
INFO    CUDA version: 9.0
INFO    cuDNN version: 7.0.4
WARNING Tensorflow currently has no official prebuild for your CUDA, cuDNN combination.
        Either install a combination that Tensorflow supports or build and install your own tensorflow-gpu.
        CUDA Version: 9.0
        cuDNN Version: 7.0
        Help:
        Building Tensorflow: https://www.tensorflow.org/install/install_sources
        Tensorflow supported versions: https://www.tensorflow.org/install/source#tested_build_configurations
Location of custom tensorflow-gpu wheel (leave blank to manually install):

**Comment by torzdf** [comment]
Download cuDNN 7.4 for CUDA 9.0

**Comment by fetchlister** [comment]
cudnn 7.4 requires cuda 10.0

**Comment by torzdf** [comment]
No it doesn't. Look at archive releases.
