### ISSUE TITLE
Upgraded to newest verson, NO LOWMEM support!

### ISSUE THREAD

**Issue by fetchlister** [deepfakes/faceswap#622]
I recently upgraded my packages which included keras, so theres no going back to the revios version I had... All my models are in lowmem, how can I get this up and running again or am I fucked?

**Comment by torzdf** [comment]
Please stop posting general questions in issues.

Use the Discord: https://discord.gg/FdEwxXd
or Faceswap playground: https://github.com/deepfakes/faceswap-playground
