### ISSUE TITLE
crashed at the beginning of train

### ISSUE THREAD

**Issue by cp0000** [deepfakes/faceswap#626]
```
  File "/opt/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value Adam/l
```

crashed on 

```
 File "/faceswap/plugins/train/trainer/_base.py", line 213, in train_one_batch
    loss = self.model.predictors[self.side].train_on_batch(*batch)
```

my environment is
 tensorflow-gpu== 1.9.0 cuda==9.0 cudnn==7.0.5 ubutun 16.04

Does anyone have any idea? Thanks

**Comment by torzdf** [comment]
Update Tensorflow to 1.12.

**Comment by changyunke** [comment]
I also have this problem, did you fix it?

**Comment by cp0000** [comment]
Update Tensorflow to 1.12.

changyunke <notifications@github.com> 于2019年2月28日周四 上午8:54写道：

**Comment by changyunke** [comment]
for my environment, when cuda9.0, cudnn 7.3 and tensorflow-gpu==1.12 are installed, there will be other issue:  for
python faceswap.py train -A ~/faceswap/data/trump -B ~/faceswap/data/cage -m ~/faceswap/models/
Traceback (most recent call last):
File "faceswap.py", line 5, in
import lib.cli as cli
File "/home/csy/faceswap/lib/cli.py", line 12, in
from lib.utils import safe_shutdown
File "/home/csy/faceswap/lib/utils.py", line 15, in
import dlib
ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory
Have you ever encountered such a problem?

**Comment by bryanlyon** [comment]
import dlib. 

This means this problem is coming from dlib

ImportError: libcublas.so.8.0: cannot open shared object file: No such file or directory

This is saying it's looking for cuda 8.  You've either force installed the wrong dlib binary or haven't rebuilt your dlib after you installed cuda 9.  Either way, you need to remove the dlib you have installed then follow the install guide to install the correct version.

**Comment by changyunke** [comment]
i solve this issue. thank you
Dlib needs to be compiled and installed, pip install dlib would not work
