### ISSUE TITLE
Match Histogram working (in Villain model with DFL mask)?

### ISSUE THREAD

**Issue by Enyakk** [deepfakes/faceswap#627]
I've just trained a model with the following parameters:
- Villain
- Coverage 87%
- Mask: DFL_FULL

Now when doing a convert it doesn't appear like the match histogram function is achieving its goal. The swapped-in face is colored like the source material and does not match the target. This is true both for A->B and B->A swaps.

**Comment by torzdf** [comment]
By the author's own admission, Villain is not so great at learning colours, so the source/dest image selection is more important, 

You can maybe get more advice from the Discord server:
https://discord.gg/FdEwxXd
