### ISSUE TITLE
Increase training_data generation speed

### ISSUE THREAD

**Issue by kilroythethird** [deepfakes/faceswap#628]
For some settings the training_data generation takes a long time especially "warp to landmarks" is pretty slow.
IMO using multiprocessing would speed stuff a lot.
But there is also some stuff that could be cached, like `get_closest_match` (used in warp to landmarks).

I did some quick and dirty profiling.
See https://github.com/kilroythethird/faceswap/tree/perf_test

<details>
  <summary>Profiling with current staging</summary>
  <p>

```
# python faceswap.py train -A faces/a -B faces/b -m model -t original -s 400 -bs 32 -it 201 -g 1 -ps 250 -wl -L INFO
Thread: load_batches_0
   ALL          PER CALL     COUNT   
 1201.998871     0.187578     6408  process_face(side=a)
  691.611971     0.107929     6408    random_warp_landmarks
  367.470097     0.057337     6409    get_closest_match
   55.490737     0.008658     6409    mask_function
   32.234393     0.005030     6409    random_transform
   23.848031     0.003721     6409    cv2.imread
    7.767768     0.001212     6409    get_landmarks
    7.564588     0.001180     6409      sha1(image)
    0.588165     0.000092     6409    do_random_flip
Thread: load_batches_0
   ALL          PER CALL     COUNT   
 1161.078251     0.175178     6628  process_face(side=b)
  730.652074     0.110237     6628    random_warp_landmarks
  282.749230     0.042660     6628    get_closest_match
   58.361239     0.008804     6629    mask_function
   33.519484     0.005056     6629    random_transform
   22.260553     0.003358     6629    cv2.imread
    7.995775     0.001206     6629    get_landmarks
    7.795409     0.001176     6629      sha1(image)
    0.688545     0.000104     6629    do_random_flip
Thread: training_0
   ALL          PER CALL     COUNT   
 1018.465688     5.092328      200  Batcher(a)->train_one_batch
  843.560930     4.217805      200    Batcher.get_next
  174.890468     0.874452      200    train_on_batch
  191.730749     0.958654      200  Batcher(b)->train_one_batch
  106.012409     0.530062      200    train_on_batch
   85.689574     0.428448      200    Batcher.get_next
```
</p></details>
  
### Multiprocessing
I wrote a "FixedProducerDispatcher" class which runs a work function in x sub processes and uses fixed shared memory to save the data. Each run creates a whole batch.
The only downside to this i see is that we now need to know how big and in which shape the batch is before starting the subprocesses.

See https://github.com/kilroythethird/faceswap/tree/mp_training_data
and https://github.com/kilroythethird/faceswap/tree/perf_test_mp (with  profiling output)

This definitely helps performance wise
<details>
  <summary>Profiling with multiprocessing</summary>
  <p>

```
# python faceswap.py train -A faces/a -B faces/b -m model -t original -s 400 -bs 32 -it 201 -g 1 -ps 250 -wl -L INFO
Thread: load_batches_0
   ALL          PER CALL     COUNT   
  184.241626     0.028362     6496  process_face(side=a)
  132.813554     0.020445     6496    random_warp_landmarks
   11.279126     0.001736     6496    get_closest_match
   10.877508     0.001674     6496    random_transform
    9.162846     0.001411     6496    mask_function
    7.910127     0.001218     6496    cv2.imread
    3.066403     0.000472     6496    get_landmarks
    2.870745     0.000442     6496      sha1(image)
    0.097161     0.000015     6496    do_random_flip
Thread: load_batches_0
   ALL          PER CALL     COUNT   
  181.656559     0.027964     6496  process_face(side=b)
  134.033812     0.020633     6496    random_warp_landmarks
   11.135122     0.001714     6496    random_transform
    8.973757     0.001381     6496    mask_function
    7.647873     0.001177     6496    get_closest_match
    7.452525     0.001147     6496    cv2.imread
    3.014454     0.000464     6496    get_landmarks
    2.841576     0.000437     6496      sha1(image)
    0.159162     0.000025     6496    do_random_flip
Thread: training_0
   ALL          PER CALL     COUNT   
  171.892934     0.859465      200  Batcher(a)->train_one_batch
  162.831906     0.814160      200    train_on_batch
    9.050015     0.045250      200    Batcher.get_next
  111.126615     0.555633      200  Batcher(b)->train_one_batch
  102.814357     0.514072      200    train_on_batch
    8.296469     0.041482      200    Batcher.get_next
```
</p></details>
  
### Caching
Also some function cached here:
https://github.com/kilroythethird/faceswap/tree/perf_test_caching
and https://github.com/kilroythethird/faceswap/tree/perf_test_all (with multiprocessing and caching)
I am not 100% sure caching + multiprocessing works properly on windows systems (spawn vs fork), if someone could test that that would be awesome.

Function cached:
- `sha1(img).hexdigest()` ie. the hash creation function.
Cached by filename and side.
This doesn't bring that much (in absolute terms), but it also doesn't really harm.
- The major (non random) part of `get_closest_match` ie "warp to landmark".
This caches only the indices of the 10 closest images from the other set for each face (so maximum some kb).
This brings performance up for "warp to landmark" by a good chunk and should def be done in some way or another i think.
- `mask_function` Currently i cache the mask only (256,256,1) but for every image.
So this sums up. Assuming 1000 faces in each set that means 250MB for each side (`(256*256*4*1000)/1024./1024.`).
I am not really sure if this is worth it to be honest.

<details>
  <summary>Profiling with caching and without multiprocessing</summary>
  <p>

```
Thread: load_batches_0
  ALL          PER CALL     COUNT   
  889.992215     0.136607     6515  process_face(side=a)
  764.990586     0.117420     6515    random_warp_landmarks
   32.839521     0.005041     6515    random_transform
   23.343189     0.003583     6515    get_closest_match
   22.460514     0.003447     6516    cv2.imread
   20.894716     0.003207     6516    mask_function
    0.799270     0.000123     6516    get_landmarks
    0.641308     0.000098     6516      sha1(image)
    0.585590     0.000090     6515    do_random_flip
Thread: load_batches_0
   ALL          PER CALL     COUNT   
  878.511239     0.137182     6404  process_face(side=b)
  744.183952     0.116206     6404    random_warp_landmarks
   33.463518     0.005225     6405    get_closest_match
   31.718939     0.004952     6405    random_transform
   22.498738     0.003513     6405    cv2.imread
   21.485141     0.003354     6405    mask_function
    1.094532     0.000171     6405    get_landmarks
    0.942542     0.000147     6405      sha1(image)
    0.604323     0.000094     6405    do_random_flip
Thread: training_0
   ALL          PER CALL     COUNT   
  727.685975     3.638430      200  Batcher(b)->train_one_batch
  625.898893     3.129494      200    Batcher.get_next
  101.772938     0.508865      200    train_on_batch
  195.816539     0.979083      200  Batcher(a)->train_one_batch
  169.204756     0.846024      200    train_on_batch
   26.595766     0.132979      200    Batcher.get_next
```
</p></details>

  
  
Let me know what you think. I could prepare patches for bot, or just subsets.
For me multiprocessing in some form and warp to landmark speed up are the important things.

**Comment by kilroythethird** [comment]
I cleaned the multiprocessing part up a bit and rebased it on staging.
https://github.com/kilroythethird/faceswap/tree/mp_training_data
I found a windows tester an at least on win10 it seem to run fine (it also does when setting multiprocessing.set_start_method("spawn")).
Code review/critic would be awesome.

IMO the training_data generator definitely needs multiprocessing. In some cases i wait over half a second on batches sometimes even more.
And mp.Queues for sending the batches is simply not useable.
See:

```
sh-5.0$ python -m timeit -n 10 -r 5 -s 'import numpy as np; import pickle; d=np.zeros(64*(256*256*3+128*128*3+128*128*3+128*128), dtype='float')' -c 'pickle.loads(pickle.dumps(d))'
10 loops, best of 5: 391 msec per loop
```
This is assuming a 128x128 model with a mask and batchsize 64. And that is just one side.

**Comment by tt0576** [comment]
Thanks, my problem has been solved after using this version!
Https://github.com/deepfakes/faceswap/issues/639

**Comment by torzdf** [comment]
I've had a quick look at this PR. It definitely speeds things up, so that's good. It does break the timelapse function though, so that will need to be looked at.

I may raise a PR against your repo for this, to try and standardise the code a bit more over what exists, and then hopefully we can pull this over and get it merged.

**Comment by torzdf** [comment]
Item 1 of this is now in staging.

**Comment by kilroythethird** [comment]
Closing as multiprocessing is in and the relevant caching is in PR #690
