### ISSUE TITLE
What does Iterations mean?

### ISSUE THREAD

**Issue by Maxinger15** [deepfakes/faceswap#631]
I think Iterations are Number of Data divided by Batch Size and that can be calculated. So what should i write in it? It should be replaces with epochs or am I wrong?
Input A has 3.798 pictures.
Input B has 14.305 pictures.
My Batch Size is 32 on OriginalHighRes Model.

**Comment by torzdf** [comment]
Please don't raise general questions here. Use either:
https://github.com/deepfakes/faceswap-playground
or Discord:
https://discord.gg/FdEwxXd
