### ISSUE TITLE
Manual extract alignments windows closing right away

### ISSUE THREAD

**Issue by berniejerom** [deepfakes/faceswap#632]
**Describe the bug**
python .\tools.py alignments -j manual -a alignmentPath -fr framesPath

**To Reproduce**
on windows 10:
run python .\tools.py alignments -j manual -a alignmentPath -fr framesPath

**Expected behavior**
GUI which would allow to fix jitter/faces 

**Screenshots**
![obraz](https://user-images.githubusercontent.com/46869905/53517991-4fec3700-3ad0-11e9-865b-b0ff180b4cc8.png)

**Desktop (please complete the following information):**
- Windows 10
- hash a71fd4234848c746cde1554e2a73c64416972401

**Additional context**
Probably it is related to Windows, I've changed:
tools/lib_alignments/jobs_manual.py
-            key = cv2.waitKey(1)
+            key = cv2.waitKey()
and I was able to see some windows after that (key bindings, face, frame). Unfortunately the image was not interactive, the key bindings worked, but moving boundary box was not interactive.

**Comment by torzdf** [comment]
There is an intermittent bug in Windows which makes it hard to monitor if the windows are open or not.

To get around this, enable the `-dm`, `--disable-monitor` flag
