### ISSUE TITLE
Tools GUI does not work

### ISSUE THREAD

**Issue by berniejerom** [deepfakes/faceswap#633]
**Describe the bug**
Looks like there is no tool GUI at all so either option description is misleading or there something is bugged

**To Reproduce**
run python .\tools.py gui

**Expected behavior**
I should see tools GUI I guess

**Screenshots**
BTW. tools.py mentions that there is GUI option, which results with:
02/27/2019 20:46:38 INFO     Log level set to: INFO
02/27/2019 20:46:40 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "D:\faceswap\lib\cli.py", line 88, in execute_script
    script = self.import_script()
  File "D:\faceswap\lib\cli.py", line 34, in import_script
    module = import_module(mod)
  File "D:\faceswap\locvirtual\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tools.gui'
02/27/2019 20:46:40 CRITICAL An unexpected crash has occurred. 

**Desktop (please complete the following information):**
Windows 10
hash a71fd4234848c746cde1554e2a73c64416972401

**Additional context**
Looks like there is no GUI in tools contrary to "scripts" used by faceswap.py
D:\faceswap\lib\cli.py
is trying to get gui from tools like:
src = "tools" if cmd == "tools.py" else "scripts"

**Comment by kilroythethird** [comment]
faceswap.py is the main entry point.
Use `python faceswap.py gui`

**Comment by r1k0** [comment]
quick note:

doc here https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#prerequisites should change from 
docker exec faceswap-gpu python /srv/tools.py gui
to
docker exec  deepfakes-gpu python /srv/faceswap.py gui
for me the gui only works this on latest manjaro (im using the nvidia-docker approach)
