### ISSUE TITLE
error when train new model

### ISSUE THREAD

**Issue by TTTJJJWWW** [deepfakes/faceswap#635]
when i try to train new model like that:
python faceswap.py train -A ~/Desktop/faceswap-master/data/trump -B ~/Desktop/faceswap-master/data/cage -m ~/Desktop/faceswap-master/model/ -t dfl-h128 -p
or 
python faceswap.py train -A ~/Desktop/faceswap-master/data/trump -B ~/Desktop/faceswap-master/data/cage -m ~/Desktop/faceswap-master/models/ -t dfaker -p

error:
02/28/2019 21:45:06 INFO     Enabled TensorBoard Logging
02/28/2019 21:45:06 ERROR    Caught exception in thread: 'load_batches_0'
02/28/2019 21:45:06 CRITICAL Error caught! Exiting...
02/28/2019 21:45:06 ERROR    Caught exception in thread: 'training_0'
02/28/2019 21:45:08 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/home/tjw/Desktop/faceswap-master/lib/training_data.py", line 158, in get_landmarks
    src_points = self.landmarks[side][lm_key]
KeyError: '75d9f98d3355397e958a9008ce2c9668f2d5a2f0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tjw/Desktop/faceswap-master/lib/cli.py", line 90, in execute_script
    process.process()
  File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 97, in process
    self.end_thread(thread, err)
  File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 122, in end_thread
    thread.join()
  File "/home/tjw/Desktop/faceswap-master/lib/multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/home/tjw/Desktop/faceswap-master/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 148, in training
    raise err
  File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 138, in training
    self.run_training_cycle(model, trainer)
  File "/home/tjw/Desktop/faceswap-master/scripts/train.py", line 210, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "/home/tjw/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 138, in train_one_step
    loss[side] = batcher.train_one_batch(is_preview_iteration)
  File "/home/tjw/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 211, in train_one_batch
    batch = self.get_next(is_preview_iteration)
  File "/home/tjw/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 219, in get_next
    batch = next(self.feed)
  File "/home/tjw/Desktop/faceswap-master/lib/training_data.py", line 118, in minibatch
    load_thread.join()
  File "/home/tjw/Desktop/faceswap-master/lib/multithreading.py", line 179, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/home/tjw/Desktop/faceswap-master/lib/multithreading.py", line 117, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tjw/Desktop/faceswap-master/lib/training_data.py", line 83, in load_batches
    queue.put(self.process_face(img, side, is_timelapse))
  File "/home/tjw/Desktop/faceswap-master/lib/training_data.py", line 130, in process_face
    src_pts = self.get_landmarks(filename, image, side)
  File "/home/tjw/Desktop/faceswap-master/lib/training_data.py", line 161, in get_landmarks
    filename))
Exception: Landmarks not found for hash: '75d9f98d3355397e958a9008ce2c9668f2d5a2f0' file: '/home/tjw/Desktop/faceswap-master/data/trump/462725350.jpg'

How can i fix this? thanks

**Comment by kvrooman** [comment]
You're trying to train a model that requires an alignment file to create masks from the landmarks in the alignment file.

The error says the software can't find 62725350.jpg in the alignment file. 

Likely you either have no alignment file, you pointed to the wrong file location for the alignment file, or the alignment file doesn't contain that image as the extract/detect tool didn't find and align a face in that image.

The alignment file is created by the extract process

**Comment by TTTJJJWWW** [comment]
@kvrooman Hi, thank you for your reply!
I have done extract process (contain alignment file from extract process) and i can train the model with original option successfully.
Need i do extract process for "dfaker" or "dfl" again? and what option i need choose for extract?

**Comment by wujiajun1999** [comment]
when i try to train new model like that:

03/01/2019 14:14:43 INFO     Loading data, this may take a while...
03/01/2019 14:14:43 INFO     Loading Model from Original plugin...
03/01/2019 14:14:43 INFO     Loading config: 'D:\phpStudy2\PHPTutorial\WWW\faces
wap\config\train.ini'
03/01/2019 14:14:43 WARNING  No existing state file found. Generating.
03/01/2019 14:14:43 WARNING  From D:\Python37\lib\site-packages\tensorflow\pytho
n\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framewo
rk.ops) is deprecated and will be removed in a future version.\nInstructions for
 updating:\nColocations handled automatically by placer.
03/01/2019 14:14:43 WARNING  Failed loading existing training data. Generating n
ew models
03/01/2019 14:14:44 INFO     Loading Trainer from Original plugin...
03/01/2019 14:14:44 INFO     Enabled TensorBoard Logging
03/01/2019 14:14:44 ERROR    Caught exception in thread: 'load_batches_0'
03/01/2019 14:14:45 CRITICAL Error caught! Exiting...
03/01/2019 14:14:45 ERROR    Caught exception in thread: 'training_0'
03/01/2019 14:14:46 ERROR    Got Exception on main handler:\nTraceback (most rec
ent call last):\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\cli.py", line
90, in execute_script\n process.process()\n File "D:\phpStudy2\PHPTutorial\WWW\f
aceswap\scripts\train.py", line 97, in process\n self.end_thread(thread, err)\n
File "D:\phpStudy2\PHPTutorial\WWW\faceswap\scripts\train.py", line 122, in end_
thread\n thread.join()\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\multith
reading.py", line 179, in join\n raise thread.err[1].with_traceback(thread.err[2
])\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\multithreading.py", line 11
7, in run\n self._target(*self._args, **self._kwargs)\n File "D:\phpStudy2\PHPTu
torial\WWW\faceswap\scripts\train.py", line 148, in training\n raise err\n File
"D:\phpStudy2\PHPTutorial\WWW\faceswap\scripts\train.py", line 138, in training\
n self.run_training_cycle(model, trainer)\n File "D:\phpStudy2\PHPTutorial\WWW\f
aceswap\scripts\train.py", line 210, in run_training_cycle\n trainer.train_one_s
tep(viewer, timelapse)\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\plugins\tra
in\trainer\_base.py", line 138, in train_one_step\n loss[side] = batcher.train_o
ne_batch(is_preview_iteration)\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\plu
gins\train\trainer\_base.py", line 211, in train_one_batch\n batch = self.get_ne
xt(is_preview_iteration)\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\plugins\t
rain\trainer\_base.py", line 219, in get_next\n batch = next(self.feed)\n File "
D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\training_data.py", line 118, in miniba
tch\n load_thread.join()\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\multi
threading.py", line 179, in join\n raise thread.err[1].with_traceback(thread.err
[2])\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\multithreading.py", line
117, in run\n self._target(*self._args, **self._kwargs)\n File "D:\phpStudy2\PHP
Tutorial\WWW\faceswap\lib\training_data.py", line 77, in load_batches\n self.val
idate_samples(images)\n File "D:\phpStudy2\PHPTutorial\WWW\faceswap\lib\training
_data.py", line 95, in validate_samples\n assert length >= self.batchsize, msg\n
AssertionError: Number of images is lower than batch-size (Note that too few ima
ges may lead to bad training). # images: 1, batch-size: 64
03/01/2019 14:14:46 CRITICAL An unexpected crash has occurred. Crash report writ
ten to D:\phpStudy2\PHPTutorial\WWW\faceswap\crash_report.2019.03.01.14144502481
9.log. Please verify you are running the latest version of faceswap before repor
ting

does anyone know why?

**Comment by torzdf** [comment]
```Number of images is lower than batch-size (Note that too few images may lead to bad training). # images: 1, batch-size: 64```

**Comment by torzdf** [comment]
These issues aren't bugs.

Please repost either in Discord or Faceswap_Playground.

**Comment by wujiajun1999** [comment]
@torzdf thank you very much  i've solved it~
