### ISSUE TITLE
Windows installer failed to download repo from GIT

### ISSUE THREAD

**Issue by deepkeks** [deepfakes/faceswap#636]
During install, fails to download from GIT. Screenshot attached. 

Tested the command from prompt by clicking and copying data to clipboard, pasting GIT command into prompt. Still failed, citing "too many arguments". 

Fixed by placing quotes around destination path. 

![failure](https://user-images.githubusercontent.com/48102717/53600246-ed417c80-3b5d-11e9-8f39-329b41f05157.png)

**Comment by devindwan** [comment]
I have the same issue. My Git is placed into 'C:\Program Files\git\bin\git.exe', And I want to install faceswap into 'D:\Program Files\faceswap'. In order to to prevent ambiguity from blanks in paths, these paths should be wrapped in quotes.

```
# Failed
C:\Program Files\git\bin\git.exe clone --depth 1 --no-single-branch https://github.com/deepfakes/faceswap.git D:\Program Files\faceswap
```

```
# Succeed
'C:\Program Files\git\bin\git.exe clone' --depth 1 --no-single-branch https://github.com/deepfakes/faceswap.git 'D:\Program Files\faceswap'
```

**Comment by torzdf** [comment]
Should be fixed in latest installer
