### ISSUE TITLE
train CUDA is not working properly. Very low usage.

### ISSUE THREAD

**Issue by tt0576** [deepfakes/faceswap#639]
Reinstalling with faceswap_setup_x64_v0.92 is also invalid
Loading the train plugin is very slow and long

The old version is normal, I tested the version of 2018/12/31 to work properly.

============ System Information ============
encoding:          cp936
git_branch:        master
git_commits:       1f8da1d Tensorflow version check
gpu_cuda:          9.0
gpu_cudnn:         7.3.1
gpu_devices:       GPU_0: GeForce GTX 1060 6GB
gpu_driver:        419.17
gpu_vram:          GPU_0: 6144MB
os_machine:        AMD64
os_platform:       Windows-10-10.0.17763-SP0
os_release:        10
py_command:        C:\Users\O\faceswap/faceswap.py gui
py_conda_version:  conda 4.5.12
py_implementation: CPython
py_version:        3.6.8
py_virtual_env:    True
sys_cores:         8
sys_processor:     Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
sys_ram:           Total: 16065MB, Available: 9571MB, Used: 6494MB, Free: 9571MB

=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
certifi==2018.11.29
Click==7.0
cloudpickle==0.8.0
cmake==3.13.3
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.1.2
decorator==4.3.2
dlib==19.16.99
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
mkl-fft==1.0.10
mkl-random==1.0.2
networkx==2.2
numpy==1.15.4
nvidia-ml-py3==7.352.0
olefile==0.46
opencv-python==4.0.0.21
pathlib==1.0.1
Pillow==5.4.1
protobuf==3.6.1
psutil==5.5.0
pyparsing==2.3.1
pyreadline==2.1
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.1
PyYAML==3.13
scikit-image==0.14.1
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
toolz==0.9.0
tornado==5.1.1
tqdm==4.31.1
Werkzeug==0.14.1
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Users\O\MiniConda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.0                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
Click                     7.0                       <pip>
cloudpickle               0.8.0                    py36_0  
cmake                     3.13.3                    <pip>
cudatoolkit               9.0                           1  
cudnn                     7.3.1                 cuda9.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.9.0.1          py36hfa6e2cd_1  
dask-core                 1.1.2                      py_0  
decorator                 4.3.2                    py36_0  
dlib                      19.16.99                  <pip>
face-recognition          1.2.3                     <pip>
face-recognition-models   0.3.0                     <pip>
ffmpeg                    4.1               h6538335_1002    conda-forge
ffmpy                     0.2.2                     <pip>
freetype                  2.9.1                ha9979f8_1  
gast                      0.2.2                    py36_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
intel-openmp              2019.1                      144  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.6                    py36_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.0.5                    py36_0  
kiwisolver                1.0.1            py36h6538335_0  
libpng                    1.6.36               h2a8f88b_0  
libprotobuf               3.6.1                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.0.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h14836fe_0  
mkl_random                1.0.2            py36h343c172_0  
networkx                  2.2                      py36_1  
numpy                     1.15.4           py36h19fb1c0_0  
numpy-base                1.15.4           py36hc3f5095_0  
nvidia-ml-py3             7.352.0                   <pip>
olefile                   0.46                     py36_0  
opencv-python             4.0.0.21                  <pip>
openssl                   1.1.1b               he774522_0  
pathlib                   1.0.1                    py36_1  
pillow                    5.4.1            py36hdc69c19_0  
pip                       19.0.3                   py36_0  
protobuf                  3.6.1            py36h33f27b4_0  
psutil                    5.5.0            py36he774522_0  
pyparsing                 2.3.1                    py36_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                    py36_0  
pytz                      2018.9                   py36_0  
pywavelets                1.0.1            py36h8c2d366_0  
pyyaml                    3.13             py36hfa6e2cd_0  
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.14.1           py36ha925a31_0  
scikit-learn              0.20.2           py36h343c172_0  
scipy                     1.2.1            py36h29ff71c_0  
setuptools                40.8.0                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.26.0               he774522_0  
tensorboard               1.12.2           py36h33f27b4_0  
tensorflow                1.12.0          gpu_py36ha5f9131_0  
tensorflow-base           1.12.0          gpu_py36h6e53903_0  
tensorflow-gpu            1.12.0               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.9.0                    py36_0  
tornado                   5.1.1            py36hfa6e2cd_0  
tqdm                      4.31.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_0  
werkzeug                  0.14.1                   py36_0  
wheel                     0.33.1                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0

**Comment by torzdf** [comment]
There is not enough information here to know if this is an issue. Which trainer are you using? What command did you run? What are your config options?

There is a known issue with filling the queue for training leading to slower launch times.
