### ISSUE TITLE
Can't install dlib or boost

### ISSUE THREAD

**Issue by studiomtn** [deepfakes/faceswap#64]
Hi all,

This is not a bug. I am just having problems with my install. Ive installed everything in this github except dlib and face_recognition. I keep getting this when I try the pip install dlib:

C:\Users\Michael Nguyen>pip install dlib
Collecting dlib
  Using cached dlib-19.8.1.tar.gz
Building wheels for collected packages: dlib
  Running setup.py bdist_wheel for dlib ... error
  Complete output from command "c:\users\michael nguyen\appdata\local\programs\python\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\MICHAE~1\\AppData\\Local\\Temp\\pip-build-bkwfh9da\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\MICHAE~1\AppData\Local\Temp\tmp_sxp8unwpip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  Detected Python architecture: 64bit
  Detected platform: win32
  Configuring cmake ...
  -- Building for: Visual Studio 14 2015
  -- Selecting Windows SDK version  to target Windows 10.0.16299.
  -- The C compiler identification is MSVC 19.0.24210.0
  -- The CXX compiler identification is MSVC 19.0.24210.0
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1610 (message):
    No header defined for python-py34; skipping header check
  Call Stack (most recent call first):
    C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  -- Could NOT find Boost
  CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1610 (message):
    No header defined for python-py35; skipping header check
  Call Stack (most recent call first):
    C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  -- Could NOT find Boost
  CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1610 (message):
    No header defined for python3; skipping header check
  Call Stack (most recent call first):
    C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
    CMakeLists.txt:9 (include)
  -- Could NOT find Boost
  -- Could NOT find Boost
  -- Found PythonLibs: C:/Users/Michael Nguyen/AppData/Local/Programs/Python/Python35/libs/python35.lib (found suitable version "3.5.4", minimum required is "3.4")
  -- Looking for sys/types.h
  -- Looking for sys/types.h - found
  -- Looking for stdint.h
  -- Looking for stdint.h - found
  -- Looking for stddef.h
  -- Looking for stddef.h - found
  -- Check size of void*
  -- Check size of void* - done
  -- Enabling SSE4 instructions
  -- Searching for BLAS and LAPACK
  -- Searching for BLAS and LAPACK
  -- Looking for pthread.h
  -- Looking for pthread.h - not found
  -- Found Threads: TRUE
  -- A library with BLAS API not found. Please specify library location.
  -- LAPACK requires BLAS
  -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found suitable version "8.0", minimum required is "7.5")
  CMake Warning at C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/CMakeLists.txt:535 (message):
    You have CUDA installed, but we can't use it unless you put visual studio
    in 64bit mode.
  -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
  -- C++11 activated.
  --  *****************************************************************************************************
  -- We couldn't find the right version of boost python.  If you installed boost and you are still getting this error then you might have installed a version of boost that was compiled with a different version of visual studio than the one you are using.  So you have to make sure that the version of visual studio is the same version that was used to compile the copy of boost you are using.
  --
  --  You will likely need to compile boost yourself rather than using one of the precompiled
  --  windows binaries.  Do this by going to the folder tools\build\ within boost and running
  --  bootstrap.bat.  Then run the command:
  --     b2 install
  --  And then add the output bin folder to your PATH.  Usually this is the C:\boost-build-engine\bin
  --  folder. Finally, go to the boost root and run a command like this:
  --     b2 -a --with-python address-model=64 toolset=msvc runtime-link=static
  --  Note that you will need to set the address-model based on if you want a 32 or 64bit python library.
  --  When it completes, set the BOOST_LIBRARYDIR environment variable equal to wherever b2 put the
  --  compiled libraries.  You will also need to set BOOST_ROOT to the root folder of the boost install.
  --  E.g.  Something like this:
  --     set BOOST_ROOT=C:\local\boost_1_57_0
  --     set BOOST_LIBRARYDIR=C:\local\boost_1_57_0\stage\lib
  --
  --  Next, if you aren't using python setup.py then you will be invoking cmake to compile dlib.
  --  In this case you may have to use cmake's -G option to set the 64 vs. 32bit mode of visual studio.
  --  Also, if you want a Python3 library you will need to add -DPYTHON3=1.  You do this with a statement like:
  --     cmake -G "Visual Studio 14 2015 Win64" -DPYTHON3=1 ..\..\tools\python
  --  Rather than:
  --     cmake ..\..\tools\python
  --  Which will build a 32bit Python2 module by default on most systems.
  --
  --  *****************************************************************************************************
  CMake Error at C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:149 (message):
     Boost python library not found.
  Call Stack (most recent call first):
    CMakeLists.txt:9 (include)
  -- Configuring incomplete, errors occurred!
  See also "C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
  See also "C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/tools/python/build/CMakeFiles/CMakeError.log".
  error: cmake configuration failed!

  ----------------------------------------
  Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
  Running setup.py install for dlib ... error
    Complete output from command "c:\users\michael nguyen\appdata\local\programs\python\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\MICHAE~1\\AppData\\Local\\Temp\\pip-build-bkwfh9da\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MICHAE~1\AppData\Local\Temp\pip-p539ppox-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Detected Python architecture: 64bit
    Detected platform: win32
    Removing build directory C:\Users\MICHAE~1\AppData\Local\Temp\pip-build-bkwfh9da\dlib\./tools/python/build
    Configuring cmake ...
    -- Building for: Visual Studio 14 2015
    -- Selecting Windows SDK version  to target Windows 10.0.16299.
    -- The C compiler identification is MSVC 19.0.24210.0
    -- The CXX compiler identification is MSVC 19.0.24210.0
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
    -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
    -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1610 (message):
      No header defined for python-py34; skipping header check
    Call Stack (most recent call first):
      C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:66 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    -- Could NOT find Boost
    CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1610 (message):
      No header defined for python-py35; skipping header check
    Call Stack (most recent call first):
      C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:68 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    -- Could NOT find Boost
    CMake Warning at C:/Program Files/CMake/share/cmake-3.10/Modules/FindBoost.cmake:1610 (message):
      No header defined for python3; skipping header check
    Call Stack (most recent call first):
      C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:71 (FIND_PACKAGE)
      CMakeLists.txt:9 (include)
    -- Could NOT find Boost
    -- Could NOT find Boost
    -- Found PythonLibs: C:/Users/Michael Nguyen/AppData/Local/Programs/Python/Python35/libs/python35.lib (found suitable version "3.5.4", minimum required is "3.4")
    -- Looking for sys/types.h
    -- Looking for sys/types.h - found
    -- Looking for stdint.h
    -- Looking for stdint.h - found
    -- Looking for stddef.h
    -- Looking for stddef.h - found
    -- Check size of void*
    -- Check size of void* - done
    -- Enabling SSE4 instructions
    -- Searching for BLAS and LAPACK
    -- Searching for BLAS and LAPACK
    -- Looking for pthread.h
    -- Looking for pthread.h - not found
    -- Found Threads: TRUE
    -- A library with BLAS API not found. Please specify library location.
    -- LAPACK requires BLAS
    -- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v8.0 (found suitable version "8.0", minimum required is "7.5")
    CMake Warning at C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/CMakeLists.txt:535 (message):
      You have CUDA installed, but we can't use it unless you put visual studio
      in 64bit mode.
    -- Disabling CUDA support for dlib.  DLIB WILL NOT USE CUDA
    -- C++11 activated.
    --  *****************************************************************************************************
    -- We couldn't find the right version of boost python.  If you installed boost and you are still getting this error then you might have installed a version of boost that was compiled with a different version of visual studio than the one you are using.  So you have to make sure that the version of visual studio is the same version that was used to compile the copy of boost you are using.
    --
    --  You will likely need to compile boost yourself rather than using one of the precompiled
    --  windows binaries.  Do this by going to the folder tools\build\ within boost and running
    --  bootstrap.bat.  Then run the command:
    --     b2 install
    --  And then add the output bin folder to your PATH.  Usually this is the C:\boost-build-engine\bin
    --  folder. Finally, go to the boost root and run a command like this:
    --     b2 -a --with-python address-model=64 toolset=msvc runtime-link=static
    --  Note that you will need to set the address-model based on if you want a 32 or 64bit python library.
    --  When it completes, set the BOOST_LIBRARYDIR environment variable equal to wherever b2 put the
    --  compiled libraries.  You will also need to set BOOST_ROOT to the root folder of the boost install.
    --  E.g.  Something like this:
    --     set BOOST_ROOT=C:\local\boost_1_57_0
    --     set BOOST_LIBRARYDIR=C:\local\boost_1_57_0\stage\lib
    --
    --  Next, if you aren't using python setup.py then you will be invoking cmake to compile dlib.
    --  In this case you may have to use cmake's -G option to set the 64 vs. 32bit mode of visual studio.
    --  Also, if you want a Python3 library you will need to add -DPYTHON3=1.  You do this with a statement like:
    --     cmake -G "Visual Studio 14 2015 Win64" -DPYTHON3=1 ..\..\tools\python
    --  Rather than:
    --     cmake ..\..\tools\python
    --  Which will build a 32bit Python2 module by default on most systems.
    --
    --  *****************************************************************************************************
    CMake Error at C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/dlib/cmake_utils/add_python_module:149 (message):
       Boost python library not found.
    Call Stack (most recent call first):
      CMakeLists.txt:9 (include)
    -- Configuring incomplete, errors occurred!
    See also "C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/tools/python/build/CMakeFiles/CMakeOutput.log".
    See also "C:/Users/Michael Nguyen/AppData/Local/Temp/pip-build-bkwfh9da/dlib/tools/python/build/CMakeFiles/CMakeError.log".
    error: cmake configuration failed!

    ----------------------------------------
Command ""c:\users\michael nguyen\appdata\local\programs\python\python35\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\MICHAE~1\\AppData\\Local\\Temp\\pip-build-bkwfh9da\\dlib\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\MICHAE~1\AppData\Local\Temp\pip-p539ppox-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\MICHAE~1\AppData\Local\Temp\pip-build-bkwfh9da\dlib\

C:\Users\Michael Nguyen>

Anyone use windows 10 and know how to tackle this?

**Comment by Clorr** [comment]
Hi,

Sorry that you have so much trouble setting things up.

There is an issue on face_recognition lib concerning windows, maybe it can help:

https://github.com/ageitgey/face_recognition/issues/158

**Comment by Clorr** [comment]
Also if you google "dlib windows python install", you may find useful links like this one: https://github.com/charlielito/install-dlib-python-windows/blob/master/README.md

**Comment by Clorr** [comment]
(However be careful the link points to an old version of dlib, try with latest one...)

**Comment by Clorr** [comment]
See #71
