### ISSUE TITLE
training broken

### ISSUE THREAD

**Issue by TobiTrom** [deepfakes/faceswap#640]
previous calculation was ok, then that

![preview](https://user-images.githubusercontent.com/40788602/53681474-6e2d7f00-3cea-11e9-9b0c-fd21617227a4.png)

**Comment by torzdf** [comment]
More information please, which model? Which commit? If you're on the GUI post the output of Tools>System Informations

This is model corruption which can happen with Convolution Networks. You can restore from the .bk files in your model folder and carry on.
