### ISSUE TITLE
ERROR    No frames to process. Exiting

### ISSUE THREAD

**Issue by qinbatista** [deepfakes/faceswap#642]
03/03/2019 21:14:38 INFO     Log level set to: INFO
03/03/2019 21:14:40 INFO     Output Directory: output
03/03/2019 21:14:40 INFO     Input Directory: input
03/03/2019 21:14:40 INFO     Loading Detect from Mtcnn plugin...
03/03/2019 21:14:40 INFO     Updating config at: '/Users/yupengqin/Desktop/faceswap/config/extract.ini'
03/03/2019 21:14:40 INFO     Loading config: '/Users/yupengqin/Desktop/faceswap/config/extract.ini'
03/03/2019 21:14:40 INFO     Loading Align from Fan plugin...
03/03/2019 21:14:40 WARNING  No GPU detected. Switching to CPU mode
03/03/2019 21:14:40 INFO     Starting, this may take a while...
03/03/2019 21:14:40 ERROR    No frames to process. Exiting

**Comment by qinbatista** [comment]
problem:
python faceswap.py extract

when I try to install numpy as 1.15.4 will be
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

I change numpy as 1.16.2 will be 
ERROR No frames to process. Exiting

I am using mac.

**Comment by torzdf** [comment]
Module not found is probably system conflicts.

No frames to process is because there are no frames in your input folder.
