### ISSUE TITLE
Faceswap Windows Installer v0.95b DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by KaveriWaikar** [deepfakes/faceswap#644]
![error](https://user-images.githubusercontent.com/44992085/53700131-2d7e5480-3e15-11e9-8af3-2ad62d358f19.PNG)

**Comment by torzdf** [comment]
Are you running CPU or GPU version of faceswap? What's your graphics card?

**Comment by torzdf** [comment]
This should be fixed in latest installer
