### ISSUE TITLE
setUpfailed

### ISSUE THREAD

**Issue by awesomedu** [deepfakes/faceswap#646]
![default](https://user-images.githubusercontent.com/28338863/53715027-7e309480-3e8b-11e9-8d5b-aebb44e63f9e.png)

dear editor,what does these mean?

**Comment by AdarshMaurya** [comment]
I faced the same issue while building it, as the log says your using python version 3.6

Consider executing with python3

python3 setup.py

python3 faceswap.py -h 

Thanks

**Comment by torzdf** [comment]
You haven't installed properly.
