### ISSUE TITLE
API for python application

### ISSUE THREAD

**Issue by RuhuiCheng** [deepfakes/faceswap#647]
**so far we can use the project just through lib.cli , but sometimes the client side is a web application so i hope one friendly API for another python programe is very necessary**

**Comment by torzdf** [comment]
We have no current plans on our roadmap to implement an api.

We are open to pull requests though

**Comment by johndpope** [comment]
@arturgontijo built out this - thought it depends on singularity 3rd party hosted solution.

https://github.com/johndpope/dnn-model-services/tree/master/services/deepfakes-faceswap
