### ISSUE TITLE
OriginalHighRes not working after models changed...

### ISSUE THREAD

**Issue by zurlam** [deepfakes/faceswap#648]
I am trying to use a previous OriginalHighRes model but it doesn't work anymore with any kind of trainer.

**Comment by torzdf** [comment]
Unfortunately stability changes to the code, and work from @andenixa means that the OHR pre-refactor does not work in the new world (it is the only model we were unable to migrate). There is a snapshot branch pre-refactor to be able to load/train this model.

See: https://github.com/deepfakes/faceswap-playground/issues/249#issuecomment-463845624
