### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by friendFapp** [deepfakes/faceswap#65]
How can we use this amazing peace of ML art? 
Having a licence would greatly improve the value of this project.

[MIT](https://en.wikipedia.org/wiki/MIT_License) license is one of the most permissive.
[GNU](https://en.wikipedia.org/wiki/GNU_General_Public_License) is a way to go if you want to force all the derivative projects to be opensource.

**Comment by Ganonmaster** [comment]
I'm personally in favor of using GPL3 or LGPL3.

**Comment by friendFapp** [comment]
@Ganonmaster, why exactly?

**Comment by Apollo122** [comment]
Should be GNU. Then other projects which use this will always be open source

**Comment by Ganonmaster** [comment]
As a contributor, I feel happier knowing that the software will be free in perpetuity; usable for everyone, rather than leaving it open to companies that wouldn't contribute anything back to the project.

Should other contributors want to opt for something more permissive, the LGPL would be an adequate compromise.

**Comment by TimT6** [comment]
I'd go with MIT or Apache because that way companies can contribute without worrying how they might be able to use it in the future. Just my 2 cent.

**Comment by mahmedov** [comment]
MIT is the way to go.

**Comment by Clorr** [comment]
The original code is from /u/deepfakes on reddit, so the decision relies on him

**Comment by melnation-com** [comment]
Any license that makes it free for life, anyone/company can contribute but understood that they cannot claim whole/part ownership of it ever(companies should sign like a waiver that even if they had contributed work/resources on it, they could never take a tiny bit whole/part ownership/partnership, cause you know companies can pay lawyers and find loopholes.), not to use whole/part of any where of the app/code to make their own free NOR especially for commercial, neither for private nor non-private use.

You can also patent it or something.

**Comment by gdunstone** [comment]
we still need to get /u/deepfakes to approve this licensing. If you can get into contact with him, then we can put a license on it.

We cant license it without /u/deepfakes because then the license is void due to the unknown license of the original source.

**Comment by fat-tire** [comment]
I think his or her address is at http://www.fakeapp.org/

**Comment by gdunstone** [comment]
I'm reopening this because it still needs a solution.

**Comment by dfaker** [comment]
@gdunstone  I strongly doubt that /u/deepfakes is going to reply or ever assert his moral right to be known as an author of parts of the original codebase for obvious reasons.

I'd be happy to assert that the masked merging is derivative of the code in /dfaker/df and as such should be under MPL-2.0 if that helps anyone line up behind a boring decision faster.

**Comment by dfaker** [comment]
#220

**Comment by dfaker** [comment]
Pull request #220 Add GNU General Public License v3.0
