### ISSUE TITLE
ERROR initialising aligner during EXTRACT

### ISSUE THREAD

**Issue by haarissiddiqie1** [deepfakes/faceswap#651]
**Describe the bug**
i am recieving an error when trying to extract. 

**To Reproduce**
1. run python extract 
2. See error

**Expected behavior**
Extract is successful for images

---------CRASH REPORT IS BELOW----------

  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\fan.py", line 254, in set_session
    session.run(self.output, feed_dict={self.input: placeholder})
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: fa/Cast = Cast[DstT=DT_INT32, SrcT=DT_FLOAT, Truncate=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fa/mul). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: fa/Cast = Cast[DstT=DT_INT32, SrcT=DT_FLOAT, Truncate=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fa/mul)]]

Caused by op 'fa/Cast', defined at:
  File "<string>", line 1, in <module>
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\_base.py", line 91, in run
    self.align(*args, **kwargs)
  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\fan.py", line 52, in align
    super().align(*args, **kwargs)
  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\_base.py", line 81, in align
    self.initialize(*args, **kwargs)
  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\fan.py", line 45, in initialize
    self.model = FAN(self.model_path, ratio=tf_ratio)
  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\fan.py", line 223, in __init__
    self.graph = self.load_graph()
  File "C:\Users\factoryorganicquery\faceswap\plugins\extract\align\fan.py", line 238, in load_graph
    self.tf.import_graph_def(graph_def, name="fa")
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\util\deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\framework\importer.py", line 553, in import_graph_def
    op_def=op_def)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): NodeDef mentions attr 'Truncate' not in Op<name=Cast; signature=x:SrcT -> y:DstT; attr=SrcT:type; attr=DstT:type>; NodeDef: fa/Cast = Cast[DstT=DT_INT32, SrcT=DT_FLOAT, Truncate=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fa/mul). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: fa/Cast = Cast[DstT=DT_INT32, SrcT=DT_FLOAT, Truncate=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fa/mul)]]
03/06/2019 20:18:11 MainProcess     MainThread      extract         launch_aligner            INFO     Waiting for Aligner... Time out in 4 minutes
03/06/2019 20:19:11 MainProcess     MainThread      extract         launch_aligner            INFO     Waiting for Aligner... Time out in 3 minutes
03/06/2019 20:20:11 MainProcess     MainThread      extract         launch_aligner            INFO     Waiting for Aligner... Time out in 2 minutes
03/06/2019 20:21:11 MainProcess     MainThread      extract         launch_aligner            INFO     Waiting for Aligner... Time out in 1 minutes
Traceback (most recent call last):
  File "C:\Users\factoryorganicquery\faceswap\lib\cli.py", line 90, in execute_script
    process.process()
  File "C:\Users\factoryorganicquery\faceswap\scripts\extract.py", line 49, in process
    self.run_extraction()
  File "C:\Users\factoryorganicquery\faceswap\scripts\extract.py", line 147, in run_extraction
    self.plugins.launch_aligner()
  File "C:\Users\factoryorganicquery\faceswap\scripts\extract.py", line 357, in launch_aligner
    raise ValueError("Error initializing Aligner")
ValueError: Error initializing Aligner

============ System Information ============
encoding:          cp1252
git_branch:        master
git_commits:       a71fd42 Extract scaling bugfix. 53e664b Alignments tool. Bug-fix - multi-faces. a96ef2a Add in encoder_dim overide for legacy iae and original. 67c4efc Add "Minumum Size" filter for extract. 5bc3ab1 Analysis tab: Fix disappearing options on large datasets
gpu_cuda:          9.0
gpu_cudnn:         7.0.4
gpu_devices:       GPU_0: Tesla K80
gpu_driver:        385.54
gpu_vram:          GPU_0: 11420MB
os_machine:        AMD64
os_platform:       Windows-2012ServerR2-6.3.9600-SP0
os_release:        2012ServerR2
py_command:        faceswap.py extract -i C:\Users\factoryorganicquery\faceswap\Photo\trump -o C:\Users\factoryorganicquery\faceswap\Data\trump
py_conda_version:  conda 4.5.12
py_implementation: CPython
py_version:        3.6.8
py_virtual_env:    True
sys_cores:         1
sys_processor:     Intel64 Family 6 Model 63 Stepping 0, GenuineIntel
sys_ram:           Total: 3839MB, Available: 2472MB, Used: 1366MB, Free: 2472MB

=============== Pip Packages ===============
absl-py==0.7.0
astor==0.7.1
bleach==1.5.0
certifi==2018.11.29
Click==7.0
cloudpickle==0.8.0
cmake==3.13.3
cycler==0.10.0
dask==1.1.2
decorator==4.3.2
dlib==19.16.99
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
grpcio==1.19.0
h5py==2.9.0
html5lib==0.9999999
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
Markdown==3.0.1
matplotlib==2.2.2
mkl-fft==1.0.10
mkl-random==1.0.2
networkx==2.2
numpy==1.15.4
nvidia-ml-py3==7.352.0
opencv-python==3.2.0.6
pathlib==1.0.1
Pillow==5.4.1
protobuf==3.6.1
psutil==5.5.1
pyparsing==2.3.1
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.2
PyYAML==3.13
scikit-image==0.14.2
scikit-learn==0.20.2
scipy==1.2.1
six==1.12.0
tensorboard==1.6.0
tensorflow-gpu==1.6.0
termcolor==1.1.0
toolz==0.9.0
tqdm==4.31.1
Werkzeug==0.14.1
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Users\factoryorganicquery\AppData\Local\conda\conda\envs\SSWAP:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.0                     <pip>
astor                     0.7.1                     <pip>
blas                      1.0                         mkl  
bleach                    1.5.0                     <pip>
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py36_0  
Click                     7.0                       <pip>
cloudpickle               0.8.0                     <pip>
cmake                     3.13.3                    <pip>
cycler                    0.10.0                    <pip>
dask                      1.1.2                     <pip>
decorator                 4.3.2                     <pip>
dlib                      19.16.99                  <pip>
face-recognition          1.2.3                     <pip>
face-recognition-models   0.3.0                     <pip>
ffmpy                     0.2.2                     <pip>
gast                      0.2.2                     <pip>
grpcio                    1.19.0                    <pip>
h5py                      2.9.0                     <pip>
html5lib                  0.9999999                 <pip>
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
intel-openmp              2019.1                      144  
jpeg                      9c                hfa6e2cd_1001    conda-forge
Keras                     2.2.4                     <pip>
Keras-Applications        1.0.7                     <pip>
Keras-Preprocessing       1.0.9                     <pip>
kiwisolver                1.0.1                     <pip>
libpng                    1.6.36            h7602738_1000    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
libwebp                   1.0.2                hfa6e2cd_1    conda-forge
Markdown                  3.0.1                     <pip>
matplotlib                2.2.2                     <pip>
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36hfa6e2cd_1    conda-forge
mkl_random                1.0.2            py36h830ac7b_2    conda-forge
networkx                  2.2                       <pip>
numpy                     1.15.4                    <pip>
numpy                     1.16.0           py36h19fb1c0_0  
numpy-base                1.16.0           py36hc3f5095_0  
nvidia-ml-py3             7.352.0                   <pip>
opencv-python             3.2.0.6                   <pip>
openssl                   1.1.1b               he774522_0  
pathlib                   1.0.1                     <pip>
Pillow                    5.4.1                     <pip>
pip                       19.0.3                   py36_0  
protobuf                  3.6.1                     <pip>
psutil                    5.5.1                     <pip>
pyparsing                 2.3.1                     <pip>
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                     <pip>
pytz                      2018.9                    <pip>
PyWavelets                1.0.2                     <pip>
PyYAML                    3.13                      <pip>
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.14.2                    <pip>
scikit-learn              0.20.2                    <pip>
scipy                     1.2.1                     <pip>
setuptools                40.8.0                   py36_0  
six                       1.12.0                    <pip>
sqlite                    3.26.0               he774522_0  
tensorboard               1.6.0                     <pip>
tensorflow-gpu            1.6.0                     <pip>
termcolor                 1.1.0                     <pip>
toolz                     0.9.0                     <pip>
tqdm                      4.31.1                    <pip>
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_0  
Werkzeug                  0.14.1                    <pip>
wheel                     0.33.1                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
zlib                      1.2.11            h2fa13f4_1004    conda-forge

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows server 2012 r2 (GPU running nvidia tesla (K80)
 - Browser chroms
===================================

**Comment by torzdf** [comment]
Pull latest code. Update requirements. Specifically tensorflow to 1.12
