### ISSUE TITLE
Configurable internal image size

### ISSUE THREAD

**Issue by rifterbater** [deepfakes/faceswap#66]
It'd be nice if the internal image size was easily configurable through the various steps to something other than 64x64. With upcoming improved plugins, or just someone willing to put in a lot more training time, going higher resolution seems inevitable.

I've tried hacking around a bit but I'm new to python and deep learning. I'm sure I'll get it eventually but this is probably a trivial change for someone familiar with these libraries.

Doesn't need to be piped all the way to the command line, but if it could be pulled up to changing a define it would be as easy a change for people as changing ENCODER_DIM is.

**Comment by Clorr** [comment]
Basically, you could just change image_shape, but there will be quite a lot of caveats and it is not guaranteed that your model performs well on another size.

**Comment by IUsedToBeAPygmy** [comment]
I'd love to have the option to switch between 64, 128 and 256.
Even if my current gpu can't hack it, it's only a matter of time before the average you can.
