### ISSUE TITLE
Can not train

### ISSUE THREAD

**Issue by HJMRX** [deepfakes/faceswap#660]
**Describe the bug**
CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\mainme\dlib\crash_report.2019.03.14.125451846201.log. Please verify you are running the latest version of faceswap before reporting
**To Reproduce**
3/14/2019 12:49:09 INFO     Log level set to: INFO
Using TensorFlow backend.
03/14/2019 12:49:13 INFO     Model A Directory: F:\deepfake\A
03/14/2019 12:49:13 INFO     Model B Directory: F:\deepfake\B
03/14/2019 12:49:13 INFO     Training data directory: F:\deepfake\models
03/14/2019 12:49:13 INFO     ===============================================
03/14/2019 12:49:13 INFO     - Starting                                    -
03/14/2019 12:49:13 INFO     - Press 'ENTER' to save and quit              -
03/14/2019 12:49:13 INFO     - Press 'S' to save model weights immediately -
03/14/2019 12:49:13 INFO     ===============================================
03/14/2019 12:49:14 INFO     Loading data, this may take a while...
03/14/2019 12:49:14 INFO     Loading Model from Original plugin...
03/14/2019 12:51:21 INFO     Loading config: 'F:\deepfake\faceswap\faceswap_master\config\train.ini'
03/14/2019 12:51:21 WARNING  No existing state file found. Generating.
03/14/2019 12:51:23 WARNING  From F:\Anaconda\envs\faceswap\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
03/14/2019 12:51:39 INFO     Creating new 'original' model in folder: 'F:\deepfake\models'
03/14/2019 12:51:51 INFO     Loading Trainer from Original plugin...
03/14/2019 12:52:22 INFO     Enabled TensorBoard Logging
03/14/2019 12:52:24 WARNING  From F:\Anaconda\envs\faceswap\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
2019-03-14 12:54:35.497568: E tensorflow/core/grappler/clusters/utils.cc:83] Failed to get device properties, error code: 30
03/14/2019 12:54:51 CRITICAL Error caught! Exiting...
03/14/2019 12:54:51 ERROR    Caught exception in thread: 'training_0'
03/14/2019 12:55:14 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "F:\deepfake\faceswap\faceswap_master\lib\cli.py", line 107, in execute_script
process.process()
File "F:\deepfake\faceswap\faceswap_master\scripts\train.py", line 101, in process
self.end_thread(thread, err)
File "F:\deepfake\faceswap\faceswap_master\scripts\train.py", line 126, in end_thread
thread.join()
File "F:\deepfake\faceswap\faceswap_master\lib\multithreading.py", line 443, in join
raise thread.err[1].with_traceback(thread.err[2])
File "F:\deepfake\faceswap\faceswap_master\lib\multithreading.py", line 381, in run
self._target(*self._args, **self._kwargs)
File "F:\deepfake\faceswap\faceswap_master\scripts\train.py", line 152, in training
raise err
File "F:\deepfake\faceswap\faceswap_master\scripts\train.py", line 142, in training
self.run_training_cycle(model, trainer)
File "F:\deepfake\faceswap\faceswap_master\scripts\train.py", line 214, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "F:\deepfake\faceswap\faceswap_master\plugins\train\trainer\_base.py", line 139, in train_one_step
loss[side] = batcher.train_one_batch(do_preview)
File "F:\deepfake\faceswap\faceswap_master\plugins\train\trainer\_base.py", line 214, in train_one_batch
loss = self.model.predictors[self.side].train_on_batch(*batch)
File "F:\Anaconda\envs\faceswap\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "F:\Anaconda\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "F:\Anaconda\envs\faceswap\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "F:\Anaconda\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
run_metadata_ptr)
File "F:\Anaconda\envs\faceswap\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[64,32,32,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node decoder_b/conv2d_7/BiasAdd-1-1-TransposeNCHWToNHWC-LayoutOptimizer}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[{{node loss_1/mul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

03/14/2019 12:55:14 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\mainme\dlib\crash_report.2019.03.14.125451846201.log. Please verify you are running the latest version of faceswap before reporting

**Expected behavior**
I want to train

**Desktop (please complete the following information):**
 ============ System Information ============
encoding:          cp936
git_branch:        Not Found
git_commits:       Not Found
gpu_cuda:          10.0
gpu_cudnn:         7.5.0
gpu_devices:       GPU_0: GeForce GTX 1050
gpu_driver:        419.17
gpu_vram:          GPU_0: 4096MB
 tensorflow-gpu Version: 1.13.1
os_machine:        AMD64
os_platform:       Windows-10-10.0.17134-SP0
os_release:        10
py_command:        F:\deepfake\faceswap\faceswap_master\faceswap.py train -A F:/deepfake/A -B F:/deepfake/B -m F:/deepfake/models -t original -s 100 -bs 64 -it 1000000 -g 1 -ps 50 -L INFO -gui
py_conda_version:  conda 4.5.12
py_implementation: CPython
py_version:        3.6.8
py_virtual_env:    True
sys_cores:         12
sys_processor:     Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
sys_ram:           Total: 8047MB, Available: 2309MB, Used: 5737MB, Free: 2309MB

**Additional context**
I am a newbie to python. I would love to know how to solve this problem. please tell me. Thanks.

**Comment by torzdf** [comment]
```tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor```
Lower your batch size or try the lowmem option

**Comment by HJMRX** [comment]
First of all, thank you for your reply, for some reason, my python is not working, I am trying to fix it, or reconfigure the environment. I will try again after I finish.

**Comment by HJMRX** [comment]
Thanks. I can train now.
