### ISSUE TITLE
train killed 

### ISSUE THREAD

**Issue by yizhiheying** [deepfakes/faceswap#661]
**Describe the bug**
when run train cmd show killed，and model generate failed。
cmd:
python3 faceswap.py train -A ./demo1/3_align -B ./demo1/5_align -m ./demo1/models

log:
eason@ubuntu:~/main/source/ai/alg/faceswap$ python3 faceswap.py train -A ./demo1/3_align -B ./demo1/5_align -m ./demo1/models
03/14/2019 00:54:53 INFO     Log level set to: INFO
Using TensorFlow backend.
03/14/2019 00:54:57 INFO     Model A Directory: /home/eason/main/source/ai/alg/faceswap/demo1/3_align
03/14/2019 00:54:57 INFO     Model B Directory: /home/eason/main/source/ai/alg/faceswap/demo1/5_align
03/14/2019 00:54:57 INFO     Training data directory: /home/eason/main/source/ai/alg/faceswap/demo1/models
03/14/2019 00:54:57 INFO     ===============================================
03/14/2019 00:54:57 INFO     - Starting                                    -
03/14/2019 00:54:57 INFO     - Press 'ENTER' to save and quit              -
03/14/2019 00:54:57 INFO     - Press 'S' to save model weights immediately -
03/14/2019 00:54:57 INFO     ===============================================
03/14/2019 00:54:58 INFO     Loading data, this may take a while...
03/14/2019 00:54:58 INFO     Loading Model from Original plugin...
03/14/2019 00:55:01 INFO     Loading config: '/home/eason/main/source/ai/alg/faceswap/config/train.ini'
03/14/2019 00:55:01 WARNING  No existing state file found. Generating.
03/14/2019 00:55:01 WARNING  From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
03/14/2019 00:55:02 INFO     Creating new 'original' model in folder: '/home/eason/main/source/ai/alg/faceswap/demo1/models'
03/14/2019 00:55:02 INFO     Loading Trainer from Original plugin...
03/14/2019 00:55:03 INFO     Enabled TensorBoard Logging
03/14/2019 00:55:05 WARNING  From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
Killed

**To Reproduce**
1. run python3 faceswap gui,extra dst image to 3_image folder
2. extra src image to 5_image folder
3.align 3_image to 3_align
4.align 5_image to 5_align
5.python3 faceswap.py train -A ./demo1/3_align -B ./demo1/5_align -m ./demo1/models
show above error msg

**Expected behavior**
train success,and generate right model

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu18.10 in VMware
 - python3.6 /gcc version 8.2.0 /cmake version 3.13.3/libprotoc 3.7.0
-CPU version 

PS: when run python3 faceswap.py gui to train model,status bar show “No session data loaded”,and train failed.

Anyone can help?

**Comment by yizhiheying** [comment]
PS: when run python3 faceswap.py gui to train model,status bar show “No session data loaded”。

**Comment by kvrooman** [comment]
I assume this is also related to your other issue where you mention you use Tensorflow 1.131.

Suggest using Tensorflow 1.12

**Comment by torzdf** [comment]
Provide a crash_report.

**Comment by Frankie34** [comment]
under Tensorflow 1.12 "killed" happens with in a docker image

**Comment by Frankie34** [comment]
[crash_report.2019.04.10.031057123301.log](https://github.com/deepfakes/faceswap/files/3061887/crash_report.2019.04.10.031057123301.log)

**Comment by Frankie34** [comment]
@torzdf

**Comment by Frankie34** [comment]
@kvrooman

**Comment by Frankie34** [comment]
Have you covered your issue? @yizhiheying
