### ISSUE TITLE
train Process exited

### ISSUE THREAD

**Issue by yizhiheying** [deepfakes/faceswap#668]
vmware ubuntu18.10/python3.6/tensorflow1.13.1

use python3 faceswap.py gui to train face image
train show blow msg:
Loading...
03/15/2019 02:10:23 INFO     Log level set to: INFO
Using TensorFlow backend.
03/15/2019 02:10:26 INFO     Model A Directory: /home/eason/main/source/ai/alg/faceswap/demo1/3_align
03/15/2019 02:10:26 INFO     Model B Directory: /home/eason/main/source/ai/alg/faceswap/demo1/5_align
03/15/2019 02:10:26 INFO     Training data directory: /home/eason/main/source/ai/alg/faceswap/demo1/models
03/15/2019 02:10:27 INFO     ===============================================
03/15/2019 02:10:27 INFO     - Starting                                    -
03/15/2019 02:10:27 INFO     - Press 'ENTER' to save and quit              -
03/15/2019 02:10:27 INFO     - Press 'S' to save model weights immediately -
03/15/2019 02:10:27 INFO     ===============================================
03/15/2019 02:10:28 INFO     Loading data, this may take a while...
03/15/2019 02:10:28 INFO     Loading Model from Original plugin...
03/15/2019 02:10:30 INFO     Loading config: '/home/eason/main/source/ai/alg/faceswap/config/train.ini'
03/15/2019 02:10:30 WARNING  No existing state file found. Generating.
03/15/2019 02:10:31 WARNING  From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
03/15/2019 02:10:31 INFO     Creating new 'original' model in folder: '/home/eason/main/source/ai/alg/faceswap/demo1/models'
03/15/2019 02:10:32 INFO     Loading Trainer from Original plugin...
03/15/2019 02:10:32 INFO     Enabled TensorBoard Logging
03/15/2019 02:10:33 WARNING  From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
Process exited.

Anyone can help?

**Comment by kvrooman** [comment]
tensorflow1.13.1 not supported. downgrade to TF 1.12 or seek help from other RTX power-users
