### ISSUE TITLE
s3fd vram

### ISSUE THREAD

**Issue by TobiTrom** [deepfakes/faceswap#669]
03/15/2019 11:54:19 INFO     Loading Align from Fan plugin...
03/15/2019 11:54:19 WARNING  Not enough free VRAM for parallel processing. Switching to serial
03/15/2019 11:54:19 INFO     Starting, this may take a while...
03/15/2019 11:54:19 INFO     Initializing S3FD Detector...
03/15/2019 11:54:31 WARNING  You are running s3fd with 4018MB VRAM. The model is optimized for 4096MB VRAM. Detection should still run but you may get warnings/Errors

i use 2x GTX 1050 TI

**Comment by torzdf** [comment]
Extraction only runs on 1 card
