### ISSUE TITLE
Cluster faces during extract using dlib.chinese_whispers_clustering

### ISSUE THREAD

**Issue by badluckwiththinking** [deepfakes/faceswap#67]
I have had some success hacking together a pre-processing script to run over my training images. It uses [dlib.chinese_whispers_clustering](http://dlib.net/python/index.html#dlib.chinese_whispers_clustering) to group the found faces in the training data based on likeness. I think one of the keys to good results is good training sets, and this helps to prevent polluting the training data with other peoples faces as tends to be the case with Google image search sets or images with multiple faces.

There are a couple of ways I think this could be integrated into the project:

1) during extract when generating face chips, discard non target faces (all faces not in the largest cluster)
2) during convert where frames have multiple faces, identifying only the target face for replacement.

Here's [the script](https://gist.github.com/badluckwiththinking/92dd6f155bc8babca6422b08b642d35d), sorry its a bit hacky, I just wanted something that worked and haven't cleaned it up. I'm not sure where I would begin to integrate it into the project, perhaps as an alternative plugin?

**Comment by Clorr** [comment]
Yes you can integrate it as an extract plugin. The extract plugin has not been much prepared for a new behavior, but it is still possible. Don't be scared of modifying the extract.py and propose something that suit you better.

**Comment by badluckwiththinking** [comment]
I couldn't wrap my head around doing it as a plug in. The clustering requires evaluating all the faces in the set rather than individual processing. In the end I've done it as a separate script, but could use some feedback before considering a pull request.

Having put some time in to writing it I'm not sure if it's going to add a huge amount of value compared to the additional layer of complexity, possibly a lot more issues non technical user. Looking at it now I think I would rather re-do it a switch for the existing extract.py but wanted to find out if it could be useful before spending time re-writing.

https://github.com/badluckwiththinking/faceswap/commit/7ada68d0a92d57e6b19b100f48e647d8291517ff

**Comment by badluckwiththinking** [comment]
This can be closed off, I think its duplication of functionality already covered in #53
