### ISSUE TITLE
Dockerfile.gpu use the latest tensorflow version 

### ISSUE THREAD

**Issue by lynnfi** [deepfakes/faceswap#677]
The Dockerfile.gpu use `FROM tensorflow/tensorflow:latest-py3`
The latest version of tensorflow is 2.0 alpha.（You may check this )[docker hub](https://hub.docker.com/r/tensorflow/tensorflow/tags?page=1)
It will cause compatibility problems。
So ,I think we should use the specified tensorflow version。
We may use `FROM tensorflow/tensorflow:1.13.1-gpu-py3 `

Anyone have some idea about this?

**Comment by torzdf** [comment]
#675
