### ISSUE TITLE
Error when launching train

### ISSUE THREAD

**Issue by zoulock** [deepfakes/faceswap#68]
Output:

[zoulock@zoulock-desktop faceswap]$ python3 faceswap.py train -A faceA -B faceB -m models -p
/usr/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING:tensorflow:From /usr/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1264: calling reduce_prod (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From /usr/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1349: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
Model A Directory: /home/zoulock/faceswap/faceA
Model B Directory: /home/zoulock/faceswap/faceB
Training data directory: /home/zoulock/faceswap/models
Not loading existing training data.
Unable to open file (unable to open file: name = '/home/zoulock/faceswap/models/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Starting, this may take a while...
usage: faceswap.py [-h] {extract,train,convert} ...

positional arguments:
  {extract,train,convert}
    extract             Extract the faces from a pictures.
    train               This command trains the model for the two faces A and
                        B.
    convert             Convert a source image to a new one with the face
                        swapped.

optional arguments:
  -h, --help            show this help message and exit

**Comment by AlphasCodes** [comment]
I can confirm the issue on my system (Lubuntu 17.10, Python 3.6, Cuda 9.1, cuDNN 7.0.5, Tensorflow 1.5). My workaround is to use the fork of @Clorr (https://github.com/Clorr/faceswap).

**Comment by dimon777** [comment]
This is not an issue, it tells that you don't have saved models yet.

**Comment by Clorr** [comment]
You lay have a silent failure. When you see `usage: faceswap.py...` it is because it has failed. With the latest versions, there should be less silent errors, but I closed this because there is not enough info
