### ISSUE TITLE
ImportError: cannot import name run

### ISSUE THREAD

**Issue by nbhhcty** [deepfakes/faceswap#683]
➜  faceswap git:(master) python setup.py
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from subprocess import CalledProcessError, run, PIPE, Popen
ImportError: cannot import name run

**Comment by torzdf** [comment]
There is no way near enough information here to diagnose anything

**Comment by RONNCC** [comment]
probably need to use >python 3.5
