### ISSUE TITLE
Error Train

### ISSUE THREAD

**Issue by Stephenfang51** [deepfakes/faceswap#695]
when I want to train, it shows the error ? 
```
Loading...
04/05/2019 19:07:05 INFO     Log level set to: INFO
Using TensorFlow backend.
04/05/2019 19:07:15 INFO     Model A Directory: C:\Users\steph\Desktop\output5
04/05/2019 19:07:15 INFO     Model B Directory: C:\Users\steph\Desktop\output3
04/05/2019 19:07:15 INFO     Training data directory: C:\Users\steph\Desktop\trainingmodel
04/05/2019 19:07:15 INFO     ===============================================
04/05/2019 19:07:15 INFO     - Starting                                    -
04/05/2019 19:07:15 INFO     - Using live preview                          -
04/05/2019 19:07:15 INFO     - Press 'ENTER' to save and quit              -
04/05/2019 19:07:15 INFO     - Press 'S' to save model weights immediately -
04/05/2019 19:07:15 INFO     ===============================================
04/05/2019 19:07:16 INFO     Loading data, this may take a while...
04/05/2019 19:07:16 INFO     Loading Model from Original plugin...
04/05/2019 19:07:24 INFO     Loading config: 'C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\config\train.ini'
04/05/2019 19:07:24 WARNING  No existing state file found. Generating.
04/05/2019 19:07:24 WARNING  From C:\Users\steph\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nColocations handled automatically by placer.
04/05/2019 19:07:26 INFO     Creating new 'original' model in folder: 'C:\Users\steph\Desktop\trainingmodel'
04/05/2019 19:07:26 INFO     Loading Trainer from Original plugin...
04/05/2019 19:07:32 ERROR    'NoneType' object has no attribute 'astype'\nTraceback (most recent call last):\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\multithreading.py", line 261, in _runner\n target(*args, **kwargs)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 105, in load_batches\n imgs = self.process_face(img_path, side, is_timelapse)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 155, in process_face\n image = self.processing.color_adjust(image)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 226, in color_adjust\n return img.astype('float32') / 255.0\nAttributeError: 'NoneType' object has no attribute 'astype'
04/05/2019 19:07:33 INFO     Enabled TensorBoard Logging
04/05/2019 19:07:33 WARNING  From C:\Users\steph\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
04/05/2019 19:08:17 CRITICAL Error caught! Exiting...
04/05/2019 19:08:17 ERROR    Caught exception in thread: 'training_0'
04/05/2019 19:08:22 ERROR    Got Exception on main handler:\nTraceback (most recent call last):\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\cli.py", line 107, in execute_script\n process.process()\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 98, in process\n self.end_thread(thread, err)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 123, in end_thread\n thread.join()\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\multithreading.py", line 443, in join\n raise thread.err[1].with_traceback(thread.err[2])\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\multithreading.py", line 381, in run\n self._target(*self._args, **self._kwargs)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 149, in training\n raise err\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 139, in training\n self.run_training_cycle(model, trainer)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 214, in run_training_cycle\n trainer.train_one_step(viewer, timelapse)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\plugins\train\trainer\_base.py", line 153, in train_one_step\n loss[side] = batcher.train_one_batch(do_preview)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\plugins\train\trainer\_base.py", line 234, in train_one_batch\n batch = self.get_next(do_preview)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\plugins\train\trainer\_base.py", line 242, in get_next\n batch = next(self.feed)\nStopIteration
04/05/2019 19:08:22 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\crash_report.2019.04.05.190817525654.log. Please verify you are running the latest version of faceswap before reporting
Process exited.
```

**Comment by kvrooman** [comment]
"C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 226, in color_adjust\n return img.astype('float32') / 255.0

\nAttributeError: 'NoneType' object has no attribute 'astype'

it's trying to process an image which isn't there. guessing that the image directory pointer could be wrong ?

**Comment by Stephenfang51** [comment]
> "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 226, in color_adjust\n return img.astype('float32') / 255.0
> 
> \nAttributeError: 'NoneType' object has no attribute 'astype'
> 
> it's trying to process an image which isn't there. guessing that the image directory pointer could be wrong ?

Thanks for replying, yeah noticed that， have checked over and over again, still no idea.. :(

**Comment by torzdf** [comment]
There is not enough information here. Provide the crash report.

**Comment by Stephenfang51** [comment]
> There is not enough information here. Provide the crash report.

Dear Sir,  here‘s my crash report

04/05/2019 19:29:11 MainProcess     training_0      training_data   __init__                  DEBUG    Initialized TrainingDataGenerator
04/05/2019 19:29:11 MainProcess     training_0      training_data   minibatch_ab              DEBUG    Queue batches: (image_count: 740, batchsize: 4, side: 'b', do_shuffle: True, is_timelapse: False)
04/05/2019 19:29:11 MainProcess     training_0      training_data   make_queues               DEBUG    ['train_b_in', 'train_b_out']
04/05/2019 19:29:11 MainProcess     training_0      queue_manager   get_queue                 DEBUG    QueueManager getting: 'train_b_in'
04/05/2019 19:29:11 MainProcess     training_0      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'train_b_in', maxsize: 0)
04/05/2019 19:29:11 SpawnProcess-2  MainThread      multithreading  _runner                   DEBUG    FixedProducerDispatcher worker for <bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x0000021D633C47F0>> started
04/05/2019 19:29:11 SpawnProcess-2  MainThread      training_data   load_batches              DEBUG    Loading batch: (image_count: 3546, side: 'a', is_timelapse: False, do_shuffle: True)
04/05/2019 19:29:11 MainProcess     training_0      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'train_b_in')
04/05/2019 19:29:11 MainProcess     training_0      queue_manager   get_queue                 DEBUG    QueueManager got: 'train_b_in'
04/05/2019 19:29:11 MainProcess     training_0      queue_manager   get_queue                 DEBUG    QueueManager getting: 'train_b_out'
04/05/2019 19:29:11 MainProcess     training_0      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'train_b_out', maxsize: 0)
04/05/2019 19:29:12 MainProcess     training_0      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'train_b_out')
04/05/2019 19:29:12 MainProcess     training_0      queue_manager   get_queue                 DEBUG    QueueManager got: 'train_b_out'
04/05/2019 19:29:12 MainProcess     training_0      multithreading  __init__                  DEBUG    Initializing FixedProducerDispatcher: (method: '<bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x000001CBBB7B2AC8>>', shapes: [(4, 192, 192, 3), (4, 64, 64, 3), (4, 128, 128, 3), (4, 128, 128, 1)], args: (['C:\\Users\\steph\\Desktop\\output3\\蔡_000025_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000026_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000027_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000028_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000029_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000030_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000031_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000032_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000033_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000034_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000035_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000036_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000037_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000038_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000039_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000040_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000041_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000042_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000043_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000044_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000045_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000046_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000047_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000048_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000049_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000050_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000051_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000052_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000053_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000054_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000055_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000056_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000057_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000058_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000059_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000060_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000061_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000062_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000063_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000064_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000065_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000066_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000067_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000068_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000069_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000070_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000071_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000072_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000073_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000074_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000075_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000076_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000077_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000078_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000079_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000080_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000081_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000082_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000083_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000084_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000085_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000086_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000087_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000088_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000089_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000090_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000091_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000092_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000093_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000094_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000095_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000096_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000097_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000098_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000099_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000100_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000101_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000102_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000103_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000104_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000105_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000106_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000107_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000108_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000109_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000110_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000111_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000112_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000113_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000114_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000115_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000116_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000117_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000118_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000119_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000120_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000121_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000122_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000123_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000124_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000125_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000126_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000127_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000128_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000129_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000130_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000131_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000132_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000133_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000134_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000135_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000136_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000137_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000138_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000139_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000140_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000141_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000142_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000143_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000144_0.png', 'C:\\Users\\steph\\Desktop\\output3\\蔡_000145_0.png'], 'b', False, True, 4), kwargs: {}, ctype: <class 'ctypes.c_float'>, workers: 1, buffers: None)
04/05/2019 19:29:12 MainProcess     training_0      multithreading  __init__                  DEBUG    Initialized FixedProducerDispatcher
04/05/2019 19:29:12 MainProcess     training_0      training_data   minibatch_ab              DEBUG    Batching to queue: (side: 'b', is_timelapse: False)
04/05/2019 19:29:12 MainProcess     training_0      _base           set_tensorboard           DEBUG    Enabling TensorBoard Logging
04/05/2019 19:29:12 MainProcess     training_0      _base           set_tensorboard           DEBUG    Setting up TensorBoard Logging. Side: a
04/05/2019 19:29:12 MainProcess     training_0      _base           name                      DEBUG    model name: 'dfaker'
04/05/2019 19:29:12 SpawnProcess-3  MainThread      multithreading  _runner                   DEBUG    FixedProducerDispatcher worker for <bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x0000028B0A244860>> started
04/05/2019 19:29:12 SpawnProcess-3  MainThread      training_data   load_batches              DEBUG    Loading batch: (image_count: 740, side: 'b', is_timelapse: False, do_shuffle: True)
04/05/2019 19:29:12 SpawnProcess-3  MainThread      multithreading  _runner                   ERROR    object supporting the buffer API required\nTraceback (most recent call last):\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\multithreading.py", line 261, in _runner\n target(*args, **kwargs)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 105, in load_batches\n imgs = self.process_face(img_path, side, is_timelapse)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 151, in process_face\n src_pts = self.get_landmarks(filename, image, side)\n File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\training_data.py", line 177, in get_landmarks\n lm_key = sha1(image).hexdigest()\nTypeError: object supporting the buffer API required
04/05/2019 19:29:12 SpawnProcess-3  MainThread      multithreading  _runner                   DEBUG    FixedProducerDispatcher worker for <bound method TrainingDataGenerator.load_batches of <lib.training_data.TrainingDataGenerator object at 0x0000028B0A244860>> shutdown
04/05/2019 19:29:13 MainProcess     training_0      _base           set_tensorboard           DEBUG    Setting up TensorBoard Logging. Side: b
04/05/2019 19:29:13 MainProcess     training_0      _base           name                      DEBUG    model name: 'dfaker'
04/05/2019 19:29:13 MainProcess     training_0      _base           set_tensorboard           INFO     Enabled TensorBoard Logging
04/05/2019 19:29:13 MainProcess     training_0      _base           use_mask                  DEBUG    True
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Samples: model: '<plugins.train.model.dfaker.Model object at 0x000001CB88707E80>', use_mask: True, coverage_ratio: 1.0)
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initialized Samples
04/05/2019 19:29:13 MainProcess     training_0      _base           use_mask                  DEBUG    True
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Timelapse: model: <plugins.train.model.dfaker.Model object at 0x000001CB88707E80>, use_mask: True, coverage_ratio: 1.0, batchers: '{'a': <plugins.train.trainer._base.Batcher object at 0x000001CBDCEF22B0>, 'b': <plugins.train.trainer._base.Batcher object at 0x000001CBBB7B2EB8>}')
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Samples: model: '<plugins.train.model.dfaker.Model object at 0x000001CB88707E80>', use_mask: True, coverage_ratio: 1.0)
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initialized Samples
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initialized Timelapse
04/05/2019 19:29:13 MainProcess     training_0      _base           __init__                  DEBUG    Initialized TrainerBase
04/05/2019 19:29:13 MainProcess     training_0      train           load_trainer              DEBUG    Loaded Trainer
04/05/2019 19:29:13 MainProcess     training_0      train           run_training_cycle        DEBUG    Running Training Cycle
04/05/2019 19:29:13 MainProcess     training_0      training_data   minibatch                 DEBUG    Launching minibatch generator for queue (side: 'a', is_timelapse: False)
04/05/2019 19:29:13 MainProcess     training_0      deprecation     new_func                  WARNING  From C:\Users\steph\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.\nInstructions for updating:\nUse tf.cast instead.
04/05/2019 19:29:44 MainProcess     training_0      _base           compile_sample            DEBUG    Compiling samples: (side: 'a', samples: 4)
04/05/2019 19:29:44 MainProcess     training_0      training_data   minibatch                 DEBUG    Launching minibatch generator for queue (side: 'b', is_timelapse: False)
04/05/2019 19:29:44 MainProcess     training_0      training_data   minibatch                 DEBUG    Finished minibatch generator for queue: (side: 'b', is_timelapse: False)
04/05/2019 19:29:44 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0):
04/05/2019 19:29:45 MainProcess     MainThread      train           monitor                   DEBUG    Thread error detected
04/05/2019 19:29:45 MainProcess     MainThread      train           monitor                   DEBUG    Closed Monitor
04/05/2019 19:29:45 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
04/05/2019 19:29:45 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
04/05/2019 19:29:45 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
04/05/2019 19:29:45 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
04/05/2019 19:29:45 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
Traceback (most recent call last):
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\cli.py", line 107, in execute_script
    process.process()
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 98, in process
    self.end_thread(thread, err)
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 123, in end_thread
    thread.join()
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\multithreading.py", line 443, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\lib\multithreading.py", line 381, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 149, in training
    raise err
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 139, in training
    self.run_training_cycle(model, trainer)
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\scripts\train.py", line 214, in run_training_cycle
    trainer.train_one_step(viewer, timelapse)
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\plugins\train\trainer\_base.py", line 153, in train_one_step
    loss[side] = batcher.train_one_batch(do_preview)
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\plugins\train\trainer\_base.py", line 234, in train_one_batch
    batch = self.get_next(do_preview)
  File "C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\plugins\train\trainer\_base.py", line 242, in get_next
    batch = next(self.feed)
StopIteration

============ System Information ============
encoding:          cp936
git_branch:        Not Found
git_commits:       Not Found
gpu_cuda:          Not Found
gpu_cudnn:         Not Found
gpu_devices:       
gpu_driver:        No Nvidia driver found
gpu_vram:          
os_machine:        AMD64
os_platform:       Windows-10-10.0.17134-SP0
os_release:        10
py_command:        C:\Users\steph\Desktop\mirrors-faceswap-master\faceswap\faceswap.py train -A C:/Users/steph/Desktop/output5 -B C:/Users/steph/Desktop/output3 -ala C:/Users/steph/Desktop/韩国语/han_alignments.json -alb C:/Users/steph/Desktop/韩国语/蔡_alignments.json -m C:/Users/steph/Desktop/trainingmodel -t dfaker -s 100 -bs 4 -it 1000000 -g 1 -ps 50 -p -L INFO -gui
py_conda_version:  N/A
py_implementation: CPython
py_version:        3.7.2
py_virtual_env:    False
sys_cores:         4
sys_processor:     Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
sys_ram:           Total: 3994MB, Available: 572MB, Used: 3422MB, Free: 572MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.7.1
astroid==2.2.5
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
Click==7.0
colorama==0.4.1
cycler==0.10.0
decorator==4.4.0
defusedxml==0.5.0
dlib==19.17.0
entrypoints==0.3
face-recognition==1.2.3
face-recognition-models==0.3.0
ffmpy==0.2.2
gast==0.2.2
google-pasta==0.1.4
grpcio==1.19.0
h5py==2.9.0
imageio==2.5.0
ipykernel==5.1.0
ipython==7.4.0
ipython-genutils==0.2.0
isort==4.3.15
jedi==0.13.3
Jinja2==2.10
jsonschema==3.0.1
jupyter-client==5.2.4
jupyter-core==4.4.0
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
Markdown==3.1
MarkupSafe==1.1.1
matplotlib==2.2.2
mccabe==0.6.1
mistune==0.8.4
mock==2.0.0
nbconvert==5.4.1
nbformat==4.4.0
networkx==2.2
notebook==5.7.7
numpy==1.16.2
nvidia-ml-py3==7.352.0
opencv-python==4.0.0.21
pandocfilters==1.4.2
parso==0.3.4
pathlib==1.0.1
pbr==5.1.3
pickleshare==0.7.5
Pillow==6.0.0
prometheus-client==0.6.0
prompt-toolkit==2.0.9
protobuf==3.7.1
psutil==5.6.1
pygame==1.9.4
Pygments==2.3.1
pylint==2.3.1
pyparsing==2.3.1
pyrsistent==0.14.11
python-dateutil==2.8.0
pytz==2018.9
PyWavelets==1.0.2
pywinpty==0.5.5
PyYAML==5.1
pyzmq==18.0.1
rope==0.12.0
scikit-image==0.15.0
scikit-learn==0.20.3
scipy==1.2.1
Send2Trash==1.5.0
six==1.12.0
tb-nightly==1.14.0a20190301
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
tf-estimator-nightly==1.14.0.dev2019030115
toposort==1.5
tornado==6.0.2
tqdm==4.31.1
traitlets==4.3.2
typed-ast==1.3.1
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.2
wrapt==1.11.1

**Comment by torzdf** [comment]
This could be any number of issues. At the moment TF 1.13.1 is not directly supported. Also, you are not installed within an environment, so you may have conflicts.

Windows users should use the installer to install faceswap to make sure everything is set up correctly:
https://github.com/deepfakes/faceswap/releases
