### ISSUE TITLE
Training doesn't start

### ISSUE THREAD

**Issue by TanayKarve** [deepfakes/faceswap#696]
<b>Tensorflow==1.12.0
CUDA=9
cuDNN=7.2
</b>

<u>Error trace:<u>

Loading...
04/06/2019 03:04:15 INFO     Log level set to: INFO
Using TensorFlow backend.
04/06/2019 03:04:20 INFO     Model A Directory: F:\Dev\ml\faceswap\output\sl
04/06/2019 03:04:20 INFO     Model B Directory: F:\Dev\ml\faceswap\output\ab
04/06/2019 03:04:20 INFO     Training data directory: F:\Dev\ml\faceswap\models
04/06/2019 03:04:20 INFO     ===============================================
04/06/2019 03:04:20 INFO     - Starting                                    -
04/06/2019 03:04:20 INFO     - Press 'ENTER' to save and quit              -
04/06/2019 03:04:20 INFO     - Press 'S' to save model weights immediately -
04/06/2019 03:04:20 INFO     ===============================================
04/06/2019 03:04:20 INFO     Exit requested! The trainer will complete its current cycle, save the models and quit (it can take up a couple of seconds depending on your training speed). If you want to kill it now, press Ctrl + c
04/06/2019 03:04:21 INFO     Loading data, this may take a while...
04/06/2019 03:04:21 INFO     Loading Model from Original plugin...
04/06/2019 03:04:55 INFO     Loading config: 'F:\Dev\ml\faceswap\config\train.ini'
04/06/2019 03:04:55 WARNING  No existing state file found. Generating.
04/06/2019 03:05:01 INFO     Creating new 'original' model in folder: 'F:\Dev\ml\faceswap\models'
04/06/2019 03:05:01 INFO     Loading Trainer from Original plugin...
04/06/2019 03:05:04 INFO     Enabled TensorBoard Logging
04/06/2019 03:10:33 ERROR    Caught exception in thread: 'training_0'
04/06/2019 03:11:01 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "F:\Dev\ml\faceswap\lib\cli.py", line 107, in execute_script
process.process()
File "F:\Dev\ml\faceswap\scripts\train.py", line 98, in process
self.end_thread(thread, err)
File "F:\Dev\ml\faceswap\scripts\train.py", line 123, in end_thread
thread.join()
File "F:\Dev\ml\faceswap\lib\multithreading.py", line 443, in join
raise thread.err[1].with_traceback(thread.err[2])
File "F:\Dev\ml\faceswap\lib\multithreading.py", line 381, in run
self._target(*self._args, **self._kwargs)
File "F:\Dev\ml\faceswap\scripts\train.py", line 149, in training
raise err
File "F:\Dev\ml\faceswap\scripts\train.py", line 139, in training
self.run_training_cycle(model, trainer)
File "F:\Dev\ml\faceswap\scripts\train.py", line 214, in run_training_cycle
trainer.train_one_step(viewer, timelapse)
File "F:\Dev\ml\faceswap\plugins\train\trainer\_base.py", line 153, in train_one_step
loss[side] = batcher.train_one_batch(do_preview)
File "F:\Dev\ml\faceswap\plugins\train\trainer\_base.py", line 235, in train_one_batch
loss = self.model.predictors[self.side].train_on_batch(*batch)
File "C:\Users\Tanay\Anaconda3\lib\site-packages\keras\engine\training.py", line 1217, in train_on_batch
outputs = self.train_function(ins)
File "C:\Users\Tanay\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
return self._call(inputs)
File "C:\Users\Tanay\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
fetched = self._callable_fn(*array_vals)
File "C:\Users\Tanay\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
run_metadata_ptr)
File "C:\Users\Tanay\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[16384] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
[[{{node training/Adam/mul_58}} = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Adam/beta_2/read, training/Adam/Variable_33/read)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

[[{{node loss/mul/_295}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1638_loss/mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

04/06/2019 03:11:01 CRITICAL An unexpected crash has occurred. Crash report written to F:\Dev\ml\faceswap\crash_report.2019.04.06.031033300715.log. Please verify you are running the latest version of faceswap before reporting
Process exited.

**Comment by torzdf** [comment]
OOM = Out of Memory. Lower your batchsize. If you still have issues provide the crash report

**Comment by TanayKarve** [comment]
<b> Crash report </b>
[crash_report.2019.04.06.130931913557.log](https://github.com/deepfakes/faceswap/files/3050221/crash_report.2019.04.06.130931913557.log)

**Comment by torzdf** [comment]
You have a 2GB GPU running on Windows.

The best you can hope for is to run the lightweight model with a low batchsize, with Memory Saving Gradients and PingPong enabled.
