### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 0: unexpected end of data

### ISSUE THREAD

**Issue by TanayKarve** [deepfakes/faceswap#697]
[Crash report ](https://pastebin.com/Hvmg5zPa)

**Comment by pengyang** [comment]
Check if you pressed "pg up"/"pg dn" arrow key when you train your  model. I have encountered the same question.

**Comment by prantoran** [comment]
I am also getting similar issue:
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 158: ordinal not in range(128)

Here is the copy of terminal logs: https://pastebin.com/j4n6suit

I tried with .png and .jpg format but got the same error.

**Comment by torzdf** [comment]
The last issue was a special character creeping into the default config. Fixed some time ago. The first issue is a non utf-8 keypress of some description, but not something that can be easily fixed.
