### ISSUE TITLE
error when saving model and exiting

### ISSUE THREAD

**Issue by wiso** [deepfakes/faceswap#699]
**Describe the bug**

I am running a training, using the docker image and master

`python3 faceswap.py train -A data/... -B data/... -m model... -bs 16`

after a while I press enter:

```
04/07/2019 11:39:49 INFO     Exit requested! The trainer will complete its current cycle, save the models and quit (it can take up a couple of seconds depending on your training speed). If you want to kill it now, press Ctrl + c
[11:39:50] [#00423] loss_A: 0.01439, loss_B: 0.02641

04/07/2019 11:39:53 INFO     saved models
Exception ignored in: <bound method BaseSession.__del__ of <tensorflow.python.client.session.Session object at 0x7fbb0005b9b0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 738, in __del__
TypeError: 'NoneType' object is not callable
```

**To Reproduce**
1. nvidia-docker run -it  --rm -v /home/myhome/faceswap:/srv deepfakes-gpu /bin/bash
2.`python3 faceswap.py train -A data/... -B data/... -m model... -bs 16`

**Desktop (please complete the following information):**
 - OS: fedora 29

**Comment by torzdf** [comment]
That's a TF error which can be safely ignored
