### ISSUE TITLE
About training model of other people.

### ISSUE THREAD

**Issue by Hsintien-Ng** [deepfakes/faceswap#702]
I am confused of how to train a good converting model.
I follow the README file and try to train a model converting cage to trump and set the default parameters but the performance seems to be awful. Could you please show me the details of training the model, especially the super parameter setting, like learning rate, epoch, and so on...
I would be appreciated if anyone could provide me a trained model file about converting cage to trump.

**Comment by torzdf** [comment]
Please post general query questions in either the Discord server or faceswap-playground
