### ISSUE TITLE
Excuse me. As there is not enough space on Drive C. Is there any way to install on other drive?

### ISSUE THREAD

**Issue by Netpolice** [deepfakes/faceswap#704]
Excuse me. As there is not enough space on Drive C. Is there any way to install on other drive?

**Comment by xiaozhitongxie** [comment]
SSD is no longer expensive，just buy one won‘t cost you much, man.

**Comment by deepfakes** [comment]
Faceswap installer allows you to specify the location. 

Miniconda will default to C:\users\Username. If you don't want it there, then download miniconda separately and install it prior to running faceswap installer.
