### ISSUE TITLE
Improving or simplifying the face recognition step

### ISSUE THREAD

**Issue by 6o6o** [deepfakes/faceswap#707]
The preprocessing, or **extract** stage consists of 3 different steps:

1. Face detection finds all the faces in the photo
2. Face recognition filters a particular person from all detected faces
3. Face alignment matches the landmarks

The recognition step is currently the bottleneck. Of 3000 frames it only manages to find 700 examples. It's very poor at detecting profile poses or with closed eyes and that's why people say that face swaps don't blink. Different examples for a reference photo only make things worse.

I'd like to implement a simpler filtering technique by sorting all detected faces based on positional distance from target person in the previous frame and just picking the first one. I managed to achieve this by modifying the [`handleImage`](https://github.com/deepfakes/faceswap/blob/20753a64b76a156aea17724348269d60dd525f87/scripts/extract.py#L64) function in `extract.py` script from one year ago, but the current version is cluttered with GUI methods and multithreading techniques and is difficult to wrap my head around. Can you pinpoint the function which I need to modify in order to sort the detected faces based on a custom metric?

Also, I figured out the recognition is poor because it fails to extract face encoding in `face_filter.py` script. Is there any way to compare faces based on the landmarks only and refrain from generating the encoding? I think it would be useful since most of the time you only need a single face extracted from an image and picking the highest scoring one seems like a natural way to go.

Thanks.

**Comment by torzdf** [comment]
We're all for different face filters. We want to remove the requirement on dlib from the whole of the project, so we have it on the 'todo' list to change the face filter (it currently relies on face-recognition, which relies on dlib). It is a long, long, long way down though.

For post processing items if you look from line 286 of `scripts/fsmedia.py` you'll see how the current actions get implemented (to be honest, I'm not too sure why they are there and not in extract.py, but anyway).

You would basicaly inherit from `class PostProcessAction()` and have a `process` method which takes an `output` item. This is a dict that is received from the aligner that contains:
``` {"filename": <filename of source frame>,
     "image": <source image>,
     "detected_faces": <list of detected_faces objects>,
     "landmarks": <list of landmarks>}```

These actions are called from the `PostProcess` class within the same file.

**Comment by 6o6o** [comment]
Well, the project has made a tremendous progress over the year, so well done! Gotta admit, the new MTCNN detector together with the FAN aligner are absolutely amazing. The results are almost perfect even with more than 90 degree head turns.

Combined with a simple filtering technique I mentioned above, it appears to produce meaningful results for [interviews](https://www.youtube.com/watch?v=_cDGkmhDxaU) with a mostly static camera. For more dynamic scenes it still requires lots of manual editing afterwards. I'm going to play with this technique a little more, check how robust it is in different scenarios, and maybe come up with a pull request if results will look promising. In general, it may be feasible to replace the recognition with some sort of tracking, preferably temporal, because of simplicity, and avoid the costly `face_encodings` calls.
![ze](https://user-images.githubusercontent.com/13799992/56316519-22804900-6163-11e9-9181-6559b8ddcd2d.gif)

Thanks for the instructions. Great to know the proper solution to the problem without hacking my way through the code :)

As a side note, is there anywhere I can read about the network architecture change, which breaks backward-compatibility of the models? Some sort of changelog? Thanks again.

**Comment by torzdf** [comment]
s3fd is even better than mtcnn. The only reason I haven't made it the default is it's quite resource heavy.

There shouldn't be any backwards compatibility breakages. Old models should still load (although the filenames may have changed)
