### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 158: ordinal not in range(128)

### ISSUE THREAD

**Issue by prantoran** [deepfakes/faceswap#713]
[pastebin link to crash report](https://pastebin.com/j4n6suit``)

**Comment by torzdf** [comment]
Looks like an error in your config file. Specifically you seem to have a long dash where you should have a short one:
https://www.fileformat.info/info/unicode/char/2013/index.htm

**Comment by prantoran** [comment]
Thanks you, checking it out

**Comment by mikeguidry** [comment]
I had pulled the latest code to a new directory and still had this error.  I fixed by modifying the command for executing like:
docker exec -e LC_ALL=C.UTF-8 deepfakes-gpu python3 /srv/faceswap.py gui
