### ISSUE TITLE
Deep Fake like this

### ISSUE THREAD

**Issue by Six-wars** [deepfakes/faceswap#714]
I was wondering if you can do this type of video conversion where the end result isn't faceswap but editing something to seem authentic with audio also

https://www.youtube.com/watch?v=cQ54GDm1eL0

**Comment by coderguy1777** [comment]
With a video like that, they most likely tracked Jordan Peele's mouth movement and then worked it in with faceswap, and while I'm not exactly sure, in faceswap and deepfakes, syncing audio and video at the same time isn't always possible, which I may be wrong on, but this is what I remember last time from using deepfakes.
