### ISSUE TITLE
I got some UnicodeEncodeError issues. How can I slove it? 

### ISSUE THREAD

**Issue by ho6009** [deepfakes/faceswap#715]
File "C:\Users\jho60\AppData\Local\Programs\Python\Python36\lib\configparser.py", line 931, in _write_section
    fp.write("{}{}\n".format(key, value))
**UnicodeEncodeError: 'cp949' codec can't encode character '\u2013' in position 159: illegal multibyte sequence**

 File "C:\faceswap\lib\logger.py", line 155, in crash_log
    outfile.writelines(freeze_log)
**UnicodeEncodeError: 'cp949' codec can't encode character '\u2013' in position 339: illegal multibyte sequence**

First issue, I can fix it with modifying code as 'open(file_name, 'w', -1, "utf-8")'
But in second issue, I don't know where can I fix it.

**Comment by torzdf** [comment]
Looks like an error in your config file. Specifically a long dash where it should be a short one:
https://www.fileformat.info/info/unicode/char/2013/index.htm

**Comment by ho6009** [comment]
Thank you for answer. But, It is hard that python beginer like me update the latest code in  /config/convert.ini.
May I explain more sepcifically? And How can I use fileformat site?

**Comment by torzdf** [comment]
Delete your faceswap folder. Get faceswap again.

**Comment by ho6009** [comment]
Thank you, it is perfectly worked
