### ISSUE TITLE
[Windows] cuda_path was not set if success on first check.

### ISSUE THREAD

**Issue by namkazt** [deepfakes/faceswap#718]
**Describe the bug**
setup.py file:
cuDNN was not detected if `cuda_check` success in first check using "nvcc -V" because of `self.env.cuda_path` not set

**To Reproduce**
1, run `python setup.py` on windows 10 environment

**Expected behavior**
detect cuDNN lib

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
I temporary disable first method to check CUDA so it working for now.

**Comment by HobbitArmy** [comment]
![error](https://user-images.githubusercontent.com/32774415/57760513-487f1600-772e-11e9-9363-35349d0a778b.jpg)
Could anybody help, already add cudnn file in correct place; but it just dosen't work.
thanks

**Comment by namkazt** [comment]
@HobbitArmy  replace [first part of this method](https://github.com/deepfakes/faceswap/blob/b1568824056513d07bd218eae2f04d56148cf60d/setup.py#L432)
```python
def cudnn_check(self):
        """ Check Linux or Windows cuDNN Version from cudnn.h """
        if self.env.os_version[0] == "Linux":
            cudnn_checkfiles = self.cudnn_checkfiles_linux()
        elif self.env.os_version[0] == "Windows":
             if self.env.cuda_path == "":
                 cuda_keys = [key
                         for key in os.environ.keys()
                         if key.lower().startswith("cuda_path_v")]
                self.env.cuda_path = os.environ[cuda_keys[0]]
            cudnn_checkfiles = self.cudnn_checkfiles_windows()
```

this will check if `self.env.cuda_path` is empty then get it from env

**Comment by torzdf** [comment]
This issue should be fixed in latest commit.
