### ISSUE TITLE
Execute conda error when running the installer.....

### ISSUE THREAD

**Issue by Loyolichoo** [deepfakes/faceswap#719]
**Describe the bug**
When I run the faceswap_setup_x64_0.97.3b.exe, it tall me that:

> Execute: "C:\Users\Lc\Miniconda3\scripts\activate.bat" && conda create -y python=3.6 -n  "faceswap" && conda deactivate
> Error Creating Conda Virtual Environment
> Install Aborted

**To Reproduce**

1. Just run it...

1. Change the installer folder....

1. It will get the source....

1. Display the error...

**Expected behavior**
When I run the command :
`conda create -y python=3.6 -n  "faceswap"`
There is the error infomation:

> Collecting package metadata: failed
> 
> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/msys2/noarch/repodata.json.bz2>
> Elapsed: -
> 
> An HTTP error occurred when trying to retrieve this URL.
> HTTP errors are often intermittent, and a simple retry will get you on your way.
> 
> If your current network has https://www.anaconda.com blocked, please file
> a support request with your network engineering team.
> 
> SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/msys2/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

I try to open the link in browser

> https://repo.anaconda.com/pkgs/msys2/noarch/repodata.json.bz2

no problem,download successful...

**Screenshots**
![image](https://user-images.githubusercontent.com/18119338/57182529-9c8a2f00-6ed2-11e9-837c-4bd1f11a6cc3.png)

![image](https://user-images.githubusercontent.com/18119338/57182525-8d0ae600-6ed2-11e9-9874-245b3a068d69.png)

**Desktop:**
 - OS: [Windows10 1809]

Maybe should I install some other softwares?

**Comment by Kirin-kun** [comment]
It's an issue with Conda, not faceswap.

See https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#ssl-connection-errors

You should be able to find which case applies to you.

**Comment by torzdf** [comment]
Latest version of conda appears to have issues....

I advise removing conda from your system and installing the following version:
https://repo.anaconda.com/miniconda/Miniconda3-4.5.12-Windows-x86_64.exe

Then running Faceswap installer again.
I may look at pinning the conda version until this is resolved upstream.
