### ISSUE TITLE
Can you make faceswap an integration package?

### ISSUE THREAD

**Issue by sktbest** [deepfakes/faceswap#721]
I hope that faceswap can be compressed like DeepFaceLab.
This is a good thing for us beginners.
Now faceswap is too complicated
Our Chinese players are basically using DeepFaceLab.
Because its use is very simple
We also donated money to the DeepFaceLab author.
I think you can also make faceswap easy to use.

**Comment by torzdf** [comment]
There is a windows installer for faceswap and a GUI. I'm not sure how it could be simpler?
https://github.com/deepfakes/faceswap/releases/tag/v0.97.3b

We cannot distribute CUDA/cuDNN as it would be in breach of their license agreement.
