### ISSUE TITLE
has installed cuDNN,but not found

### ISSUE THREAD

**Issue by chenkarl** [deepfakes/faceswap#722]
**Describe the bug**
has installed cuDNN,but not found

**To Reproduce**
python setup.py

**Expected behavior**
WARNING Running without root/admin privileges
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Windows 10
INFO    Installed Python: 3.6.8 64bit
INFO    Encoding: cp936
INFO    Upgrading pip...
INFO    Installed pip: 19.1.1
Enable  Docker? [y/N] n
INFO    Docker Disabled
Enable  CUDA? [Y/n] y
INFO    CUDA Enabled
INFO    CUDA version: 10.1
ERROR   cuDNN not found. See https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#cudnn for instructions
WARNING The minimum Tensorflow requirement is 1.12.
        Tensorflow currently has no official prebuild for your CUDA, cuDNN combination.
        Either install a combination that Tensorflow supports or build and install your own tensorflow-gpu.
        CUDA Version: 10.1
        cuDNN Version:
        Help:
        Building Tensorflow: https://www.tensorflow.org/install/install_sources
        Tensorflow supported versions: https://www.tensorflow.org/install/source#tested_build_configurations
Location of custom tensorflow-gpu wheel (leave blank to manually install):
INFO    Checking System Dependencies...
INFO    CMake version: 3.14.3
INFO    Visual Studio 2015 version: 14.0
INFO    Visual Studio C++ version: v14.0.24215.01
INFO    1. Install PIP requirements
        You may want to execute `chcp 65001` in cmd line
        to fix Unicode issues on Windows when installing dependencies

**Screenshots**
![1](https://user-images.githubusercontent.com/26109912/57536578-07c27e00-7377-11e9-9efa-e3f35b30284f.png)
![2](https://user-images.githubusercontent.com/26109912/57536599-114be600-7377-11e9-9631-59e5a78b6d64.png)
![3](https://user-images.githubusercontent.com/26109912/57536731-60921680-7377-11e9-9845-ce5efd5e07ca.png)

**Desktop (please complete the following information):**
 - Windows 10

**Comment by torzdf** [comment]
Uninstall Cuda and cuDNN and install using the Windows Installer.
https://github.com/deepfakes/faceswap/releases
