### ISSUE TITLE
Windows installation Guide Missing Chocolatey as Preliminary Install

### ISSUE THREAD

**Issue by s92025592025** [deepfakes/faceswap#723]
**Describe the bug**
Windows install exe will have installation failure if Chocolatey is not manually installed before hand

**To Reproduce**
Run the Windows install without Chocolatey installed

**Expected behavior**
I think this failure is expected, since the Chocolatey is involved as part of the installation process

**Desktop (please complete the following information):**
Windows 10 Pro
Python 3.6

**Additional context**
I have CUDA, cudNN, Python3.6 all installed on my machine. The windows installation just keeps failing and give the following message
```
conda deactivate Error Setting up Faceswap Install Aborted
```

Once I installed Chocolatey, the install exe successfully installed faceswap on my machine

**Comment by torzdf** [comment]
This is most likely an error specific to you. I would need the full output from the installer, and then the output of a test run of that command.

Chocolately is not a pre-requisite for Faceswap.
