### ISSUE TITLE
Facehull mask is initialized with 1.0 instead of 255.0

### ISSUE THREAD

**Issue by mpuels** [deepfakes/faceswap#726]
**Describe the bug**
After training a dfaker model with mask facehull for 3 days, the model doesn't swap faces, i.e. the input image and the "swapped" image look exactly the same. Also, using the `--swap-model` flag did not help.

**To Reproduce**
Train a dfaker model with the default settings, i.e. with the facehull mask.

**Expected behavior**
After 3 days of training I expect that the model swaps faces.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Additional context**
I could resolve the problem by initializing the "transparent" pixels in the class [facehull](https://github.com/deepfakes/faceswap/blob/057f715a84e1f3eb138b9a410c42cfdb18b356f6/lib/model/masks.py#L130) to 255.0 instead of 1.0. Note: The "transparent" pixels in the other masks are also initialized to 255.0 and not 1.0.

**Comment by torzdf** [comment]
This is fixed in latest commit.
