### ISSUE TITLE
FEATURE - Parameters for setup.py

### ISSUE THREAD

**Issue by AlessandroAnnini** [deepfakes/faceswap#730]
FEATURE
I would like to run the setup.py script using a parameters for the docker and the CUDA options so it can run unattended.

CONTEXT
I am requesting this in order to use it on google colaboratory but I don't know how to answer the script's questions.

**Comment by DKingCN** [comment]
This is never an unattended script since it requires manual os dependencies installation as well as cuda/cudnn inatallation.

**Comment by torzdf** [comment]
Google colab is not directly supported, so we're unlikely to put in options to support this.

It *can* be run unattended if run in a conda environment by passing `--installer` and optionally `--gpu` if the tf-gpu version is required. This is an undocumented feature to support the Windows installer.

**Comment by DKingCN** [comment]
I regretted making the stupid script. Too buggy to keep up with  the changes.
@torzdf do you have any thought about the situation in issues list that nearly half open issues are about setup.py? a way to improve the situation. like switching to another env setup solution.

**Comment by torzdf** [comment]
I thought most issues had now been resolved? I'll re-review.

The biggest barrier is getting the location of cuDNN, as Nvidia/various OSes seem to move that around at will. Executing nvcc -V gets the CUDA version across systems, but doesn't support multi-CUDAs... but covering it all off across all OSes is next to impossible.

I'm glad you made the script. It's been a big help, and it probably works fine in 99% of cases. As most users now use the installer, it's fully automated for Conda environments, with no other downloads required.

**Comment by AlessandroAnnini** [comment]
Thanks, the answer is clear, do you know of any service where I could run the setup? Maybe only on a wps? Or Maybe with a docker image: the script could run from the `.dockerfile`..

**Comment by torzdf** [comment]
@AlessandroAnnini You should look into this repo for faceswap on Colab:
https://github.com/seranus/faceswap-notebooks/blob/master/faceswap_trainer.ipynb
