### ISSUE TITLE
Effmpeg not working with Docker installation because Dockerfile does not include an installation of ffmpeg

### ISSUE THREAD

**Issue by timothydelter** [deepfakes/faceswap#731]
Effmpeg does not work with the Docker container because there is no ffmpeg installation.

**Comment by torzdf** [comment]
Honestly? None of the primary devs use docker. It is kept around as it's always been there, and we will accept PRs to fix issues, but none of us are likely to fix this.

**Comment by timothydelter** [comment]
Oh i see, I'll just make a pull request with the fix for the users that might prefer to use Faceswap with Docker. Thanks!
