### ISSUE TITLE
GUI - extract - status bar - progress - UNIT

### ISSUE THREAD

**Issue by nerotiger** [deepfakes/faceswap#733]
When extracting face images from a video, it shows xx "s/it". 

./lib/gui/wrapper.py 
295         processtime = "Elapsed: {}  Remaining: {}".format(tqdm["tme"].split("<")[0],
296                                                           tqdm["tme"].split("<")[1])
297         message = "{}  |  {} *****  |  {}  |  {}".format(processtime,

actrully it is second per frame, as [vedio duration * fps == total images (frames) to extract].
and when reading _tqdm.py / function format_meter, it said we can define UNIT rather than default "it".

 284         unit  : str, optional
 285             The iteration unit [default: 'it'].

Can we pass "frame" to this?

**Comment by torzdf** [comment]
This is unlikely to be implemented.
