### ISSUE TITLE
cv2.imread() returning None, but not caught

### ISSUE THREAD

**Issue by CrossElectronics** [deepfakes/faceswap#734]
**Describe the bug**
At first, I cannot even train the model. As soon as I start training, it crashes and reports an NoneType error (see crash reports at the end). Then I traced from the log, quickly viewed the sourcecode and looked up in the cv2 documentation. I learned that cv2.imread() will not throw anything if failed to read the image. ([See here](https://docs.opencv.org/3.0-beta/doc/py_tutorials/py_gui/py_image_display/py_image_display.html)) Instead, it just returns None, hence the NoneType error. Invalid characters in the file names or paths can easily cause this problem. In my case, that were Chinese characters. It seems Python is not very good at dealing with coding issues.
If the problem cannot be solved, would you please add a check below? I'm not sure if `except TypeError:` works. But `if image is None:` works for sure.

**To Reproduce**
1. Start training with any param
2. If files selected for a batch has some invalid characters in its path or name, program crashes

**Expected behavior**
If possible, please add support to more encodings. If that is technically impossible, add a check to warn users of the file name/path cannot contain invalid characters.

**Screenshots**
![屏幕截图(32)](https://user-images.githubusercontent.com/31400327/58025057-2fb79b80-7b46-11e9-9432-18bdbc3558ce.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Crash report:
[crash_report.2019.05.20.182957704067.log](https://github.com/deepfakes/faceswap/files/3198142/crash_report.2019.05.20.182957704067.log)

**Comment by torzdf** [comment]
This should now be caught and handled in the latest commit.
