### ISSUE TITLE
ERROR    Caught exception in thread: 'training_0'//original type is ok,but any other model cannot succeed

### ISSUE THREAD

**Issue by Jinwanqi** [deepfakes/faceswap#735]
wanqi@amax:~/Desktop/faceswap-master$ python faceswap.py train -A faces/source -B faces/lyf -m models/lyf-128/ -p -t realface
05/22/2019 09:57:53 INFO     Log level set to: INFO
Using TensorFlow backend.
05/22/2019 09:57:57 INFO     Model A Directory: /home/wanqi/Desktop/faceswap-master/faces/source
05/22/2019 09:57:57 INFO     Model B Directory: /home/wanqi/Desktop/faceswap-master/faces/lyf
05/22/2019 09:57:57 INFO     Training data directory: /home/wanqi/Desktop/faceswap-master/models/lyf-128
05/22/2019 09:57:57 INFO     ===============================================
05/22/2019 09:57:57 INFO     - Starting                                    -
05/22/2019 09:57:57 INFO     - Using live preview                          -
05/22/2019 09:57:57 INFO     - Press 'ENTER' to save and quit              -
05/22/2019 09:57:57 INFO     - Press 'S' to save model weights immediately -
05/22/2019 09:57:57 INFO     ===============================================
05/22/2019 09:57:58 INFO     Loading data, this may take a while...
05/22/2019 09:57:58 INFO     Loading Model from Realface plugin...
05/22/2019 09:58:04 WARNING  No existing state file found. Generating.
05/22/2019 09:58:27 INFO     Creating new 'realface' model in folder: '/home/wanqi/Desktop/faceswap-master/models/lyf-128'
05/22/2019 09:58:28 INFO     Loading Trainer from Original plugin...
05/22/2019 09:58:29 CRITICAL Error caught! Exiting...
05/22/2019 09:58:29 ERROR    Caught exception in thread: 'training_0'
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
05/22/2019 09:58:39 ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/home/wanqi/Desktop/faceswap-master/lib/cli.py", line 110, in execute_script
    process.process()
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 98, in process
    self.end_thread(thread, err)
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 123, in end_thread
    thread.join()
  File "/home/wanqi/Desktop/faceswap-master/lib/multithreading.py", line 460, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/home/wanqi/Desktop/faceswap-master/lib/multithreading.py", line 390, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 149, in training
    raise err
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 138, in training
    trainer = self.load_trainer(model)
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 197, in load_trainer
    self.args.batch_size)
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 51, in __init__
    self.process_training_opts()
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 96, in process_training_opts
    landmarks = Landmarks(self.model.training_opts).landmarks
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 604, in __init__
    self.landmarks = self.get_alignments()
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 617, in get_alignments
    serializer=serializer)
  File "/home/wanqi/Desktop/faceswap-master/lib/alignments.py", line 36, in __init__
    self.data = self.load()
  File "/home/wanqi/Desktop/faceswap-master/lib/alignments.py", line 121, in load
    "{}".format(self.file))
ValueError: Error: Alignments file not found at /home/wanqi/Desktop/faceswap-master/faces/source/alignments.json
05/22/2019 09:58:39 CRITICAL An unexpected crash has occurred. Crash report written to /home/wanqi/Desktop/faceswap-master/crash_report.2019.05.22.095829236316.log. Please verify you are running the latest version of faceswap before reporting

05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE                                                                   leaky_re_lu_60[0][0]
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  __________________________________________________________________________________________________
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  leaky_re_lu_63 (LeakyReLU)      (None, 8, 8, 512)    0           add_14[0][0]
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  __________________________________________________________________________________________________
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  conv2d_54 (Conv2D)              (None, 4, 4, 1024)   13108224    leaky_re_lu_63[0][0]
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  __________________________________________________________________________________________________
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  leaky_re_lu_64 (LeakyReLU)      (None, 4, 4, 1024)   0           conv2d_54[0][0]
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  ==================================================================================================
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  Total params: 29,604,608
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  Trainable params: 29,604,608
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  Non-trainable params: 0
05/22/2019 09:58:28 MainProcess     training_0      _base           <lambda>                  VERBOSE  __________________________________________________________________________________________________
05/22/2019 09:58:28 MainProcess     training_0      _base           compile_predictors        DEBUG    Compiling Predictors
05/22/2019 09:58:28 MainProcess     training_0      _base           get_optimizer             DEBUG    Optimizer kwargs: {'lr': 5e-05, 'beta_1': 0.5, 'beta_2': 0.999}
05/22/2019 09:58:28 MainProcess     training_0      _base           loss_function             VERBOSE  Using DSSIM Loss
05/22/2019 09:58:28 MainProcess     training_0      _base           loss_function             VERBOSE  Penalizing mask for Loss
05/22/2019 09:58:28 MainProcess     training_0      _base           mask_loss_function        VERBOSE  Using Mean Squared Error Loss for mask
05/22/2019 09:58:28 MainProcess     training_0      _base           add_session_loss_names    DEBUG    Adding session loss_names. (side: 'a', loss_names: ['total_loss', 'loss', 'mask_loss']
05/22/2019 09:58:28 MainProcess     training_0      _base           add_session_loss_names    DEBUG    Adding session loss_names. (side: 'b', loss_names: ['total_loss', 'loss', 'mask_loss']
05/22/2019 09:58:28 MainProcess     training_0      _base           compile_predictors        DEBUG    Compiled Predictors. Losses: ['total_loss', 'loss', 'mask_loss']
05/22/2019 09:58:28 MainProcess     training_0      _base           set_training_data         DEBUG    Setting training data
05/22/2019 09:58:28 MainProcess     training_0      _base           calculate_coverage_ratio  DEBUG    Requested coverage_ratio: 0.625
05/22/2019 09:58:28 MainProcess     training_0      _base           calculate_coverage_ratio  DEBUG    Final coverage_ratio: 0.625
05/22/2019 09:58:28 MainProcess     training_0      _base           set_training_data         DEBUG    Set training data: {'alignments': {'a': '/home/wanqi/Desktop/faceswap-master/faces/source/alignments.json', 'b': '/home/wanqi/Desktop/faceswap-master/faces/lyf/alignments.json'}, 'preview_scaling': 0.5, 'warp_to_landmarks': False, 'no_flip': False, 'pingpong': False, 'training_size': 256, 'no_logs': False, 'mask_type': 'components', 'coverage_ratio': 0.625, 'preview_images': 14}
05/22/2019 09:58:28 MainProcess     training_0      _base           __init__                  DEBUG    Initialized ModelBase (Model)
05/22/2019 09:58:28 MainProcess     training_0      realface        __init__                  DEBUG    Initialized Model
05/22/2019 09:58:28 MainProcess     training_0      train           load_model                DEBUG    Loaded Model
05/22/2019 09:58:28 MainProcess     training_0      train           load_trainer              DEBUG    Loading Trainer
05/22/2019 09:58:28 MainProcess     training_0      plugin_loader   _import                   INFO     Loading Trainer from Original plugin...
05/22/2019 09:58:28 MainProcess     training_0      _base           __init__                  DEBUG    Initializing TrainerBase: (model: '<plugins.train.model.realface.Model object at 0x7f233af0e0b8>', batch_size: 64)
05/22/2019 09:58:28 MainProcess     training_0      _base           add_session_batchsize     DEBUG    Adding session batchsize: 64
05/22/2019 09:58:28 MainProcess     training_0      _base           process_training_opts     DEBUG    {'alignments': {'a': '/home/wanqi/Desktop/faceswap-master/faces/source/alignments.json', 'b': '/home/wanqi/Desktop/faceswap-master/faces/lyf/alignments.json'}, 'preview_scaling': 0.5, 'warp_to_landmarks': False, 'no_flip': False, 'pingpong': False, 'training_size': 256, 'no_logs': False, 'mask_type': 'components', 'coverage_ratio': 0.625, 'preview_images': 14}
05/22/2019 09:58:28 MainProcess     training_0      _base           landmarks_required        DEBUG    True
05/22/2019 09:58:28 MainProcess     training_0      _base           __init__                  DEBUG    Initializing Landmarks: (training_opts: '{'alignments': {'a': '/home/wanqi/Desktop/faceswap-master/faces/source/alignments.json', 'b': '/home/wanqi/Desktop/faceswap-master/faces/lyf/alignments.json'}, 'preview_scaling': 0.5, 'warp_to_landmarks': False, 'no_flip': False, 'pingpong': False, 'training_size': 256, 'no_logs': False, 'mask_type': 'components', 'coverage_ratio': 0.625, 'preview_images': 14}')
05/22/2019 09:58:28 MainProcess     training_0      alignments      __init__                  DEBUG    Initializing Alignments: (folder: '/home/wanqi/Desktop/faceswap-master/faces/source', filename: 'alignments', serializer: 'json')
05/22/2019 09:58:28 MainProcess     training_0      alignments      get_serializer            DEBUG    Getting serializer: (filename: 'alignments', serializer: 'json')
05/22/2019 09:58:28 MainProcess     training_0      alignments      get_serializer            DEBUG    Serializer set from argument: 'json'
05/22/2019 09:58:28 MainProcess     training_0      alignments      get_serializer            VERBOSE  Using 'json' serializer for alignments
05/22/2019 09:58:28 MainProcess     training_0      alignments      get_location              DEBUG    Getting location: (folder: '/home/wanqi/Desktop/faceswap-master/faces/source', filename: 'alignments')
05/22/2019 09:58:28 MainProcess     training_0      alignments      get_location              DEBUG    File extension set from serializer: 'json'
05/22/2019 09:58:28 MainProcess     training_0      alignments      get_location              VERBOSE  Alignments filepath: '/home/wanqi/Desktop/faceswap-master/faces/source/alignments.json'
05/22/2019 09:58:28 MainProcess     training_0      alignments      load                      DEBUG    Loading alignments
05/22/2019 09:58:28 MainProcess     training_0      multithreading  run                       DEBUG    Error in thread (training_0): Error: Alignments file not found at /home/wanqi/Desktop/faceswap-master/faces/source/alignments.json
05/22/2019 09:58:29 MainProcess     MainThread      train           monitor                   DEBUG    Thread error detected
05/22/2019 09:58:29 MainProcess     MainThread      train           monitor                   DEBUG    Closed Monitor
05/22/2019 09:58:29 MainProcess     MainThread      train           end_thread                DEBUG    Ending Training thread
05/22/2019 09:58:29 MainProcess     MainThread      train           end_thread                CRITICAL Error caught! Exiting...
05/22/2019 09:58:29 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'training'
05/22/2019 09:58:29 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'training_0'
05/22/2019 09:58:29 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: 'training_0'
Traceback (most recent call last):
  File "/home/wanqi/Desktop/faceswap-master/lib/cli.py", line 110, in execute_script
    process.process()
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 98, in process
    self.end_thread(thread, err)
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 123, in end_thread
    thread.join()
  File "/home/wanqi/Desktop/faceswap-master/lib/multithreading.py", line 460, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/home/wanqi/Desktop/faceswap-master/lib/multithreading.py", line 390, in run
    self._target(*self._args, **self._kwargs)
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 149, in training
    raise err
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 138, in training
    trainer = self.load_trainer(model)
  File "/home/wanqi/Desktop/faceswap-master/scripts/train.py", line 197, in load_trainer
    self.args.batch_size)
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 51, in __init__
    self.process_training_opts()
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 96, in process_training_opts
    landmarks = Landmarks(self.model.training_opts).landmarks
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 604, in __init__
    self.landmarks = self.get_alignments()
  File "/home/wanqi/Desktop/faceswap-master/plugins/train/trainer/_base.py", line 617, in get_alignments
    serializer=serializer)
  File "/home/wanqi/Desktop/faceswap-master/lib/alignments.py", line 36, in __init__
    self.data = self.load()
  File "/home/wanqi/Desktop/faceswap-master/lib/alignments.py", line 121, in load
    "{}".format(self.file))
ValueError: Error: Alignments file not found at /home/wanqi/Desktop/faceswap-master/faces/source/alignments.json

============ System Information ============
encoding:            ANSI_X3.4-1968
git_branch:          Not Found
git_commits:         Not Found
gpu_cuda:            8.0
gpu_cudnn:           Not Found. Check Conda packages for Conda cuDNN
gpu_devices:         GPU_0: Tesla K80, GPU_1: Tesla K80, GPU_2: Tesla K80, GPU_3: Tesla K80, GPU_4: Tesla K80, GPU_5: Tesla K80, GPU_6: Tesla K80, GPU_7: Tesla K80, GPU_8: Tesla K80, GPU_9: Tesla K80
gpu_devices_active:  GPU_0, GPU_1, GPU_2, GPU_3, GPU_4, GPU_5, GPU_6, GPU_7, GPU_8, GPU_9
gpu_driver:          375.66
gpu_vram:            GPU_0: 11439MB, GPU_1: 11439MB, GPU_2: 11439MB, GPU_3: 11439MB, GPU_4: 11439MB, GPU_5: 11439MB, GPU_6: 11439MB, GPU_7: 11439MB, GPU_8: 11439MB, GPU_9: 11439MB
os_machine:          x86_64
os_platform:         Linux-3.19.0-80-generic-x86_64-with-debian-jessie-sid
os_release:          3.19.0-80-generic
py_command:          faceswap.py train -A faces/source -B faces/lyf -m models/lyf-128/ -p -t realface
py_conda_version:    conda 4.6.14
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           40
sys_processor:       x86_64
sys_ram:             Total: 257847MB, Available: 204245MB, Used: 41256MB, Free: 44618MB

=============== Pip Packages ===============
absl-py==0.6.1
alabaster==0.7.10
alfred==0.2
alfred-py==2.4.8
anaconda-client==1.6.14
anaconda-navigator==1.9.7
anaconda-project==0.8.2
ansimarkup==1.4.0
asn1crypto==0.24.0
astor==0.7.1
astroid==1.6.3
astropy==3.0.2
attrs==18.1.0
Babel==2.5.3
backcall==0.1.0
backports.shutil-get-terminal-size==1.0.0
backports.weakref==1.0rc1
beautifulsoup4==4.6.0
better-exceptions-fork==0.2.1.post6
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==2.1.3
blessings==1.7
bokeh==0.12.16
boto==2.48.0
Bottleneck==1.2.1
certifi==2019.3.9
cffi==1.11.5
chardet==3.0.4
click==6.7
cloudpickle==0.5.3
clyent==1.2.2
colorama==0.3.9
conda==4.6.14
conda-build==3.10.5
conda-verify==2.0.0
contextlib2==0.5.5
cryptography==2.4.2
cycler==0.10.0
Cython==0.28.2
cytoolz==0.9.0.1
dask==0.17.5
datashape==0.5.4
decorator==4.3.0
Deprecated==1.2.5
distributed==1.21.8
dlib==19.17.0
docutils==0.14
entrypoints==0.2.3
et-xmlfile==1.0.1
face-recognition==1.2.3
face-recognition-models==0.3.0
fastcache==1.0.2
fastcluster==1.1.25
ffmpeg==1.4
ffmpy==0.2.2
filelock==3.0.4
Flask==1.0.2
Flask-Cors==3.0.4
future==0.17.1
gast==0.2.1
gevent==1.3.0
glob2==0.6
gmpy2==2.0.8
gpustat==0.5.0
greenlet==0.4.13
grpcio==1.16.1
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
idna==2.6
imageio==2.3.0
imageio-ffmpeg==0.3.0
imagesize==1.0.0
ipykernel==4.8.2
ipython==6.4.0
ipython-genutils==0.2.0
ipywidgets==7.2.1
isort==4.3.4
itsdangerous==0.24
jdcal==1.4
jedi==0.12.0
Jinja2==2.10
joblib==0.13.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.3
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.32.1
jupyterlab-launcher==0.10.5
Keras==2.2.4
Keras-Applications==1.0.7
Keras-Preprocessing==1.0.9
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
leveldb==0.20
llvmlite==0.23.1
lmdb==0.94
locket==0.2.0
loguru==0.2.5
lxml==4.2.1
Markdown==3.0.1
MarkupSafe==1.0
matplotlib==2.2.2
mccabe==0.6.1
mistune==0.8.3
mkl-fft==1.0.12
mkl-random==1.0.2
mock==2.0.0
more-itertools==4.1.0
mpmath==1.0.0
msgpack==0.6.1
msgpack-python==0.5.6
multipledispatch==0.5.0
navigator-updater==0.2.1
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.1
nltk==3.3
nose==1.3.7
notebook==5.5.0
numba==0.38.0
numexpr==2.6.9
numpy==1.16.2
numpydoc==0.8.0
nvidia-ml-py3==7.352.0
odo==0.5.1
olefile==0.45.1
opencv-contrib-python==4.0.0.21
opencv-python==4.1.0.25
openpyxl==2.5.3
packaging==17.1
pandas==0.23.0
pandocfilters==1.4.2
parso==0.2.0
partd==0.3.8
path.py==11.0.1
pathlib==1.0.1
pathlib2==2.3.2
patsy==0.5.0
pbr==5.1.3
pep8==1.7.1
pexpect==4.5.0
pickleshare==0.7.4
Pillow==6.0.0
pkginfo==1.4.2
pluggy==0.6.0
ply==3.11
prometheus-client==0.4.2
prompt-toolkit==1.0.15
protobuf==3.6.1
psutil==5.6.2
ptyprocess==0.5.2
py==1.5.3
pycocotools==2.0
pycodestyle==2.4.0
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0.2
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.8.4
pyodbc==4.0.23
pyOpenSSL==18.0.0
pyparsing==2.2.0
PySocks==1.6.8
pytest==3.5.1
pytest-arraydiff==0.2
pytest-astropy==0.3.0
pytest-doctestplus==0.1.3
pytest-openfiles==0.3.0
pytest-remotedata==0.2.1
python-dateutil==2.7.3
python-gflags==3.1.2
pytz==2018.4
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==17.0.0
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.4.1
requests==2.18.4
rope==0.10.7
ruamel-yaml==0.15.35
scandir==1.5
scikit-image==0.15.0
scikit-learn==0.21.1
scipy==1.2.1
seaborn==0.8.1
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.6.1
sortedcontainers==1.5.10
Sphinx==1.7.4
sphinxcontrib-websupport==1.0.1
spyder==3.2.8
SQLAlchemy==1.2.7
statsmodels==0.9.0
sympy==1.1.1
tables==3.4.3
tblib==1.3.2
tensorboard==1.12.2
tensorflow==1.12.0
tensorflow-estimator==1.13.0
tensorflow-tensorboard==1.5.1
termcolor==1.1.0
terminado==0.8.1
testpath==0.3.1
toolz==0.9.0
toposort==1.5
torch==1.0.1
tornado==5.0.2
tqdm==4.31.1
traitlets==4.3.2
typing==3.6.4
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
web.py==0.40.dev0
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.2.1
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.4
xlwt==1.3.0
zict==0.1.3

============== Conda Packages ==============
# packages in environment at /home/wanqi/anaconda3/envs/chineseocr:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0  
astor                     0.7.1                    py36_0  
backcall                  0.1.0                    py36_0  
backports                 1.0                      py36_1  
backports.weakref         1.0rc1                   py36_0  
blas                      1.0                         mkl  
bleach                    1.5.0                    py36_0  
bzip2                     1.0.6                h14c3975_5  
c-ares                    1.15.0               h7b6447c_1  
ca-certificates           2019.1.23                     0  
cairo                     1.14.12              h8948797_3  
certifi                   2019.3.9                 py36_0  
cffi                      1.11.5           py36he75722e_1  
cloudpickle               1.0.0                      py_0  
cudatoolkit               9.0                  h13b8566_0  
cudnn                     7.3.1                 cuda9.0_0  
cupti                     9.0.176                       0  
cycler                    0.10.0                   py36_0  
cytoolz                   0.9.0.1          py36h14c3975_1  
dask-core                 1.2.2                      py_0  
dbus                      1.13.2               h714fa37_1  
decorator                 4.3.0                    py36_0  
entrypoints               0.2.3                    py36_2  
expat                     2.2.6                he6710b0_0  
ffmpeg                    4.0                  hcdf2ecd_0  
fontconfig                2.13.0               h9420a91_0  
freeglut                  3.0.0                hf484d3e_5  
freetype                  2.9.1                h8a8886c_1  
gast                      0.2.2                    py36_0  
glib                      2.56.2               hd408876_0  
gmp                       6.1.2                h6c8ec71_1  
graphite2                 1.3.13               h23475e2_0  
grpcio                    1.16.1           py36hf8bcb03_1  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.9.0            py36h7918eee_0  
harfbuzz                  1.8.8                hffaf4a1_0  
hdf5                      1.10.4               hb1b8bf9_0  
html5lib                  0.9999999                py36_0  
icu                       58.2                 h9c2bf20_1  
imageio                   2.5.0                    py36_0  
intel-openmp              2019.0                      118  
ipykernel                 5.1.0            py36h39e3cac_0  
ipython                   7.1.1            py36h39e3cac_0  
ipython_genutils          0.2.0                    py36_0  
ipywidgets                7.4.2                    py36_0  
jasper                    2.0.14               h07fcdf6_1  
jedi                      0.13.1                   py36_0  
jinja2                    2.10                     py36_0  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   h024ee3a_2  
jsonschema                2.6.0                    py36_0  
jupyter                   1.0.0                    py36_7  
jupyter_client            5.2.3                    py36_0  
jupyter_console           6.0.0                    py36_0  
jupyter_core              4.4.0                    py36_0  
keras-applications        1.0.7                      py_0  
keras-base                2.2.4                    py36_0  
keras-gpu                 2.2.4                         0  
keras-preprocessing       1.0.9                      py_0  
kiwisolver                1.1.0            py36he6710b0_0  
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                hd88cf55_4  
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran               3.0.0                         1  
libgfortran-ng            7.3.0                hdf63c60_0  
libglu                    9.0.0                hf484d3e_1  
libopenblas               0.3.3                h5a2b251_3  
libopus                   1.3                  h7b6447c_0  
libpng                    1.6.35               hbc83047_0  
libprotobuf               3.7.1                hd408876_0  
libsodium                 1.0.16               h1bed415_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
libtiff                   4.0.10               h2733197_2  
libuuid                   1.0.3                h1bed415_2  
libvpx                    1.7.0                h439df22_0  
libxcb                    1.13                 h1bed415_1  
libxml2                   2.9.8                h26e45fe_1  
markdown                  3.1                      py36_0  
markupsafe                1.0              py36h14c3975_1  
matplotlib                2.2.2            py36hb69df0a_2  
mistune                   0.8.4            py36h7b6447c_0  
mkl                       2019.3                      199  
mkl_fft                   1.0.12           py36ha843d7b_0  
mkl_random                1.0.2            py36hd81dba3_0  
mock                      2.0.0                    py36_0  
nbconvert                 5.3.1                    py36_0  
nbformat                  4.4.0                    py36_0  
nccl                      1.3.5                 cuda9.0_0  
ncurses                   6.1                  hf484d3e_0  
networkx                  2.3                        py_0  
ninja                     1.9.0            py36hfd86e86_0  
notebook                  5.7.0                    py36_0  
numpy                     1.16.3           py36h7e9f1db_0  
numpy-base                1.16.3           py36hde5b4d6_0  
olefile                   0.46                     py36_0  
openblas                  0.2.19                        0  
openssl                   1.1.1b               h7b6447c_1  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py36_1  
parso                     0.3.1                    py36_0  
pathlib                   1.0.1                    py36_1  
pbr                       5.1.3                      py_0  
pcre                      8.42                 h439df22_0  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.5                    py36_0  
pillow                    6.0.0            py36h34e0f95_0  
pip                       18.1                     py36_0  
pixman                    0.38.0               h7b6447c_0  
prometheus_client         0.4.2                    py36_0  
prompt_toolkit            2.0.7                    py36_0  
protobuf                  3.7.1            py36he6710b0_0  
psutil                    5.6.2            py36h7b6447c_0  
ptyprocess                0.6.0                    py36_0  
pycparser                 2.19                     py36_0  
pygments                  2.2.0                    py36_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py36h05f1152_2  
python                    3.6.8                h0371630_0  
python-dateutil           2.7.5                    py36_0  
pytorch                   1.0.1           cuda90py36h8b0c50b_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py36hdd07704_1  
pyyaml                    5.1              py36h7b6447c_0  
pyzmq                     17.1.2           py36h14c3975_0  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.4.2                    py36_0  
readline                  7.0                  h7b6447c_5  
scikit-image              0.15.0           py36he6710b0_0  
scikit-learn              0.21.1           py36hd81dba3_0  
scipy                     1.2.1            py36h7c811a0_0  
send2trash                1.5.0                    py36_0  
setuptools                40.5.0                   py36_0  
sip                       4.19.8           py36hf484d3e_0  
six                       1.11.0                   py36_1  
sqlite                    3.26.0               h7b6447c_0  
tensorboard               1.12.2           py36he6710b0_0  
tensorflow                1.12.0          gpu_py36he68c306_0  
tensorflow-base           1.12.0          gpu_py36h8e0ae2d_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.12.0               h0d30ee6_0  
tensorflow-gpu-base       1.7.0            py36hcdda91b_1  
tensorflow-tensorboard    1.5.1            py36hf484d3e_1  
termcolor                 1.1.0                    py36_1  
terminado                 0.8.1                    py36_1  
testpath                  0.4.2                    py36_0  
tk                        8.6.8                hbc83047_0  
toolz                     0.9.0                    py36_0  
tornado                   5.1.1            py36h7b6447c_0  
tqdm                      4.31.1                   py36_1  
traitlets                 4.3.2                    py36_0  
wcwidth                   0.1.7                    py36_0  
webencodings              0.5.1                    py36_1  
werkzeug                  0.15.2                     py_0  
wheel                     0.32.2                   py36_0  
widgetsnbextension        3.4.2                    py36_0  
xz                        5.2.4                h14c3975_4  
yaml                      0.1.7                had09818_2  
zeromq                    4.2.5                hf484d3e_1  
zlib                      1.2.11               ha838bed_2  
zstd                      1.3.7                h0b5b093_0

**Comment by kvrooman** [comment]
ValueError: Error: Alignments file not found at /home/wanqi/Desktop/faceswap-master/faces/source/alignments.json

You specified an alignment file that does not exist apparently...
Likely, the Original model is not using a mask in your config file, but all the other models are setup to use a mask and thus need the alignment file.

**Comment by Kirin-kun** [comment]
Villain does not need a mask either.

Though it's really memory hungry, I found it's the best model out of all of them.

**Comment by Kirin-kun** [comment]
And 10 GPU?

Using a mining rig to faceswap? xD
