### ISSUE TITLE
can I only train model B？because I only need face A swap to B.

### ISSUE THREAD

**Issue by zuijiu997** [deepfakes/faceswap#738]
can I only train model B？because I only want to face A swap to B. if both train model A and B，it will be waste the GPU and other resource

**Comment by torzdf** [comment]
Please raise these kinds of questions in Faceswap Playground or the Discord Server

**Comment by bryanlyon** [comment]
While yes, torzdf is right.  The short answer is no you can't.  Both are required to train even one-way swaps.
