### ISSUE TITLE
unable to open image . Skipping 'xxxx.png' when extract from mp4 video

### ISSUE THREAD

**Issue by yaozhou** [deepfakes/faceswap#741]
II'm working on nvidia-docker , ubuntu16.04 cuda9.0 tensorflow 1.12.0 gpu, python3.5.2 when I extract images from video , use

python3 faceswap.py extract -i src/xxxx.mp4 -o out/xxx/

 I got  this warning.
'Unable to open image. Skipping: xxxx.png',  and then I check the output path, there are nothing in it.
Is there something wrong with my docker ?  But I can create file in the output path in docker.

Could someone help?

Thanks

**Comment by torzdf** [comment]
We use opencv for extracting from videos, and it only supports a limited number of codecs. Most likely, it does not support the codec that your mp4 is encoded in.

We may look to change this in future, but in the meantime you should look to use the effmpeg tool to split your video into separate frames.

**Comment by yaozhou** [comment]
OK, I'll try the ffmpeg, thanks again.

**Comment by torzdf** [comment]
We have now switched to ImageIO for reading videos in, so hopefully that has resolved this issue.

Please raise a new issue if it persists.
