### ISSUE TITLE
ModuleNotFoundError: No module named 'cv2.cv2'

### ISSUE THREAD

**Issue by Hobeam** [deepfakes/faceswap#744]
**Describe the bug**
Opencv import error
Version opencv-python==4.1.0.25
ModuleNotFoundError: No module named 'cv2.cv2'

**To Reproduce**
1. I create new envirment with anaconda and run setup.py
2. Run faceswap.py
3. Process stop in line  " from .cv2 import *  "

**Desktop (please complete the following information):**
 - OS: win10

**Additional context**
I fix this problem that down-grade opencv-python version 4.0.1.23
In command line "pip install opencv-python==4.0.1.23"
And it works very well
Thank you

**Comment by Hobeam** [comment]
Also fastcluster module has same import problem
Down-grade to fastcluster==1.1.24 (newist is 1.1.25)

**Comment by torzdf** [comment]
This is likely to be a problem somewhere else in your setup. Probably a conflict.

I run: 
fastcluster==1.1.25
opencv-python==4.1.0.25

with zero issues.

**Comment by obiwankenoobi** [comment]
try `pip3 install opencv-python`
