### ISSUE TITLE
Cannot connect to server X

### ISSUE THREAD

**Issue by JPFrancoia** [deepfakes/faceswap#745]
I'm trying to run the training step on an Amazon EC2 instance with gpu. I installed faceswap with the command:

```
python setup.py install
```

I don't use docker. I use tensor flow 1.12, with the appropriate version of CUDA and cudnn.

I run the training step with:

```
python faceswap.py train -w -A faces/someone1 -B faces/someone2 -m models -p
```

If I run it as is, the training start, but as soon as it's supposed to refresh the preview, I get:

```
cannot connect to server x loss_A: 0.06808
```

One loss is printed. If I slightly modify the `scripts/train.py` file from:

```python
        if self.args.write_image or self.args.redirect_gui or self.args.preview:
            display_func = self.show
        else:
            display_func = None
```

to:

```python
        display_func = None
```

I can run the training without problem. But I the preview image isn't written to disk.

Any idea how I could solve this? It's also hard to debug, because when this happen, I loose the prompt on my ssh session.

**Comment by torzdf** [comment]
Use the -w flag

**Comment by JPFrancoia** [comment]
You misread the issue. I do use the -w flag. Please re-open.

**Comment by torzdf** [comment]
The file is written to the root of the faceswap folder. This definitely works. It may be a permissions issue on aws which is not directly supported by this project

**Comment by torzdf** [comment]
You may have better luck getting help in the discord server

**Comment by JPFrancoia** [comment]
It's definitely not a permission problem. The script would crash on an OSError. Also I can read/write in this folder. Also the image is generated at the very beginning of the process. Writing to the image works.

The code tries to render something at some point. I might try on the discord server later, but I would like a confirmation first that the training works on a remote server with a X server, because I don't think it's specific to AWS.

**Comment by torzdf** [comment]
You mean ssh tunneling with x forwarding? Yes it does. Many people run it this way, myself included (from a headless linux box)

**Comment by JPFrancoia** [comment]
ah, see, I don't do the X forwarding. I just ssh through the command line, there is no X at all here :).
I thought I would just scp the preview image when it's written to disk.

So, do you confirm the script absolutely needs a X to run?

**Comment by torzdf** [comment]
No, it definitely doesn't need X to run.

There are certainly people in the Discord who run on Google Collab, so I would imagine that AWS would work too, and some people may have done it.
