### ISSUE TITLE
[help needed] Why do we use random_warp to create distorted images?

### ISSUE THREAD

**Issue by zikuicai** [deepfakes/faceswap#748]
I have noticed that many faceswap projects use distorted images as conditional information. But why do we need the distorted images in the generation process? Can anyone help me to understand this practice? Many thanks in advance!

**Comment by torzdf** [comment]
Please post these kind of questions in faceswap playground or the Discord server

**Comment by zikuicai** [comment]
Thanks for referring. I found the answer there.

**Comment by deyu260** [comment]
> Thanks for referring. I found the answer there.

please tell me the answer

**Comment by zikuicai** [comment]
@deyu260  Sorry for the late reply. Here is the link:
https://github.com/deepfakes/faceswap-playground/issues/168#issuecomment-391056247
