### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by xuyue101012** [deepfakes/faceswap#751]
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "<frozen importlib._bootstrap>", line 980, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import

**Comment by torzdf** [comment]
Almost definitely a conflict with a pre-installed python version. Check your environment and system installed pythons.

**Comment by xuyue101012** [comment]
I used python3.7.3,must be use python3.6?

**Comment by torzdf** [comment]
Yes,

**Comment by xuyue101012** [comment]
Thanks
