### ISSUE TITLE
whether the model building process is in correct state?

### ISSUE THREAD

**Issue by Royalways** [deepfakes/faceswap#758]
**Describe the bug**
Console capture of model building as below, and the process paused here for more than 10 mins until I cancel
![image](https://user-images.githubusercontent.com/28914921/59351113-3b1a7300-8d50-11e9-9b90-707a2bac4db7.png)

result by using the model
![donald_trump_wallpaper_14](https://user-images.githubusercontent.com/28914921/59352269-d44a8900-8d52-11e9-8001-d39626e6ed7f.png)

a related info is that number of the source faces is only about 70, which may be the reason, that sample is too small

**Comment by gessyoo** [comment]
@Royalways, you need to train with a much larger data set (500 to 3,000 images) and you need to train the model longer (days of training, 24 to 48 hours or more).

**Comment by Royalways** [comment]
@gessyoo Thanks for your reply, and the small sample is one problem, another one may be the model building. I am not sure if the model building is okay. Do you have any console snapshot of model building which ended successfully? if you do, can you show me here?

**Comment by gessyoo** [comment]
This area is for reporting bugs in the code, not for tutorials on how to use the program.  Post questions in faceswap playground, or visit the discord server.

**Comment by Royalways** [comment]
@gessyoo so sorry for my mistake
