### ISSUE TITLE
i have got a problem when i use the newest version

### ISSUE THREAD

**Issue by aaronkingdom** [deepfakes/faceswap#760]
hi guys, this is my probelm:
  
File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node fa/convolution (defined at D:\faceswap\plugins\extract\align\fan.py:208)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fa/Pad, fa/split)]]
	 [[{{node fa/transpose_647/_3}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2785_fa/transpose_647", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'fa/convolution', defined at:
  File "<string>", line 1, in <module>
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\multiprocessing\spawn.py", line 118, in _main
    return self._bootstrap()
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\faceswap\lib\multithreading.py", line 360, in run
    super().run()
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\faceswap\plugins\extract\align\_base.py", line 106, in run
    self.align(*args, **kwargs)
  File "D:\faceswap\plugins\extract\align\_base.py", line 121, in align
    self.initialize(*args, **kwargs)
  File "D:\faceswap\plugins\extract\align\fan.py", line 41, in initialize
    self.model = FAN(self.model_path, ratio=tf_ratio)
  File "D:\faceswap\plugins\extract\align\fan.py", line 193, in __init__
    self.graph = self.load_graph()
  File "D:\faceswap\plugins\extract\align\fan.py", line 208, in load_graph
    self.tf.import_graph_def(graph_def, name="fa")
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 442, in import_graph_def
    _ProcessNewOps(graph)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\importer.py", line 234, in _ProcessNewOps
    for new_op in graph._add_new_tf_operations(compute_devices=False):  # pylint: disable=protected-access
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3440, in _add_new_tf_operations
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3440, in <listcomp>
    for c_op in c_api_util.new_tf_operations(self)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 3299, in _create_op_from_tf_operation
    ret = Operation(c_op, self)
  File "C:\Users\Administrator\MiniConda3\envs\faceswap\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

UnknownError (see above for traceback): Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node fa/convolution (defined at D:\faceswap\plugins\extract\align\fan.py:208)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fa/Pad, fa/split)]]
	 [[{{node fa/transpose_647/_3}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_2785_fa/transpose_647", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Traceback (most recent call last):
  File "D:\faceswap\lib\cli.py", line 110, in execute_script
    process.process()
  File "D:\faceswap\scripts\extract.py", line 58, in process
    self.run_extraction()
  File "D:\faceswap\scripts\extract.py", line 177, in run_extraction
    self.extractor.launch()
  File "D:\faceswap\plugins\extract\pipeline.py", line 147, in launch
    self.launch_aligner()
  File "D:\faceswap\plugins\extract\pipeline.py", line 182, in launch_aligner
    raise ValueError("Error initializing Aligner")
ValueError: Error initializing Aligner

============ System Information ============
encoding:            cp936
git_branch:          master
git_commits:         d447c7d Bugfixes
gpu_cuda:            9.0
gpu_cudnn:           7.0.5
gpu_devices:         
gpu_devices_active:  
gpu_driver:          No Nvidia driver found
gpu_vram:            
os_machine:          AMD64
os_platform:         Windows-10-10.0.17763-SP0
os_release:          10
py_command:          D:\faceswap\faceswap.py extract -i C:/Users/Administrator/Desktop/deepfakes AI换脸/w/A.flv -o C:/Users/Administrator/Desktop/deepfakes AI换脸/w/a -l 0.4 --serializer json -D mtcnn -A fan -bt 0.0 -sz 256 -min 0 -een 1 -si 0 -L INFO -gui
py_conda_version:    conda 4.5.12
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           12
sys_processor:       Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
sys_ram:             Total: 32640MB, Available: 19087MB, Used: 13552MB, Free: 19087MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.7.1
certifi==2019.3.9
cloudpickle==1.1.1
cycler==0.10.0
cytoolz==0.9.0.1
dask==1.2.2
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.0
olefile==0.46
opencv-python==4.1.0.25
pathlib==1.0.1
Pillow==6.0.0
protobuf==3.8.0
psutil==5.6.2
pyparsing==2.4.0
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
PyYAML==5.1
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.2.1
six==1.12.0
tensorboard==1.12.2
tensorflow==1.12.0
tensorflow-estimator==1.13.0
termcolor==1.1.0
toolz==0.9.0
toposort==1.5
tornado==6.0.2
tqdm==4.32.1
Werkzeug==0.15.4
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Users\Administrator\MiniConda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.1.0                       gpu  
absl-py                   0.7.1                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.3.9                 py36_0  
cloudpickle               1.1.1                      py_0  
cudatoolkit               9.0                           1  
cudnn                     7.6.0                 cuda9.0_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.9.0.1          py36hfa6e2cd_1  
dask-core                 1.2.2                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25                    <pip>
ffmpeg                    4.1.3                h6538335_0    conda-forge
ffmpy                     0.2.2                     <pip>
freetype                  2.9.1                ha9979f8_1  
gast                      0.2.2                    py36_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                     <pip>
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9b                   hb83a4c4_2  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libmklml                  2019.0.3                      0  
libpng                    1.6.37               h2a8f88b_0  
libprotobuf               3.8.0                h7bd577a_0  
libtiff                   4.0.10               hb898794_2  
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.0.2            py36he774522_0  
mkl_fft                   1.0.12           py36h14836fe_0  
mkl_random                1.0.2            py36h343c172_0  
mock                      3.0.5                    py36_0  
networkx                  2.3                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.0                   <pip>
olefile                   0.46                     py36_0  
opencv-python             4.1.0.25                  <pip>
openssl                   1.1.1c               he774522_1  
pathlib                   1.0.1                    py36_1  
pillow                    6.0.0            py36hdc69c19_0  
pip                       19.1.1                   py36_0  
protobuf                  3.8.0            py36h33f27b4_0  
psutil                    5.6.2            py36he774522_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py36h8c2d366_1  
pyyaml                    5.1              py36he774522_0  
qt                        5.9.7            vc14h73c81de_0  
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.2           py36h6288b17_0  
scipy                     1.2.1            py36h29ff71c_0  
setuptools                41.0.1                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.28.0               he774522_0  
tensorboard               1.12.2           py36h33f27b4_0  
tensorflow                1.12.0          gpu_py36ha5f9131_0  
tensorflow-base           1.12.0          gpu_py36h6e53903_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.12.0               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.9.0                    py36_0  
toposort                  1.5                       <pip>
tornado                   6.0.2            py36he774522_0  
tqdm                      4.32.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
xz                        5.2.4                h2fa13f4_4  
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11               h62dcd97_3  
zstd                      1.3.7                h508b16e_0  

the gpu not working, too

**Comment by torzdf** [comment]
cuDNN didn't initialize because it can't find your GPU. Check your drivers. This is a system issue, not a Faceswap Issue.

**Comment by aaronkingdom** [comment]
ok, thank you.   i use the newest installer i think everything is ok when i finish...
