### ISSUE TITLE
Error thrown when converting

### ISSUE THREAD

**Issue by olie304** [deepfakes/faceswap#763]
When converting, the error
`(-215:Assertion failed) !ssize.empty() in function 'cv::resize'`
occurs at
`faceswap\plugins\extract\align\cv2_dnn.py, line 85, in align_image interpolation=interpolation)`
and it fails. Full stack trace and system info here: https://gist.github.com/olie304/7e23000c9067588b6ea90fabd43623be
I'm using this in Anaconda.

**Comment by torzdf** [comment]
I'm hoping that moving CV2-DNN detection from pooled process to spawned process has fixed this issue.

Please open a new issue if the problem persists.
