### ISSUE TITLE
Invalid directory name

### ISSUE THREAD

**Issue by AaIiMm** [deepfakes/faceswap#766]
hi, I was trying to use the "train" module of faceswap but it kept telling me that this "Invalid directory name"

NotADirectoryError: [WinError 267] Nom de répertoire non valide: 'C:\\Users\\Raj\\faceeswap\\src\\aime.MOV'
06/21/2019 11:47:14 CRITICAL An unexpected crash has occurred. Crash report written to C:\Users\Raj\faceeswap\crash_report.2019.06.21.114711377083.log. Please verify you are running the latest version of faceswap before reporting

but my file does exist and i can open it from the faceswap terminal...

Could you help me ?

Thanks

.

**Comment by torzdf** [comment]
crash_report

**Comment by torzdf** [comment]
It may be a capitalization issue. If you give me the crash_report I can look to bugfix

**Comment by AaIiMm** [comment]
06/21/2019 11:40:53 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
06/21/2019 11:40:53 MainProcess     MainThread      cli             execute_script            DEBUG    Executing: extract. PID: 1656
06/21/2019 11:41:02 MainProcess     MainThread      cli             test_for_tf_version       DEBUG    Installed Tensorflow Version: 1.14
06/21/2019 11:41:02 MainProcess     MainThread      extract         __init__                  DEBUG    Initializing Extract: (args: Namespace(align_eyes=False, aligner='fan', alignments_path=None, blur_thresh=0.0, configfile=None, debug_landmarks=False, detector='mtcnn', extract_every_n=1, filter=None, func=<bound method ScriptExecutor.execute_script of <lib.cli.ScriptExecutor object at 0x000001E80862FCC0>>, input_dir='C:\\Users\\Raj\\Desktop\\inputFacesAime\\P6210490.mp4.MOV', logfile=None, loglevel='INFO', min_size=0, nfilter=None, normalization='none', output_dir='C:\\Users\\Raj\\Desktop\\OutputFacesAime', redirect_gui=False, ref_threshold=0.4, rotate_images=None, save_interval=0, serializer='json', singleprocess=False, size=256, skip_existing=False, skip_faces=False)
06/21/2019 11:41:02 MainProcess     MainThread      utils           set_system_verbosity      DEBUG    System Verbosity level: 2
06/21/2019 11:41:02 MainProcess     MainThread      utils           get_folder                DEBUG    Requested path: 'C:\Users\Raj\Desktop\OutputFacesAime'
06/21/2019 11:41:02 MainProcess     MainThread      utils           get_folder                DEBUG    Returning: 'C:\Users\Raj\Desktop\OutputFacesAime'
06/21/2019 11:41:02 MainProcess     MainThread      extract         __init__                  INFO     Output Directory: C:\Users\Raj\Desktop\OutputFacesAime
06/21/2019 11:41:02 MainProcess     MainThread      fsmedia         __init__                  DEBUG    Initializing Images
06/21/2019 11:41:02 MainProcess     MainThread      fsmedia         check_input_folder        INFO     Input Directory: C:\Users\Raj\Desktop\inputFacesAime\P6210490.mp4.MOV
Traceback (most recent call last):
  File "C:\Users\Raj\faceeswap\lib\cli.py", line 113, in execute_script
    process = script(arguments)
  File "C:\Users\Raj\faceeswap\scripts\extract.py", line 30, in __init__
    self.images = Images(self.args)
  File "C:\Users\Raj\faceeswap\scripts\fsmedia.py", line 140, in __init__
    self.input_images = self.get_input_images()
  File "C:\Users\Raj\faceeswap\scripts\fsmedia.py", line 173, in get_input_images
    input_images = get_image_paths(self.args.input_dir)
  File "C:\Users\Raj\faceeswap\lib\utils.py", line 54, in get_image_paths
    dir_scanned = sorted(os.scandir(directory), key=lambda x: x.name)
NotADirectoryError: [WinError 267] Nom de répertoire non valide: 'C:\\Users\\Raj\\Desktop\\inputFacesAime\\P6210490.mp4.MOV'

**Comment by AaIiMm** [comment]
thanks for the fast answer !

**Comment by torzdf** [comment]
Should be fixed in latest commit.
