### ISSUE TITLE
FFMPEG image sequence with longer durations after generated an output video

### ISSUE THREAD

**Issue by datomnurdin** [deepfakes/faceswap#767]
**Describe the bug**
The problem is the original duration video is shorter than the generated one. Original is 35 seconds but generated is 41 seconds. Image frames captured and converted are same, 1037 frames.

**To Reproduce**
I'm using this command to generate the video.
```
ffmpeg -i video-frame-%0d.png -c:v libx264 -vf "fps=25,format=yuv420p" out.mp4
```

**Expected behavior**
The output video duration supposedly to be exactly same with the original video.

**Desktop (please complete the following information):**
 - OS: High Sierra 10.13.6

**Comment by bryanlyon** [comment]
I'm guessing that the original was actually 30fps not 25fps which is the cause of your problem.  When you encode a new video you need to match the original's framerate.

Please don't post issues on this repo if they're not about the coffee if the repo.  You can go to faceswap-playground or the discord for issues like this.
