### ISSUE TITLE
You are trying to load a weight file containing 7 layers into a model with 6 layers.

### ISSUE THREAD

**Issue by room3dev** [deepfakes/faceswap#77]
I try to load a trained model from FakeApp with "faceswap.py train ..." but I got this message
`You are trying to load a weight file containing 7 layers into a model with 6 layers.`
How can I fix this? I use this train setting in FakeApp

Model:
Processor: GPU
Layers: 4
Node: 512
Mem Ratio: default
GPU Growth: false

Thanks.

**Comment by fakeapp** [comment]
Increase Nodes to 1024 and it should work. There's a discrepancy between your model complexity and the default model complexity of FakeApp.
