### ISSUE TITLE
convert never completes

### ISSUE THREAD

**Issue by yililuminsec** [deepfakes/faceswap#773]
**Describe the bug**

The convert (either to images or video) can never complete. It always stops at 99% and then hang there forever.  In the test, there are 1600 frames from the input video. the converts stops at around 1580 frames. When the target is a video, the final video is not produced. Just a _tem... video file with 0 byte. 

Here are logs in debug mode when this state is reached.  No error reported. It seems most of the thread completed. When the app reach this state, the CPU and GPU usage becomes almost 0%, but GPU memory is still held by the app. 

....... 

06/24/2019 18:50:04 SpawnPoolWorker-12 MainThread      convert         process                   DEBUG    Patch queue finished
06/24/2019 18:50:04 SpawnPoolWorker-12 MainThread      convert         process                   DEBUG    Putting EOF back to in_queue
06/24/2019 18:50:04 SpawnPoolWorker-12 MainThread      convert         process                   DEBUG    Completed convert process

**To Reproduce**
On the GUI, 
1. Extract images from source and target videos. 
2. train the model with the exacted face images.
3. convert the source video with the trained model and with the source video as the reference. 
  then the issue is produced. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by torzdf** [comment]
This bug should be fixed.
