### ISSUE TITLE
About showing iterations and loss 

### ISSUE THREAD

**Issue by Super-Ivan** [deepfakes/faceswap#775]
I want to know the iterations and loss number when it's training. But I found that it only showed imformations like "INFO    saved models" when training without GUI. 

So I insert two lines of code after .\plugins\train\model\_base.py line 424, like that:
        logger.info("saved models")
        logger.info("iterations: %s ", self.state.iterations)
        logger.info("loss: %s ", self.state.lowest_avg_loss)
Now it can show the iterations and loss number like this:
06/26/2019 07:32:18 INFO     saved models
06/26/2019 07:32:18 INFO     iterations: 29107 
06/26/2019 07:32:18 INFO     loss: {'a': 0.007832647301256657, 'b': 0.02996937371790409}

I wonder if there's a better way to solve the problem?

**Comment by torzdf** [comment]
Loss is displayed in the console when training.
