### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by s97712** [deepfakes/faceswap#777]
**Describe the bug**
Hi, I'm try to install the repo follow [General-Install-Guide](https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#General-Install-Guide)

But when I run `python setup.py`, It throw the error `AttributeError: 'NoneType' object has no attribute 'split'`. How should I fit it? 

```sh
$ pip install -r requirements.txt
$ pip install tensorflow-gpu
$ pytyon ./setup.py
INFO    Running as Root/Admin
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Linux 4.14.79+
INFO    Installed Python: 3.6.8 64bit
INFO    Encoding: UTF-8
INFO    Upgrading pip...
INFO    Installed pip: 19.1.1
INFO    AMD Support: AMD GPU support is currently limited.
        Nvidia Users MUST answer 'no' to this option.
Enable AMD Support? [y/N] 
INFO    AMD Support Disabled
Enable  Docker? [y/N] 
INFO    Docker Disabled
Enable  CUDA? [Y/n] 
INFO    CUDA Enabled
INFO    CUDA version: 10.0
INFO    cuDNN version: 7.4.2
Please ensure your System Dependencies are met. Continue? [y/N] y
Traceback (most recent call last):
  File "./setup.py", line 753, in <module>
    Install(ENV)
  File "./setup.py", line 524, in __init__
    self.check_missing_dep()
  File "./setup.py", line 544, in check_missing_dep
    key = pkg.split("==")[0]
AttributeError: 'NoneType' object has no attribute 'split'
```
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by torzdf** [comment]
I have just this minute update INSTALL.md. It is recommended to use Conda for your faceswap environment, as it removes the requirement to manually install Cuda and cuDNN.

**Comment by s97712** [comment]
I try to run it on colab and met some trouble, Here is my [colab](https://colab.research.google.com/drive/18h5xYp4WBgl50OXhr98I70OwuEzIkG0H), but it can't work, can you hava some help?

**Comment by torzdf** [comment]
We do not directly support Colab. You are best off looking for help in this repo:
https://github.com/seranus/faceswap-notebooks/blob/master/faceswap_trainer.ipynb

**Comment by aesthese** [comment]
I'm having the same problem running in Conda

**Comment by torzdf** [comment]
That check shouldn't run if you run in Conda

An example output from running in a Conda environment:
```
WARNING Running without root/admin privileges
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Windows 10
INFO    Installed Python: 3.6.8 64bit
INFO    Running in Conda
```
Note the last line in the example.

Please could you open up an Anaconda Prompt. Enter your faceswap environment and post the output of this:
```bash
python -c "import sys ; print(sys.version.lower()) ; print('conda' in sys.version.lower())"
```

**Comment by torzdf** [comment]
Actually, this looks like a bug.... Will push a potential fix shortly.

**Comment by torzdf** [comment]
This issue should be fixed in latest commit
