### ISSUE TITLE
Cron Error on remote server

### ISSUE THREAD

**Issue by SasiKiranK** [deepfakes/faceswap#780]
Cron Error on remote server

**To Reproduce**
Using remote cron to run the training

**Expected behavior**
running training in background.

Error:
As it is requires Keyboard events. It is crashing with below error

 **Got Exception on main handler:\nTraceback (most recent call last):\n File "/var/www/html/deep/faceswap/lib/cli.py", line 124, in execute_script\n process.process()\n File "/var/www/html/deep/faceswap/scripts/train.py", line 96, in process\n err = self.monitor(thread)\n File "/var/www/html/deep/faceswap/scripts/train.py", line 257, in monitor\n keypress = KBHit(is_gui=self.args.redirect_gui)\n File "/var/www/html/deep/faceswap/lib/keypress.py", line 42, in __init__\n self.new_term = termios.tcgetattr(self.file_desc)\ntermios.error: (25, 'Inappropriate ioctl for device')**

I'm not sure what lines to be commented / changed. please comment

below is my report

06/29/2019 19:12:01 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
06/29/2019 19:12:01 MainProcess     MainThread      cli             execute_script            DEBUG    Executing: train. PID: 20689
06/29/2019 19:12:02 MainProcess     MainThread      cli             test_for_tf_version       DEBUG    Installed Tensorflow Version: 1.13
06/29/2019 19:12:02 MainProcess     MainThread      train           __init__                  DEBUG    Initializing Train: (args: Namespace(alignments_path_a=None, alignments_path_b=None, allow_growth=False, amd=False, batch_size=64, configfile=None, func=<bound method ScriptExecutor.execute_script of <lib.cli.ScriptExecutor object at 0x7f70ebc0b3c8>>, gpus=1, input_a='/var/www/html/deep/faceswap/output/kum', input_b='/var/www/html/deep/faceswap/output/div', iterations=1000000, logfile=None, loglevel='INFO', memory_saving_gradients=False, model_dir='/var/www/html/deep/faceswap/model', no_augment_color=False, no_flip=False, no_logs=False, pingpong=False, preview=False, preview_scale=50, redirect_gui=False, save_interval=100, snapshot_interval=25000, timelapse_input_a=None, timelapse_input_b=None, timelapse_output=None, trainer='original', warp_to_landmarks=False, write_image=False)
06/29/2019 19:12:02 MainProcess     MainThread      train           get_images                DEBUG    Getting image paths
06/29/2019 19:12:02 MainProcess     MainThread      utils           get_image_paths           DEBUG    Scanned Folder contains 93 files
06/29/2019 19:12:02 MainProcess     MainThread      utils           get_image_paths           DEBUG    Returning 93 images
06/29/2019 19:12:02 MainProcess     MainThread      utils           get_image_paths           DEBUG    Scanned Folder contains 95 files
06/29/2019 19:12:02 MainProcess     MainThread      utils           get_image_paths           DEBUG    Returning 95 images
06/29/2019 19:12:02 MainProcess     MainThread      train           get_images                INFO     Model A Directory: /var/www/html/deep/faceswap/output/kum
06/29/2019 19:12:02 MainProcess     MainThread      train           get_images                INFO     Model B Directory: /var/www/html/deep/faceswap/output/div
06/29/2019 19:12:02 MainProcess     MainThread      train           get_images                DEBUG    Got image paths: [('a', '93 images'), ('b', '95 images')]
06/29/2019 19:12:02 MainProcess     MainThread      train           __init__                  DEBUG    Initialized Train
06/29/2019 19:12:02 MainProcess     MainThread      train           process                   DEBUG    Starting Training Process
06/29/2019 19:12:02 MainProcess     MainThread      train           process                   INFO     Training data directory: /var/www/html/deep/faceswap/model
06/29/2019 19:12:02 MainProcess     MainThread      utils           set_system_verbosity      DEBUG    System Verbosity level: 2
06/29/2019 19:12:02 MainProcess     MainThread      train           start_thread              DEBUG    Launching Trainer thread
06/29/2019 19:12:02 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'training', thread_count: 1)
06/29/2019 19:12:02 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'training'
06/29/2019 19:12:02 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'training'
06/29/2019 19:12:02 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'training_0'
06/29/2019 19:12:02 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'training': 1
06/29/2019 19:12:02 MainProcess     MainThread      train           start_thread              DEBUG    Launched Trainer thread
06/29/2019 19:12:02 MainProcess     MainThread      train           monitor                   DEBUG    Launching Monitor
06/29/2019 19:12:02 MainProcess     MainThread      train           monitor                   INFO     ===================================================
06/29/2019 19:12:02 MainProcess     MainThread      train           monitor                   INFO       Starting
06/29/2019 19:12:02 MainProcess     MainThread      train           monitor                   INFO       Press 'ENTER' to save and quit
06/29/2019 19:12:02 MainProcess     MainThread      train           monitor                   INFO       Press 'S' to save model weights immediately
06/29/2019 19:12:02 MainProcess     MainThread      train           monitor                   INFO     ===================================================
Traceback (most recent call last):
  File "/var/www/html/deep/faceswap/lib/cli.py", line 124, in execute_script
    process.process()
  File "/var/www/html/deep/faceswap/scripts/train.py", line 96, in process
    err = self.monitor(thread)
  File "/var/www/html/deep/faceswap/scripts/train.py", line 257, in monitor
    keypress = KBHit(is_gui=self.args.redirect_gui)
  File "/var/www/html/deep/faceswap/lib/keypress.py", line 42, in __init__
    self.new_term = termios.tcgetattr(self.file_desc)
termios.error: (25, 'Inappropriate ioctl for device')

============ System Information ============
encoding:            UTF-8
git_branch:          Not Found
git_commits:         Not Found
gpu_cuda:            No global version found
gpu_cudnn:           No global version found
gpu_devices:         
gpu_devices_active:  
gpu_driver:          []
gpu_vram:            
os_machine:          x86_64
os_platform:         Linux-5.0.0-1010-gcp-x86_64-with-Ubuntu-19.04-disco
os_release:          5.0.0-1010-gcp
py_command:          /var/www/html/deep/faceswap/faceswap.py train -A /var/www/html/deep/faceswap/output/kum/ -B /var/www/html/deep/faceswap/output/div -m /var/www/html/deep/faceswap/model/
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.7.3
py_virtual_env:      False
sys_cores:           8
sys_processor:       x86_64
sys_ram:             Total: 30149MB, Available: 29144MB, Used: 556MB, Free: 25356MB

=============== Pip Packages ===============
absl-py==0.7.1
ansible==2.8.1
asn1crypto==0.24.0
astor==0.8.0
attrs==18.2.0
Automat==0.6.0
blinker==1.4
certifi==2018.8.24
cffi==1.12.3
chardet==3.0.4
Click==7.0
cloud-init==19.1
colorama==0.3.7
command-not-found==0.3
configobj==5.0.6
constantly==15.1.0
cryptography==2.3
cycler==0.10.0
decorator==4.4.0
distro==1.3.0
distro-info===0.21ubuntu2
entrypoints==0.3
enum34==1.1.6
fastcluster==1.1.25
ffmpy==0.2.2
future==0.17.1
gast==0.2.2
google-compute-engine==2.8.16
google-pasta==0.1.7
grpcio==1.21.1
h5py==2.9.0
httplib2==0.11.3
hyperlink==17.3.1
idna==2.6
imageio==2.5.0
imageio-ffmpeg==0.3.0
incremental==16.10.1
Jinja2==2.10
joblib==0.13.2
jsonpatch==1.21
jsonpointer==1.10
jsonschema==2.6.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
keyring==17.1.1
keyrings.alt==3.1.1
kiwisolver==1.1.0
language-selector==0.1
Markdown==3.1.1
MarkupSafe==1.1.0
matplotlib==2.2.2
mock==3.0.5
netifaces==0.10.4
networkx==2.3
np-utils==0.5.10.0
numpy==1.16.2
nvidia-ml-py3==7.352.0
oauthlib==2.1.0
opencv-python==4.1.0.25
pathlib==1.0.1
Pillow==6.0.0
plaidml==0.6.1
plaidml-keras==0.6.1
protobuf==3.8.0
psutil==5.6.3
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.19
pycrypto==2.6.1
PyGObject==3.32.0
PyJWT==1.7.0
pymacaroons==0.13.0
PyNaCl==1.3.0
pyOpenSSL==19.0.0
pyparsing==2.4.0
pyserial==3.4
python-apt==1.8.4
python-dateutil==2.8.0
python-debian==0.1.34
pytz==2019.1
PyWavelets==1.0.3
pyxdg==0.25
PyYAML==3.13
requests==2.21.0
requests-unixsocket==0.1.5
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
SecretStorage==2.3.1
service-identity==16.0.0
six==1.12.0
ssh-import-id==5.7
systemd-python==234
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
toposort==1.5
tqdm==4.32.2
Twisted==18.9.0
ubuntu-advantage-tools==19.2
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.24.1
Werkzeug==0.15.4
wrapt==1.11.2
xkit==0.0.0
zope.interface==4.3.2

**Comment by deepfakes** [comment]
This is outside of scope for how FaceSwap is meant to be run. It monitors the terminal for keypresses. You are welcome to raise a PR for background running as long as it is correctly detected/handled.
