### ISSUE TITLE
Loss info not showing in the cloud server

### ISSUE THREAD

**Issue by SasiKiranK** [deepfakes/faceswap#781]
Hi 

Showing the below in the local server but not displaying in the cloud server
[06:52:22] [#02277] loss_A: 0.06049, loss_B: 0.08593

only displaying saved models repeatedly without data.
06/30/2019 06:49:54 INFO     saved models
06/30/2019 06:52:54 INFO     saved models

Can you please provide the file and the line so i can add log info. 
tried in print_loss fun not working

**Comment by SasiKiranK** [comment]
@torzdf

**Comment by deepfakes** [comment]
Loss prints to console. This works for 99% of use cases. I cannot test this on a cloud server, but you are welcome to raise a PR to fix.

Alternatively you can use tensorboard to view the logs
