### ISSUE TITLE
Freetype version error

### ISSUE THREAD

**Issue by evankulp** [deepfakes/faceswap#783]
When trying to run faceswap.py (on macOS Mojave), the following error occurs:

`Traceback (most recent call last):
  File "/Users/user/faceswap/faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "/Users/user/faceswap/lib/cli.py", line 17, in <module>
    from lib.utils import FaceswapError, safe_shutdown
  File "/Users/user/faceswap/lib/utils.py", line 18, in <module>
    import cv2
ImportError: dlopen(/Users/user/anaconda3/envs/faceswap/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libfreetype.6.dylib
  Referenced from: /Users/user/anaconda3/envs/faceswap/lib/libopencv_freetype.4.1.dylib
  Reason: Incompatible library version: libopencv_freetype.4.1.dylib requires version 24.0.0 or later, but libfreetype.6.dylib provides version 23.0.0`

This happens regardless of whether I try to use the GUI or command line. I'm not sure, but it seems that freetype is an engine or displaying text. If this is the case, why do I need it in order to use the command line? How can I update freetype?

**Comment by twipz333** [comment]
Same probem on win10

**Comment by andynguy3n** [comment]
Not sure if this can help. May you try in your env:

`conda install -c conda-forge basemap fiona`

**Comment by twipz333** [comment]
mmm…again
Here is error:

(faceswap) D:\FaceSwap\faceswap-master\faceswap-master>python faceswap.py -h
Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "D:\FaceSwap\faceswap-master\faceswap-master\lib\cli.py", line 16, in <module>
    from lib.logger import crash_log, log_setup
  File "D:\FaceSwap\faceswap-master\faceswap-master\lib\logger.py", line 13, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by torzdf** [comment]
For some reason you aren't setup correctly.

From inside your faceswap folder (whilst in your faceswap environment):
```python update_deps.py```
