### ISSUE TITLE
Microsoft SmartScrren detected a Malware in your exe file

### ISSUE THREAD

**Issue by gittyhub2018** [deepfakes/faceswap#787]
**Describe the bug**
Microsoft Antivirus find a malware in your files. Virustotal find via heuristic a malware, too.
URL: https://www.virustotal.com/gui/file/066ad1b0c174372e3fdc0869a293e0bfb23b23e7cce2b114addc35225825505b/detection

**To Reproduce**
Open the installer on windows 10 with all updates (09.07.2019)

**Expected behavior**
No malware warning.

**Desktop (please complete the following information):**
 Windows 10 1903 Build: 18362.175

**Smartphone (please complete the following information):**
 Not tested on smartphones.

**Comment by torzdf** [comment]
It's not a virus. Source Code is included in the repository. If you really don't trust it you can compile the installer yourself.
