### ISSUE TITLE
Compare model results

### ISSUE THREAD

**Issue by khcy82dyc** [deepfakes/faceswap#788]
Hi, is there a figure to compare the faceswap results using different trainers? 
at the moment I see some trainers 'not so well', or 'don't expect' good results.
would be really nice to know which are the best trainers to use for the best results/details/resolutions
thanks!

**Comment by torzdf** [comment]
There isn't really such a thing as "Best Trainer". The data you feed a model is by far and away the most important factor.

As a general rule of thumb, the heavier the model, the better it will perform (with the same data), but this is by no means a hard and fast rule.
