### ISSUE TITLE
Cannot run software

### ISSUE THREAD

**Issue by candicetang55** [deepfakes/faceswap#796]
**Describe the bug**
When I try to run the gui it gave me this error prompt:
The ordinal 242 could not be located in the dynamic link library.

The following error is shown in the comand line when I try to run:
INTEL MKL ERROR: The operating system cannot run %1. mkl_intel_thread.dll.
Intel MKL FATAL ERROR: Cannot load mkl_intel_thread.dll.

However, I was able to locate the mkl_intel_thread.dll file inside "Miniconda3\Library\bin".
I tried both using the windows complete installation and installing dependencies with command line. Both ways gave me the same error

**Screenshots**
![error1](https://user-images.githubusercontent.com/47726378/61333499-b27a7100-a7ec-11e9-863c-19816d4d9fe8.PNG)
![error2](https://user-images.githubusercontent.com/47726378/61333500-b27a7100-a7ec-11e9-9d55-2401a765ea89.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: python 3.6, cuda 9.0, GTX 1050, RAM 16G

**Comment by torzdf** [comment]
This is an Anaconda issue, not a faceswap Issue. You should look to see if you can resolve this upstream:
https://github.com/ContinuumIO/anaconda-issues/issues/10213

**Comment by bryanlyon** [comment]
They already have a solution, see the following which details how to fix. 
 https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed
