### ISSUE TITLE
Existing Model unable to resume under latest FS version

### ISSUE THREAD

**Issue by Enyakk** [deepfakes/faceswap#797]
**Describe the bug**
I have created a new Model (Villain) under July 15 version:
https://github.com/deepfakes/faceswap/tree/8510b2a6968828c269ddca4765f656259a21cfbc

Settings:
  "config": {
    "mask_type": "extended",
    "icnr_init": true,
    "subpixel_upscaling": false,
    "reflect_padding": true,
    "dssim_loss": true,
    "penalized_mask_loss": true,
    "lowmem": false,
    "coverage": 62.5
  }

**To Reproduce**
Switch to latest commit including changes from July 16. Resume existing model. Produces error:
File "F:\Programme\Anaconda3\envs\faceswap\lib\site-packages\keras\layers\merge.py", line 61, in _compute_elemwise_op_output_shape
str(shape1) + ' ' + str(shape2))
ValueError: Operands could not be broadcast together with shapes (30, 30, 512) (32, 32, 512)

See included log.
[crash_report.2019.07.17.074252670733.log](https://github.com/deepfakes/faceswap/files/3400419/crash_report.2019.07.17.074252670733.log)

**Comment by torzdf** [comment]
This should be fixed in latest commit.
