### ISSUE TITLE
Suggestion: Progress bar during extraction and conversion

### ISSUE THREAD

**Issue by Irastris** [deepfakes/faceswap#80]
Would it be possible to have a progress bar while extracting faces from photos and while swapping faces with trained model? Currently, atleast during extraction, it just says `Starting, this may take a while...` until the process ends.

**Comment by gdunstone** [comment]
with tqdm this is super easy, not sure about including it as a dependency, I'll fork tomorrow.

*faceswap/lib/cli.py:51*
```
def process_directory(self):
        for filename in tqdm(self.input_dir):
            if self.arguments.verbose:
                print('Processing: {}'.format(os.path.basename(filename)))

            self.process_image(filename)
            self.images_processed = self.images_processed + 1

        self.finalize()
```

**Comment by gdunstone** [comment]
This will probably impact https://github.com/deepfakes/faceswap/pull/62  with the multicore directory processor.

**Comment by Clorr** [comment]
I'm closing this as you did a pull request ;-)
