### ISSUE TITLE
Can you cut the avatar into a transparent one, so you can better integrate into another face

### ISSUE THREAD

**Issue by kamike** [deepfakes/faceswap#802]
I am a newbie.The result of my training has a lot of obvious black borders. The effect is not very natural. I wonder if this can be done by setting the training picture to a transparent background, which can eliminate the influence of surrounding colors.
for example:
![20161016183041_8ztEa](https://user-images.githubusercontent.com/3920019/61575799-ddbdd280-ab02-11e9-8103-d23224972bf5.png)
change it to
![33](https://user-images.githubusercontent.com/3920019/61575851-fa0e3f00-ab03-11e9-98f6-22ef78fda05f.png)

Need to add an option in the extractor, it can automatically crop only the background transparent image of the face.thank you very much!!

**Comment by bryanlyon** [comment]
This feature is already available in the software.  Check out the convert plug-in options.
