### ISSUE TITLE
DeepFaceLab SAE Model

### ISSUE THREAD

**Issue by randomkpopfan** [deepfakes/faceswap#804]
**Is your feature request related to a problem? Please describe.**
The SAE Model from DeepFaceLab by iperov is not currently available in the Faceswap app.

**Describe the solution you'd like**
Please add the full SAE model from https://github.com/iperov/DeepFaceLab/ to the trainer options for Faceswap

**Describe alternatives you've considered**
If the SAE model trainer is already available under a different name in the Faceswap app, perhaps add a tool tip or change the name so that it is more readily identifiable.

**Additional context**
This is the exact URL to the model repository: https://github.com/iperov/DeepFaceLab/tree/master/models/Model_SAE

It would be great to have this model available, since many people feel it produces the best results.

Thanks very much for your hard work!

**Comment by sdgandhi** [comment]
Hey @randomkpopfan SAE model is now available in master!

**Comment by kvrooman** [comment]
Closing as this is resolved
