### ISSUE TITLE
Starting, this may take a while... or eternity.

### ISSUE THREAD

**Issue by FlamesoFF** [deepfakes/faceswap#806]
**Describe the bug**
07/22/2019 15:17:38 INFO     Extracting: 'face-alignment-network_2d4'
07/22/2019 15:17:39 INFO     Starting, this may take a while...

**To Reproduce**
Run extraction.

**Current behavior**
Forever stuck at `Starting, this may take a while...`
CPU and GPU both not loaded. No errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/5371279/61636857-c9aada00-ac96-11e9-8c8d-6a7b06dd73c1.png)

**Desktop (please complete the following information):**
OS: Win 10
GPU: ASUS GTX 1070
Version: latest

**Info:**
Everything was installed in accordance with this manual: https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#setup

Other tensorflow  projects are working, except this one.

**Comment by Thepokefreek** [comment]
Are you using studio drivers ? 
If you are, use the game ready driver. 
This solved the issu for me.

**Comment by torzdf** [comment]
For some reason On first initialization it can get stuck for a while. Stop it and try again. If it still hasn't started after 5 minutes, please post set loglevel to "TRACE" and let it run until it hangs. Let it run for about 30 seconds more, then kill it. Go into your Faceswap folder and post the faceswap.log file.....

**Comment by FlamesoFF** [comment]
@torzdf It's working now.
I've already restarted it several times, but after I set the `TRACE` level, as you said, it suddenly started working!
It looks like a bug.

**Comment by torzdf** [comment]
Heh. Always the way.
Don't leave trace logging on. It will slow everything down and will generate massive log files!

**Comment by FlamesoFF** [comment]
@torzdf And I tested it again several times.
It's not working in "INFO" mode, but working in every other mode. Definitely a bug.

**Comment by torzdf** [comment]
There was an issue where if a crash occurred in the loading/saving threads then the process would hang indefinitely. This *should* now be caught and handled. If this issue has not been resolved, please comment and I will re-open.
