### ISSUE TITLE
Crashing after 129400 Iterations

### ISSUE THREAD

**Issue by Thepokefreek** [deepfakes/faceswap#807]
**Describe the bug**
After approximately 129400 iterations this is observed:
CRITICAL An unexpected crash has occurred.

**To Reproduce**
1. Go to 'Train'
2. Fill out 'Input (A,B), Alignment (A,B), Model, Trainer (Original), Save Interval (100), Snapshot Interval (25000), Batch Size (64), Iterations (1000000), GPUs (1), Preview Scale (50), Loglevel (INFO) and Options (Allow Growth, Optimizer Savings) '
3.  Click 'Train'

**Expected behavior**
Training to resume normally and to continue without crashing.

**Screenshots**
![Screenshot (8)](https://user-images.githubusercontent.com/14138669/61682431-f4864400-ad11-11e9-9a4a-12383f398eb1.png)

**Desktop:**
 - OS: Windows 10 (1903)
 - GPU: Gigabyte GTX 1060 3GB OC 2GHz
 - CPU: i7-4790k OC 4.7GHz
 - RAM: 16GB DDR3 1333MHz
 - PWS: Corsair CX850M 80+ Bronz
 - Version: 1.0.0

**Crash Report**
[crash_report.2019.07.22.174059746080.log](https://github.com/deepfakes/faceswap/files/3420209/crash_report.2019.07.22.174059746080.log)

**Comment by torzdf** [comment]
We have not seen this issue before, and it really shouldn't happen (especially since it must have successfully snapshotted  4 times before.

Did you roll back to a previous backup/snapshot prior to hitting this error? This is the only way I can see that this might have occured?

**Comment by Thepokefreek** [comment]
> We have not seen this issue before, and it really shouldn't happen (especially since it must have successfully snapshotted 4 times before.
> 
> Did you roll back to a previous backup/snapshot prior to hitting this error? This is the only way I can see that this might have occured?

Yes but around the 90k and up to the 124k I've had no problem

**Comment by torzdf** [comment]
Ok. Thanks for the feedback. I think I know why this happens then and will look to push a fix

**Comment by torzdf** [comment]
This should be fixed in latest commit.
