### ISSUE TITLE
I found this issue during the extracting

### ISSUE THREAD

**Issue by ZakariaMHTX** [deepfakes/faceswap#808]
Loading...
07/23/2019 20:24:11 INFO     Log level set to: INFO
Traceback (most recent call last):
File "C:\Users\lpmc_user\faceswap\faceswap.py", line 36, in <module>
ARGUMENTS.func(ARGUMENTS)
File "C:\Users\lpmc_user\faceswap\lib\cli.py", line 115, in execute_script
plaidml_found = self.setup_amd(arguments.loglevel)
File "C:\Users\lpmc_user\faceswap\lib\cli.py", line 148, in setup_amd
import plaidml  # noqa pylint:disable=unused-import
File "C:\Users\lpmc_user\AppData\Roaming\Python\Python37\site-packages\plaidml\__init__.py", line 50, in <module>
import plaidml.settings
File "C:\Users\lpmc_user\AppData\Roaming\Python\Python37\site-packages\plaidml\settings.py", line 33, in <module>
_setup_config('PLAIDML_EXPERIMENTAL_CONFIG', 'experimental.json')
File "C:\Users\lpmc_user\AppData\Roaming\Python\Python37\site-packages\plaidml\settings.py", line 30, in _setup_config
'Could not find PlaidML configuration file: "{}".'.format(filename))
plaidml.exceptions.PlaidMLError: Could not find PlaidML configuration file: "experimental.json".
Process exited.

**Comment by torzdf** [comment]
@kilroythethird

**Comment by kilroythethird** [comment]
How did you install faceswap ?

And are you using and AMD or NVIDIA card ?

**Comment by ZakariaMHTX** [comment]
I used this guide https://github.com/deepfakes/faceswap/blob/master/INSTALL.md
and I m using AMD card.

**Comment by kilroythethird** [comment]
Just to be sure: You used the installer and selected the "Setup for AMD gpu option" ?

If so please open the anaconda prompt (find it via the start menu) and do a:
```
conda activate faceswap
pip freeze
```

and post the output here.

**Comment by ZakariaMHTX** [comment]
Yes I choose   "Setup for AMD gpu option" 
`(base) C:\Users\lpmc_user>conda activate faceswap

(faceswap) C:\Users\lpmc_user>pip freeze
absl-py==0.7.1
astor==0.8.0
certifi==2019.6.16
cffi==1.12.3
cycler==0.10.0
decorator==4.4.0
enum34==1.1.6
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
grpcio==1.22.0
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.12
mkl-random==1.0.2
mock==3.0.5
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.1
opencv-python==4.1.0.25
pathlib==1.0.1
Pillow==6.1.0
plaidml==0.6.3
plaidml-keras==0.6.3
protobuf==3.9.0
psutil==5.6.3
pycparser==2.19
pyparsing==2.4.1
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32==224
PyYAML==5.1.1
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.3.0
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
toposort==1.5
tqdm==4.32.2
Werkzeug==0.15.5
wincertstore==0.2

(faceswap) C:\Users\lpmc_user>`

**Comment by kilroythethird** [comment]
Thank you. It looks like you have also a plaidml version installed outside of this virtual environment.
I need to check how plaidml is set up under window. Will get back to you shortly.

**Comment by ZakariaMHTX** [comment]
Thanks for you help.

**Comment by kilroythethird** [comment]
Happy to help.
It for sure looks like you have plaidml installed twice. Are you using anything else which requires plaidml ?
The easiest fix for now would probably be to simply delete `C:\Users\lpmc_user\AppData\Roaming\Python\Python37\site-packages\plaidml` if you don't need it for something else.

**Comment by ZakariaMHTX** [comment]
I also use  deepfacelab "https://github.com/iperov/DeepFaceLab". I had it installed before I installed anaconda and faceswap.
Should I delete  `C:\Users\lpmc_user\AppData\Roaming\Python\Python37\site-packages\plaidml`

**Comment by kilroythethird** [comment]
Well it should at least solve this issue.
It might lead to DeefaceLab not working anymore, but as far as i see in the current settings it should produce the same error i think.
In the worst case you would need to reinstall plaidml system wide again to use deepfacelab (They really should use conda too tho).

As alternative you could try to downgrade your system wide installed plaidml to plaidml==0.6.0, but that is just a shot in the dark.

**Comment by ZakariaMHTX** [comment]
I deleted `C:\Users\lpmc_user\AppData\Roaming\Python\Python37\site-packages\plaidml`
It gives me now this error 
`Loading...
07/24/2019 16:13:07 INFO     Log level set to: INFO
07/24/2019 16:13:07 ERROR    PlaidML not found. Run `pip install plaidml-keras` for AMD support
Process exited.`

**Comment by kilroythethird** [comment]
Conda on windows is just no fun ;)
This one should be easy enough to solve though.

Please open your anaconda prompt and do:
```
conda activate faceswap
pip install -U plaidml-keras plaidml
```

**Comment by ZakariaMHTX** [comment]
I executed these commands, it shows me like this : 

`(base) C:\Users\lpmc_user>conda activate faceswap

(faceswap) C:\Users\lpmc_user>pip install -U plaidml-keras plaidml
Requirement already up-to-date: plaidml-keras in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (0.6.3)
Requirement already up-to-date: plaidml in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (0.6.3)
Requirement already satisfied, skipping upgrade: six in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from plaidml-keras) (1.12.0)
Requirement already satisfied, skipping upgrade: keras==2.2.4 in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from plaidml-keras) (2.2.4)
Requirement already satisfied, skipping upgrade: enum34>=1.1.6 in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from plaidml) (1.1.6)
Requirement already satisfied, skipping upgrade: cffi in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from plaidml) (1.12.3)
Requirement already satisfied, skipping upgrade: numpy in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from plaidml) (1.16.2)
Requirement already satisfied, skipping upgrade: pyyaml in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from keras==2.2.4->plaidml-keras) (5.1.1)
Requirement already satisfied, skipping upgrade: scipy>=0.14 in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from keras==2.2.4->plaidml-keras) (1.3.0)
Requirement already satisfied, skipping upgrade: keras-applications>=1.0.6 in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from keras==2.2.4->plaidml-keras) (1.0.8)
Requirement already satisfied, skipping upgrade: h5py in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from keras==2.2.4->plaidml-keras) (2.9.0)
Requirement already satisfied, skipping upgrade: keras-preprocessing>=1.0.5 in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from keras==2.2.4->plaidml-keras) (1.1.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\lpmc_user\appdata\roaming\python\python37\site-packages (from cffi->plaidml) (2.19)
`

**Comment by ZakariaMHTX** [comment]
the error still the same 
`Loading...
07/24/2019 16:34:59 INFO     Log level set to: INFO
07/24/2019 16:34:59 ERROR    PlaidML not found. Run `pip install plaidml-keras` for AMD support
Process exited.`

**Comment by ZakariaMHTX** [comment]
but when I uncheck the option 'AMD' in faceswap interface, the extraxting starts runing on CPU.

**Comment by kilroythethird** [comment]
Sorry, just deleting the plaidml folder doesn't seem to cut it.
But it is definitely one step in the right direction.

The proper way would be a `pip uninstall plaidml plaidml-keras` if you know how to run pip **outside** of your anaconda environment.

Otherwise try to delete everything in you `c:\users\lpmc_user\appdata\roaming\python\python37\site-packages` folder with plaidml in the name.
Afterwards try to install plaidml in your anaconda environment with the commands in the post above.

If that doesn't work let me know and i am going to install python in my windows VM so i can guide you better through this.

**Comment by ZakariaMHTX** [comment]
I don't know how to run pip outside of anaconda environment.
could you please tell me how?

**Comment by kilroythethird** [comment]
Depending on how python is installed on your system its a bit hard for me to guide you through that step sorry.

Did you try:

> 
Otherwise try to delete everything in you c:\users\lpmc_user\appdata\roaming\python\python37\site-packages folder with plaidml in the name.

If that works that is way easier.

**Comment by torzdf** [comment]
Ok, I have read through this, and the issue is basically that DFL does not install python into a virtual environment. This is shoddy, and is going to lead to more issues down the line.

My advice (and you are probably not going to like it) is to do one of 2 things.

1) Delete DFL. Nuke everything, run installer. See here: https://faceswap.dev/forum/app.php/faqpage#f1r1
2) Clean up your base python and create proper environments for DFL and Faceswap and install each into their relevant environment. You will not be able to use the installer for this option, and you will need to research this for yourself.

Ultimately, there is only so much support we can give because of poor design in other applications.

**Comment by ZakariaMHTX** [comment]
It works now, it shows me like this 
`Loading...
07/24/2019 17:36:16 INFO     Log level set to: INFO
07/24/2019 17:36:16 INFO     Setting up for PlaidML
07/24/2019 17:36:17 INFO     Setting GPU to largest available experimental device. If you want to override this selection, run `plaidml-setup` from the command line.
07/24/2019 17:36:17 INFO     Using GPU: ['opencl_amd_oland.0']
07/24/2019 17:36:17 INFO     Successfully set up for PlaidML
07/24/2019 17:36:19 INFO     Output Directory: D:\faces
07/24/2019 17:36:19 INFO     Input Video: D:\src\data_dst.mp4
07/24/2019 17:36:19 INFO     Loading Detect from S3Fd plugin...
07/24/2019 17:36:19 INFO     Loading Align from Fan plugin...
07/24/2019 17:36:19 INFO     Starting, this may take a while...
07/24/2019 17:36:20 INFO     Initializing Face Alignment Network...
07/24/2019 17:36:23 WARNING  Using CPU
07/24/2019 17:36:34 INFO     Initialized Face Alignment Network.
07/24/2019 17:36:35 INFO     Initializing S3FD Detector...
07/24/2019 17:36:49 WARNING  Using CPU
07/24/2019 17:36:49 WARNING  You are running s3fd with 2048MB VRAM. The model is optimized for 4096MB VRAM. Detection should still run but you may get warnings/errors`

**Comment by ZakariaMHTX** [comment]
is that normal?

**Comment by torzdf** [comment]
You should use the fan-amd plugin, and make sure that you enable the "AMD" option (at the bottom of the extract page).

**Comment by ZakariaMHTX** [comment]
Yes, I choose fan-amd and I enable AMD option.
The extraction runs on CPU. is it normal? or I should run the extraction on GPU.

**Comment by kilroythethird** [comment]
Only a part of the pipeline currently supports AMD cards.
So if you choose fan-amd and checked the amd checkbox a part of the flow uses you GPU, but its still CPU heavy.

**Comment by torzdf** [comment]
I'm considering this issue closed.

**Comment by ZakariaMHTX** [comment]
At the first time, I selected `Fan`. but now I am using` Fan-amd`. Thank you for helping me out; I really appreciate your kindness and support.
I have another question:
Does this program support "Audio manipulation" ?? like for example this video https://www.youtube.com/watch?v=347jdBs-mRU

**Comment by torzdf** [comment]
No.

Questions like these are based placed in our discord server or our forum. Links to both can be found at https://faceswap.dev

**Comment by ZakariaMHTX** [comment]
Thanks.

**Comment by jaredscheib** [comment]
Just FYI we just now ran into this same issue on a Paperspace Ubuntu 18.04 machine, while using conda virtual env, so we ran `pip uninstall plaidml plaidml-keras`, and it finally worked. Thanks!

**Comment by torzdf** [comment]
Just to be clear, plaidml shouldn't be uninstalled from inside the environment (for AMD cards) otherwise you'll be forced into CPU mode.

For Nvidia cards, plaidml shouldn't be installed anyway

**Comment by jaredscheib** [comment]
cool, yep, makes sense. thank you. yeah i just accidentally chose to back it with AMD confit (during 'python setup.py'). this machine had plaid l pre-installed because of the ML-in-a-Box template (Paperspace machine) that i was working from. currently they're nVidia.
