### ISSUE TITLE
Where we can adjust the erosion kernel size ?? 

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap#81]
i found below in Convert_Masked.py.
to adjust the self.erosion_kernel, we just need to key in a numbers ?? 

         #if args.erosionKernelSize > 0:
             #self.erosion_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(args.erosionKernelSize,args.erosionKernelSize))
         #else:
             #self.erosion_kernel = None

        self.erosion_kernel = None #None

**Comment by Clorr** [comment]
Sadly we don't have proper parsing of command line parameters for this part yet. I just let the original code so you can uncomment it if you want.

**Comment by gdunstone** [comment]
we do now,
you can use --erosion-kernel-size

**Comment by ruah1984** [comment]
thanks @gdunstone , and where  i can adjust if i would like to use it.

**Comment by gdunstone** [comment]
`python faceswap.py convert --erosion-kernel-size 8`
