### ISSUE TITLE
GPU usage is less than %20

### ISSUE THREAD

**Issue by kamike** [deepfakes/faceswap#811]
I trained for 60 hours, Iterations is 1,6000. CPU usage is around 100%，but GPU usage hash been less than %20, This should be abnormal？This seems to be still training with the CPU.How should I troubleshoot where the problem is?

I download the file faceswap_setup_x64.exe use gui version, and install Nvidia CUDA cuDNN for my PC.

============ System Information ============
encoding:            cp936
git_branch:          master
git_commits:         c3adc93 Update GUI Graph + Stats when model has finished saving. 2610eff Bugfix: GUI: Progress bar on times over 1 hour (extract/convert). c1c60a9 bugfix: Clip output from scaling in convert. 8b2f166 Update helptext for CA Initialization. b6c830c Bugfix: Alignments tool: Correctly set items attribute on Check job
gpu_cuda:            10.1
gpu_cudnn:           7.6.2
gpu_devices:         GPU_0: GeForce GT 1030
gpu_devices_active:  GPU_0
gpu_driver:          430.86
gpu_vram:            GPU_0: 2048MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.17134-SP0
os_release:          10
py_command:          d:\Users\Administrator\faceswap/faceswap.py gui
py_conda_version:    conda 4.7.10
py_implementation:   CPython
py_version:          3.6.8
py_virtual_env:      True
sys_cores:           8
sys_processor:       Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
sys_ram:             Total: 16320MB, Available: 13362MB, Used: 2958MB, Free: 13362MB

=============== Pip Packages ===============
absl-py==0.7.1
astor==0.7.1
certifi==2019.6.16
cloudpickle==1.2.1
cycler==0.10.0
cytoolz==0.10.0
dask==2.1.0
decorator==4.4.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
grpcio==1.16.1
h5py==2.9.0
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.13.2
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
mkl-fft==1.0.12
mkl-random==1.0.2
mkl-service==2.0.2
mock==3.0.5
networkx==2.3
numpy==1.16.2
nvidia-ml-py3==7.352.1
olefile==0.46
pathlib==1.0.1
Pillow==6.1.0
protobuf==3.8.0
psutil==5.6.3
pyparsing==2.4.0
pyreadline==2.1
python-dateutil==2.8.0
pytz==2019.1
PyWavelets==1.0.3
pywin32==223
PyYAML==5.1.1
scikit-image==0.15.0
scikit-learn==0.21.2
scipy==1.2.1
six==1.12.0
tensorboard==1.13.1
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
toolz==0.10.0
toposort==1.5
tornado==6.0.3
tqdm==4.32.1
Werkzeug==0.15.4
wincertstore==0.2

============== Conda Packages ==============
# packages in environment at C:\Users\Administrator\MiniConda3\envs\faceswap:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.7.1                    py36_0  
astor                     0.7.1                    py36_0  
blas                      1.0                         mkl  
ca-certificates           2019.5.15                     0  
certifi                   2019.6.16                py36_0  
cloudpickle               1.2.1                      py_0  
cycler                    0.10.0           py36h009560c_0  
cytoolz                   0.10.0           py36he774522_0  
dask-core                 2.1.0                      py_0  
decorator                 4.4.0                    py36_1  
fastcluster               1.1.25          py36h830ac7b_1000    conda-forge
ffmpeg                    4.1.3                h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1  
gast                      0.2.2                    py36_0  
grpcio                    1.16.1           py36h351948d_1  
h5py                      2.9.0            py36h5e291fa_0  
hdf5                      1.10.4               h7ebc959_0  
icc_rt                    2019.0.0             h0cc432a_1  
icu                       58.2                 ha66f8fd_1  
imageio                   2.5.0                    py36_0  
imageio-ffmpeg            0.3.0                      py_0    conda-forge
intel-openmp              2019.4                      245  
joblib                    0.13.2                   py36_0  
jpeg                      9c                hfa6e2cd_1001    conda-forge
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py36_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py36ha925a31_0  
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
liblapacke                3.8.0                     8_mkl    conda-forge
libmklml                  2019.0.3                      0  
libpng                    1.6.37               h7602738_0    conda-forge
libprotobuf               3.8.0                h7bd577a_0  
libtiff                   4.0.10            h6512ee2_1003    conda-forge
libwebp                   1.0.2                hfa6e2cd_2    conda-forge
lz4-c                     1.8.3             he025d50_1001    conda-forge
markdown                  3.1.1                    py36_0  
matplotlib                2.2.2            py36had4c4a9_2  
mkl                       2019.4                      245  
mkl-service               2.0.2            py36he774522_0  
mkl_fft                   1.0.12           py36h14836fe_0  
mkl_random                1.0.2            py36h343c172_0  
mock                      3.0.5                    py36_0  
networkx                  2.3                        py_0  
numpy                     1.16.2           py36h19fb1c0_0  
numpy-base                1.16.2           py36hc3f5095_0  
nvidia-ml-py3             7.352.1                  pypi_0    pypi
olefile                   0.46                     py36_0  
opencv                    4.1.0            py36hb4945ee_6    conda-forge
openssl                   1.1.1c               he774522_1  
pathlib                   1.0.1                    py36_1  
pillow                    6.1.0            py36hdc69c19_0  
pip                       19.1.1                   py36_0  
protobuf                  3.8.0            py36h33f27b4_0  
psutil                    5.6.3            py36he774522_0  
pyparsing                 2.4.0                      py_0  
pyqt                      5.9.2            py36h6538335_2  
pyreadline                2.1                      py36_1  
python                    3.6.8                h9f7ef89_7  
python-dateutil           2.8.0                    py36_0  
pytz                      2019.1                     py_0  
pywavelets                1.0.3            py36h8c2d366_1  
pywin32                   223              py36hfa6e2cd_1  
pyyaml                    5.1.1            py36he774522_0  
qt                        5.9.7                hc6833c9_1    conda-forge
scikit-image              0.15.0           py36ha925a31_0  
scikit-learn              0.21.2           py36h6288b17_0  
scipy                     1.2.1            py36h29ff71c_0  
setuptools                41.0.1                   py36_0  
sip                       4.19.8           py36h6538335_0  
six                       1.12.0                   py36_0  
sqlite                    3.29.0               he774522_0  
tensorboard               1.13.1           py36h33f27b4_0  
tensorflow                1.13.1          mkl_py36hd212fbe_0  
tensorflow-base           1.13.1          mkl_py36hcaf7020_0  
tensorflow-estimator      1.13.0                     py_0  
termcolor                 1.1.0                    py36_1  
tk                        8.6.8                hfa6e2cd_0  
toolz                     0.10.0                     py_0  
toposort                  1.5                        py_3    conda-forge
tornado                   6.0.3            py36he774522_0  
tqdm                      4.32.1                     py_0  
vc                        14.1                 h0510ff6_4  
vs2015_runtime            14.15.26706          h3a45250_4  
werkzeug                  0.15.4                     py_0  
wheel                     0.33.4                   py36_0  
wincertstore              0.2              py36h7fe50ca_0  
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7                hc54c509_2  
zlib                      1.2.11            h2fa13f4_1005    conda-forge
zstd                      1.4.0                hd8a0e53_0    conda-forge

**Comment by bryanlyon** [comment]
Are you checking your GPU usage with Windows Task manager?  See https://faceswap.dev/forum/app.php/faqpage#f0r3 for why that is not a good idea.

**Comment by kamike** [comment]
I am really use Windows Task manager. now i use  nvidia-smi, GPU usage rate no more than %30. Most of the time it is %0,  Memory-Usage always is 220M/2048M, How should I troubleshoot where the problem is? thank you very much!

![image](https://user-images.githubusercontent.com/3920019/62002579-85f21d80-b139-11e9-8c62-5010e823bbda.png)
![image](https://user-images.githubusercontent.com/3920019/62002612-1cbeda00-b13a-11e9-8c90-b9f9bf0dbab9.png)

**Comment by torzdf** [comment]
This is a setup/configuration issue and is best discussed in the Discord server or on faceswap.dev/forum

**Comment by Dian-Yi** [comment]
Have you solved this problem? i meet the same problem. I only use tensorflow-gpu, the code dont run, must install tensorflow. when i train the model, gpu usage is less than %20 and i guess the code using cpu, but the log dont show using cpu.
