### ISSUE TITLE
Update the code to use tensorflow 1.13.0

### ISSUE THREAD

**Issue by MateuszHW** [deepfakes/faceswap#814]
**Is your feature request related to a problem? Please describe.**

Problem: Faceswap (FS) for NVIDIA crashes after update.
FS is not working with tensorflow 1.13.0 with GPU.
It seems that FS does not install (include) proper tensorflow-gpu package or cannot initialize GPU.

**Describe the solution you'd like**

Update FS to use new tensorflow and tensorflow-gpu. As for now there is tensorflow 1.14 already available :-).

**Describe alternatives you've considered**

Add option within installation with GPU support to either use CPU of GPU, when work with GPU  is not possible due to crashes of underlying libs (e.g. cuDNN failed to initialize).

**Additional context**

[crash_report.2019.07.27.223220495106.log](https://github.com/deepfakes/faceswap/files/3438597/crash_report.2019.07.27.223220495106.log)

[crash_report.2019.07.27.232237382220.log](https://github.com/deepfakes/faceswap/files/3438624/crash_report.2019.07.27.232237382220.log)

**Comment by torzdf** [comment]
Faceswap supports up to TF 1.13.1. Most likely you have a Cuda/cuDNN / TF Mismatch
