### ISSUE TITLE
CRITICAL An unexpected crash has occurred during conversion

### ISSUE THREAD

**Issue by CarterLilley** [deepfakes/faceswap#815]
[crash_report.2019.07.27.191805371170.log](https://github.com/deepfakes/faceswap/files/3438692/crash_report.2019.07.27.191805371170.log)

Attached is my crash report. Extracted about 100 photos from both parties, trained for about 2hrs. 40 mins. Applying photo face to a video of me talking. 

Not sure what's going on. I'm using a Microsoft Surface Book II, with a GTX 1060, i7, 16GB ram. 

Need help ASAP please! Working on a time sensitive project! Thanks for everyone's hard work on this very impressive and cool program. Thought I would have way more issues up until now. Thanks.

**Comment by torzdf** [comment]
This looks like a bug in face filter. Don't use the face filter and it should run through fine.

Also. 100 photos? 2 hours 40 mins? Your swap is going to be bad!

See here: https://faceswap.dev/forum/app.php/faqpage

**Comment by CarterLilley** [comment]
No, totally, I get that! This was just a preliminary test to see if I understand the workflow and process. Once I get this whole thing start to finish I'll be able to make a more complex one later this week.

Thanks for the help, by the way! I'm unsure how to not use the face filter - using the GUI version of faceswap. Is it a box or something? Sorry!

**Comment by torzdf** [comment]
You should follow the FAQ because it will take you to a guide for extraction etc.

Basically don't use the filter/nfilter box. I will look to fix it at some point, but it won't be immediate.

**Comment by CarterLilley** [comment]
I relied on the FAQ and the documentation pretty heavily to get me to this point! Im just trying to make a shitty preliminary test so that, should I not be able to do this for one reason or another, I don't waste _too_ much time haha.

So, clearing both of those fields let it run without error, and gave me a converted clip as output. Which is nice...but there appears to be no discernible difference between the before/after. No edit at all.

I knew it wouldn't be good, but I was kind of expecting at least a garbled face-mess to confirm the process is working. Should it remain completely unchanged?

**Comment by torzdf** [comment]
Usage issues are best raised in the Forum or in the Discord Server.

I am leaving this open as the initial issue is a bug.

**Comment by torzdf** [comment]
The filter/nfilter bug in convert should be fixed in latest commit
