### ISSUE TITLE
cpu and gpu usage is nearly 0%

### ISSUE THREAD

**Issue by zenglian** [deepfakes/faceswap#817]
It stucks at the first step (extracting). Both cpu/gpu usage is below 1%. How to config/tune it?

Logs:
> Loading...
> 07/29/2019 10:42:35 INFO     Log level set to: TRACE
> 07/29/2019 10:42:38 INFO     Output Directory: E:\video\mlx\fake\clips
> 07/29/2019 10:42:38 INFO     Input Video: E:\video\mlx\fake\clips\ym.mp4
> 07/29/2019 10:42:38 VERBOSE  Using 'json' serializer for alignments
> 07/29/2019 10:42:38 VERBOSE  Alignments filepath: 'E:\video\mlx\fake\clips\ym_alignments.json'
> 07/29/2019 10:42:38 INFO     Loading Detect from Mtcnn plugin...
> 07/29/2019 10:42:38 VERBOSE  Loading config: 'D:\workspaces\ai\faceswap\config\extract.ini'
> 07/29/2019 10:42:38 INFO     Loading Align from Fan plugin...
> 07/29/2019 10:42:38 VERBOSE  **GeForce MX150 - 1983MB free of 2048MB**
> 07/29/2019 10:42:38 WARNING  **Not enough free VRAM for parallel processing. Switching to serial**
> 07/29/2019 10:42:38 INFO     Starting, this may take a while...

**Comment by torzdf** [comment]
Get the latest code and try again. A bug was fixed around this recently.

As an aside, you are going to struggle with that card. Your best bet will be the Lightweight model.

I'm closing this issue off. If it persists, please reply with a full trace log (enable `loglevel` `TRACE`, let it run till about 30 seconds after it gets stuck, then post the `faceswap.log` file from your faceswap folder)

NB: Only run with tracelogging when requested. It will slow down your process and generate massive files.
