### ISSUE TITLE
Faceswap in the cloud!

### ISSUE THREAD

**Issue by permosegaard** [deepfakes/faceswap#82]
Hi all! Just wanted to let you know that i've spent some time putting some code together to run your project on a GPU instance at AWS. It's run as a spot request to reduce the cost to about $0.3/hour (at time of post).

The code's available at https://github.com/permosegaard/faceswap-aws if you want to check it out and/or reference it in your docs.

I've tried to make it as simple to approach as possible so everyone can focus on improving the model instead of wasting time getting the tooling working. A typical run would just be a "git clone [repo]; make pre-run; [place files]; make run" to cover everything, including instance creation+upload+extract+train+convert+download+instance destruction.

Hopefully this helps someone out :)

**Comment by Clorr** [comment]
Thanks for this info. If you have some code/doc modification to add here, feel free to do a pull request.

**Comment by jondubin** [comment]
@permosegaard looks awesome! i didn't see any of the faceswapping/model code itself in the repo. is it meant to be used in conjunction with this project?

**Comment by permosegaard** [comment]
@jondubin, that's correct. My project is to compliment yours, more specifically it's for people that don't have the local resources available ie. AMD GPU, can't dedicate GPU for long periods, wanting to spin up more than one run at once, etc. etc.

**Comment by gdunstone** [comment]
I'm going to close this.

When you want to add a pull request to merge your changes please reference this issue.
