### ISSUE TITLE
muti face all in one ?? can be OK?

### ISSUE THREAD

**Issue by willshion** [deepfakes/faceswap#830]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by willshion** [comment]
one model  A :3or4 kind faces    B: one faces

**Comment by zenglian** [comment]
how do you know which face to extract and ignore others?

**Comment by deepfakes** [comment]
This usage question is covered by our extract guide here:
https://faceswap.dev/forum/viewtopic.php?f=5&t=27
