### ISSUE TITLE
if this model can achieve this function？when i input Trump ‘s image and a person's image，the model could convert the trump's face to the person's image

### ISSUE THREAD

**Issue by xt479910344** [deepfakes/faceswap#840]

**Comment by torzdf** [comment]
That is pretty much exactly what this repo is.

https://faceswap.dev

**Comment by xt479910344** [comment]
> That is pretty much exactly what this repo is.
> 
> https://faceswap.dev

the model is  a general model which i can use to  convert  trump’s face to anyone‘s face  which i input  without trainning a model using Two specific people

**Comment by torzdf** [comment]
No, you need to train the model for the two people you want to swap.

https://github.com/deepfakes/faceswap/blob/master/USAGE.md
