### ISSUE TITLE
Serialization failure / ProtoBuf/ tf.GraphDef protocol buffer limit

### ISSUE THREAD

**Issue by mgreene1234** [deepfakes/faceswap#843]
It's impossible to fully utilize the multigpu functionality of faceswap because the protocol buffers of tensorflow have a limit of 2GB. Trying to run an SAE model at full scale (256 input size, 1024 ae dims, 85edims, 85ddims) will only result in an error after suffering through an eternal CA initialization. 

tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot serialize protocol buffer of type tensorflow.GraphDef as the serialized size (3350368680bytes) would be larger than the limit (2147483647 bytes)

The code needs to be fixed to implement one of several work-arounds available, e.g. https://developers.google.com/protocol-buffers/docs/techniques#streaming

**Comment by torzdf** [comment]
I have not seen this bug reported anywhere else, so I am closing this issue, as I suspect it is unique to your setup.
