### ISSUE TITLE
Incorrect EGs/sec in summary

### ISSUE THREAD

**Issue by mdingena** [deepfakes/faceswap#850]
**Describe the bug**
On the Analysis tab, the table contains information about all the training sessions. The EGs/sec is incorrect for the **Total** row. It appears to sum the EGs/sec of all sessions and divide by the number of sessions, but this is not an accurate representation of your total EGs/sec for all training sessions.

**To Reproduce**
1. Start a new model, and in the first training session, only train it for 1 iteration.
2. Start another session, and let it run for many iterations.
3. The total EGs/sec is the average of the two sessions records.

**Expected behavior**
I expect the total EGs/sec to truly represent the EGs/sec for this entire model. To do that accurately, it needs to sum the samples (iterations * batch size) for all sessions, and sum the time elapsed for all the sessions, and then divide them (total samples / total time elapsed).

The EGs/sec in the screenshot below should be 
```
1274869 samples / 63777 seconds = 19.99 EGs/sec
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13388489/63988196-5bbbc300-cb1e-11e9-8711-cbfdb9506c73.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64-bit
 - Browser (what does browser have to do with Faceswap?)

**Smartphone (please complete the following information):**
 - Device: I don't understand why this is relevant to Faceswap...

**Comment by torzdf** [comment]
Changed
