### ISSUE TITLE
Feature: AMD GPU Support

### ISSUE THREAD

**Issue by shadycuz** [deepfakes/faceswap#86]
Hey, 

  So I want in on the fun and I have been looking for a machine learning type project ever since  I seen that guy on youtube teach his computer to drive in GTA. I don't know a ton about machine learning and neural networks but I can write some decent python. 

However, I'm an AMD fanboy

Do you think we can use something like this https://github.com/hughperkins/coriander ? It recompiles cuda code for OpenCL 1.2.

I'll look into it this weekend.

Thanks,
Levi

**Comment by Clorr** [comment]
Hi !

This project does not use CUDA directly. CUDA is used in tensorflow, which maybe also have AMD support. Did you try installing the project on your machine?

**Comment by shadycuz** [comment]
@Clorr I posted to early, found the https://github.com/deepfakes/faceswap/blob/027b833e6971f28f57ba92cf12c9037e0ea222e6/INSTALL.md file that mentions the issue is with tensorflow. 

After some searching I found this, which might work, but is 4 times slower then CUDA.

https://github.com/hughperkins/tf-coriander/blob/master/doc/execution_speed.md

**Comment by AlphasCodes** [comment]
faceswap is based on the Tensorflow framework. And Tensorflow itself only supports CPU and NVIDIA GPU (CUDA). There are forks available that provide AMD GPU support for Tensorflow but these forks are very slow compared to NVIDIA (CUDA).

See my [https://github.com/AlphasCodes/DeepLearning](github page) for more information.

**Comment by Clorr** [comment]
Thanks for the info. Feel free to close the issue if it is solved ;-)

**Comment by shadycuz** [comment]
Yeah I think Im going to have to rent out an AWS machine to train =/ 

Thanks

**Comment by FalkF** [comment]
There seems to be hope :)
[how_to_do_make_deepfakes_with_an_amd_card_(linux)](https://www.reddit.com/r/deepfakes/comments/7uo04h/how_to_do_make_deepfakes_with_an_amd_card_linux/)

**Comment by iperov** [comment]
https://www.deepfakes.club/deepfakes-with-amd-graphics-card/

**Comment by shadycuz** [comment]
Hey guys, 

Thanks for coming back and posting these.

**Comment by deepfakes** [comment]
Faceswap now has partial AMD support
