### ISSUE TITLE
setup.py on Fedora 30

### ISSUE THREAD

**Issue by djhenry** [deepfakes/faceswap#860]
**Describe the bug**
When running `python setup.py` on Fedora 30, `cudnn_checkfiles_linux()` is returning cudnn_checkfiles with path /include64 rather than  /usr/include causing setup to incorrectly report "ERROR   cuDNN not found. See https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#cudnn for instructions".  

I was able to work around by creating a symlink to that path `ln -s /usr/include /include64`

I notice this `cudnn_checkfiles_linux()` is also duplicated in lib/sysinfo.py

**To Reproduce**
Follow install steps found at https://github.com/deepfakes/faceswap/blob/master/INSTALL.md#user-content-general-install-guide
(Not using Docker, using conda environment, Negativo repositories for nvidia and cuda driver, nvidia repositories for nvcc and libcudnn)

**Expected behavior**
Setup success with cuda enabled

**Desktop (please complete the following information):**
encoding:            UTF-8
git_branch:          master
git_commits:         967f97f Minor extract fixups
gpu_cuda:            10.1
gpu_cudnn:           7.6.3
gpu_devices:         GPU_0: GeForce RTX 2080
gpu_devices_active:  GPU_0
gpu_driver:          430.40
gpu_vram:            GPU_0: 7979MB
os_machine:          x86_64
os_platform:         Linux-5.2.9-200.fc30.x86_64-x86_64-with-fedora-30-Thirty
os_release:          5.2.9-200.fc30.x86_64
py_command:          faceswap.py gui
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.7.4
py_virtual_env:      False
sys_cores:           6
sys_processor:       x86_64
sys_ram:             Total: 15972MB, Available: 6881MB, Used: 8534MB, Free: 294MB

**Comment by torzdf** [comment]
Feel free to raise a PR for checking of cuDNN on Fedora.

Unfortunately different OSes have it in different places, so it is hard to capture them all

**Comment by djhenry** [comment]
I'm relatively new to python.  I'll see what I can do.

**Comment by torzdf** [comment]
I'm closing this issue as the recommended install method for Linux is to use the install script:

https://github.com/deepfakes/faceswap/releases/tag/v1.0.0
