### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by LumingSun** [deepfakes/faceswap#861]
**Describe the bug**
When I build the docker file (GPU version), there is error when RUN pip command inside the docker.

**To Reproduce**
1. followed the install instructions
2. docker build -t deepfakes-gpu -f Dockerfile.gpu .
3. Error info when executing pip (or python) command:

Could not find platform independent libraries <prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

Current thread 0x00007f3a58908700 (most recent call first):
Aborted (core dumped)

**Expected behavior**
I tried to set PYTHONHOME 'RUN export PYTHONHOME=/usr/local/lib/python3.5' but still doesn't work.
And I tried 'RUN python' but got the same error

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - GPU docker cuda-9.0

**Comment by torzdf** [comment]
Whilst we maintain a Docker build, none of the devs actively use or support it. We welcome PRs to fix any issues though.
