### ISSUE TITLE
A critical Error occured

### ISSUE THREAD

**Issue by gthb96** [deepfakes/faceswap#863]
I try to sort images using the provided guide but the application crashed immediately.
What to do against this?
I uploaded the crash log.

[crash_report.2019.09.04.191917786563.log](https://github.com/deepfakes/faceswap/files/3575740/crash_report.2019.09.04.191917786563.log)

**Comment by kvrooman** [comment]
to be clear, you have no GPU and are running this on the CPU?

**Comment by gthb96** [comment]
Yes I am running on a VM in the cloud.
Now it works after clicking "Update Faceswap..."
It downloaded some plugin... I don't know why it didn't install that plugin in the first time.

Sorry for the "bug report"

**Comment by kvrooman** [comment]
No worries... so all working? Please close if resolved. Thanks

**Comment by gthb96** [comment]
The sorting part is working now.
Thanks for your quick contribution.
