### ISSUE TITLE
The Python script is not working in Linux Mint.

### ISSUE THREAD

**Issue by januarionclx** [deepfakes/faceswap#864]
The full details of the system:

`RELEASE=19.1
CODENAME=tessa
EDITION="Xfce"
DESCRIPTION="Linux Mint 19.1 Tessa"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=https://www.linuxmint.com/rel_tessa_xfce_whatsnew.php
RELEASE_NOTES_URL=https://www.linuxmint.com/rel_tessa_xfce.php
USER_GUIDE_URL=https://www.linuxmint.com/documentation.php
GRUB_TITLE=Linux Mint 19.1 Xfce`

The actual error (for any parameter to faceswap.py)
```
Traceback (most recent call last):
  File "faceswap.py", line 5, in <module>
    import lib.cli as cli
  File "/home/januario/Documents/faceswap/lib/cli.py", line 16, in <module>
    from lib.logger import crash_log, log_setup
  File "/home/januario/Documents/faceswap/lib/logger.py", line 5, in <module>
    from logging.handlers import QueueHandler, QueueListener, RotatingFileHandler
ImportError: cannot import name QueueHandler
```

Yeah I could try Docker or simply installing this on Windows, but thought it would be a good idea to report 🤷

**Comment by torzdf** [comment]
You haven't activated your environment
