### ISSUE TITLE
cannot extract faces from video

### ISSUE THREAD

**Issue by ok-sweat** [deepfakes/faceswap#866]
After finish basis settings, I execute
 `python faceswap.py extract -i ~/faceswap/src/trump.mp4 -o ~/faceswap/faces/trump`
in the terminal followed by the instructions.

But there is no output and bugs, just a dialog in command line:
`Setting Faceswap backend to NVIDIA`
`09/07/2019 10:45:12 INFO     Log level set to: INFO`

there are no faces in ~/faceswap/faces/trump

**Comment by Charles-Bao** [comment]
Same here, using anaconda3 in Windows 10. GPU is 1080Ti, manually installed tk and tensorflow-gpu(1.14) as instructed in Install.md

**Comment by MG2033** [comment]
Refer to this:

https://github.com/deepfakes/faceswap/issues/867#issuecomment-531588430
