### ISSUE TITLE
extracting not working

### ISSUE THREAD

**Issue by Banginpadr** [deepfakes/faceswap#867]
**Describe the bug**
it keep  stoping at some point of extracting the frames from videos or even photos. it will stop at 19%.
im also using all the cpu modes because it cant extract using my gpu. im using a mac pro  python 3.6

**Comment by torzdf** [comment]
There is a refactor of extract coming in the next few days. I suggest you wait for that and then let me know if the issue persists afterwards

**Comment by MG2033** [comment]
Install packages: pynvml and fastcluster using pip or conda.

**Comment by ok-sweat** [comment]
problem solved, thanks!
