### ISSUE TITLE
Install error for setup nvidia

### ISSUE THREAD

**Issue by Marechal17** [deepfakes/faceswap#875]
I install with CPU => ok

I install with GPU, and when i click on launcher =>
![Sans titre](https://user-images.githubusercontent.com/53652826/65102639-014ead80-d9cc-11e9-914a-fd98e93679ac.png)

During installation I got this error : => 
ERROR conda.core.link:_execute(700)
errno 13 permission denied

torzdf say : 
https://faceswap.dev/forum/app.php/faqpage#f1r1

@torzdf, Yes I do every task below but install work only with install CPU. (I try 5 times and do every step)

Uninstall Conda: Add/Remove programs > python (Check for both MiniConda and AnaConda)
Uninstall any other Python installs you have on your system.
Go to your
C:\users\<your username>
folder and delete any files/folders with "conda" in the name
Go to your
 C:\users\<your username>\AppData\Roaming
folder and delete any folders with "Python" in the name
Delete your Faceswap folder
Reboot
Re-run the faceswap installer

But always same error.

for info my config
1050 Ti, Win 7  

(with another pc config:  1050, win 10 => no error)

**Comment by Marechal17** [comment]
During installation I got error : => 
ERROR conda.core.link:_execute(700)
errno 13 permission denied

**Comment by torzdf** [comment]
Windows 7 is not directly supported and is untested, so it may or may not be to do with this.

Either way, you are better off getting support on usage on either the discord server or the forums (links in README.md). These issues are for code issues.
