### ISSUE TITLE
Extracted samples 

### ISSUE THREAD

**Issue by akatray** [deepfakes/faceswap#876]
Any chance to get the function to recombine extracted faces back to source images?
It could just be convert function that skips transformation and places original face back onto image.
This would be very useful to test external program that loads extracted samples, transforms them and saves back to file. External program only capabilities to learn and transform.

**Comment by bryanlyon** [comment]
This is already how Faceswap works.  It will convert a face on the original image.

**Comment by akatray** [comment]
I mean not to convert face. If i extract A faces I need converter to add them back.

**Comment by torzdf** [comment]
I'm not sure what you're asking. You want the converter to output frames with the original faces on the original frames....

Which is just the original frames? So just use the original frames??

**Comment by akatray** [comment]
Extractor cuts faces out to aligned folder. External program then transforms all images in aligned folder.
Then I need something that places them back to original picture. Converter already does that, but I need it to skip Prediction/Transformation. Like converter flag to skip prediction step.

**Comment by kvrooman** [comment]
so just have ffmpeg split a video into frames?

**Comment by torzdf** [comment]
Yeah, we wont be implementing that as I can't see how that will be useful to the project. Sorry.

**Comment by akatray** [comment]
My rational is someone familiar with codebase could do this in less than hour. For me it will take days. But can't blame you. It is specific thing to ask.
