### ISSUE TITLE
Windows 10 Conda setup

### ISSUE THREAD

**Issue by stevepowellGV** [deepfakes/faceswap#877]
**Describe the bug**
When running python setup.py on Windows 10 on a clean `conda 4.7.10` virtual machine, the script is failing with the following stack trace - 

```
INFO    Running as Root/Admin
INFO    The tool provides tips for installation
        and installs required python packages
INFO    Setup in Windows 10
INFO    Installed Python: 3.5.6 64bit
INFO    Running in Conda
INFO    Running in a Virtual Environment
INFO    Encoding: cp1252
INFO    Installed pip: 10.0.1
Traceback (most recent call last):
  File "setup.py", line 803, in <module>
    ENV = Environment()
  File "setup.py", line 56, in __init__
    self.installed_packages = self.get_installed_packages()
  File "setup.py", line 195, in get_installed_packages
    shell=True, stdout=PIPE)
  File "C:\Users\User\Miniconda3\envs\faceswap_gpu\lib\subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "C:\Users\User\Miniconda3\envs\faceswap_gpu\lib\subprocess.py", line 957, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**To Reproduce**
1 Create a VM in Anaconda (I used Miniconda)
2. Activate the VM
3. Download the code for faceswap from git
4. Run setup.py

**Expected behavior**
The setup script should run and install all dependencies for faceswap

**Desktop (please complete the following information):**
 - OS: Windows 10
-  Miniconda 4.7.10
```
# packages in environment at C:\Users\User\Miniconda3\envs\faceswap_gpu:
#
# Name                    Version                   Build  Channel
certifi                   2018.8.24                py35_1
pip                       10.0.1                   py35_0
python                    3.5.6                he025d50_0
setuptools                40.2.0                   py35_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
wheel                     0.31.1                   py35_0
wincertstore              0.2              py35hfebbdb8_0
```

**Comment by torzdf** [comment]
This is a conda issue :/

My advice would be to completely remove Conda from your machine, clean it up (as per: https://faceswap.dev/forum/app.php/faqpage?sid=6c5e612f4f04596edebf98168c1ecb8f#f1r1) and run the latest installer from here: https://github.com/deepfakes/faceswap/releases/tag/v1.0.0

**Comment by stevepowellGV** [comment]
Many thanks. I'll give that a go and see how I get on.

**Comment by stevepowellGV** [comment]
Cleared out my installs - Conda and Python, cleaned up as per the instructions. 

Running the all-in-one installer ran into a problem creating the Conda envirnment...
![miniconda_fail](https://user-images.githubusercontent.com/20094391/65422829-79b7d300-ddff-11e9-8983-94007378881d.png)

I tried creating the environment manually from Miniconda command line, which worked fine - but then ran into the same issue with the setup script as before.

**Comment by fuomag9** [comment]
@stevepowellGV I incurred into the same error, I installed miniconda without creating anything and the installer worked. Remember to remove the old Anaconda folders as they contain libraries and stuff that may break the installer

**Comment by stevepowellGV** [comment]
Still having no success with that.
I cleaned out all Anaconda/Miniconda files. Restarted, successfully installed Miniconda and ran the faceswap install package. Got exactly the same error.

I tried a couple of times, running the installer under main user, and again with admin privileges. Same problem.

Again, I was able to create a conda environment from the command line without any problems,

**Comment by torzdf** [comment]
This is a Conda issue, not a faceswap issue. We have seen this problem before, when Conda made changes.

You can try installing an older version of miniconda. 4.5.12 is known to work

**Comment by stevepowellGV** [comment]
Ok thanks, I'll give that a try.

**Comment by stevepowellGV** [comment]
Thanks for that suggestion. Obviously it's not your issue, but for some reason I was unable to install that older version of Miniconda. The errors returned were strangely similar to those I get trying to run the Faceswap install script.
![miniconda3-4-5-12-screen1](https://user-images.githubusercontent.com/20094391/65698567-a1fc3780-e074-11e9-95a3-eccf7e9eabc1.png)
![miniconda3-4-5-12-screen2](https://user-images.githubusercontent.com/20094391/65698577-a6c0eb80-e074-11e9-9a25-f147a5aca1be.png)

**Comment by bryanlyon** [comment]
Yes, this is a bug with the conda installer or your local install.  Unfortunately there is really nothing that we can do about this ourselves.  Our only suggestion is to try a clean install.  Remove all signs of Python and Conda and try again.  If that doesn't solve it, please raise an issue with Anaconda as they're the only ones who could resolve it.
