### ISSUE TITLE
Training Fail every time

### ISSUE THREAD

**Issue by mynoulol** [deepfakes/faceswap#878]
somebody could help me? I'm new and I don't know what happens when I try train on faceapp

undefinedUsing GPU0 for processing
Traceback (most recent call last):
  File "execute.py", line 69, in <module>
  File "train.py", line 42, in main
MemoryError
[8080] Failed to execute script execute

my pc:
i5 3570k
16Gb RAM
gigabite 1060 3gb
Thank you.

**Comment by bryanlyon** [comment]
This repo is for FaceSwap, not Faceapp.  If the problem you're having is for FaceSwap please go to https://faceswap.dev/forum/ or our Discord and post your crash log.
