### ISSUE TITLE
MacOS issue GUI

### ISSUE THREAD

**Issue by s1rleblanc** [deepfakes/faceswap#882]
Hi all!,
I am on MacOS and when i run "$ python faceswap.py gui" the screen goes black and close everything on the finder and comes with login screen and i logging in again  as if I hadn't logged in.

MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Setting up for PlaidML
MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Using GPU: ['opencl_amd_radeon_pro_vega_20_compute_engine.0']
MainProcess     MainThread      plaidml_tools   setup_plaidml             INFO     Successfully set up for PlaidML

this is all appears at faceswap_gui.log file... any one know if im doing something wrong ?..

Thank you in advance...

**Comment by torzdf** [comment]
Whilst Faceswap runs on MacOS, none of the current devs have a Mac to test on. You will probably be best off getting help on either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg)
