### ISSUE TITLE
How to train model with a mask in faceswap ?

### ISSUE THREAD

**Issue by qiaoerr** [deepfakes/faceswap#883]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by torzdf** [comment]
For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg)
