### ISSUE TITLE
Face Reenactment model? (Similar to AVATAR by DFL)

### ISSUE THREAD

**Issue by cbsudux** [deepfakes/faceswap#893]
**Is your feature request related to a problem? Please describe.**
Looking for a face reenactment model, like AVATAR by DeepFaceLab. (https://www.youtube.com/watch?v=rRGOQpR_3hw)

**Describe the solution you'd like**
The face's aren't swapped, but one face's expressions are transferred to another. Like Face2Face (https://www.youtube.com/watch?v=ohmajJTcpNk)

**Describe alternatives you've considered**
AVATAR by DFL

**Comment by deepfakes** [comment]
We have no plans to port this model as we don't believe it is of a high enough quality. We do welcome PRs though

**Comment by cbsudux** [comment]
Oh okay, I'd love to contribute. Any suggestions for papers/implementations? (Apart from avatar)

**Comment by torzdf** [comment]
You're best bet is to come to our Discord Server. Link on the front page.
