### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute '__all__'

### ISSUE THREAD

**Issue by mehrdadazizi72** [deepfakes/faceswap#898]
**Describe the bug**
I run GUI and extract faces then run train but error happened.

**To Reproduce**
1. run python3 faceswap.py gui
2. Click on train tab
3. Set input and outputs parameters
4. Click on train bottom
5. See error

 - OS: Ubuntu 18.04
 - Python Version 3.6.7
 - Commit ID 5887cb5
[crash_report.2019.10.08.105533436934.log](https://github.com/deepfakes/faceswap/files/3703313/crash_report.2019.10.08.105533436934.log)

**Comment by torzdf** [comment]
This is an internal error to Tensorflow, most likely caused by a conflict.

You have not installed in a virtual environment, we cannot possibly troubleshoot all possible conflicts.

You should install faceswap inside a virtual environment.
