### ISSUE TITLE
Tensorflow import error

### ISSUE THREAD

**Issue by jcplemons** [deepfakes/faceswap#901]
## Expected behavior

Successful initial execution of command "python faceswap.py gui"

## Actual behavior

Failure of "python faceswap.py gui" due to unsuccessful import of Tensorflow – specifically, error message “ImportError: libComputeCpp.so: cannot open shared object file: No such file or directory”

## Steps to reproduce

Executed steps described in “https://github.com/deepfakes/faceswap/blob/master/INSTALL.md”, section “Setup” (installation of Anaconda, creation of faceswap virtual environment, successful install via “python setup.py”, answering “Enable AMD Support? [y/N]” as “y” and “Please ensure your System Dependencies are met. Continue? [y/N]” as “y”).

## Other relevant information
- Operating system and version: Linux Mint 19.2, kernel 5.2.11.
- Python version: 3.6.9
- Faceswap version: Not sure how to determine
- Faceswap method: Not sure how to determine – I have a Ryzen 2400g CPU, which contains Radeon RX Vega 11 Graphics onboard.
- Other related issues: Similar to issue #880 except that this user appears to have been configuring for NVIDIA rather than AMD as I am.
- Tensorflow status:“conda install tensorflow” yields “# All requested packages already installed.”, so I know Tensorflow exists in some fashion somehow.

[crash_report.2019.10.09.115211782283.log](https://github.com/deepfakes/faceswap/files/3708563/crash_report.2019.10.09.115211782283.log)

**Comment by kilroythethird** [comment]
This might be related to `tensorflow==1.5.0rc0` you have installed via pip.
Not sure if that coming from outside your env or not, but `pip uninstall tensorflow` might already solve your problem.
AFAIK the only project using `libComputeCpp.so` is https://github.com/codeplaysoftware/tensorflow so maybe you tried that one once ?

Additionally it looks like we don't detect your GPU.
If after uninstalling tensorflow==1.5.0rc0 it still won't work try running `plaidml-setup`.
Select experimental and the opencl version.
If you only see llvm as option there you are missing opencl support and need to install an opencl driver.

**Comment by jcplemons** [comment]
Beautiful - tensorflow version was the problem - simply uninstalling righted things.  BTW, appreciate your help even though this was not an issue with faceswap itself.  Now to locate an OpenCL driver for Ryzen 5 2400g . . .
