### ISSUE TITLE
-w ffmepg gives the output video just the same as the input

### ISSUE THREAD

**Issue by MengXinChengXuYuan** [deepfakes/faceswap#906]
Hi all training process goes well and I can get a good A <-> B result according to the preview pic
However when I tried to finish the whole process by converting a mp4 file with the code below:
`python faceswap.py convert 
-i /xxx/faceswap/test.mp4
-o /xxx/faceswap/output_fake/ 
-m /xxx/faceswap/model_snapshot_75001_iters/ 
-g 1  -c seamless-clone -w ffmpeg
`
The converted mp4 file is always the same as the input.
I'm sure the model is well trained and saved correctly, beacause if I run the above code in defaut saving mode, which saves the converted result as a seriers images, the result is correct (the face is swap correctly)

I tried to debug by following the whole process, but sorry the project is too complex for me.
I traced in scripts/convert.py, func process, I think self.convert_images() goes well (I can get the correctly converted image in defaut saing mode),  but self.disk_io.save_thread.join() is getting the wrong input (the unconverted images) with -w ffmpeg flag?

Is this a bug?

**Comment by kilroythethird** [comment]
First of all: are you sure you use the same command for both converts ?
If not 100% sure try adding `-s` to swap the sides.

Additionally, and probably unrelated to your problem:
- Seamless clone is not really a good option for videos
- You are using your model_snapshot folder. The snapshots are normally only to restore the model in case something goes wrong.
