### ISSUE TITLE
Error thrown when convert 

### ISSUE THREAD

**Issue by Maxinger15** [deepfakes/faceswap#917]
#763 
**Describe the bug**
I get the same Problem as in the tagged issue.

**To Reproduce**
1. Go to convert
2. InputDir = a mp4 Video
3. OutputDir = some Folder I don't think this is important
4. ModelDir = The Folder from the trained Model
ColorAdjustment: Color-Transfer (other values don't change the result)
Mask Type: Dfl Full
Scaling: Sharpen
Writer: Ffmpeg
Settings->Trainer: villain (because I trained the model with villain)
everything else is default.
the press convert and in the last part of the convertion the error rises.
Sometimes the reuslt video is playable but has no sound and sometimes it is not playable.

Error Log:
https://pastebin.com/BvMdU0RV

Looking forward to hearing from you :) @torzdf

**Comment by lixun95** [comment]
I got the same problem too. 
I test a mini video with a man whose face is without rotation, and it works.
But with rotation, it doesn't. That's why?
Looking forward to resolution.

**Comment by Maxinger15** [comment]
I spoke with torzdf on discord and it looks like it is a error in the function that detects the faces in the video. 
To fix it:
Go to tools -> EFFMPEG
in the action section select extract.
Input: The video you want to convert.
Output: any folder where the frames from the video will be saved
Fps: -1
the press the button effmpeg.
Then go to extract and extract the faces from the frames of the video like you do it for your training data. Check the results and delete the wrong detected faces. Refactor the aligment to remove the deleted faces from it.
Then go to convert.
InputFile: File with the frames from the video (not the extracted faces!!!)
output dir: where the video would be saved
aligments: aligments file in the frame folder.
reference Video: the original video
every thing else like you want it. 
This fixed it for me.
For a good tutorial for extraction and refactor the aligment file look at https://forum.faceswap.dev/viewtopic.php?f=5&t=27
