### ISSUE TITLE
Error: alignments file not found

### ISSUE THREAD

**Issue by Tylersuard** [deepfakes/faceswap#919]
Error: Alignments file not found at C:\Users\tyler\Desktop\KenGolfSwap\kenvids\GolfOrigTrimmed_alignments.fsa.fsa
10/30/2019 00:49:52 INFO     To get more information on this error see the crash report written to 'C:\Users\tyler\faceswap\crash_report.2019.10.30.004952109519.log'

I think it might have something to do with the program appending a second ".fsa" to the file name?

**Comment by torzdf** [comment]
Should be fixed in latest commit

**Comment by Tylersuard** [comment]
Thank you for fixing that :)  Should I just update?
