### ISSUE TITLE
New repo:GAN convert found issue: Failed to convert image:XXX. Reason: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ruah1984** [deepfakes/faceswap#93]
I use back previous model to run convert with the new repo found below issue
Failed to convert image: C:\Users\photo\video-frame-98.png. Reason: 'NoneType' object is not iterable

or i need to train a new model before run convert?

**Comment by Clorr** [comment]
Models did not change AFAIK

If you use gan, it is not yet finished, so please add this to the pull request so that we know that the error belongs there

**Comment by WesleyNery** [comment]
I had this NoneType issue when my machine crashed and corrupted my source images...try opening that one or the entire folder to see.

**Comment by gdunstone** [comment]
This was my bad, I wasn't checking a value in the converter.

If this is still an issue please reopen.

**Comment by gdunstone** [comment]
here is the pull request where I made the changes:
https://github.com/deepfakes/faceswap/pull/95/

**Comment by ruah1984** [comment]
@gdunstone , fix.
show loading bar when convert.

https://imgur.com/a/3WtFb

**Comment by gdunstone** [comment]
is this fixed? I cant see anything wrong with your screenshot

**Comment by ruah1984** [comment]
The screen shoot only show convert can be done without error with loading bar. After this try , no more error for "Failed to convert image:XXX. Reason: 'NoneType' object is not iterable". 

i think the issue maybe due to i forget to copy the "shape_predictor_68_face_landmarks.dat" to this repo. and it not able to apply the face shape landmark.

**Comment by gdunstone** [comment]
No it was my coding error.
