### ISSUE TITLE
run problems

### ISSUE THREAD

**Issue by wp2333** [deepfakes/faceswap#930]
when i satisfy all the requirements,and i run:
`python faceswap.py extract -i ./data/trump -o ./face/trump`

it raise: 
Setting Faceswap backend to NVIDIA
11/10/2019 18:12:52 INFO     Log level set to: INFO

but nothing happened!

of course,i have dataset.

what's happen?thx for your answer

**Comment by s1rleblanc** [comment]
i have problem with extract too... something like this:

File "/Developer/faceswap/plugins/extract/detect/_base.py", line 199, in to_detected_face
y=int(round(top)),
OverflowError: cannot convert float infinity to integer

**Comment by lgtming** [comment]
i have problem with extract too...

**Comment by seta-quynhbui** [comment]
yeah, i have the same problem with extract too, i run;
`python faceswap.py gui `

**Comment by beleafs** [comment]
Got the exact same problem. Clean Windows 10 installation with Nvidia GPUs

**Comment by eliliam** [comment]
I'm still having the same problem as well, and as I have multiple conda environments, I cannot just blow away and reinstall it. Has anyone had any success outside of this atomic option?

**Comment by eliliam** [comment]
Update:
I fixed my issue by changing my conda environment's python version from 3.7 to 3.6 and re-running pip install -r requirements.txt

**Comment by ZackJohn** [comment]
I have a problem with extract too... 
face = cv2.resize(face, dsize=sizes, interpolation=interpolation)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

02/15/2020 18:51:45 CRITICAL An unexpected crash has occurred. Crash report written to '/home/zph/faceswap/crash_report.2020.02.15.185145448631.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting

Running pass 1 of 1: Extraction:   3%|▏    | 1022/33830 [00:34<17:50, 30.64it/s]terminate called without an active exception
Aborted (core dumped)

**Comment by torzdf** [comment]
@ZackJohn This bug has finally been found and fixed in latest commit
