### ISSUE TITLE
IndexError: Tuple index out of range, Training, Ubuntu 18.04 & Windows 10

### ISSUE THREAD

**Issue by lesreaper** [deepfakes/faceswap#934]
## Expected behavior

Went to start training, attempted in both GUI and command line. Expected Tensorboard to load and training to begin.

## Actual behavior

```
1/16/2019 23:52:20 INFO     Enabled TensorBoard Logging
11/16/2019 23:52:25 CRITICAL Error caught! Exiting...
11/16/2019 23:52:25 ERROR    Caught exception in thread: 'training_0'
11/16/2019 23:52:25 ERROR    Got Exception on main handler:
Traceback (most recent call last):

...

File "/home/username/faceswap/lib/training_data.py", line 214, in _process_batch
    self._processing.initialize(batch.shape[1])
IndexError: tuple index out of range
```

## Steps to reproduce

Extracted faces from images, cleaned up the folder if images were not good.
In training, added folder of original person in A, person to swap in on B. Added image alignment folder, added directory for model output. Set up timelapse folder.

## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Ubuntu 18.04
- **Python version: 3.6.8
- **Faceswap version: `578aec2 Update INSTALL.md`
- **Faceswap method:** GPU, CUDA 10.0

Link to crashfile: https://www.dropbox.com/s/088t1j0q5bwnpw2/crash_report.2019.11.17.002746410979.log?dl=0

**Comment by lesreaper** [comment]
I just ran this on another Linux machine, 19.04, fresh install of Faceswap, ran the extractions, and went to train with the files provided.

Same error.

Tried lowering batch sizes in case it was a GPU memory error, but didn't matter.

System difference: CUDA 10.1, Python 3.7

In the logs, neither of them seem to find cuDnn, thought the libraries are clearly installed, don't know if that plays a part.

**Comment by lesreaper** [comment]
I just did the same exact process on a Windows 10 machine, CUDA 10.1, cuDNN installed, and same exact error.

**Comment by torzdf** [comment]
```
Loading minibatch generator: (image_count: 0, side: 'b', do_shuffle: False)
```

You have specified a timelapse folder with no faces in it.

**Comment by lesreaper** [comment]
Awesome, thank you that fixed it!
