### ISSUE TITLE
blocked when specify the filer

### ISSUE THREAD

**Issue by karvn** [deepfakes/faceswap#936]
**Describe the bug**
1 update faceswap from menu--help-Update faceswap
2 restart faceswap
3 extract face, specify mutiple filter images to the "filter"
4 run the extract
5 the progress don't go ahead, and blocked
6 All verbose logs print to console is:
Loading...
Setting Faceswap backend to NVIDIA
11/19/2019 21:18:15 INFO     Log level set to: VERBOSE
11/19/2019 21:18:17 INFO     Output Directory: C:\fw\Characters\Crystal\faces

11/19/2019 21:18:17 VERBOSE  Alignments filepath: 'C:\fw\Characters\Crystal\assets\Crystal_alignments.fsa'
11/19/2019 21:18:17 INFO     Extracting and aligning face for Face Filter...
11/19/2019 21:18:17 INFO     Filter: ['C:\\fw\\Characters\\Crystal\\filter\\Crystal01.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal02.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal03.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal04.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal05.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal06.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal07.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal08.jpg', 'C:\\fw\\Characters\\Crystal\\filter\\Crystal09.jpg']
11/19/2019 21:18:19 INFO     Loading Detect from Cv2_Dnn plugin...
11/19/2019 21:18:19 VERBOSE  Loading config: 'C:\Users\bd\faceswap\config\extract.ini'
11/19/2019 21:18:19 INFO     Loading Align from Cv2_Dnn plugin...
11/19/2019 21:18:19 VERBOSE  Loading config: 'C:\Users\bd\faceswap\config\extract.ini'
11/19/2019 21:18:19 VERBOSE  GeForce GTX 1080 Ti - 10675MB free of 11264MB

**Desktop (please complete the following information):**
============ System Information ============
encoding:            cp936
git_branch:          master
git_commits:         d5c2063 fix to error on out of bounds. 578aec2 Update INSTALL.md. e4b7717 Minor fixes. 47681a8 Landmarks stored and used as floating point numbers (#928). 36be6cd Vectorize FAN post-processing (#926)
gpu_cuda:            10.0
gpu_cudnn:           7.4.2
gpu_devices:         GPU_0: GeForce GTX 1080 Ti
gpu_devices_active:  GPU_0
gpu_driver:          441.12
gpu_vram:            GPU_0: 11264MB
os_machine:          AMD64
os_platform:         Windows-10-10.0.18362-SP0
os_release:          10
py_command:          C:\Users\bd\faceswap/faceswap.py gui
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.7.4
py_virtual_env:      False
sys_cores:           12
sys_processor:       Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
sys_ram:             Total: 48959MB, Available: 38366MB, Used: 10592MB, Free: 38366MB

**Crash Report**
Threre is not creash report files in the root of faceswap directory

**Comment by bryanlyon** [comment]
Please run with logging set to trace, zip the faceswap.log file and send that to us.  The current information is not enough to go off of,.

However, filter is a less than ideal solution for filtering (ironic we know), we recommend instead following the extract guide in our forums and using the sort tool after extract instead.

**Comment by karvn** [comment]
I attach the trace logs.
I may use sort tool, thank you.

[trace.zip](https://github.com/deepfakes/faceswap/files/3867118/trace.zip)

**Comment by RomanSteinberg** [comment]
I think I have a related issue. But I use "extract" with default parameters (I don't touch filter). It runs for 1 batch and handles on the detection. 

Like [here](https://pastenow.ru/1b4a9c88878278f554677e35b153cfd5). This is my trace:
[faceswap.log](https://github.com/deepfakes/faceswap/files/3882454/faceswap.log).
.

**Comment by RomanSteinberg** [comment]
I checked out into  54b6e860084bf21f7971ed0c35ec96bc686d8403 and now extract images works correctly.
