### ISSUE TITLE
extract error

### ISSUE THREAD

**Issue by wa15aa** [deepfakes/faceswap#938]
`Running pass 2 of 3: Align:   0%|                         | 0/1 [00:05<?, ?it/s]WARNING: Could not generate requirement for distribution -vidia-ml-py3 7.352.1 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages): Parse error at "'-vidia-m'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -ensorflow 2.0.0 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages): Parse error at "'-ensorfl'": Expected W:(abcd...)
WARNING: Could not generate requirement for distribution -ensorboard 1.14.0 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages): Parse error at "'-ensorbo'": Expected W:(abcd...)
11/20/2019 07:55:06 ERROR    Got Exception on main handler: 
.....
IndexError: index 64 is out of bounds for axis 3 with size 64
11/20/2019 07:55:06 CRITICAL An unexpected crash has occurred. Crash report written to '/Users/xxx/Downloads/faceswap-master/crash_report.2019.11.20.075506446544.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
Running pass 2 of 3: Align:   0%|                         | 0/1 [00:25<?, ?it/s]

`

**Comment by wa15aa** [comment]
> `Running pass 2 of 3: Align: 0%| | 0/1 [00:05<?, ?it/s]WARNING: Could not generate requirement for distribution -vidia-ml-py3 7.352.1 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages): Parse error at "'-vidia-m'": Expected W:(abcd...)
> WARNING: Could not generate requirement for distribution -ensorflow 2.0.0 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages): Parse error at "'-ensorfl'": Expected W:(abcd...)
> WARNING: Could not generate requirement for distribution -ensorboard 1.14.0 (/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages): Parse error at "'-ensorbo'": Expected W:(abcd...)
> 11/20/2019 07:55:06 ERROR Got Exception on main handler:
> .....
> IndexError: index 64 is out of bounds for axis 3 with size 64
> 11/20/2019 07:55:06 CRITICAL An unexpected crash has occurred. Crash report written to '/Users/xxx/Downloads/faceswap-master/crash_report.2019.11.20.075506446544.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
> Running pass 2 of 3: Align: 0%| | 0/1 [00:25<?, ?it/s]
> 
> `

This error is triggered when i run  python3 faceswap.py extract -i ./cl_s/ -o ./cl_s_dist/

**Comment by torzdf** [comment]
```
Crash report written to '/Users/xxx/Downloads/faceswap-master/crash_report.2019.11.20.075506446544.log'. You MUST provide this file if seeking assistance.
```

**Comment by wa15aa** [comment]
> ```
> Crash report written to '/Users/xxx/Downloads/faceswap-master/crash_report.2019.11.20.075506446544.log'.
> You MUST provide this file if seeking assistance.
> ```

- [ ] 

> ```
> Crash report written to '/Users/xxx/Downloads/faceswap-master/crash_report.2019.11.20.075506446544.log'.
> You MUST provide this file if seeking assistance.
> ```

`11/20/2019 10:28:07 MainProcess     MainThread      pipeline        detected_faces            DEBUG    Running Detection. Phase: 'detect'
11/20/2019 10:28:07 MainProcess     detect_input_0  _base           _thread_process           DEBUG    Putting EOF
11/20/2019 10:28:17 MainProcess     detect_predict_0 _base           _thread_process           DEBUG    Putting EOF
11/20/2019 10:28:17 MainProcess     detect_output_0 _base           _thread_process           DEBUG    Putting EOF
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'detect_input'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'detect_input_0'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joined all Threads: 'detect_input'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'detect_predict'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'detect_predict_0'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joined all Threads: 'detect_predict'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Threads: 'detect_output'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joining Thread: 'detect_output_0'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  join                      DEBUG    Joined all Threads: 'detect_output'
11/20/2019 10:28:17 MainProcess     MainThread      pipeline        detected_faces            DEBUG    Switching to align phase
11/20/2019 10:28:17 MainProcess     MainThread      extract         _run_extraction           DEBUG    Reloading images
11/20/2019 10:28:17 MainProcess     MainThread      extract         _threaded_redirector      DEBUG    Threading task: (Task: 'reload')
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: '_reload', thread_count: 1)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: '_reload'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): '_reload'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: '_reload_0'
11/20/2019 10:28:17 MainProcess     _reload_0       extract         _reload                   DEBUG    Reload Images: Start. Detected Faces Count: 1
11/20/2019 10:28:17 MainProcess     _reload_0       image           load                      DEBUG    Initializing Load Generator
11/20/2019 10:28:17 MainProcess     _reload_0       image           _set_thread               DEBUG    Setting thread
11/20/2019 10:28:17 MainProcess     _reload_0       multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'ImagesLoader', thread_count: 1)
11/20/2019 10:28:17 MainProcess     _reload_0       multithreading  __init__                  DEBUG    Initialized MultiThread: 'ImagesLoader'
11/20/2019 10:28:17 MainProcess     _reload_0       image           _set_thread               DEBUG    Set thread: <lib.multithreading.MultiThread object at 0x154491f60>
11/20/2019 10:28:17 MainProcess     _reload_0       multithreading  start                     DEBUG    Starting thread(s): 'ImagesLoader'
11/20/2019 10:28:17 MainProcess     _reload_0       multithreading  start                     DEBUG    Starting thread 1 of 1: 'ImagesLoader_0'
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads '_reload': 1
11/20/2019 10:28:17 MainProcess     MainThread      pipeline        _launch_plugin            DEBUG    Launching align plugin
11/20/2019 10:28:17 MainProcess     MainThread      pipeline        _launch_plugin            DEBUG    in_qname: extract_align_in, out_qname: extract_mask_in
11/20/2019 10:28:17 MainProcess     MainThread      _base           initialize                DEBUG    initialize Align: (args: (), kwargs: {'in_queue': <queue.Queue object at 0x1516727f0>, 'out_queue': <queue.Queue object at 0x1516728d0>})
11/20/2019 10:28:17 MainProcess     ImagesLoader_0  image           _process                  DEBUG    Load iterator: <bound method ImagesLoader._from_folder of <lib.image.ImagesLoader object at 0x151455a58>>
11/20/2019 10:28:17 MainProcess     ImagesLoader_0  image           _from_folder              DEBUG    Loading images from folder: '/Users/wutongtong/Downloads/faceswap-master/cl_s'. with_hash: False
11/20/2019 10:28:17 MainProcess     _reload_0       multithreading  start                     DEBUG    Started all threads 'ImagesLoader': 1
11/20/2019 10:28:17 MainProcess     MainThread      _base           initialize                INFO     Initializing FAN (Align)...
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align_predict'
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'align_predict', maxsize: 1)
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'align_predict')
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align_predict'
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager getting: 'align_post'
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager adding: (name: 'align_post', maxsize: 1)
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   add_queue                 DEBUG    QueueManager added: (name: 'align_post')
11/20/2019 10:28:17 MainProcess     MainThread      queue_manager   get_queue                 DEBUG    QueueManager got: 'align_post'
11/20/2019 10:28:17 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiling align threads
11/20/2019 10:28:17 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_input, function: <bound method Align.process_input of <plugins.extract.align.fan.Align object at 0x15145ec50>>, in_queue: <queue.Queue object at 0x1516727f0>, out_queue: <queue.Queue object at 0x154491a20>)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_input', thread_count: 1)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_input'
11/20/2019 10:28:17 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_input
11/20/2019 10:28:17 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_predict, function: <bound method Aligner._predict of <plugins.extract.align.fan.Align object at 0x15145ec50>>, in_queue: <queue.Queue object at 0x154491a20>, out_queue: <queue.Queue object at 0x1544919b0>)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_predict', thread_count: 1)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_predict'
11/20/2019 10:28:17 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_predict
11/20/2019 10:28:17 MainProcess     MainThread      _base           _add_thread               DEBUG    Adding thread: (name: align_output, function: <bound method Align.process_output of <plugins.extract.align.fan.Align object at 0x15145ec50>>, in_queue: <queue.Queue object at 0x1544919b0>, out_queue: <queue.Queue object at 0x1516728d0>)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initializing MultiThread: (target: 'align_output', thread_count: 1)
11/20/2019 10:28:17 MainProcess     MainThread      multithreading  __init__                  DEBUG    Initialized MultiThread: 'align_output'
11/20/2019 10:28:17 MainProcess     MainThread      _base           _add_thread               DEBUG    Added thread: align_output
11/20/2019 10:28:17 MainProcess     MainThread      _base           _compile_threads          DEBUG    Compiled align threads: [<lib.multithreading.MultiThread object at 0x154491b00>, <lib.multithreading.MultiThread object at 0x154491828>, <lib.multithreading.MultiThread object at 0x1544917f0>]
11/20/2019 10:28:17 MainProcess     MainThread      session         load_model                VERBOSE  Initializing plugin model: FAN
11/20/2019 10:28:18 MainProcess     _reload_0       image           load                      DEBUG    Closing Load Generator
11/20/2019 10:28:18 MainProcess     _reload_0       multithreading  join                      DEBUG    Joining Threads: 'ImagesLoader'
11/20/2019 10:28:18 MainProcess     _reload_0       multithreading  join                      DEBUG    Joining Thread: 'ImagesLoader_0'
11/20/2019 10:28:18 MainProcess     _reload_0       multithreading  join                      DEBUG    Joined all Threads: 'ImagesLoader'
11/20/2019 10:28:24 MainProcess     MainThread      library         _logger_callback          INFO     Analyzing Ops: 1052 of 3641 operations complete
11/20/2019 10:28:26 MainProcess     MainThread      library         _logger_callback          INFO     Analyzing Ops: 2946 of 3641 operations complete
11/20/2019 10:28:45 MainProcess     MainThread      _base           initialize                INFO     Initialized FAN (Align) with batchsize of 12
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'align_input'
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'align_input_0'
11/20/2019 10:28:45 MainProcess     align_input_0   _base           _thread_process           DEBUG    threading: (function: 'process_input')
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'align_input': 1
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'align_predict'
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'align_predict_0'
11/20/2019 10:28:45 MainProcess     _reload_0       extract         _reload                   DEBUG    Reload Images: Complete
11/20/2019 10:28:45 MainProcess     align_predict_0 _base           _thread_process           DEBUG    threading: (function: '_predict')
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'align_predict': 1
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread(s): 'align_output'
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Starting thread 1 of 1: 'align_output_0'
11/20/2019 10:28:45 MainProcess     align_output_0  _base           _thread_process           DEBUG    threading: (function: 'process_output')
11/20/2019 10:28:45 MainProcess     MainThread      multithreading  start                     DEBUG    Started all threads 'align_output': 1
11/20/2019 10:28:45 MainProcess     MainThread      pipeline        _launch_plugin            DEBUG    Launched align plugin
11/20/2019 10:28:45 MainProcess     MainThread      pipeline        detected_faces            DEBUG    Running Detection. Phase: 'align'
11/20/2019 10:28:45 MainProcess     align_input_0   fan             process_input             DEBUG    Aligning faces around center
11/20/2019 10:28:45 MainProcess     align_input_0   fan             get_center_scale          DEBUG    Calculating center and scale
11/20/2019 10:28:45 MainProcess     align_input_0   fan             crop                      DEBUG    Cropping images
11/20/2019 10:28:45 MainProcess     align_input_0   fan             transform                 DEBUG    Transforming Points
11/20/2019 10:28:45 MainProcess     align_input_0   fan             transform                 DEBUG    Transforming Points
11/20/2019 10:28:45 MainProcess     align_input_0   _base           _thread_process           DEBUG    Putting EOF
11/20/2019 10:28:45 MainProcess     align_predict_0 fan             predict                   DEBUG    Predicting Landmarks
11/20/2019 10:28:49 MainProcess     align_predict_0 library         _logger_callback          INFO     Analyzing Ops: 1516 of 3641 operations complete
11/20/2019 10:28:51 MainProcess     align_predict_0 library         _logger_callback          INFO     Analyzing Ops: 3377 of 3641 operations complete
11/20/2019 10:29:06 MainProcess     align_predict_0 _base           _thread_process           DEBUG    Putting EOF
11/20/2019 10:29:06 MainProcess     align_output_0  fan             get_pts_from_predict      DEBUG    Obtain points from prediction
11/20/2019 10:29:06 MainProcess     align_output_0  multithreading  run                       DEBUG    Error in thread (align_output_0): index 64 is out of bounds for axis 3 with size 64
11/20/2019 10:29:07 MainProcess     MainThread      multithreading  check_and_raise_error     DEBUG    Thread error caught: [(<class 'IndexError'>, IndexError('index 64 is out of bounds for axis 3 with size 64',), <traceback object at 0x15167f4c8>)]
11/20/2019 10:29:07 MainProcess     MainThread      plaidml_tools   initialize                DEBUG    PlaidML already initialized
11/20/2019 10:29:07 MainProcess     MainThread      plaidml_tools   get_supported_devices     DEBUG    []
11/20/2019 10:29:07 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    Experimental Devices: [<plaidml._DeviceConfig object at 0x153201dd8>]
11/20/2019 10:29:07 MainProcess     MainThread      plaidml_tools   get_all_devices           DEBUG    [<plaidml._DeviceConfig object at 0x153201dd8>]
11/20/2019 10:29:07 MainProcess     MainThread      plaidml_tools   __init__                  DEBUG    Initialized: PlaidMLStats
11/20/2019 10:29:07 MainProcess     MainThread      plaidml_tools   supported_indices         DEBUG    []
Traceback (most recent call last):
  File "/Users/wutongtong/Downloads/faceswap-master/lib/cli.py", line 128, in execute_script
    process.process()
  File "/Users/wutongtong/Downloads/faceswap-master/scripts/extract.py", line 116, in process
    self._run_extraction()
  File "/Users/wutongtong/Downloads/faceswap-master/scripts/extract.py", line 212, in _run_extraction
    for idx, faces in enumerate(status_bar):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tqdm/std.py", line 1091, in __iter__
    for obj in iterable:
  File "/Users/wutongtong/Downloads/faceswap-master/plugins/extract/pipeline.py", line 217, in detected_faces
    if self._check_and_raise_error():
  File "/Users/wutongtong/Downloads/faceswap-master/plugins/extract/pipeline.py", line 482, in _check_and_raise_error
    if plugin.check_and_raise_error():
  File "/Users/wutongtong/Downloads/faceswap-master/plugins/extract/_base.py", line 292, in check_and_raise_error
    err = thread.check_and_raise_error()
  File "/Users/wutongtong/Downloads/faceswap-master/lib/multithreading.py", line 84, in check_and_raise_error
    raise error[1].with_traceback(error[2])
  File "/Users/wutongtong/Downloads/faceswap-master/lib/multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/wutongtong/Downloads/faceswap-master/plugins/extract/_base.py", line 405, in _thread_process
    batch = function(batch)
  File "/Users/wutongtong/Downloads/faceswap-master/plugins/extract/align/fan.py", line 129, in process_output
    self.get_pts_from_predict(batch)
  File "/Users/wutongtong/Downloads/faceswap-master/plugins/extract/align/fan.py", line 147, in get_pts_from_predict
    x_subpixel_shift = batch["prediction"][offsets[0]] - batch["prediction"][offsets[1]]
IndexError: index 64 is out of bounds for axis 3 with size 64

============ System Information ============
encoding:            UTF-8
git_branch:          Not Found
git_commits:         Not Found
gpu_cuda:            Unsupported OS
gpu_cudnn:           Unsupported OS
gpu_devices:         GPU_0: Intel - Iris Pro (experimental)
gpu_devices_active:  GPU_0
gpu_driver:          ['1.2(Apr 25 2019 22:05:48)']
gpu_vram:            GPU_0: 1536MB
os_machine:          x86_64
os_platform:         Darwin-17.7.0-x86_64-i386-64bit
os_release:          17.7.0
py_command:          faceswap.py extract -i ./cl_s/ -o ./cl_s_dist/
py_conda_version:    N/A
py_implementation:   CPython
py_version:          3.6.3
py_virtual_env:      False
sys_cores:           8
sys_processor:       i386
sys_ram:             Total: 16384MB, Available: 4861MB, Used: 11520MB, Free: 1151MB

=============== Pip Packages ===============
absl-py==0.8.1
astor==0.8.0
cachetools==3.1.1
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
Click==7.0
cmake==3.15.3
cycler==0.10.0
decorator==4.4.1
dlib==19.18.0
enum34==1.1.6
face-recognition==1.2.3
face-recognition-models==0.3.0
fastcluster==1.1.25
ffmpy==0.2.2
gast==0.2.2
google-auth==1.7.1
google-auth-oauthlib==0.4.1
google-images-download==2.8.0
google-pasta==0.1.8
grpcio==1.25.0
h5py==2.9.0
idna==2.8
imageio==2.5.0
imageio-ffmpeg==0.3.0
joblib==0.14.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
Markdown==3.1.1
matplotlib==2.2.2
networkx==2.4
numpy==1.16.2
nvidia-ml-py3==7.352.1
oauthlib==3.1.0
opencv-contrib-python==4.1.1.26
opencv-python==4.1.1.26
opt-einsum==3.1.0
pathlib==1.0.1
Pillow==6.1.0
plaidml==0.6.4
plaidml-keras==0.6.4
protobuf==3.10.0
psutil==5.6.5
pyasn1==0.4.8
pyasn1-modules==0.2.7
pycparser==2.19
pynvx==0.0.4
pyparsing==2.4.5
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.1.2
requests==2.22.0
requests-oauthlib==1.3.0
rsa==4.0
scikit-image==0.16.2
scikit-learn==0.21.3
scipy==1.3.2
selenium==3.141.0
six==1.13.0
tensorboard==1.14.0
tensorflow==1.14.0
tensorflow-estimator==1.14.0
termcolor==1.1.0
toposort==1.5
# Editable install with no version control (tqdm==4.38.0)
-e /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
urllib3==1.25.7
Werkzeug==0.16.0
wrapt==1.11.2

================= Configs ==================
--------- convert.ini ---------

[color.color_transfer]
clip:                     True
preserve_paper:           True

[color.match_hist]
threshold:                99.0

[color.manual_balance]
colorspace:               HSV
balance_1:                0.0
balance_2:                0.0
balance_3:                0.0
contrast:                 0.0
brightness:               0.0

[writer.pillow]
format:                   png
draw_transparent:         False
optimize:                 False
gif_interlace:            True
jpg_quality:              75
png_compress_level:       3
tif_compression:          tiff_deflate

[writer.ffmpeg]
container:                mp4
codec:                    libx264
crf:                      23
preset:                   medium
tune:                     none
profile:                  auto
level:                    auto

[writer.gif]
fps:                      25
loop:                     0
palettesize:              256
subrectangles:            False

[writer.opencv]
format:                   png
draw_transparent:         False
jpg_quality:              75
png_compress_level:       3

[mask.mask_blend]
type:                     normalized
radius:                   3.0
passes:                   4
erosion:                  0.0

[mask.box_blend]
type:                     gaussian
distance:                 11.0
radius:                   5.0
passes:                   1

[scaling.sharpen]
method:                   unsharp_mask
amount:                   150
radius:                   0.3
threshold:                5.0

--------- gui.ini ---------

[global]
fullscreen:               False
tab:                      extract
options_panel_width:      30
console_panel_height:     20
font:                     default
font_size:                9

--------- .faceswap ---------
backend:                  amd

--------- extract.ini ---------

[global]
allow_growth:             False

[detect.mtcnn]
minsize:                  20
threshold_1:              0.6
threshold_2:              0.7
threshold_3:              0.7
scalefactor:              0.709
batch-size:               8

[detect.cv2_dnn]
confidence:               50

[detect.s3fd]
confidence:               70
batch-size:               4

[align.fan]
batch-size:               12

[mask.unet_dfl]
batch-size:               8

[mask.vgg_obstructed]
batch-size:               2

[mask.vgg_clear]
batch-size:               6

--------- train.ini ---------

[global]
coverage:                 68.75
mask_type:                none
mask_blur:                False
icnr_init:                False
conv_aware_init:          False
subpixel_upscaling:       False
reflect_padding:          False
penalized_mask_loss:      True
loss_function:            mae
learning_rate:            5e-05

[model.realface]
input_size:               64
output_size:              128
dense_nodes:              1536
complexity_encoder:       128
complexity_decoder:       512

[model.dfl_sae]
input_size:               128
clipnorm:                 True
architecture:             df
autoencoder_dims:         0
encoder_dims:             42
decoder_dims:             21
multiscale_decoder:       False

[model.unbalanced]
input_size:               128
lowmem:                   False
clipnorm:                 True
nodes:                    1024
complexity_encoder:       128
complexity_decoder_a:     384
complexity_decoder_b:     512

[model.dlight]
features:                 best
details:                  good
output_size:              256

[model.villain]
lowmem:                   False

[model.original]
lowmem:                   False

[model.dfl_h128]
lowmem:                   False

[trainer.original]
preview_images:           14
zoom_amount:              5
rotation_range:           10
shift_range:              5
flip_chance:              50
color_lightness:          30
color_ab:                 8
color_clahe_chance:       50
color_clahe_max_size:     4
`

**Comment by torzdf** [comment]
Get latest code. This has been fixed.

**Comment by wa15aa** [comment]
> Get latest code. This has been fixed.

I clone the code from https://github.com/deepfakes/faceswap ,Isn't this the latest code?

**Comment by wa15aa** [comment]
> Get latest code. This has been fixed.

Does it have anything to do with my GPU support

**Comment by torzdf** [comment]
No it doesn't, although Intel Iris is not directly supported, so your mileage may vary.

You have downloaded as a zip rather than cloned the repo, so it's impossible to know what version you are on

```
Downloads/faceswap-master
git_branch:          Not Found
git_commits:         Not Found
```

But the specific bug you are displaying was fixed in a recent commit
