### ISSUE TITLE
preview and extract both stopped

### ISSUE THREAD

**Issue by michealcorvin** [deepfakes/faceswap#943]
![2](https://user-images.githubusercontent.com/42247920/69890643-ddd5a680-131c-11ea-9875-2f88678bd5aa.JPG)
![3](https://user-images.githubusercontent.com/42247920/69890644-de6e3d00-131c-11ea-85ef-21756fbd5532.JPG)
![4](https://user-images.githubusercontent.com/42247920/69890645-de6e3d00-131c-11ea-84a5-7ed802edbaba.JPG)
![5](https://user-images.githubusercontent.com/42247920/69890646-de6e3d00-131c-11ea-80d6-7fac4891e8e4.JPG)

I am using the windows version,
I am not able to extract the images both src / dst 
It shows that its extracted 100% but i dont find any images nor preview,
Please go through the pictures for better understanding,
Using a gtx 1080 graphics with core i7

**Desktop (please complete the following information):**
 - Python Version 3.7.4
 - Conda Version one which comes with the installer faceswap.exe

**Comment by torzdf** [comment]
It says it there were no faces detected in your penultimate image.

**Comment by vlccdl** [comment]
I have the same porblem after the update 17 hours ago

**Comment by torzdf** [comment]
Run with trace logging and post log please.

**Comment by vlccdl** [comment]
run with the default extract values
Images found:        22
Faces detected:      17
[faceswap.log](https://github.com/deepfakes/faceswap/files/3907228/faceswap.log)

**Comment by torzdf** [comment]
Try latest code

**Comment by vlccdl** [comment]
thanks,it's work now
