### ISSUE TITLE
How do I remove ugly dark shadows on my face after changing face?

### ISSUE THREAD

**Issue by hnjiakai** [deepfakes/faceswap#945]
face A
![img_5815_0](https://user-images.githubusercontent.com/18085449/70026258-49986780-15da-11ea-9a46-caad802ec1b4.jpg)
face B
![img_3280_0](https://user-images.githubusercontent.com/18085449/70026270-5321cf80-15da-11ea-9326-568522ada4a5.jpg)
Converted face
![image](https://user-images.githubusercontent.com/18085449/70026341-7f3d5080-15da-11ea-8079-6e12e55cdcdd.png)
The converted face has black shadows. How can I eliminate it?

**Comment by torzdf** [comment]
https://forum.faceswap.dev/viewtopic.php?f=6&t=244
