### ISSUE TITLE
openCL error

### ISSUE THREAD

**Issue by gianganlam** [deepfakes/faceswap#947]
on extract step, if I select Cv2-Dnn on aligned, there is not error. but if I select fan, I get errors:

unable to run OpenCL kernel kernel_c30_sdk_55: CL_MEM_OBJECT_ALLOCATION_FAILURE
ERROR    unable to run OpenCL kernel kernel_c30_sdk_55: CL_MEM_OBJECT_ALLOCATION_FAILURE
Unable to map memory: CL_MAP_FAILURE
ERROR    Unable to map memory: CL_MAP_FAILURE

can someone help me, i am a newbie. my laptop have 4gb ram, amd radeon m335 with 2gb and 2gb shared, cpu is intel HD graphics 520

**Comment by torzdf** [comment]
Try changing the extractor batch size settings in Extract Settings to 1.

@kilroythethird May be able to offer more advise as he is The AMD Guy.

**Comment by kilroythethird** [comment]
Yeah that is a Memory error. Reduce the batchsize for FAN.
But tbh. you probably won't get anything really good out of that machine.
Think about using cloud computing our using another machine with a better GPU with more VRAM.
