### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by robomotic** [deepfakes/faceswap#959]
**Describe the bug**
When moving through frames in the Alignment Manual mode, I get a None Exception. I believe it happens if the frame skipping points to a frame that doesn't exist.
I think there should be a check to see if the frame is None.

**To Reproduce**
1. Go to Tools
2. Click on Alignments
3. Scroll down to Manual
4. Disable Monitor
5. Select Any Mode
4. Press go to last Frame key }

**Expected behavior**
It should go to last frame

**Screenshots**
01/07/2020 14:13:44 INFO     [MANUAL PROCESSING]
01/07/2020 14:13:44 INFO     Loading Align from Fan plugin...
01/07/2020 14:13:44 INFO     Initializing FAN (Align)...
01/07/2020 14:14:04 INFO     Initialized FAN (Align) with batchsize of 1

=============== NAVIGATION ===============
- 's': Skip Mode (All, No Faces, Multi Faces, Has Faces)
- 'z': Previous Frame
- 'x': Next Frame
- '}': Go to Last Frame
- '{': Go to First Frame
- 'ESC': Exit
- '/': Cycle Frame Zoom
- ']': 100 Frames Forward
- '[': 100 Frames Back
================ DISPLAY ================
- 'y': Toggle Image
================= COLOR =================
- 'u': Cycle Bounding Box Color
- 'i': Cycle Extract Box Color
- 'o': Cycle Landmarks Color
- 'p': Cycle Landmarks Mesh Color
================== SIZE ==================
- 'h': Cycle Bounding Box thickness
- 'j': Cycle Extract Box thickness
- 'k': Cycle Landmarks - point size
- 'l': Cycle Landmarks Mesh - thickness
================== EDIT ==================
- 'Left Click': Bounding Box - Move
- 'Middle Click': Bounding Box - Resize
- 'm': Change Mode (View, Edit)
- 'v': Copy Alignments from Next Frame with Alignments
- 'c': Copy Alignments from Previous Frame with Alignments
- 'd': Delete Selected Alignment
- 'r': Reload Alignments (Discard all changes)
- 'SPACE': Save Alignments
- '0 to 9': Select/Deselect Face at this Index
01/07/2020 14:14:54 ERROR    Got Exception on main handler:
Traceback (most recent call last):
File "D:\faceswap\lib\cli.py", line 128, in execute_script
process.process()
File "D:\faceswap\tools\alignments.py", line 49, in process
job.process()
File "D:\faceswap\tools\lib_alignments\jobs_manual.py", line 467, in process
self.display_frames()
File "D:\faceswap\tools\lib_alignments\jobs_manual.py", line 514, in display_frames
frame, faces = self.get_frame()
File "D:\faceswap\tools\lib_alignments\jobs_manual.py", line 574, in get_frame
frame = FrameDisplay(image, alignments, roi, self.interface).image
File "D:\faceswap\tools\lib_alignments\jobs_manual.py", line 624, in __init__
self.annotate_frame()
File "D:\faceswap\tools\lib_alignments\jobs_manual.py", line 633, in annotate_frame
annotate.draw_black_image()
File "D:\faceswap\tools\lib_alignments\annotate.py", line 34, in draw_black_image
height, width = self.image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Desktop (please complete the following information):**
 - OS: Windows10
 - Python Version 3.7
 - Conda Version conda 4.8.1
 - Commit ID ff76461
 - 
**Additional context**

**Crash Report**
See [https://pastebin.com/JnJcqNBC](crash log here)

**Comment by torzdf** [comment]
Thanks for the report.

Manual Tool is end of life, with an improved tool being developed, so we are unlikely to look to fix this bug.

**Comment by torzdf** [comment]
Closing issue as Manual Tool will be replaced soon
