### ISSUE TITLE
Be careful with the coverage of the face in training_data.py

### ISSUE THREAD

**Issue by PhilipGarnero** [deepfakes/faceswap#96]
Apparently, @shaoanlu recommended 220 when 160 was the original value.  
220 did not work for me at all. Even though I was under 0.02 loss, the merging in the preview and the convert showed horrible results (zombie like). 
I reverted back to 160 and i now get more acceptable results.  
I think we should warn users about this.

**Comment by duoyu5555** [comment]
Which param does the 220/160 refer to?

**Comment by PhilipGarnero** [comment]
You can [see it there](https://github.com/deepfakes/faceswap/blob/master/lib/training_data.py#L8).
