### ISSUE TITLE
License, really?

### ISSUE THREAD

**Issue by Aspie96** [deepfakes/faceswap#961]
So, I checked the license and, before using the code, I need somebody to clarify, please.

Issue #65 says:
> we still need to get /u/deepfakes to approve this licensing. If you can get into contact with him, then we can put a license on it.
> We cant license it without /u/deepfakes because then the license is void due to the unknown license of the original source.

If the original author does not provide a license, it is ALL RIGHTS RESERVED. One can't just stick a GPL license to it!

Then #122 reopened the issue and in #220 the license got added.
If there is no approval from the original author, no license should be attached at all, as it is protected by copyright.

**Comment by torzdf** [comment]
That is hideously outdated.

The entire code base has been entirely rewritten from the ground up, several times over

**Comment by Aspie96** [comment]
Ok, thank you very much for telling me, as I didn't notice it in the mentioned issues.

Before closing the issue, however, I'd like to ask: is this still a derived work from the original or not?

I checked:
- http://digital-law-online.info/lpdi1.0/treatise27.html
- https://softwareengineering.stackexchange.com/questions/208776/would-copyrights-drop-if-i-re-write-open-source-project-into-another-language (I know in this case the language is the same).
- https://softwareengineering.stackexchange.com/questions/81705/rewriting-gpl-code-to-change-license

The answer seems to be that it's not very clear. If you take somebody else's code and you modify it, even extensively, until no similarity can be found, it's still derivative work. If you start from scratch and make something with similar functionalities, it is clearly not. Everything in between (expecially when studying the original source code) seems to be a gray area.

**Comment by torzdf** [comment]
I would say that this is "gray area" territory.

Ultimately no-one knows who /u/deepfakes is and he has never come forward to make himself known. At no point are we looking to profit from this project, but that isn't to say others won't be looking to profit themselves.

@bryanlyon Is more up to speed on this kind of thing, so hopefully he will come along and add his 2 cents when he's around.

**Comment by Aspie96** [comment]
> Ultimately no-one knows who /u/deepfakes is and he has never come forward to make himself known.

That is very irrelevant, though.
The fact that obtaining a license is hard, or even impossible, does not matter: if it did, licenses wouldn't matter, as everybody would just give themselves a license.
Plese, note: I am not an expert in law, so I could be wrong about the gray area (not giving yourself a license is not a gray area). However, unless the user can be sure to be allowed to use the project, this potential problem should be noted in the documentation: not doing so can potentially harm a user who wants to be sure they can legally use the project.

> At no point are we looking to profit from this project, but that isn't to say others won't be looking to profit themselves.

Exactly! If it is free software, it must be possible to use it for commercial purposes (otherwise it's not).

I think this project is awesome, but this potential issue should not be unnoticed by the user, if it exist. If we can determine this is safe, however, I will obviously close the issue.

**Comment by HysMagus** [comment]
> The entire code base has been entirely rewritten from the ground up, several times over

This is good, if I understand correctly, all contributions after u/deepfakes have been under GPL 3.0. If we can do a blame on the code, and see how much of u/deepfake's code is remaining, from that we can keep an eye out. 

It's entirely possible that in the future, through continuous improvement, and contributions, we could reach a point where u/deepfake's code will have been cycled out to the 99%-100% range. 

I can self assign an issue to tracking down how much of u/deepfake's original code is in the repo if there's interest?

**Comment by Aspie96** [comment]
> This is good, if I understand correctly, all contributions after u/deepfakes have been under GPL 3.0.7

I am not even sure that is true.
All contributions after the pull request that added the license were released under GPL 3.0. If there are any contributions before then from authors that no longer are part of the project, their contributions are also provided without any license (which is bad).

But let's say it's true and we already are at that point: there is no code from u/deepfake. This would not help: the code would still qualify as a derviative.

Imagine translating a book in French: even if there is no word from the original author, the book is still a derivative.

I think it's ok to say "all our contributions are under GPL 3.0": that means a potential user will never be sued by any of the current authors (as long as they are not breaking the license) and, if they trust that u/deepfake will never sue them either (note that he absolutely could have proofs he is the original author even if he was anonymous: in Italy, where I live, I know of some proofs one can have, I don't know about the rules of other countries), which is indeed unlikely, they can feel pretty much safe using the software.

However, for many, including myself, it's different: many don't care whether it's likely to get sued or not, but want to fallow copyright law as a matter of principle. Additionally, many companies take extra care and free software must be usable for commercial purposes as well. Additionally, I would argue if this still is a derivative work of the original, it's not fair to u/deepfake to claim it has a license which he didn't give.

The core point here is what we mean by "ground up": if we mean there is simply not a line of code that he wrote originally, it doesn't matter. If we mean a different team of people, without ever looking at the source code (based on descriptions of the program, on papers about it etc...) build it from scratch and **independently**, releasing every contribution under GPL 3.0, there is no copyright issue (at worst patent issues). Everything in between, as I said, is either a gray area or an area which I do not understand since I am not an expert in laws.

**Comment by bryanlyon** [comment]
The code written by /u/deepfakes was released a long time ago and represents a very tiny amount of code.  When he released it, he didn't assign a specific license to it, however, he did provide an implied license by providing it and allowing people to use it.  Since then he commented on posts about the use of the code in other places including reddit posts about this repo and other forks (some of which were closed source) which further supports the license to use it.  Unfortunately, all of this history has been deleted by Reddit when they purged deepfakes from the site.

Today, the only parts that can even remotely be considered even "derived" would be the Original model (whose code is by necessity of maintaining compatibility closely related to the original code).  All other code has been COMPLETELY rewritten from scratch with absolutely no remaining relation to the original code.

Further, I think you guys are missing the point of a "Derivative work".  In the US and all countries that have copyright treaties with the US, Deritivative works have their own copyright protection independent of the original's (which also has copyright protection).  This doesn't mean we have to clean room develop Faceswap, just that Faceswap is protected on it's own.  Any use of u/Deepfakes' code is either under implied license or fair use for compatibility.

Faceswap is licensed as GPLv3 .  Nothing here changes that.

If you have any other questions on this, please bring them to our Discord server https://discord.gg/FC54sYg
