### ISSUE TITLE
the newest  windows release lack yaml?

### ISSUE THREAD

**Issue by Dian-Yi** [deepfakes/faceswap#965]
i install the newest windows release, but it can not run successfully.
when i extract the faces, the debug info:
Loading...
Setting Faceswap backend to NVIDIA
01/20/2020 18:10:24 INFO     Log level set to: DEBUG
2020-01-20 18:10:24.943963: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Process exited.

i try change tensorflow version but failed. 
when i install the pyyaml, it can work well. And i find requirement.txt has not yaml dependence.
So in some case, when lack of yaml dependence, it can not work well but the debug info has no tips about yaml.

**Comment by torzdf** [comment]
pyyaml isn't a dependency of Faceswap, so I'm not sure why this issue would occur.

**Comment by torzdf** [comment]
I'm closing this issue as I don't think there is anything to do here. Please comment again if you disagree and I can look to reopen.
