### ISSUE TITLE
Fedora install

### ISSUE THREAD

**Issue by Azat868** [deepfakes/faceswap#967]
docker build -t deepfakes-gpu -f Dockerfile.gpu .

![изображение](https://user-images.githubusercontent.com/29046741/73160152-4791e700-40f9-11ea-82e7-d304d9bdc6f5.png)

pip list
langtable          0.0.50    
libcomps           0.1.14    
Mako               1.1.0.dev0
MarkupSafe         1.1.1     
matplotlib         3.1.1     
ntplib             0.3.3     
numpy              1.18.1    
olefile            0.46      
ordered-set        3.1

**Comment by torzdf** [comment]
The docker version is community maintained, none of the current Devs use it.

You should be able to edit requirements.txt and change

```
matplotlib==3.1.1
```
to
```
matplotlib
```
