### ISSUE TITLE
Can't extract

### ISSUE THREAD

**Issue by shadowfolder** [deepfakes/faceswap#97]
I've install all packages, but i'm getting:
root@localhost:~/Desktop/faceswap# python faceswap.py extract
Input Directory: input
Output Directory: output
Starting, this may take a while...
Traceback (most recent call last):
  File "faceswap.py", line 18, in <module>
    arguments.func(arguments)
  File "/root/Desktop/faceswap/lib/cli.py", line 44, in process_arguments
    self.output_dir = get_folder(self.arguments.output_dir)
  File "/root/Desktop/faceswap/lib/utils.py", line 11, in get_folder
    output_dir.mkdir(parents=True, exist_ok=True)
TypeError: mkdir() got an unexpected keyword argument 'exist_ok'

**Comment by gdunstone** [comment]
Are you using python 3?
The exist_ok keyword argument was only added in python 3

**Comment by shadowfolder** [comment]
Ahh python 3, damnit. I was runned it from python 2.x. Thanks mate, problem is solved! :)
