### ISSUE TITLE
update-hashes in alignments tool crashing 

### ISSUE THREAD

**Issue by geomaster1234** [deepfakes/faceswap#974]
After modifying extracted faces (in this case resizing), when attempting to update hashes within the alignments file the script crashes with the traceback message ultimately pointing to `AttributeError: 'AlignmentData' object has no attribute 'add_face_hashes'` as the culprit.

Looking at some of the code it looks like add_face_hashes is a non existent function and probably got deprecated but not all references to it are cleaned up. I've tried to update hashes with both resized images and recolored images and the same error results. It looks like this part of the tool is broken at the moment.

 - OS: Ubuntu 18.04
 - Python Version 3.7.6
 - Conda Version 4.7.12
 - Commit ID 7024047

Attaching crash report.
[crash_report.2020.02.18.095554501029.log](https://github.com/deepfakes/faceswap/files/4220838/crash_report.2020.02.18.095554501029.log)

**Comment by torzdf** [comment]
This is reinstated in the latest commit.
