### ISSUE TITLE
Could not find a version that satisfies the requirement opencv-python==4.1.2.30

### ISSUE THREAD

**Issue by Tockra** [deepfakes/faceswap#975]
## Expected behavior
Installing requirments

## Actual behavior
Error
## Steps to reproduce
tip pip3 install -r requirements.txt 

I'll get: 
```bash
ERROR: Could not find a version that satisfies the requirement opencv-python==4.1.2.30 (from -r requirements.txt (line 5)) (from versions: none)
ERROR: No matching distribution found for opencv-python==4.1.2.30 (from -r requirements.txt (line 5))
``` 
## Other relevant information
- **Command lined used (if not specified in steps to reproduce)**: faceswap.py ...
- **Operating system and version:** Ubuntu 18.04
- **Python version:** 3.6.9
- **Faceswap version:** master
- **Faceswap method:** -

**Comment by torzdf** [comment]
I'm not sure why you are hitting this issue, this package is definitely available:
https://pypi.org/project/opencv-python/4.1.2.30/
