### ISSUE TITLE
Dockerfiles outdated

### ISSUE THREAD

**Issue by wardVD** [deepfakes/faceswap#977]
Crash report:
`root@19e13ca3b3aa:/srv/faceswap# python faceswap.py -h
Setting Faceswap backend to CPU
Traceback (most recent call last):
  File "faceswap.py", line 11, in <module>
    raise Exception("This program requires at least python3.6")
Exception: This program requires at least python3.6
`

Bug
The current Dockerfiles start from images that have python 3.5 installed. These should be updated.

**Comment by torzdf** [comment]
This should be fixed in latest commit

**Comment by wardVD** [comment]
Could you link me to this commit @torzdf ? I do not find it.

**Comment by torzdf** [comment]
https://github.com/deepfakes/faceswap/pull/976
