### ISSUE TITLE
Unable to merge alignment files

### ISSUE THREAD

**Issue by michaeldeprospo** [deepfakes/faceswap#979]
## Expected behavior
Merging two alignment files will generate one file containing alignments from both files.

## Actual behavior
Merge fails every time returning:
`self.final_alignments.file = filename
AttributeError: can't set attribute`

## Steps to reproduce
Running the merge command through the GUI. Selecting two alignment files, and their corresponding faces folder.

## Other relevant information
crash log attached
[crash_report.2020.03.05.124208091265.log](https://github.com/deepfakes/faceswap/files/4294321/crash_report.2020.03.05.124208091265.log)

**Comment by torzdf** [comment]
Update. This was fixed in the latest commit.
