### ISSUE TITLE
IndexError: list index out of range on training

### ISSUE THREAD

**Issue by dimon777** [deepfakes/faceswap#98]
```
# python3.6 faceswap.py train -A ~/faceswap/data/trump -B ~/faceswap/data/stalone -m ~/faceswap/models/
Model A Directory: /root/faceswap/data/trump
Model B Directory: /root/faceswap/data/stalone
Training data directory: /root/faceswap/models
Loading data, this may take a while...
Loading Model from Model_Original plugin...
/usr/local/lib/python3.6/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/usr/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Failed loading existing training data.
Unable to open file (unable to open file: name = '/root/faceswap/models/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
Loading Trainer from Model_Original plugin...
Starting. Press "Enter" to stop training and save model
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/root/faceswap/lib/utils.py", line 42, in run
    for item in self.generator:
  File "/root/faceswap/lib/training_data.py", line 43, in minibatch
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
  File "/root/faceswap/lib/training_data.py", line 43, in <listcomp>
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
IndexError: list index out of range
```

## Expected behavior
There shouldn't be "IndexError: list index out of range"

## Actual behavior

*Describe, in some detail, what the program does instead. Be sure to include any error message or screenshots.*

## Other relevant information
H/W: 4 cores, 16GB, Nvidial P100
S/W: Ubuntu 16.04, NVIDIA binary driver - version 384.111
CUDA 8.0
CuDNN 6
Python 3.6
faceswap commit: 0f8d9db826d7588f9feb151ab234f2aaf0d8ecf2

**Comment by gdunstone** [comment]
> Unable to open file (unable to open file: name = '/root/faceswap/models/encoder.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

models directory doesn't exist, I'll look into writing a fix now. for the time being just mkdir the models directory and it should work.

**Comment by dimon777** [comment]
missing models dir is not an issue. Rather:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/root/faceswap/lib/utils.py", line 42, in run
    for item in self.generator:
  File "/root/faceswap/lib/training_data.py", line 44, in minibatch
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
  File "/root/faceswap/lib/training_data.py", line 44, in <listcomp>
    rtn = numpy.float32([read_image(data[j]) for j in range(i,i+size)])
IndexError: list index out of range
```

**Comment by gdunstone** [comment]
Yea I just got this too. @Clorr ?

**Comment by gdunstone** [comment]
I think I worked this out. Are you using a small number of images?
I got the same error trying to train on less than 64 images.
if you really want to train on such a small number of images you can set the `--batch-size` argument to something less than number of images.

**Comment by Clorr** [comment]
Yes it seems to come from there. Possibly it can be solved with a slice notation like `rtn = numpy.float32([read_image(item) for item in data[i,size])`

But having so few images that it is below batch-size is a problem because the training won't have much varied data and won't train well IMHO

**Comment by gdunstone** [comment]
Im going to close this as wontfix because this low number of training images shouldn't happen.

Warn about low number of images?

**Comment by Clorr** [comment]
As you want, but this is not mandatory

**Comment by dimon777** [comment]
Yes, I was using small number of images. Thanks for figuring it out.
