### ISSUE TITLE
No output after Extracting

### ISSUE THREAD

**Issue by chenbinghui1** [deepfakes/faceswap#980]
Hi, I am on Linux. I use the provided installer for linux to install faceswap. But I cannot extract faces. By conducting python3 faceswap.py extract -i src/trump -o faces/trump, the consule only print the following two lines:

Setting Faceswap backend to CPU
03/10/2020 21:09:10 INFO     Log level set to: INFO

And I find no output in target dir.
could you help me? what happens?

**Comment by torzdf** [comment]
From inside your virtual environment, inside your faceswap folder, run: 
```python -c "from lib.sysinfo import SysInfo ;  print(SysInfo().full_info())"```
and post output
