### ISSUE TITLE
Incorrect CuDNN detection procedure in Linux

### ISSUE THREAD

**Issue by akimovmike** [deepfakes/faceswap#983]
Right now, setup.py detects cudnn presence by checking ldconfig output for libcudnn.so and looking under /include folder of the same path for cudnn.h or equivalent. However, at least sometimes ldconfig returns not the absolute path to libcudnn.so, but a path to the symlink to this file, like /lib/x86_64-linux-gnu/libcudnn.so.7
After the script replaces in this path /lib with /include, it gets /include/x86_64-linux-gnu/ as the search path, which is not correct, and the cudnn check fails.
The above symlink dereferences to /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0, and there, under /usr/include/, the cudnn.h is present.
I suggest adding the following code to dereference the symlink:
cudnn_path = os.path.realpath(cudnn_path)
after the line 541 in the setup.py to avoid this behavior.

**Comment by torzdf** [comment]
Thanks. Makes sense. Done.
