### ISSUE TITLE
Run problems again

### ISSUE THREAD

**Issue by Valeronich** [deepfakes/faceswap#993]
when i satisfy all the requirements,and i run:
python faceswap.py extract -i ./data/trump -o ./face/trump

it raise:
Setting Faceswap backend to NVIDIA
11/10/2019 18:12:52 INFO Log level set to: INFO

but nothing happened!

of course,i have dataset.

what's happen? thx for your answer

This issue doesn't help
https://github.com/deepfakes/faceswap/issues/930

**Comment by torzdf** [comment]
Please provide your system info.

**GUI Users:** Go to Help -> Output system information

**CLI Users**: From inside your virtual environment, inside your faceswap folder, run: 
```python -c "from lib.sysinfo import SysInfo ;  print(SysInfo().full_info())"```

**Comment by VicGrygorchyk** [comment]
Seeing similar problem running 
Running a command inside the docker container:
```
faceswap.py extract -L INFO -D=s3fd -A=fan -nm=clahe -i=/srv/trump -o=/srv/trump_out -f /srv/trump_example/*
```
Output:
```
Setting Faceswap backend to NVIDIA
03/28/2020 10:48:53 INFO     Log level set to: INFO
03/28/2020 10:48:54 INFO     Output Directory: /srv/trump_out
03/28/2020 10:48:55 INFO     Extracting and aligning face for Face Filter...
03/28/2020 10:48:55 INFO     Filter: ['/srv/trump_example/11_0.jpeg', '/srv/trump_example/1_0.jpeg', '/srv/trump_example/21_0.jpg'']
03/28/2020 10:48:55 INFO     Loading Detect from Cv2_Dnn plugin...
03/28/2020 10:48:55 INFO     Loading Align from Cv2_Dnn plugin..
```
Then it got stuck.
Tried on two different platfoms: Laptop Ubuntu 18.04 Geforce GTX 965m and GCP instance with Nvidia T4:


[logs.txt](https://github.com/deepfakes/faceswap/files/4396998/logs.txt)

**Comment by VicGrygorchyk** [comment]
I've just noticed the log `INFO     Loading Align from Cv2_Dnn plugin..` is shown regardless if `-A=fan` or `-A=cv2-dnn`.
Is it intended?

**Comment by VicGrygorchyk** [comment]
Well, not sure I have the same issue as @Valeronich , as I run script with `-f` filter provided.
From my debugging I ended up seeing the problem in `def queue_images()` method of `faceswap/lib/face_filter.py`. It tries to execute `in_queue.put(feed_dict)` and wait for free slot.
If we add `timeout` to `put()` it crahes with:
```
INFO     Sending EOF to filter queue
ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/srv/lib/cli.py", line 127, in execute_script
    process = script(arguments)
  File "/srv/scripts/extract.py", line 51, in __init__
    self._post_process = PostProcess(arguments)
  File "/srv/scripts/fsmedia.py", line 349, in __init__
    self._actions = self._set_actions()
  File "/srv/scripts/fsmedia.py", line 368, in _set_actions
    task = globals()[action](*args, **kwargs)
  File "/srv/scripts/fsmedia.py", line 533, in __init__
    self._filter = self._load_face_filter(**kwargs)
  File "/srv/scripts/fsmedia.py", line 576, in _load_face_filter
    ref_threshold)
  File "/srv/lib/face_filter.py", line 46, in __init__
    self.align_faces("cv2-dnn", "cv2-dnn", "none", multiprocess)
  File "/srv/lib/face_filter.py", line 78, in align_faces
    self.run_extractor(extractor)
  File "/srv/lib/face_filter.py", line 89, in run_extractor
    self.queue_images(extractor)
  File "/srv/lib/face_filter.py", line 125, in queue_images
    in_queue.put("EOF", timeout=1)
  File "/usr/lib/python3.6/queue.py", line 141, in put
    raise Full
queue.Full

```

**Comment by VicGrygorchyk** [comment]
Well, I changed `self.queue_size = 0` and checked out to `18660da1c92994615e88a032242c552295dc96e3` commit, as next commit, where `ExtractMedia` has been added - failed for me, I got no instance of `ExtractMedia`, but a dict.

**Comment by torzdf** [comment]
> 
> 
> Seeing similar problem running
> Running a command inside the docker container:
> 
> ```
> faceswap.py extract -L INFO -D=s3fd -A=fan -nm=clahe -i=/srv/trump -o=/srv/trump_out -f /srv/trump_example/*
> ```
> 
> Output:
> 
> ```
> Setting Faceswap backend to NVIDIA
> 03/28/2020 10:48:53 INFO     Log level set to: INFO
> 03/28/2020 10:48:54 INFO     Output Directory: /srv/trump_out
> 03/28/2020 10:48:55 INFO     Extracting and aligning face for Face Filter...
> 03/28/2020 10:48:55 INFO     Filter: ['/srv/trump_example/11_0.jpeg', '/srv/trump_example/1_0.jpeg', '/srv/trump_example/21_0.jpg'']
> 03/28/2020 10:48:55 INFO     Loading Detect from Cv2_Dnn plugin...
> 03/28/2020 10:48:55 INFO     Loading Align from Cv2_Dnn plugin..
> ```
> 
> Then it got stuck.
> Tried on two different platfoms: Laptop Ubuntu 18.04 Geforce GTX 965m and GCP instance with Nvidia T4:
> 
> [logs.txt](https://github.com/deepfakes/faceswap/files/4396998/logs.txt)

Syntactically incorrect. Don't use an equals sign, use a space

**Comment by torzdf** [comment]
Closing as OP didn't respond and follow up is off-topic

Please open a new issue if problems persist.
