### ISSUE TITLE
Microsoft Faceshifter

### ISSUE THREAD

**Issue by Spharax** [deepfakes/faceswap#996]
The actual faceswaping models are trained against specific faces and consume a lots of GPU power for all those training. The output quality also be improved against occlusions and identity conservation.

Microsoft released a new paper called Faceshifter (https://arxiv.org/abs/1912.13457) which address all those issues: universal model and better overall quality.

It would be awesome to have this paper implemented and pretrained.

**Comment by torzdf** [comment]
People are welcome to port models.
