### ISSUE TITLE
Status:Failed - extract.py. Return Code:1

### ISSUE THREAD

**Issue by hbrt** [deepfakes/faceswap#997]
When I use Faceswap GUI, It not work. Please see the image down. 
![image](https://user-images.githubusercontent.com/11226105/77620187-c5953180-6f74-11ea-8e3d-3c826a89d597.png)

**Comment by torzdf** [comment]
Help > Output System Info > Paste here

**Comment by hbrt** [comment]
Error obtaining system info: Could not find PlaidML configuration file: "experimental.json".

**Comment by hbrt** [comment]
> 帮助>输出系统信息>粘贴在这里

Error obtaining system info: Could not find PlaidML configuration file: "experimental.json".

**Comment by torzdf** [comment]
From inside your faceswap environment

```plaidml-setup```

**Comment by hbrt** [comment]
> 在您的换脸环境中
> 
> `plaidml-setup`

![image](https://user-images.githubusercontent.com/11226105/78325259-b8e29000-75a9-11ea-9f4b-3ef3dfa37b91.png)
It still error!

**Comment by torzdf** [comment]
This is a local issue to do with your plaidML install. 

Unfortunately I no longer have an AMD graphics card to test, but hopefully you'll find a solution here:

https://github.com/plaidml/plaidml/issues/370
