### ISSUE TITLE
OpenCV(4.1.2) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

### ISSUE THREAD

**Issue by millerf** [deepfakes/faceswap#998]
*Note: For general usage questions and help, please use either our [FaceSwap Forum](https://faceswap.dev/forum) 
or [FaceSwap Discord server](https://discord.gg/FC54sYg). General usage questions are liable to be closed without
response.*

**Crash reports MUST be included when reporting bugs.**

**Describe the bug**

Happened a brand new install (with install script) on Linux (Ubuntu).

Launch an extract command with base settings:
` python faceswap.py extract -i ../faceswap_data/convert/photos/ -o ../faceswap_data/convert/faces/`

Image folder are all frames of a video extracted with ffmpeg (with command provided in `USAGE.cmd`). Images are 1920x1080 in PNG.

**To Reproduce**
Extract form a brand new install on linux.

**Expected behavior**

Works
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Python Version 3.7.7
 - Conda Version 4.8.2
 - Commit ID 86a5921c8d8f4f3948f78755ba8fd3a092aae298
 
**Additional context**

**Crash Report**
[crash_report.2020.03.26.214738016368.log](https://github.com/deepfakes/faceswap/files/4389861/crash_report.2020.03.26.214738016368.log)

**Comment by torzdf** [comment]
Can you provide a frame/video which fails?

**Comment by millerf** [comment]
@torzdf I tried directly fomr video and form images. I'll get you an image right now

**Comment by millerf** [comment]
FYI, it fails at first or second frame...
Here you have first, second and 34th frame.

No judgement, it is just a personal project 
 :)

![video-frame-1](https://user-images.githubusercontent.com/790558/77750735-9f2ecf00-7024-11ea-8267-8605a540d855.png)![video-frame-2](https://user-images.githubusercontent.com/790558/77750835-ca192300-7024-11ea-9a52-07990e8bc595.png)

![video-frame-34](https://user-images.githubusercontent.com/790558/77750748-a3f38300-7024-11ea-9069-34e8e08db9f6.png)

**Comment by torzdf** [comment]
Are the first 2 images meant to be blank?

![image](https://user-images.githubusercontent.com/36920800/77751267-4445a980-701d-11ea-821d-947ae7b03d00.png)

**Comment by millerf** [comment]
I guess, they are the first frame of the video. Could it come from there?

**Comment by torzdf** [comment]
It shouldn't. When I have a sec I'll run some tests

**Comment by millerf** [comment]
Same error when deleting the first blank frames

**Comment by millerf** [comment]
My new first frames

![video-frame-8](https://user-images.githubusercontent.com/790558/77751984-fe8dde80-7026-11ea-9a3c-1ed70a6d56b3.png)
![video-frame-9](https://user-images.githubusercontent.com/790558/77752063-211ff780-7027-11ea-9269-9fed746146ae.png)

**Comment by millerf** [comment]
@torzdf Any luck?

**Comment by torzdf** [comment]
Should be fixed in latest commit

**Comment by millerf** [comment]
Nice. thanks
