### ISSUE TITLE
Train Error:  Caught exception in thread: '_training_0'

### ISSUE THREAD

**Issue by Tian14267** [deepfakes/faceswap#999]
I get an error with training on Linux and Windows :
Linux: 
When I train on Linux,I only get this: 
```
Setting Faceswap backend to NVIDIA
03/27/2020 09:43:23 INFO     Log level set to: INFO
Using TensorFlow backend.
```
Windows:
I get this error windows:
```
Setting Faceswap backend to NVIDIA
03/27/2020 09:45:45 INFO     Log level set to: INFO
Using TensorFlow backend.
03/27/2020 09:45:48 INFO     Model A Directory: E:\fffan\DeepFake\FacesWap\faceswap-master\input\input_A
03/27/2020 09:45:48 INFO     Model B Directory: E:\fffan\DeepFake\FacesWap\faceswap-master\input\input_B
03/27/2020 09:45:48 INFO     Training data directory: E:\fffan\DeepFake\FacesWap\faceswap-master\models
03/27/2020 09:45:48 INFO     ===================================================
03/27/2020 09:45:48 INFO       Starting
03/27/2020 09:45:48 INFO       Press 'ENTER' to save and quit
03/27/2020 09:45:48 INFO       Press 'S' to save model weights immediately
03/27/2020 09:45:48 INFO     ===================================================
03/27/2020 09:45:49 INFO     Loading data, this may take a while...
03/27/2020 09:45:49 INFO     Loading Model from Original plugin...
03/27/2020 09:45:49 INFO     No existing state file found. Generating.
03/27/2020 09:45:50 CRITICAL Error caught! Exiting...
03/27/2020 09:45:50 ERROR    Caught exception in thread: '_training_0'
```
Why get this error when Train, and why the  different error in Linux and Windows?
Linux : tensorflow==1.14; cuda == 9.0;  cudnn==7.4.2  
Windows : tensorflow==1.14; cuda == 10.0;  cudnn==7.6.1

**Comment by torzdf** [comment]
Please provide crash report from you Faceswap Folder

**Comment by Tian14267** [comment]
The error Log of Faceswap Folder in Linux system is :
`03/30/2020 13:51:17 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO`

The error Log of Faceswap Folder in Windows system is:
`03/30/2020 13:47:13 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
03/30/2020 13:47:29 MainProcess     MainThread      train           _get_images               INFO     Model A Directory: E:\fffan\DeepFake\FacesWap\faceswap-master\input\input_A
03/30/2020 13:47:29 MainProcess     MainThread      train           _get_images               INFO     Model B Directory: E:\fffan\DeepFake\FacesWap\faceswap-master\input\input_B
03/30/2020 13:47:29 MainProcess     MainThread      train           process                   INFO     Training data directory: E:\fffan\DeepFake\FacesWap\faceswap-master\models
03/30/2020 13:47:29 MainProcess     MainThread      train           _monitor                  INFO     ===================================================
03/30/2020 13:47:29 MainProcess     MainThread      train           _monitor                  INFO       Starting
03/30/2020 13:47:29 MainProcess     MainThread      train           _monitor                  INFO       Press 'ENTER' to save and quit
03/30/2020 13:47:29 MainProcess     MainThread      train           _monitor                  INFO       Press 'S' to save model weights immediately
03/30/2020 13:47:29 MainProcess     MainThread      train           _monitor                  INFO     ===================================================
03/30/2020 13:47:30 MainProcess     _training_0     train           _training                 INFO     Loading data, this may take a while...
03/30/2020 13:47:30 MainProcess     _training_0     plugin_loader   _import                   INFO     Loading Model from Original plugin...
03/30/2020 13:47:30 MainProcess     _training_0     _base           load                      INFO     No existing state file found. Generating.
03/30/2020 13:47:30 MainProcess     _training_0     deprecation_wrapper __getattr__               DEBUG    From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:68: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.\n
03/30/2020 13:47:30 MainProcess     _training_0     deprecation_wrapper __getattr__               DEBUG    From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:507: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.\n
03/30/2020 13:47:30 MainProcess     _training_0     deprecation_wrapper __getattr__               DEBUG    From D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py:3831: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.\n
03/30/2020 13:47:31 MainProcess     MainThread      train           _end_thread               CRITICAL Error caught! Exiting...
03/30/2020 13:47:31 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: '_training_0'`
Do you konw why and How to run it ?

**Comment by Tian14267** [comment]
@torzdf

**Comment by Tian14267** [comment]
My configuration of Linux System is here:
[configuration.log](https://github.com/deepfakes/faceswap/files/4401648/configuration.log)

**Comment by lockontan** [comment]
I encountered the same problem, have you solved it?

**Comment by torzdf** [comment]
No one has provided a crash report, hence the issue closed.

Please open a new issue with the crash report for support.

**Comment by lockontan** [comment]
I solved it, because of the CUDA driver version is insufficient for CUDA runtime version
